### ISSUE TITLE
[Windows] Issue, while running

### ISSUE THREAD

**Issue by XCanG** [Just-Some-Bots/MusicBot#101]
What I do: 1) download develop build
2) download and install **Git-2.7.1.2-64-bit.exe** as [this guide](https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up#1b-install-git) say
2) download and install **python-3.5.1.exe** (also use this guide)
3) configure **option.txt**
4) run as admin **runbot.bat**

First time I get some error and in bat and get solution with this command `python -m pip install --upgrade pip` and I use it.
5) run again and also see errors

Log: http://hnng.moe/f/7uj

```
Attempting to install dependencies...
Collecting discord.py>=0.10.0 from git+https://github.com/Rapptz/discord.py@async#egg=discord.py >= 0.10.0 (from -r requirements.txt (line 1))
  Cloning https://github.com/Rapptz/discord.py (to async) to c:\users\x4\appdata\local\temp\pip-build-85om_69g\discord.py
  Requested discord.py>=0.10.0 from git+https://github.com/Rapptz/discord.py@async#egg=discord.py >= 0.10.0 (from -r requirements.txt (line 1)), but installing version None
Collecting youtube-dl>=2016.01.01 (from -r requirements.txt (line 2))
  Using cached youtube_dl-2016.02.13-py2.py3-none-any.whl
Collecting aiohttp==0.19.0 (from discord.py>=0.10.0->-r requirements.txt (line 1))
  Using cached aiohttp-0.19.0.tar.gz
Collecting websockets==2.7 (from discord.py>=0.10.0->-r requirements.txt (line 1))
  Using cached websockets-2.7-py33.py34-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): chardet in c:\users\x4\appdata\local\programs\python\python35-32\lib\site-packages (from aiohttp==0.19.0->discord.py>=0.10.0->-r requirements.txt (line 1))
Installing collected packages: aiohttp, websockets, discord.py, youtube-dl
  Running setup.py install for aiohttp ... error
Exception:
Traceback (most recent call last):
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\compat\__init__.py", line 67, in console_to_str
    return s.decode(sys.__stdout__.encoding)
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp65001.py", line 17, in decode
    return codecs.code_page_decode(65001, input, errors, True)
UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\commands\install.py", line 317, in run
    prefix=options.prefix_path,
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_set.py", line 731, in install
    **kwargs
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_install.py", line 890, in install
    spinner=spinner,
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\utils\__init__.py", line 660, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\X4\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\compat\__init__.py", line 69, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte

You may need to run as admin to install dependencies.

E:\MusicBot-develop>
```

**Comment by imayhaveborkedit** [comment]
Usually when I see this its because someone set their username to something with a character like `é`, but I don't see one here.  This is the fix I give for this.  Try this and see if it works.
`
python -c "import pip, os; os.environ['PYTHONIOENCODING'] = 'utf_8'; pip.main('install --upgrade -r requirements.txt'.split())"
`

**Comment by XCanG** [comment]
Hm, I found solution when I go on page [https://github.com/Rapptz/discord.py](https://github.com/Rapptz/discord.py#installing) and use command 
`pip install git+https://github.com/Rapptz/discord.py@async`
in **cmd.exe**.
After that when I starting **runbot.bat** bot starting normally:

```
Attempting to install dependencies...
Collecting discord.py>=0.10.0 from git+https://github.com/Rapptz/discord.py@async#egg=discord.py >= 0.10.0 (from -r requirements.txt (line 1))
  Cloning https://github.com/Rapptz/discord.py (to async) to c:\users\x4\appdata\local\temp\pip-build-00jgtuxg\discord.py
  Requested discord.py>=0.10.0 from git+https://github.com/Rapptz/discord.py@async#egg=discord.py >= 0.10.0 (from -r requirements.txt (line 1)), but installing version 0.10.0a0
Collecting youtube-dl>=2016.01.01 (from -r requirements.txt (line 2))
  Using cached youtube_dl-2016.02.13-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): aiohttp==0.19.0 in c:\users\x4\appdata\local\programs\python\python35-32\lib\site-packages (from discord.py>=0.10.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): websockets==2.7 in c:\users\x4\appdata\local\programs\python\python35-32\lib\site-packages (from discord.py>=0.10.0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): chardet in c:\users\x4\appdata\local\programs\python\python35-32\lib\site-packages (from aiohttp==0.19.0->discord.py>=0.10.0->-r requirements.txt (line 1))
Installing collected packages: discord.py, youtube-dl
  Found existing installation: discord.py 0.10.0a0
    Uninstalling discord.py-0.10.0a0:
      Successfully uninstalled discord.py-0.10.0a0
  Running setup.py install for discord.py ... done
Successfully installed discord.py-0.10.0a0 youtube-dl-2016.2.13

Ok lets hope it worked

Connected!

Username: MusicBot-X4
Bot ID: 149478079297748992
Owner ID: 117363957903130627

Command prefix is /
Whitelist check is disabled
Skip threshold at 2 votes or 50%
Now Playing message @mentions are disabled
Autosummon is enabled
Auto-playlist is enabled
Downloaded songs will be saved after playback

--Server List--
JumpJet
```

Add this step in guide. I think this is important. Also may be important part is use command `python -m pip install --upgrade pip` **before** start bat.

**Comment by imayhaveborkedit** [comment]
:ok_hand:
