### ISSUE TITLE
egg_info on line 1 error code. [AGAIN]

### ISSUE THREAD

**Issue by SamHDev** [Just-Some-Bots/MusicBot#1034]
I'm trying to use the MusicBot in Centos7. Why not ubento you ask (Yes I spelt that wrong on purpose). I just dont like it.

So Everythime I run this bot it gives me an error. 
`[root@ns3055264 MusicBot-master]# python run.py
Python 3.5+ is required. This version is 2.7.5
Attempting to locate python 3.5...

Python 3 found.  Re-launching bot using: 
  /usr/bin/python3.5 run.py

No module named 'aiohttp'
Attempting to install dependencies...
Ignoring cffi: markers 'sys_platform == "win32"' don't match your environment
Collecting discord.py[voice]~=0.12.0 (from -r requirements.txt (line 1))
  Using cached discord.py-0.12.0.zip
Collecting youtube_dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2017.3.26-py2.py3-none-any.whl
Requirement already up-to-date: pip in /usr/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached aiohttp-1.0.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting websockets<4.0,>=3.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached websockets-3.3-py33.py34.py35.py36-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib64/python3.5/distutils/unixccompiler.py", line 128, in _compile
        extra_postargs)
      File "/usr/lib64/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "/usr/lib64/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/usr/lib64/python3.5/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/usr/lib64/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.5/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.5/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.5/distutils/unixccompiler.py", line 130, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-sf4mnwdz/cffi-1.10.0/setup.py", line 232, in <module>
        package_dir={"": "src"},
      File "/usr/lib64/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 258, in run_setup
        raise
      File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib64/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3.5/site-packages/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
        return func()
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-sf4mnwdz/cffi-1.10.0/setup.py", line 232, in <module>
        package_dir={"": "src"},
      File "/usr/lib64/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zbcl8j9n/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/lib64/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 318, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 373, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1135, in obtain
        return installer(requirement)
      File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 441, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 700, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zbcl8j9n/PyNaCl/

You may need to use sudo to install dependencies.`

So. I can't fix it.
I've researched the issue vigorously and tried everything that was a fix in those instances. However, nothing worked.
I've tried:

- Reinstalling Python
- Reinstalling Pip.
- Upgrading Pip
- Reinstalling Bot
- Setup Tools
- Installing Easy Tools
- Uninstalling and Installing Build tools ("Dev Tools")
- opus-devel
- libogg-devel
- libffi-devel
- libsodium-devel
- Reinstalling Centos.
IT JUST WONT WORK.
WHY!
6 Hours later no hope. Pls HELP!

**Comment by TBK** [comment]
Have you tried the docker version? With that you can forget about the manual depencency configuration hell.

**Comment by max-bromberg** [comment]
Are you trying to use the ubuntu version on CentOS? That won't work m8.

**Comment by jayktaylor** [comment]
You are missing the development headers for Python, which are included in the package `python3.5-dev`.
