### ISSUE TITLE
Bot crashes in around 1 day

### ISSUE THREAD

**Issue by BaiqingL** [Just-Some-Bots/MusicBot#1038]
The bot has not received any commands, nor any interaction. It has always been used as a personal bot. Yet everytime I have to restart the bot due to this error:

Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at /home/MusicBot/musicbot/player.py:280> exception=TimeoutError()>
Traceback (most recent call last):
  File "/home/andy/MusicBot/musicbot/player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/andy/MusicBot/musicbot/player.py", line 291, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "/home/andy/MusicBot/musicbot/bot.py", line 310, in reconnect_voice_client
    new_vc = await self.get_voice_client(vc.channel)
  File "/home/andy/MusicBot/musicbot/bot.py", line 237, in get_voice_client
    s_id_data = await asyncio.wait_for(s_id, timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 397, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by Zenrac** [comment]
If you can't fix that, make an autorestart every day ;)

**Comment by BaiqingL** [comment]
yeah I guess that's what I would have to resort to
