### ISSUE TITLE
[WinError 10060]

### ISSUE THREAD

**Issue by SonixApache** [Just-Some-Bots/MusicBot#1050]
Hey, tried running the bot today, having some issues,
Connects to channels just fine, seems to play the autoplaylist just fine as well, but it refuses to parse any !play commands.
Not sure if it's the bot, the firewall, or something wrong with my local system. I've been having some weird connectivity issues to websites lately, not sure if they're related.

```
[23.541688919] 2017-04-10 23:53:43,676 - INFO - launcher: Starting sanity checks
[23.541688919] 2017-04-10 23:53:43,676 - INFO - launcher: Checking for python 3.5+
[24.042129517] 2017-04-10 23:53:43,677 - INFO - launcher: Checking console encoding
[24.042129517] 2017-04-10 23:53:43,677 - INFO - launcher: Setting console encoding to UTF-8
[24.042129517] 2017-04-10 23:53:43,677 - INFO - launcher: Ensuring we're in the right folder
[25.044202805] 2017-04-10 23:53:43,678 - INFO - launcher: Adding local bins/ folder to path
[25.545120239] 2017-04-10 23:53:43,678 - INFO - launcher: Checks passed.
[25.545120239] 2017-04-10 23:53:43,678 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.7027547359466553] 2017-04-10 23:53:44,355 - DEBUG - musicbot.config | In config.py::MainThread(5384), line 254 in find_autoplaylist: Copying _autoplaylist.txt to autoplaylist.txt
[0.9867501258850098] 2017-04-10 23:53:44,639 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 200 in _setup_logging: Set logging level to INFO
[0.9872510433197021] 2017-04-10 23:53:44,640 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 77 in __init__: Loaded autoplaylist with 2531 entries
[0.988252878] launcher-INFO: Connecting
[3.5821011066436768] 2017-04-10 23:53:47,235 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 990 in on_ready: Connection established, ready to go.
[3.5825927257537842] 2017-04-10 23:53:47,235 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 311 in _cache_app_info: Caching app info
[3.7097268104553223] 2017-04-10 23:53:47,362 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 807 in _scheck_ensure_env: Ensuring data folders exist
[3.7107286453247070] 2017-04-10 23:53:47,363 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 823 in _scheck_server_permissions: Checking server permissions
[3.7107286453247070] 2017-04-10 23:53:47,363 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 827 in _scheck_autoplaylist: Auditing autoplaylist
[3.7107286453247070] 2017-04-10 23:53:47,363 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 831 in _scheck_configs: Validating config
[3.7107286453247070] 2017-04-10 23:53:47,363 - DEBUG - musicbot.config | In config.py::MainThread(5384), line 175 in async_validate: Validating options...
[3.7107286453247070] 2017-04-10 23:53:47,363 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 834 in _scheck_configs: Validating permissions config
[3.7107286453247070] 2017-04-10 23:53:47,363 - DEBUG - musicbot.permissions | In permissions.py::MainThread(5384), line 59 in async_validate: Validating permissions...
[3.7107286453247070] 2017-04-10 23:53:47,363 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1001 in on_ready: Connected!  Musicbot v1.9.6-review

[3.7112295627593994] 2017-04-10 23:53:47,364 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1011 in on_ready: Bot:   [BOT-ID-CENSORED]/MUSIC-BOT#xxxx [BOT]
[3.7117304801940918] 2017-04-10 23:53:47,364 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1019 in on_ready: Owner: [OWNER-ID-CENSORED]/SonixApache#xxxx

[3.7122321128845215] 2017-04-10 23:53:47,365 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1022 in on_ready: Server List:
[3.7127382755279541] 2017-04-10 23:53:47,365 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1023 in <listcomp>:  - [SERVER-CENSORED]
[3.7127382755279541] 2017-04-10 23:53:47,365 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1054 in on_ready: Bound to text channels:
[3.7132332324981689] 2017-04-10 23:53:47,366 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1055 in <listcomp>:  - [SERVER-CENSORED]/commandprompt
[3.7132332324981689] 2017-04-10 23:53:47,366 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1083 in on_ready: Not autojoining any voice channels
[3.7137339115142822] 2017-04-10 23:53:47,366 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1097 in on_ready: Options:
[3.7142379283905029] 2017-04-10 23:53:47,367 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1099 in on_ready:   Command prefix: !
[3.7147357463836670] 2017-04-10 23:53:47,367 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1100 in on_ready:   Default volume: 15%
[3.7147357463836670] 2017-04-10 23:53:47,367 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1102 in on_ready:   Skip threshold: 4 votes or 50%
[3.7152450084686279] 2017-04-10 23:53:47,368 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1103 in on_ready:   Now Playing @mentions: Disabled
[3.7152450084686279] 2017-04-10 23:53:47,368 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1104 in on_ready:   Auto-Summon: Disabled
[3.7157382965087891] 2017-04-10 23:53:47,368 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1105 in on_ready:   Auto-Playlist: Disabled
[3.7157382965087891] 2017-04-10 23:53:47,368 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1106 in on_ready:   Auto-Pause: Disabled
[3.7162384986877441] 2017-04-10 23:53:47,369 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1107 in on_ready:   Delete Messages: Disabled
[3.7162384986877441] 2017-04-10 23:53:47,369 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1110 in on_ready:   Debug Mode: Disabled
[3.7162384986877441] 2017-04-10 23:53:47,369 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1111 in on_ready:   Downloaded songs will be saved
[12.6078844070434570] 2017-04-10 23:53:56,261 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 2357 in on_message: [OWNER-ID-CENSORED]/SonixApache#xxxx: !summon
[12.6088860034942627] 2017-04-10 23:53:56,262 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 1766 in cmd_summon: Joining [SERVER-CENSORED]/DnD
[12.6093955039978027] 2017-04-10 23:53:56,262 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 424 in get_voice_client: Connection attempt 1 to DnD
[12.6093955039978027] 2017-04-10 23:53:56,262 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 363 in join_voice_channel: (join_voice_channel) creating futures
[12.6093955039978027] 2017-04-10 23:53:56,262 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 369 in join_voice_channel: (join_voice_channel) setting voice state
[12.6098875999450684] 2017-04-10 23:53:56,263 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 372 in join_voice_channel: (join_voice_channel) waiting for session id
[12.7201347351074219] 2017-04-10 23:53:56,373 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 2526 in on_voice_state_update: Voice state update for [BOT-ID-CENSORED]/MUSIC-BOT#xxxx on [SERVER-CENSORED]/DnD -> [JOIN, CONNECT]
[12.7201347351074219] 2017-04-10 23:53:56,373 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 2537 in on_voice_state_update: [BOT-ID-CENSORED]/MUSIC-BOT#xxxx has joined [SERVER-CENSORED]/DnD
[12.7206363677978516] 2017-04-10 23:53:56,373 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 376 in join_voice_channel: (join_voice_channel) waiting for voice data
[12.8164062500000000] 2017-04-10 23:53:56,469 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 390 in join_voice_channel: (join_voice_channel) connecting...
[12.9759631156921387] 2017-04-10 23:53:56,629 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 402 in join_voice_channel: (join_voice_channel) connection successful
[12.9759631156921387] 2017-04-10 23:53:56,629 - DEBUG - musicbot.bot | In bot.py::MainThread(5384), line 450 in get_voice_client: Connected in 0.4s
[12.9759631156921387] 2017-04-10 23:53:56,629 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 451 in get_voice_client: Connected to [SERVER-CENSORED]/DnD
[12.9764714241027832] 2017-04-10 23:53:56,629 - VOICEDEBUG - musicbot.player | In player.py::MainThread(5384), line 313 in websocket_check: Starting websocket check loop for [SERVER-CENSORED]
[23.0734872817993164] 2017-04-10 23:54:06,726 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 2357 in on_message: [OWNER-ID-CENSORED]/SonixApache#xxxx: !play darude sandstorm
[45.7676699161529541] 2017-04-10 23:54:29,420 - ERROR - musicbot.bot | In bot.py::MainThread(5384), line 2493 in on_message: Exception in on_message
Traceback (most recent call last):
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 854, in send
    self.connect()
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1229, in connect
    super().connect()
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 498, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 1089, in https_open
    req, **kwargs)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1302, in _real_extract
    video_webpage = self._download_webpage(url, video_id)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 630, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 527, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 507, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Sonix\Firefox\PROJECTTO\MusicBot\musicbot\bot.py", line 2464, in on_message
    response = await handler(**handler_kwargs)
  File "F:\Sonix\Firefox\PROJECTTO\MusicBot\musicbot\bot.py", line 1302, in cmd_play
    info = await self.downloader.extract_info(player.playlist.loop, song_url, download=False, process=False)
  File "F:\Sonix\Firefox\PROJECTTO\MusicBot\musicbot\downloader.py", line 83, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Sonix\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None),))
[66.8641707897186279] 2017-04-10 23:54:50,517 - INFO - musicbot.bot | In bot.py::MainThread(5384), line 2357 in on_message: [OWNER-ID-CENSORED]/SonixApache#xxxx: !shutdown
[67.2334210872650146] 2017-04-10 23:54:50,886 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(5384), line 2526 in on_voice_state_update: Voice state update for [BOT-ID-CENSORED]/MUSIC-BOT#xxxx on [SERVER-CENSORED]/DnD -> [DISCONNECT]
[67.241696358] launcher-INFO: All done.
```

Any ideas?

**Comment by SonixApache** [comment]
Instant update; I queued up the same command a bunch of times and after 4 errors it actually managed to run the song.
![image](https://cloud.githubusercontent.com/assets/8468269/24884581/5b6e2056-1e4a-11e7-9be1-5326eb9322d9.png)
Seems to be an issue on my end.
Going to call my ISP tomorrow, see if they can fix it. Will update this if anything changes.

**Comment by SonixApache** [comment]
Called my ISP, they acknowledged that there have been webpage loading issues, so that's the issue.

**Comment by jayktaylor** [comment]
Thanks for the updates.
