### ISSUE TITLE
I keep getting this message.. in python :\ please help!

### ISSUE THREAD

**Issue by Naterrama** [Just-Some-Bots/MusicBot#1055]
Traceback (most recent call last):
  File "run.py", line 163, in main
    m = MusicBot()
  File "C:\Program Files (x86)\Music Bot\MusicBot-master\musicbot\bot.py", line 75, in __init__
    self.config = Config(config_file)
  File "C:\Program Files (x86)\Music Bot\MusicBot-master\musicbot\config.py", line 74, in __init__
    self.now_playing_mentions = config.getboolean('MusicBot', 'NowPlayingMentions', fallback=ConfigDefaults.now_playing_mentions)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 827, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 807, in _get_conv
    **kwargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 801, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 1153, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: yeah

C:\Program Files (x86)\Music Bot\MusicBot-master>

**Comment by jayktaylor** [comment]
In the `NowPlayingMentions` option of your `options.ini` file, you've wrote 'yeah' rather than 'yes' or 'no'.

**Comment by Naterrama** [comment]
now i am getting this error. :S and the bots in chat but isnt playing any music. [😲]

Connected!  Musicbot v1.9.5_2

Bot:   303194271312379914/DJ Bot#6129
Owner: 200436156242853888/Naterrama#4225

Server List:
 - TheGamePad(Loading...)

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !
  Default volume: 15%
  Skip threshold: 2 votes or 50%
  Now Playing @mentions: Enabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be deleted

Attempting to autosummon...
Found owner in "Music", attempting to join...
Attempting connection...
Connection established.
Done!
Starting auto-playlist

Traceback (most recent call last):
  File "C:\Program Files (x86)\Song Bot\MusicBot-master\musicbot\entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'audio_cache'
Future exception was never retrieved
future: <Future finished exception=PermissionError(13, 'Access is denied')>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Song Bot\MusicBot-master\musicbot\entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'audio_cache'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Song Bot\MusicBot-master\musicbot\entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'audio_cache'
Failed to get entry.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Song Bot\MusicBot-master\musicbot\player.py", line 234, in _play
    entry = await self.playlist.get_next_entry()
  File "C:\Program Files (x86)\Song Bot\MusicBot-master\musicbot\playlist.py", line 245, in get_next_entry
    return await entry.get_ready_future()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
    value = future.result()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Program Files (x86)\Song Bot\MusicBot-master\musicbot\entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'audio_cache'



________________________________

**Comment by Naterrama** [comment]
nevermind i got it working :D it's audio is sounding a bit weird though. sped up sometimes and cutting out :O


________________________________

**Comment by Naterrama** [comment]
Hey so i got it working for the past couple of days but now  the bot says this video is up nexted but doesnt play anything and i am getting this string of text when i booted it up today.


Server List:
 - TheGamePad(Loading...)

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !
  Default volume: 40%
  Skip threshold: 2 votes or 50%
  Now Playing @mentions: Enabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be deleted

Could not delete old audio cache, moving on.
Attempting to autosummon...
Found owner in "General", attempting to join...
Attempting connection...
Connection established.
Done!
Starting auto-playlist

[Download] Started: https://www.youtube.com/watch?v=8fGLiIvKKys
ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'
Traceback (most recent call last):
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 175, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 449, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
    value = future.result()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 771, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 825, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1539, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1803, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1745, in dl
    return fd.download(name, info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 180, in real_download
    self.report_error('unable to open for writing: %s' % str(err))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'
Future exception was never retrieved
future: <Future finished exception=ExtractionError(DownloadError("ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'",),)>
Traceback (most recent call last):
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 175, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 449, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
    value = future.result()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 771, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 825, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1539, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1803, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1745, in dl
    return fd.download(name, info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 180, in real_download
    self.report_error('unable to open for writing: %s' % str(err))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'
[Download] Started: https://www.youtube.com/watch?v=8fGLiIvKKys
ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'
Traceback (most recent call last):
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 175, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 449, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
    value = future.result()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 771, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 825, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1539, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1803, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1745, in dl
    return fd.download(name, info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 180, in real_download
    self.report_error('unable to open for writing: %s' % str(err))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'
Failed to get entry.
Traceback (most recent call last):
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 175, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 449, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
    value = future.result()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 771, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 825, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1539, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1803, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1745, in dl
    return fd.download(name, info)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 180, in real_download
    self.report_error('unable to open for writing: %s' % str(err))
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 162, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 559, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\player.py", line 234, in _play
    entry = await self.playlist.get_next_entry()
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\playlist.py", line 245, in get_next_entry
    return await entry.get_ready_future()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 288, in _wakeup
    value = future.result()
  File "C:\Users\Nat\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Program Files (x86)\DJ Bot\MusicBot-master\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to open for writing: [Errno 13] Permission denied: 'audio_cache\\youtube-8fGLiIvKKys-Roxette_-_Fading_Like_A_Flower.webm.part'


________________________________

**Comment by jayktaylor** [comment]
Run the program as an administrator.

**Comment by Naterrama** [comment]
thanks! [😃]  So everytime it joins the first song will be from the playlist then I can skip it? or is there a way to go straight to the songs I ask for?

________________________________

**Comment by Technetium1** [comment]
@Naterrama https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L80
