### ISSUE TITLE
cant connect for some reason. was working before...

### ISSUE THREAD

**Issue by Huliou** [Just-Some-Bots/MusicBot#1068]
Options:
  Command prefix: !
  Default volume: 30%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Enabled
  Auto-Playlist: Disabled
  Auto-Pause: Enabled
  Delete Messages: Disabled
  Debug Mode: Disabled
  Downloaded songs will be deleted

Attempting to autojoin Music bot in Zxanth's Mountain Hangout
Attempting connection...
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 382, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (1/3)...
Attempting connection...
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 382, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (2/3)...
Attempting connection...
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 382, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (3/3)...
Failed to join Music bot

I have tried doing
git pull
python3.5 -m pip install -U -r requirements.txt

and still nothing

**Comment by Zenrac** [comment]
Sometimes i've this issue, and sometimes that's because i've more than one bot connected

**Comment by Huliou** [comment]
its odd though, i've done a hard reset and remade them (via the wiki steps). i've only tried the one bot....

**Comment by jayktaylor** [comment]
This should be less of an issue in recent updates to the bot.
