### ISSUE TITLE
BOT keeps deleting autoplaylist from YouTube Links

### ISSUE THREAD

**Issue by SuchKnife** [Just-Some-Bots/MusicBot#1073]
I keep getting errors when I try !play [YouTube Links], this error: 
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\chris\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

And in the Runbot.bat it says: 

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\chris\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=yzTuBuRdAyA

**Comment by jayktaylor** [comment]
#1072
