### ISSUE TITLE
ERROR: Signature extraction failed: 

### ISSUE THREAD

**Issue by Aequil** [Just-Some-Bots/MusicBot#1076]
PLZZ Send Help Im sinking!

**Comment by Aequil** [comment]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by TomLongAshfords** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#event-1061982903
