### ISSUE TITLE
Player does not exist error

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#108]
Hi guys,

I get this error

`Player does not exist. It has not been summoned yet into a voice channel.  Use !summon to summon it to your voice channel.`

autosummon is enabled (see config below) and the bot is also joining my voice channel. If I want him to play a song the above shown error is dropped

``` ini
[Credentials]
; The bot needs its own account to run on (not yours)
Username = XX
Password = XX

[Permissions]
; This need to be your id, not the bot's id.  The bot does not own the bot.  You do.
OwnerID = 14XXX01

[Chat]
; Change this if you don't want commands to trigger another bot
CommandPrefix = !

[MusicBot]
; This option is not implemented yet
DaysActive = 0

; Only allow whitelisted users to use commands
WhiteListCheck = no

; Skips required to skip a song.  Whichever is lower will be used.
; Skip ratio refers to the percent of non-deafened, non-owner users
; in the voice channel needed to skip a song.
SkipsRequired = 7
SkipRatio = 0.5

; If no, delete videos after they've played, if the video
; isn't still in the queue, to avoid redownloading it
SaveVideos = yes

; Mentions the user who queued a song when the song plays
NowPlayingMentions = no

; On start up, if the owner is in a voice channel, join that channel
AutoSummon = yes

; Play random songs when nothing is queued
UseAutoPlaylist = yes 
```

**Comment by aarc0456** [comment]
You have to give the other account an invite link

**Comment by imayhaveborkedit** [comment]
Does it work if you turn off autosummon, manually summon it, and play a song?

**Comment by ghost** [comment]
No, if I manually summon it, it throws the error that `Multiple servers` are `not supported at this time.`

**Comment by XCanG** [comment]
1) You bot bot have access to join in voice channel, where you summon it?
2) You stay in channel and use command?

3) If you do all right and also need help, try to use my code (currently not work at 100%)
Find **bot.py**, backup it, open and find this 2 lines:

```
if self.voice_clients:
            raise CommandError("Multiple servers not supported at this time.")
```

Then replace it to:

```
if self.voice_clients:
            server = channel.server #X4: Define server
            channel = None #X4: Set null, because undefined
            for channel in server.channels: #X4: List of channels on the server
                if discord.utils.get(channel.voice_members, id=author.id): #X4: Searching user in channels
                    break #X4: Stop at current seleced channel and go next
            player = await self.get_player(channel, create=True) #X4: Check player
            if channel.server.id in self.players: #X4: Check same server (true) or other (else)
                await self.get_voice_client(channel) #X4: This does not work on same server, need to fix!
            else: #X4: Else
                await self.get_voice_client(channel) #X4: Move bot to other new server and in new channel
            if player.is_stopped: #X4: Check if player stopped (practically almost stopped)
                player.play() #X4: Send "play" state
            if not player.playlist.entries and self.config.auto_playlist: #X4: Check player for tracks. New summoned player is empty.
                song_url = choice(self.backuplist) #X4: Choose random track from auto playlist
                await player.playlist.add_entry(song_url, channel=None, author=None) #X4: Send chosen track to player and start playing music
```

Now save file, and try to summon again. With this code bot ignore _Multiple server warning_ and have some algorithm to join in channel.

But be worry, I don't finish this code and it also does not have exceptions. Bot need to be connected on the same servr, where are you, you need to stay in channel, bot need to be able to join in channel and then you can use command **!summon**.

**Comment by ghost** [comment]
Thanks for your code. I will give it a try this evening (Central European Time)

P.S.: It's time to learn Python :D

**Comment by ghost** [comment]
When I delete this two lines and add the ones you posted, I'm getting this kind of error:

```
Traceback (most recent call last):
  File "run.py", line 202, in <module>
    main()
  File "run.py", line 181, in main
    from musicbot import MusicBot
  File "/home/daniel/MusicBot-develop/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/home/daniel/MusicBot-develop/musicbot/bot.py", line 461
    player = await self.get_player(channel, create=True) #X4: Check player
```

**Comment by XCanG** [comment]
Check agian:

```
async def handle_summon(self, channel, author):
        """
        Usage {command_prefix}summon
        This command is for summoning the bot into your voice channel [but it should do it automatically the first time]
        """

        if self.voice_clients:
            #raise CommandError("Multiple servers not supported at this time. / X4: In queue to update")

            server = channel.server #X4: Define server
            channel = None #X4: Set null, because undefined
            for channel in server.channels: #X4: List of channels on the server
                if discord.utils.get(channel.voice_members, id=author.id): #X4: Searching user in channels
                    break #X4: Stop at current seleced channel and go next
            player = await self.get_player(channel, create=True) #X4: Check player
            if channel.server.id in self.players: #X4: Check same server (true) or other (else)
                await self.get_voice_client(channel) #X4: This does not work on same server, need to fix!
            else: #X4: Else
                await self.get_voice_client(channel) #X4: Move bot to other new server and in new channel
            if player.is_stopped: #X4: Check if player stopped (practically almost stopped)
                player.play() #X4: Send "play" state
            if not player.playlist.entries and self.config.auto_playlist: #X4: Check player for tracks. New summoned player is empty.
                song_url = choice(self.backuplist) #X4: Choose random track from auto playlist
                await player.playlist.add_entry(song_url, channel=None, author=None) #X4: Send chosen track to player and start playing music
```

Or try to use code form my repository https://github.com/JumpJets/MusicBot (but uncomment it!)

**Comment by ghost** [comment]
Thanks, with your code it's working

**Comment by XCanG** [comment]
Good to see it, but try to find a root of problem, because I can start bot without this code now. This code only for resummon.
