### ISSUE TITLE
Unable to parse data, even after upgrading all pip packages.

### ISSUE THREAD

**Issue by BaiqingL** [Just-Some-Bots/MusicBot#1084]
Error as following:
`
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))
Error adding song from autoplaylist: Could not extract information from www.youtube.com/watch?v=MisLXxaagnM
`

**Comment by BaiqingL** [comment]
Soundcloud is still confirmed to be working, youtube however is not.

**Comment by BaiqingL** [comment]
Nvm, a reinstall of youtube-dl version 2017.4.28 fixed it.
