### ISSUE TITLE
Getting error while using bot any help?

### ISSUE THREAD

**Issue by DashingN** [Just-Some-Bots/MusicBot#1085]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1063, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Zack\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 951, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by junhui-f** [comment]
>> https://github.com/Just-Some-Bots/MusicBot/issues/1072

Next time look at **closed** issues and other similar **issues** before opening more duplicate threads
