### ISSUE TITLE
Signature Error

### ISSUE THREAD

**Issue by Palaract** [Just-Some-Bots/MusicBot#1088]
The most time when i use !play the bot writes following:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by rafaelwastaken** [comment]
Update youtube-dl.
