### ISSUE TITLE
Can't request

### ISSUE THREAD

**Issue by bumbleduck** [Just-Some-Bots/MusicBot#1089]
`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "D:\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))`

How do i fix this

**Comment by bumbleduck** [comment]
duplicate
