### ISSUE TITLE
Many songs are now throwing error `Cannot identify player`

### ISSUE THREAD

**Issue by amandasaffer** [Just-Some-Bots/MusicBot#1092]
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Amanda\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Amanda\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))
```

**Comment by thomasbsh** [comment]
I am having the exact same problem.

**Comment by thomasbsh** [comment]
Hey I just found out a fix to the problem.
Go to the location mentionned in the error ("C:\Users\Amanda\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py") and delete the file called "youtube.py". Restart the bot and it should reinstall the youtube.py. Restart the bot again and there you go! Hope it fixed it for you too. :)

**Comment by rafaelwastaken** [comment]
Update youtube-dl

**Comment by FIERCEDINO080** [comment]
I fixed it by running update_deps.bat and restarting the bot

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717
