### ISSUE TITLE
Bot won't !play

### ISSUE THREAD

**Issue by ConArtist54** [Just-Some-Bots/MusicBot#1095]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Conno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Conno\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by ConArtist54** [comment]
Reinstalled Python... Fixed

**Comment by jayktaylor** [comment]
#1072
