### ISSUE TITLE
update_deps.bat errors

### ISSUE THREAD

**Issue by aster1196** [Just-Some-Bots/MusicBot#1103]
Exception:
Traceback (most recent call last):
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\req\req_set.py", line 487, in _prepare_file
    req_to_install, finder)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\req\req_set.py", line 428, in _check_skip_installed
    req_to_install, upgrade_allowed)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\html5parser.py", line 35, in parse
    return p.parse(doc, **kwargs)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\html5parser.py", line 235, in parse
    self._parse(stream, False, None, *args, **kwargs)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\html5parser.py", line 85, in _parse
    self.tokenizer = _tokenizer.HTMLTokenizer(stream, parser=self, **kwargs)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\_tokenizer.py", line 36, in __init__
    self.stream = HTMLInputStream(stream, **kwargs)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\_inputstream.py", line 151, in HTMLInputStream
    return HTMLBinaryInputStream(source, **kwargs)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\_inputstream.py", line 412, in __init__
    HTMLUnicodeInputStream.__init__(self, self.rawStream)
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\_inputstream.py", line 194, in __init__
    self.reset()
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-pa
ckages\pip\_vendor\html5lib\_inputstream.py", line 435, in reset
    self.dataStream = self.charEncoding[0].codec_info.streamreader(self.rawStrea
m, 'replace')
AttributeError: 'NoneType' object has no attribute 'codec_info'

C:\Users\NPSTUD~1\Desktop\MUSICB~1>

as a result my bot gives me the yt error of signature traceback 

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\NPStudent\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

thanks in advance!

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717
