### ISSUE TITLE
"Could not extract information from yt_link"

### ISSUE THREAD

**Issue by Minxxe** [Just-Some-Bots/MusicBot#1104]
```
Could not extract information from "youtube_link"

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Dominik\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))
```
That is basicly happening all the time, with the master and review version.

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717
