### ISSUE TITLE
player problem

### ISSUE THREAD

**Issue by kamyrdol32** [Just-Some-Bots/MusicBot#1105]
Hello, i have problem with thas BOT, when i start it on Debian 8.7 i hava:

`
Attempting to autosummon...
Found owner in "Publiczny #3", attempting to join...
Attempting connection...
Connection established.
Done!
Starting auto-playlist

[Download] Started: https://www.youtube.com/watch?v=WQtGqmi2O2U
[Download] Complete: https://www.youtube.com/watch?v=WQtGqmi2O2U
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /root/MusicBot/musicbot/player.py:221> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 427, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "/usr/local/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/root/MusicBot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable
`

**Comment by MintLily** [comment]
go to https://discordapp.com/developers/applications/me and update the bot token

**Comment by chuushi** [comment]
```
File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable
```

You need to install ffmpeg on your system.  It is currently missing from the PATH environment.  Follow [the guide for Debian](https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Debian).

**Comment by jayktaylor** [comment]
Thanks, @SimonOrJ.
