### ISSUE TITLE
It can't play specific tracks

### ISSUE THREAD

**Issue by fouadhammad1229** [Just-Some-Bots/MusicBot#1106]
It displays this error everytime it plays specfic song:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Fouad Hammad\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fouad Hammad\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by fouadhammad1229** [comment]
Nevermind to fix that issue you need to update the depositories through the "update_deps.bat" in your folder.
Hope this helps for anyone who has this issue as well.
