### ISSUE TITLE
Player help?

### ISSUE THREAD

**Issue by Helwind** [Just-Some-Bots/MusicBot#1107]
Not sure what this means and I am new to python and coding.

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Admin account\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Admin account\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 897, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player '/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by rafaelwastaken** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717
