### ISSUE TITLE
python3 install error

### ISSUE THREAD

**Issue by abakisensoy** [Just-Some-Bots/MusicBot#1118]
hi;
i use ubuntu 16.04 64bit.
i get an error at step : python3 -m pip install -U -r requirements.txt

here is the error:

```
Building wheels for collected packages: discord.py, PyNaCl, pycparser
  Running setup.py bdist_wheel for discord.py ... done
  Stored in directory: /home/gedo/.cache/pip/wheels/be/10/3c/6a208dacacfb23729b4575b565a0fcac34ee7061ea4a1a1cfb
  Running setup.py bdist_wheel for PyNaCl ... done
  Stored in directory: /home/gedo/.cache/pip/wheels/5c/e3/22/01d05a856963e55f2377627dfb192503c4383fb4b1e3419535
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/gedo/.cache/pip/wheels/a8/0b/41/dc95621f9d3a0da7bc191b8a71f0e8182ffd3cc5f33ac55005
Successfully built discord.py PyNaCl pycparser
Installing collected packages: chardet, multidict, async-timeout, aiohttp, websockets, pycparser, cffi, PyNaCl, discord.py, youtube-dl
  Found existing installation: chardet 2.3.0
    Uninstalling chardet-2.3.0:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/chardet' -> '/tmp/pip-039oyx67-uninstall/usr/lib/python3/dist-packages/chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gedo/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/gedo/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/gedo/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/gedo/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/gedo/.local/lib/python3.5/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/gedo/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.5/shutil.py", line 550, in move
    rmtree(src)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'chardetect.py'

```

**Comment by TBK** [comment]
Have you tried to run the command with sudo?
`sudo python3 -m pip install -U -r requirements.txt`

**Comment by jayktaylor** [comment]
See comment above.
