### ISSUE TITLE
Musicbot play problem

### ISSUE THREAD

**Issue by Starry-Miracle** [Just-Some-Bots/MusicBot#1126]
Here are the error messages displayed

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Server\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Server\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl3DiVMI/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl3DiVMI/en_US/base.js'",))

Tried reinstalling music bot and python, does not help.

**Comment by TBK** [comment]
#1123 might resolve your issue.

**Comment by Starry-Miracle** [comment]
thx bro that helps

**Comment by TBK** [comment]
Please close the issue.
