### ISSUE TITLE
Error Message when trying to play any song using !play

### ISSUE THREAD

**Issue by AwkwardScreeching** [Just-Some-Bots/MusicBot#1135]
I got this odd error message that I don't understand: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\marve\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\marve\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'",))

and it wont go offline or respond once if I have closed out and reopened runbot.bat

please help!

**Comment by TBK** [comment]
#1072
