### ISSUE TITLE
Error message when using !play or !search

### ISSUE THREAD

**Issue by PolkaPens** [Just-Some-Bots/MusicBot#1140]
The bot used to run these commands just fine, but just this week my friends and I can't play a song not on autoplaylist.txt, rendering the commands !play and !search useless. The error message reads as follows:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\[My name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\[My name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfltmLGsd/en_US/base.js'",))

Any ideas on how to fix this?

**Comment by spgill** [comment]
Same issue here

**Comment by Loxworth** [comment]
I have the same issue, however I receive the following error message:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\[My Name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\[My Name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\[My Name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\[My Name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\[My Name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\[My Name]\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'',))

**Comment by Axelen123** [comment]
same issue for me ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'',))

**Comment by junhui-f** [comment]
Updated dependencies?

**Comment by Loxworth** [comment]
> Updated dependencies? -Grift

@Grift I ran the update_deps.bat file, but that seemed to only work for about 60 seconds before giving me the same error message again...

**Comment by spgill** [comment]
So it's a problem with the youtube-dl module. They pushed an update to pypi, but people seem to have trouble getting it. Try completely uninstalling it and reinstalling it:

`pip uninstall youtube-dl`
and say yes to the prompt, then
`pip install youtube-dl`

**Comment by HardUIKnow** [comment]
just done the pip upgrade and it says i'm already upto date
and i still get the error

**Comment by Loxworth** [comment]
I got the same result as HardUIKnow

**Comment by TheRealhanBrolo** [comment]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\holdu\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\holdu\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\holdu\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\holdu\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\holdu\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\holdu\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'',))


Even after pip update. tried ramking the bot. nothing

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1141

**Comment by Loxworth** [comment]
@arunesh90 What is that good for? I don't see any solutions suggested in the comments of that thread...

**Comment by arunesh90** [comment]
@Loxworth I recommend checking the other open issues.
