### ISSUE TITLE
Error, bot won't play music

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1141]
The bot won't play music, only some specific songs. I already updated the bot so I don't know what's wrong with it.

When requesting a song:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "D:\Program Files\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "D:\Program Files\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "D:\Program Files\Python\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "D:\Program Files\Python\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "D:\Program Files\Python\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'',))

**Comment by zulrax** [comment]
I can confirm, I got this earlier:
`
  Problem:  Cannot establish connection to voice chat.  Something may be blocking outgoing UDP connections.                                                                                                                                  
  Solution: This may be an issue with a firewall blocking UDP.  Figure out what is blocking UDP and disable it.  It's most likely a system firewall or overbearing anti-virus firewall.          `

And then `ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    else:
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1004, in _extract_signature_function
    },
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1057, in <lambda>
    assert os.path.basename(func_id) == func_id
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'',))
`

**Comment by ThePoet444** [comment]
Third it.. I think it's an error with youtube_dl, I am seeing the same errors over there on their github as well. So I think Youtube changed something... This is however, my uneducated guess.

**Comment by pieterrombauts** [comment]
Fourth it, also receiving the exact same error message.

**Comment by PurpleDish** [comment]
I'm getting this error on most searches, it appears to be when I'm downloading a video from a copyrighted artist... Or like it feels more official. But it seems like covers and remixes and stuff are still working fine.

**Comment by Mitaeus** [comment]
I am getting the same error, but the bot can't play any songs.

**Comment by Manuxxxxx** [comment]
Same

**Comment by arunesh90** [comment]
https://github.com/rg3/youtube-dl/issues/13123

**Comment by arunesh90** [comment]
It's already fixed, just update your dependencies.
