### ISSUE TITLE
Need help :P

### ISSUE THREAD

**Issue by DerDEZY** [Just-Some-Bots/MusicBot#1142]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Damien\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Damien\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Damien\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Damien\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Damien\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Damien\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'',))

Can someone help me plz, already tryed "update_deps.bat"...

**Comment by arunesh90** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/1141
