### ISSUE TITLE
not playing and deleting from autoplaylist

### ISSUE THREAD

**Issue by jaschuu** [Just-Some-Bots/MusicBot#1143]
just wondering how to fix this please

[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=zNgcYGgtf8M
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "D:\Program Files\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "D:\Program Files\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1004, in _extract_signature_function
    cache_res = res(test_string)
  File "D:\Program Files\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1057, in <lambda>
    return lambda s: initial_function([s])
  File "D:\Program Files\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 255, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "D:\Program Files\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "D:\Program Files\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 143, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "D:\Program Files\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 219, in extract_object
    r'\}\s*;' % _FUNC_NAME_RE,
TypeError: not all arguments converted during string formatting
 (caused by TypeError('not all arguments converted during string formatting',))
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=_LmnP7wZUck

**Comment by jaschuu** [comment]
this problem is fixed run update_deps.bat and all will be good

**Comment by Loxworth** [comment]
If @jaschuu 's suggestion doesn't help, try using the following command in Git Bash `pip install -U -r requirements.txt`
