### ISSUE TITLE
error youtube-dl

### ISSUE THREAD

**Issue by LukasCCB** [Just-Some-Bots/MusicBot#1149]
The bot connect in my channel and write in char, but is error in youtube-dl.

Connected!  Musicbot v1.9.5_2

Bot:   315283425093353473/MusicBOT#5143
Owner: 194778393655377921/LukasCCB#4179

Server List:
 - Piratas ( Í¡Í¡ Â° Íœ Ê– Í¡ Â°)

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !
  Default volume: 15%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Disabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

[Command] 194778393655377921/LukasCCB (!help)
[Command] 194778393655377921/LukasCCB (!summon)
Attempting connection...
Connection established.
Traceback (most recent call last):
  File "C:\Python\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Python\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Python\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Python\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Python\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Python\lib\http\client.py", line 1252, in connect
    super().connect()
  File "C:\Python\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Python\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Nenhuma conexÃ£o pÃ´de ser feita porque
 a mÃ¡quina de destino as recusou ativamente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\youtube_dl\extractor\common.py", line 502, i
n _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 2106, in urlo
pen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Python\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Python\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Python\lib\site-packages\youtube_dl\utils.py", line 1090, in https_op
en
    req, **kwargs)
  File "C:\Python\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] Nenhuma conexÃ£o pÃ´de se
r feita porque a mÃ¡quina de destino as recusou ativamente>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 760, in extra
ct_info
    ie_result = ie.extract(url)
  File "C:\Python\lib\site-packages\youtube_dl\extractor\common.py", line 433, i
n extract
    ie_result = self._real_extract(url)
  File "C:\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1397,
 in _real_extract
    video_webpage = self._download_webpage(url, video_id)
  File "C:\Python\lib\site-packages\youtube_dl\extractor\common.py", line 634, i
n _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote,
 fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Python\lib\site-packages\youtube_dl\extractor\common.py", line 531, i
n _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal,
 data=data, headers=headers, query=query)
  File "C:\Python\lib\site-packages\youtube_dl\extractor\common.py", line 511, i
n _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error [Win
Error 10061] Nenhuma conexÃ£o pÃ´de ser feita porque a mÃ¡quina de destino as re
cusou ativamente> (caused by URLError(ConnectionRefusedError(10061, 'Nenhuma con
exÃ£o pÃ´de ser feita porque a mÃ¡quina de destino as recusou ativamente', None,
 10061, None),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Discord\MusicBot\musicbot\bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Discord\MusicBot\musicbot\bot.py", line 1331, in cmd_summon
    await self.on_player_finished_playing(player)
  File "C:\Discord\MusicBot\musicbot\bot.py", line 420, in on_player_finished_pl
aying
    info = await self.downloader.safe_extract_info(player.playlist.loop, song_ur
l, download=False, process=False)
  File "C:\Discord\MusicBot\musicbot\downloader.py", line 85, in safe_extract_in
fo
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.s
afe_ytdl.extract_info, *args, **kwargs))
  File "C:\Python\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Python\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "C:\Python\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Python\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 783, in extra
ct_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 589, in repor
t_error
    self.trouble(error_message, tb)
  File "C:\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 542, in troub
le
    self.to_stderr(message)
  File "C:\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 496, in to_st
derr
    self._write_string(output, self._err_file)
  File "C:\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 475, in _writ
e_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "C:\Python\lib\site-packages\youtube_dl\utils.py", line 1392, in write_st
ring
    if _windows_write_string(s, out):
  File "C:\Python\lib\site-packages\youtube_dl\utils.py", line 1376, in _windows
_write_string
    raise OSError('Failed to write string')
OSError: Failed to write string

**Comment by neoblizz** [comment]
@LukasCCB `pip install -U -r requirements.txt` solved it for me. on linux. Maybe try running `update_deps.bat` again?

**Comment by badboyjerry** [comment]
im having trouble with looks like the same problem got any suggestions?

**Comment by jayktaylor** [comment]
Try updating youtube-dl. This isn't our issue.
