### ISSUE TITLE
Error when installing via pip

### ISSUE THREAD

**Issue by MarvinBerger** [Just-Some-Bots/MusicBot#1171]
Hey there!
I am trying to install the bot on my debian 8 server. I followed this recipe:
https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Debian

Everythin went fine, except I had to install pip manually and upgraded it as mentioned in #831 .

But I am still getting an error:
```
sudo -H python -m pip install --upgrade -r requirements.txt
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 274, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2686, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'discord.py[voice] ~= 0.12.0', 'at', ' ~= 0.12.0')

Storing debug log for failure in /root/.pip/pip.log

```
I dont know, why python2.7 is mentioned there, python --version returns the version 3.5.2.

**Comment by mayokek** [comment]
Do `sudo -H python3 -m pip install --upgrade -r requirements.txt` 
With `python3`, it's probably that or `python3.5`

**Comment by pdisser8** [comment]
hello,
did you try to set up via pyenv? 
did you set your PATH variable in bash?
I am unaware of how to make pyenv work correctly being new to Linux, and also ran into this problem.

how I fixed it: if you don't care much about breaking your Debian machine you could always compile python 3.5 directly. Check the guide for raspbian to see how to do so.
