### ISSUE TITLE
Suddenly stops working

### ISSUE THREAD

**Issue by IlPicasso** [Just-Some-Bots/MusicBot#1179]
Hello, the bot sudddenly stops working this is the message
`
Autojoining voice chanels:
 - ComuGamers/🎶 Música 🎶

Options:
  Command prefix: *
  Default volume: 15%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Enabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

Attempting to autojoin 🎶 Música 🎶 in ComuGamers

Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at /home/MusicBot/musicbot/player.py:280> exception=TimeoutError()>
Traceback (most recent call last):
  File "/home/MusicBot/musicbot/player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/MusicBot/musicbot/player.py", line 291, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "/home/MusicBot/musicbot/bot.py", line 310, in reconnect_voice_client
    new_vc = await self.get_voice_client(vc.channel)
  File "/home/MusicBot/musicbot/bot.py", line 237, in get_voice_client
    s_id_data = await asyncio.wait_for(s_id, timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
`

**Comment by jayktaylor** [comment]
This is a Discord issue, but may be helped by recent updates to the bot - try updating your bot and dependencies.
