### ISSUE TITLE
[BUG] User with "(╭ರᴥ•́)" character in their are not recognize by the bot.

### ISSUE THREAD

**Issue by Loupning** [Just-Some-Bots/MusicBot#119]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 283, in _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "C:\Users\micha\Desktop\MusicBot-develop\musicbot\bot.py", line 709, in on_message
    print("[Command] {0.id}/{0.name} ({1})".format(message.author, message_content))
  File "C:\Users\micha\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 42-46: character maps to <undefined>

**Comment by imayhaveborkedit** [comment]
Known issue, this should be fixed in review.
