### ISSUE TITLE
Getting an issue that I don't understand

### ISSUE THREAD

**Issue by Esp10n** [Just-Some-Bots/MusicBot#1195]
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py:265> exception=ConnectionClosed('WebSocket connection is closed: code = 1006, no reason.',)>
Traceback (most recent call last):
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 604, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 386, in wait_for
    return fut.result()
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 272, in poll_voice_ws
    yield from self.ws.poll_event()
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 607, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
Error disconnecting during reconnect
Traceback (most recent call last):
  File "C:\Users\Imad\MusicBot\musicbot\player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Imad\MusicBot\musicbot\bot.py", line 302, in reconnect_voice_client
    await vc.disconnect()
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 293, in disconnect
    yield from self.ws.close()
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 242, in close
    self.worker_task, self.timeout, loop=self.loop)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 386, in wait_for
    return fut.result()
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 414, in run
    msg = yield from self.read_message()
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 436, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 491, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 526, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\streams.py", line 509, in readexactly
    block = yield from self.read(n)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\streams.py", line 482, in read
    yield from self._wait_for_data('read')
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\streams.py", line 423, in _wait_for_data
    yield from self._waiter
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\selector_events.py", line 664, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at C:\Users\Imad\MusicBot\musicbot\player.py:280> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\Users\Imad\MusicBot\musicbot\player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Imad\MusicBot\musicbot\player.py", line 291, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "C:\Users\Imad\MusicBot\musicbot\bot.py", line 310, in reconnect_voice_client
    new_vc = await self.get_voice_client(vc.channel)
  File "C:\Users\Imad\MusicBot\musicbot\bot.py", line 238, in get_voice_client
    voice_data = await asyncio.wait_for(_voice_data, timeout=10, loop=self.loop)
  File "C:\Users\Imad\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

No idea what this means...

**Comment by pauldisser** [comment]
did you run update_deps.bat? 

Also, sounds like it cant find the voice channel that its supposed to be connecting to... 
did you follow all the directions on this page?
https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ#how-do-i-create-a-bot-account

and then the directions on this page? so it knows you are the owner and what its token is?
https://github.com/Just-Some-Bots/MusicBot/wiki/Configuration

**Comment by Esp10n** [comment]
It works fine just randomly when I come back to my PC i see these messages on CMD... and i always update_deps.bat whenever i switch on my PC.

**Comment by jayktaylor** [comment]
Try updating the bot and dependencies and seeing if that helps. This is a Discord issue.
