### ISSUE TITLE
music doesnt play

### ISSUE THREAD

**Issue by halabalazar** [Just-Some-Bots/MusicBot#1201]
the bot has been working well for a month but now out of nowhere when i request a song with the !play command it finds the song but it doesnt download any files into audio_cache. This is what the cmd looks like
Connected!  Musicbot v1.9.5_2

Bot:   326122184034746381/evliyababa#1157
Owner: 303104253344612364/halabalazar#8869

Server List:
 - Hexagon'

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !
  Default volume: 15%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

Attempting to autosummon...
Found owner in "Hoşgeldin OROSPU ÇOCUĞU", attempting to join...
Attempting connection...
Connection established.
Done!
Starting auto-playlist

[Download] Started: https://www.youtube.com/watch?v=BB2scW2yuLE
ERROR: giving up after 0 retries
Traceback (most recent call last):
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Users\Berke\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 773, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1562, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1826, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1768, in dl
    return fd.download(name, info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 131, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 602, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 572, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: giving up after 0 retries
Future exception was never retrieved
future: <Future finished exception=ExtractionError(DownloadError('ERROR: giving up after 0 retries',),)>
Traceback (most recent call last):
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Users\Berke\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 773, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1562, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1826, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1768, in dl
    return fd.download(name, info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 131, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 602, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 572, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: giving up after 0 retries
Failed to get entry.
Traceback (most recent call last):
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Users\Berke\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 773, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1562, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1826, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1768, in dl
    return fd.download(name, info)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 131, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 602, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 572, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Berke\MusicBot\musicbot\player.py", line 234, in _play
    entry = await self.playlist.get_next_entry()
  File "C:\Users\Berke\MusicBot\musicbot\playlist.py", line 245, in get_next_entry
    return await entry.get_ready_future()
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Berke\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Users\Berke\MusicBot\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: giving up after 0 retries

**Comment by tahamsaglam** [comment]
Same problem.

**Comment by halabalazar** [comment]
seems fixed thanks anyway
