### ISSUE TITLE
My bot doesnt't know its in a voice channel

### ISSUE THREAD

**Issue by Classified123** [Just-Some-Bots/MusicBot#1223]
Attempting to autosummon...
Found owner in "🎮 Gaming Room 1 🎮", attempting to join...
Traceback (most recent call last):
  File "C:\Users\charlie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\charlie\MusicBot\musicbot\bot.py", line 710, in on_ready
    owner_vc = await self._auto_summon()
  File "C:\Users\charlie\MusicBot\musicbot\bot.py", line 149, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "C:\Users\charlie\MusicBot\musicbot\bot.py", line 1325, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "C:\Users\charlie\MusicBot\musicbot\bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\charlie\MusicBot\musicbot\bot.py", line 249, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "C:\Users\charlie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\voice_client.py", line 217, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

i get that when i attempt to run the bot, when i try to play a song it tells me to summon it

**Comment by TimmyTheRat** [comment]
not an issue, install PyNaCl

**Comment by MeepCastana** [comment]
#386

**Comment by Classified123** [comment]
everything is already like that

**Comment by Classified123** [comment]
but when i update my dependencies i get 
![image](https://user-images.githubusercontent.com/29813110/27761034-91a743fe-5e4c-11e7-9b9b-46a5a784e874.png)

**Comment by Classified123** [comment]
(im using the latest version)
and it wont let me install pynacl

**Comment by MeepCastana** [comment]
Then install 3.5 py

**Comment by Classified123** [comment]
How?

**Comment by Classified123** [comment]
i click on dl and it just takes me to a different page that doesnt even have the dl

**Comment by MeepCastana** [comment]
https://www.python.org/ftp/python/3.5.1/python-3.5.1-amd64.exe - 64

https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe - 32

**Comment by Classified123** [comment]
thx

**Comment by Classified123** [comment]
now its telling me to upgrade pip, but when i do that it tells me its up to date

**Comment by Classified123** [comment]
Nvm it works THANKS

**Comment by TimmyTheRat** [comment]
uninstall ur old py version
