### ISSUE TITLE
[PersistentQueue failure]  line 221, in _delete_file

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#1228]
when I use the persistent queue from the review branch and then try restarting or shutting down it does this

[Logs]
 udio_cache\youtube-CQFGAmiWQmg-Indie_Dance_-_WRLD_-_Little_Too_Close_feat._Veronika_Redd_Monstercat_EP_Release.webm: No such file or directory
[ERROR:player] Error trying to delete audio_cache\youtube-CQFGAmiWQmg-Indie_Dance_-_WRLD_-_Little_Too_Close_feat._Veronika_Redd_Monstercat_EP_Release.webm
Traceback (most recent call last):
  File "E:\Home\Helix\Desktop\Randoms\randoms2\Helixbots\HelixBot\runable\musicbot\player.py", line 221, in _delete_file
    os.unlink(filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'audio_cache\\youtube-CQFGAmiWQmg-Indie_Dance_-_WRLD_-_Little_Too_Close_feat._Veronika_Redd_Monstercat_EP_Release.webm'
-------------------------------------------------------------------------------------------------------------------
[36.096334457] 2017-07-04 01:33:47,346 - INFO - launcher: Starting sanity checks
[36.597013474] 2017-07-04 01:33:47,346 - INFO - launcher: Checking for python 3.5+
[36.597013474] 2017-07-04 01:33:47,346 - INFO - launcher: Checking console encoding
[36.597013474] 2017-07-04 01:33:47,346 - INFO - launcher: Setting console encoding to UTF-8
[37.098169327] 2017-07-04 01:33:47,347 - INFO - launcher: Enabling colors in pycharm pseudoconsole
[37.098169327] 2017-07-04 01:33:47,347 - INFO - launcher: Ensuring we're in the right folder
[38.101434708] 2017-07-04 01:33:47,348 - INFO - launcher: Adding local bins/ folder to path
[40.607929230] 2017-07-04 01:33:47,350 - INFO - launcher: Checks passed.
[40.607929230] 2017-07-04 01:33:47,350 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[2.2524907588958740] 2017-07-04 01:33:49,562 - WARNING - musicbot.config | In config.py::MainThread(9600), line 164 in run_checks: Invalid DebugLevel option "CRITICAL, ERROR, WARNING, INFO, DEBUG, VOICEDEBUG, FFMPEG, NOISY, EVERYTHING" given, falling back to INFO
[2.8174958229064941] 2017-07-04 01:33:50,127 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 215 in _setup_logging: Set logging level to INFO
[2.8179965019226074] 2017-07-04 01:33:50,128 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 77 in __init__: Loaded autoplaylist with 2530 entries
[2.819000006] launcher-INFO: Connecting
[5.4460322856903076] 2017-07-04 01:33:52,756 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 5435 in on_message: 227165660478832641/OzoneHelix#7627: .cclear
[5.4631121158599854] 2017-07-04 01:33:52,773 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 1005 in on_ready: Connection established, ready to go.
[5.4635796546936035] 2017-07-04 01:33:52,773 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 326 in _cache_app_info: Caching app info
[5.6515367031097412] 2017-07-04 01:33:52,961 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 822 in _scheck_ensure_env: Ensuring data folders exist
[5.6545457839965820] 2017-07-04 01:33:52,964 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 832 in _scheck_ensure_env: Deleted old audio cache
[5.6545457839965820] 2017-07-04 01:33:52,964 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 838 in _scheck_server_permissions: Checking server permissions
[5.6545457839965820] 2017-07-04 01:33:52,964 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 842 in _scheck_autoplaylist: Auditing autoplaylist
[5.6550469398498535] 2017-07-04 01:33:52,965 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 846 in _scheck_configs: Validating config
[5.6550469398498535] 2017-07-04 01:33:52,965 - DEBUG - musicbot.config | In config.py::MainThread(9600), line 175 in async_validate: Validating options...
[5.6550469398498535] 2017-07-04 01:33:52,965 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 849 in _scheck_configs: Validating permissions config
[5.6550469398498535] 2017-07-04 01:33:52,965 - DEBUG - musicbot.permissions | In permissions.py::MainThread(9600), line 59 in async_validate: Validating permissions...
[5.6550469398498535] 2017-07-04 01:33:52,965 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1016 in on_ready: Startup Complete! OzoneBot Version 4.2.2 Cloud 9

[5.6550469398498535] 2017-07-04 01:33:52,965 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1026 in on_ready: Bot:   323953046667132938/Devbot#6843 [BOT]
[5.6550469398498535] 2017-07-04 01:33:52,965 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1034 in on_ready: Owner: 227165660478832641/OzoneHelix#7627

[5.6555483341217041] 2017-07-04 01:33:52,965 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1037 in on_ready: Server List:
[5.6555483341217041] 2017-07-04 01:33:52,965 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1038 in <listcomp>:  - Ozone's bots dev
[5.6555483341217041] 2017-07-04 01:33:52,965 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1082 in on_ready: Not bound to any text channels
[5.6555483341217041] 2017-07-04 01:33:52,965 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1108 in on_ready: Not autojoining any voice channels
[5.6560502052307129] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1112 in on_ready: Options:
[5.6560502052307129] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1114 in on_ready:   Command prefix: .
[5.6560502052307129] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1115 in on_ready:   Default volume: 25%
[5.6560502052307129] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1117 in on_ready:   Skip threshold: 4 votes or 50%
[5.6565511226654053] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1118 in on_ready:   Now Playing @mentions: Enabled
[5.6565511226654053] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1119 in on_ready:   Auto-Summon: Disabled
[5.6565511226654053] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1120 in on_ready:   Auto-Playlist: Disabled
[5.6565511226654053] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1121 in on_ready:   Auto-Pause: Enabled
[5.6565511226654053] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1122 in on_ready:   Delete Messages: Enabled
[5.6565511226654053] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1124 in on_ready:     Delete Invoking: Disabled
[5.6565511226654053] 2017-07-04 01:33:52,966 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1125 in on_ready:   Debug Mode: Disabled
[5.6570522785186768] 2017-07-04 01:33:52,967 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1126 in on_ready:   Downloaded songs will be deleted
[5.6570522785186768] 2017-07-04 01:33:52,967 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 254 in _join_startup_channels: Found resumable voice channel Ozone's bots dev/General
[5.6570522785186768] 2017-07-04 01:33:52,967 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 269 in _join_startup_channels: Attempting to join Ozone's bots dev/General
[5.6570522785186768] 2017-07-04 01:33:52,967 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 439 in get_voice_client: Connection attempt 1 to General
[5.6570522785186768] 2017-07-04 01:33:52,967 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 378 in join_voice_channel: (join_voice_channel) creating futures
[5.6575543880462646] 2017-07-04 01:33:52,967 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 384 in join_voice_channel: (join_voice_channel) setting voice state
[5.6575543880462646] 2017-07-04 01:33:52,967 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 387 in join_voice_channel: (join_voice_channel) waiting for session id
[5.7415187358856201] 2017-07-04 01:33:53,051 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 5592 in on_voice_state_update: Resumed voice connection to Ozone's bots dev/General
[5.7420489788055420] 2017-07-04 01:33:53,052 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 5604 in on_voice_state_update: Voice state update for 323953046667132938/Devbot#6843 on Ozone's bots dev/General -> [RESUME, CONNECT]
[5.7420489788055420] 2017-07-04 01:33:53,052 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 391 in join_voice_channel: (join_voice_channel) waiting for voice data
[5.7990860939025879] 2017-07-04 01:33:53,109 - ERROR - musicbot.bot | In bot.py::MainThread(9600), line 5571 in on_message: Exception in on_message
Traceback (most recent call last):
  File "C:\Users\Helix\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 1050, in purge_from
    msg = yield from iterator.iterate()
  File "C:\Users\Helix\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\iterators.py", line 85, in iterate
    return self.messages.get_nowait()
  File "C:\Users\Helix\AppData\Local\Programs\Python\Python35\lib\asyncio\queues.py", line 183, in get_nowait
    raise QueueEmpty
asyncio.queues.QueueEmpty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Home\Helix\Desktop\Randoms\randoms2\Helixbots\BotmainDev2\runable\musicbot\bot.py", line 5542, in on_message
    response = await handler(**handler_kwargs)
  File "E:\Home\Helix\Desktop\Randoms\randoms2\Helixbots\BotmainDev2\runable\musicbot\bot.py", line 5103, in cmd_cclear
    deleted = await self.purge_from(channel, check=check, limit=search_range, before=message)
  File "C:\Users\Helix\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 1056, in purge_from
    yield from self.delete_messages(to_delete)
  File "C:\Users\Helix\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 978, in delete_messages
    yield from self.http.delete_messages(channel.id, message_ids, guild_id)
  File "C:\Users\Helix\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): You can only bulk delete messages that are under 14 days old.
[5.8375234603881836] 2017-07-04 01:33:53,147 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 405 in join_voice_channel: (join_voice_channel) connecting...
[6.7308835983276367] 2017-07-04 01:33:54,041 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 417 in join_voice_channel: (join_voice_channel) connection successful
[6.7308835983276367] 2017-07-04 01:33:54,041 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 465 in get_voice_client: Connected in 1.1s
[6.7308835983276367] 2017-07-04 01:33:54,041 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 466 in get_voice_client: Connected to Ozone's bots dev/General
[6.7313892841339111] 2017-07-04 01:33:54,041 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 799 in deserialize_queue: Deserializing queue for 291818106290962432
[6.9424133300781250] 2017-07-04 01:33:54,252 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 557 in get_player: Created player via deserialization for server 291818106290962432 with 12 entries
[6.9424133300781250] 2017-07-04 01:33:54,252 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 285 in _join_startup_channels: Joined Ozone's bots dev/General
[6.9429142475128174] 2017-07-04 01:33:54,253 - VOICEDEBUG - musicbot.player | In player.py::MainThread(9600), line 313 in websocket_check: Starting websocket check loop for Ozone's bots dev
[6.9429142475128174] 2017-07-04 01:33:54,253 - FFMPEG - musicbot.player | In player.py::MainThread(9600), line 270 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-NQSjzVMBwNs-San_Holo_-_Light_WRLD_Remix.webm
[6.9540057182312012] 2017-07-04 01:33:54,264 - INFO - musicbot.entry | In entry.py::MainThread(9600), line 219 in _really_download: Download started: https://www.youtube.com/watch?v=7fugVGRFqe0
[6.9644732475280762] 2017-07-04 01:33:54,274 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 775 in serialize_queue: Serializing queue for 291818106290962432
[6.9865300655364990] 2017-07-04 01:33:54,296 - FFMPEG - musicbot.player | In player.py::Thread-6 stderr reader(2636), line 411 in filter_stderr: Data from ffmpeg: b'audio_cache\\youtube-NQSjzVMBwNs-San_Holo_-_Light_WRLD_Remix.webm: No such file or directory\r\n'
[7.0136349201202393] 2017-07-04 01:33:54,323 - DEBUG - musicbot.player | In player.py::MainThread(9600), line 199 in _playback_finished: Deleting file: audio_cache\youtube-NQSjzVMBwNs-San_Holo_-_Light_WRLD_Remix.webm
[7.0292744636535645] 2017-07-04 01:33:54,339 - ERROR - musicbot.player | In player.py::MainThread(9600), line 229 in _delete_file: Error trying to delete audio_cache\youtube-NQSjzVMBwNs-San_Holo_-_Light_WRLD_Remix.webm
Traceback (most recent call last):
  File "E:\Home\Helix\Desktop\Randoms\randoms2\Helixbots\BotmainDev2\runable\musicbot\player.py", line 221, in _delete_file
    os.unlink(filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'audio_cache\\youtube-NQSjzVMBwNs-San_Holo_-_Light_WRLD_Remix.webm'
[7.0402762889862061] 2017-07-04 01:33:54,350 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 775 in serialize_queue: Serializing queue for 291818106290962432
[7.0874018669128418] 2017-07-04 01:33:54,397 - INFO - musicbot.entry | In entry.py::MainThread(9600), line 219 in _really_download: Download started: https://www.youtube.com/watch?v=ofCY5Sfgvbo
[11.5515379905700684] 2017-07-04 01:33:58,861 - INFO - musicbot.entry | In entry.py::MainThread(9600), line 226 in _really_download: Download complete: https://www.youtube.com/watch?v=7fugVGRFqe0
[11.5535433292388916] 2017-07-04 01:33:58,863 - FFMPEG - musicbot.player | In player.py::MainThread(9600), line 270 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-7fugVGRFqe0-Indie_Dance_-_WRLD_-_Awake_feat._Colordrive_Monstercat_EP_Release.webm
[11.5625681877136230] 2017-07-04 01:33:58,872 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 775 in serialize_queue: Serializing queue for 291818106290962432
[11.5966584682464600] 2017-07-04 01:33:58,906 - FFMPEG - musicbot.player | In player.py::Thread-9 stderr reader(16692), line 411 in filter_stderr: Data from ffmpeg: b'[s16le @ 00f14ac0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2216 >= 2191\r\n'
[12.6792066097259521] 2017-07-04 01:33:59,989 - INFO - musicbot.entry | In entry.py::MainThread(9600), line 226 in _really_download: Download complete: https://www.youtube.com/watch?v=ofCY5Sfgvbo
[15.0398216247558594] 2017-07-04 01:34:02,349 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 5435 in on_message: 227165660478832641/OzoneHelix#7627: .restart
[15.8456826210021973] 2017-07-04 01:34:03,155 - DEBUG - musicbot.player | In player.py::MainThread(9600), line 199 in _playback_finished: Deleting file: audio_cache\youtube-7fugVGRFqe0-Indie_Dance_-_WRLD_-_Awake_feat._Colordrive_Monstercat_EP_Release.webm
[16.0475492477416992] 2017-07-04 01:34:03,357 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 5604 in on_voice_state_update: Voice state update for 323953046667132938/Devbot#6843 on Ozone's bots dev/General -> [DISCONNECT]
[16.0816392898559570] 2017-07-04 01:34:03,391 - WARNING - musicbot.config | In config.py::MainThread(9600), line 164 in run_checks: Invalid DebugLevel option "CRITICAL, ERROR, WARNING, INFO, DEBUG, VOICEDEBUG, FFMPEG, NOISY, EVERYTHING" given, falling back to INFO
[16.0946733951568604] 2017-07-04 01:34:03,404 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 180 in _setup_logging: Skipping logger setup, already set up
[16.0946733951568604] 2017-07-04 01:34:03,404 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 77 in __init__: Loaded autoplaylist with 2530 entries
[16.095174789] launcher-INFO: Connecting
[18.7838685512542725] 2017-07-04 01:34:06,094 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 1005 in on_ready: Connection established, ready to go.
[18.7843706607818604] 2017-07-04 01:34:06,094 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 326 in _cache_app_info: Caching app info
[18.8668460845947266] 2017-07-04 01:34:06,176 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 822 in _scheck_ensure_env: Ensuring data folders exist
[18.8709027767181396] 2017-07-04 01:34:06,181 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 834 in _scheck_ensure_env: Could not delete old audio cache, moving on.
[18.8714041709899902] 2017-07-04 01:34:06,181 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 838 in _scheck_server_permissions: Checking server permissions
[18.8714041709899902] 2017-07-04 01:34:06,181 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 842 in _scheck_autoplaylist: Auditing autoplaylist
[18.8719060420989990] 2017-07-04 01:34:06,182 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 846 in _scheck_configs: Validating config
[18.8723635673522949] 2017-07-04 01:34:06,182 - DEBUG - musicbot.config | In config.py::MainThread(9600), line 175 in async_validate: Validating options...
[18.8723635673522949] 2017-07-04 01:34:06,182 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 849 in _scheck_configs: Validating permissions config
[18.8723635673522949] 2017-07-04 01:34:06,182 - DEBUG - musicbot.permissions | In permissions.py::MainThread(9600), line 59 in async_validate: Validating permissions...
[18.8729081153869629] 2017-07-04 01:34:06,183 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1016 in on_ready: Startup Complete! OzoneBot Version 4.2.2 Cloud 9

[18.8733673095703125] 2017-07-04 01:34:06,183 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1026 in on_ready: Bot:   323953046667132938/Devbot#6843 [BOT]
[18.8738996982574463] 2017-07-04 01:34:06,184 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1034 in on_ready: Owner: 227165660478832641/OzoneHelix#7627

[18.8738996982574463] 2017-07-04 01:34:06,184 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1037 in on_ready: Server List:
[18.8744013309478760] 2017-07-04 01:34:06,184 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1038 in <listcomp>:  - Ozone's bots dev
[18.8749027252197266] 2017-07-04 01:34:06,185 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1082 in on_ready: Not bound to any text channels
[18.8749027252197266] 2017-07-04 01:34:06,185 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1108 in on_ready: Not autojoining any voice channels
[18.8754024505615234] 2017-07-04 01:34:06,185 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1112 in on_ready: Options:
[18.8754024505615234] 2017-07-04 01:34:06,185 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1114 in on_ready:   Command prefix: .
[18.8759036064147949] 2017-07-04 01:34:06,186 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1115 in on_ready:   Default volume: 25%
[18.8763723373413086] 2017-07-04 01:34:06,186 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1117 in on_ready:   Skip threshold: 4 votes or 50%
[18.8763723373413086] 2017-07-04 01:34:06,186 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1118 in on_ready:   Now Playing @mentions: Enabled
[18.8769063949584961] 2017-07-04 01:34:06,187 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1119 in on_ready:   Auto-Summon: Disabled
[18.8769063949584961] 2017-07-04 01:34:06,187 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1120 in on_ready:   Auto-Playlist: Disabled
[18.8774092197418213] 2017-07-04 01:34:06,187 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1121 in on_ready:   Auto-Pause: Enabled
[18.8774092197418213] 2017-07-04 01:34:06,187 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1122 in on_ready:   Delete Messages: Enabled
[18.8779094219207764] 2017-07-04 01:34:06,188 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1124 in on_ready:     Delete Invoking: Disabled
[18.8784213066101074] 2017-07-04 01:34:06,188 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1125 in on_ready:   Debug Mode: Disabled
[18.8784213066101074] 2017-07-04 01:34:06,188 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1126 in on_ready:   Downloaded songs will be deleted
[19.7434399127960205] 2017-07-04 01:34:07,053 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 5435 in on_message: 227165660478832641/OzoneHelix#7627: .join
[19.8387589454650879] 2017-07-04 01:34:07,148 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 1846 in cmd_join: Joining Ozone's bots dev/General
[19.8387589454650879] 2017-07-04 01:34:07,148 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 439 in get_voice_client: Connection attempt 1 to General
[19.8387589454650879] 2017-07-04 01:34:07,148 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 378 in join_voice_channel: (join_voice_channel) creating futures
[19.8387589454650879] 2017-07-04 01:34:07,148 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 384 in join_voice_channel: (join_voice_channel) setting voice state
[19.8392925262451172] 2017-07-04 01:34:07,149 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 387 in join_voice_channel: (join_voice_channel) waiting for session id
[19.9222650527954102] 2017-07-04 01:34:07,232 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 5604 in on_voice_state_update: Voice state update for 323953046667132938/Devbot#6843 on Ozone's bots dev/General -> [JOIN, CONNECT]
[19.9222650527954102] 2017-07-04 01:34:07,232 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 5615 in on_voice_state_update: 323953046667132938/Devbot#6843 has joined Ozone's bots dev/General
[19.9227676391601562] 2017-07-04 01:34:07,232 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 391 in join_voice_channel: (join_voice_channel) waiting for voice data
[20.0183384418487549] 2017-07-04 01:34:07,328 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 405 in join_voice_channel: (join_voice_channel) connecting...
[20.9026792049407959] 2017-07-04 01:34:08,212 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 417 in join_voice_channel: (join_voice_channel) connection successful
[20.9026792049407959] 2017-07-04 01:34:08,212 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 465 in get_voice_client: Connected in 1.1s
[20.9026792049407959] 2017-07-04 01:34:08,212 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 466 in get_voice_client: Connected to Ozone's bots dev/General
[20.9031357765197754] 2017-07-04 01:34:08,213 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 799 in deserialize_queue: Deserializing queue for 291818106290962432
[20.9703433513641357] 2017-07-04 01:34:08,280 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 557 in get_player: Created player via deserialization for server 291818106290962432 with 11 entries
[20.9703433513641357] 2017-07-04 01:34:08,280 - VOICEDEBUG - musicbot.player | In player.py::MainThread(9600), line 313 in websocket_check: Starting websocket check loop for Ozone's bots dev
[20.9708478450775146] 2017-07-04 01:34:08,280 - FFMPEG - musicbot.player | In player.py::MainThread(9600), line 270 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-7fugVGRFqe0-Indie_Dance_-_WRLD_-_Awake_feat._Colordrive_Monstercat_EP_Release.webm
[20.9793653488159180] 2017-07-04 01:34:08,289 - INFO - musicbot.entry | In entry.py::MainThread(9600), line 195 in _download: Download cached: https://www.youtube.com/watch?v=ofCY5Sfgvbo
[20.9798684120178223] 2017-07-04 01:34:08,290 - DEBUG - musicbot.bot | In bot.py::MainThread(9600), line 775 in serialize_queue: Serializing queue for 291818106290962432
[21.0099201202392578] 2017-07-04 01:34:08,320 - FFMPEG - musicbot.player | In player.py::Thread-15 stderr reader(14888), line 411 in filter_stderr: Data from ffmpeg: b'[s16le @ 00d64ac0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2216 >= 2191\r\n'
[36.1525225639343262] 2017-07-04 01:34:23,462 - INFO - musicbot.bot | In bot.py::MainThread(9600), line 5435 in on_message: 227165660478832641/OzoneHelix#7627: .shutdown
[36.2540419101715088] 2017-07-04 01:34:23,564 - DEBUG - musicbot.player | In player.py::MainThread(9600), line 199 in _playback_finished: Deleting file: audio_cache\youtube-7fugVGRFqe0-Indie_Dance_-_WRLD_-_Awake_feat._Colordrive_Monstercat_EP_Release.webm
[36.4530267715454102] 2017-07-04 01:34:23,763 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(9600), line 5604 in on_voice_state_update: Voice state update for 323953046667132938/Devbot#6843 on Ozone's bots dev/General -> [DISCONNECT]
[36.493829727] launcher-INFO: All done.

**Comment by OzzyHelix** [comment]
not sure whats up from what I've tested it seems to be deleting the audio_cache folder ever time it restarts even with Persistent queue enabled

**Comment by OzzyHelix** [comment]
also forgive me I was just playing around with the review branch version of the bot and this happened

**Comment by rdnt** [comment]
Please kindly close the issue if the problem has been resolved.

**Comment by OzzyHelix** [comment]
@ShtHappens796  it has not been resolved

**Comment by OzzyHelix** [comment]
@ShtHappens796 I am just trying to get help with this issue so again the issue is not resolved and I mean this with great respect

**Comment by rdnt** [comment]
@Helixrelic45 Could you show me your cache folder directory? It could be that those files have the .part extention on their back. I can't be sure until I see it though.

**Comment by OzzyHelix** [comment]
@ShtHappens796  here
![a2601c011820cd056b4b1e8a65366a41](https://user-images.githubusercontent.com/29835364/27866379-14c0743a-6164-11e7-8a28-5fc7c8ef1324.png)

**Comment by OzzyHelix** [comment]
its a .webm extention

**Comment by ShtHappens796** [comment]
![image](https://user-images.githubusercontent.com/17600197/27945941-f30fd106-62f7-11e7-9266-38bf568744e3.png)
The files are clearly not the same. Delete the contents of the audio_cache folder. The issue must be in the search function.

**Comment by rdnt** [comment]
The files are clearly not the same. Delete the contents of the audio_cache folder. The issue must be in the search function.
![image](https://user-images.githubusercontent.com/17600197/27945966-1ab72524-62f8-11e7-976c-2edc46bb5f9b.png)

**Comment by OzzyHelix** [comment]
Forgive me I had just gotten to bed after trying to figure out the issue for 48 hours it would be helpful if you would know where it might be in the search fuction again I've attempted fixing it myself with little sucess

**Comment by OzzyHelix** [comment]
Most llikely I will look into this tomorrow and look in the search fuction and see if I end up fixing it I will make make a pull request and close this

**Comment by rdnt** [comment]
The bot doesn't seem to be actively maintained so I would assume your pull request will never make it on the develop branch. You are free to try though. Also, I can't replicate the issue so it would be vital for you to be able to replicate it and tell the steps necessary. Any debugging will be impossible otherwise.

**Comment by OzzyHelix** [comment]
Forgive me if I never mention this the version of the bot I am using is from the review branch and I have the video saving feature disabled and persistentqueue on the bug seems to be when I use it with video saving off it it deletes the audiophile and cache before the bot can queue them

**Comment by OzzyHelix** [comment]
So if I am to tell you the parameters in which I used it the parameter is being video saving off and persistentqueue on and for instance you queue like a playlist from YouTube then the audio cash is deleted before it can do anything with it and forgive me for the typos it's difficult for me to type on my phone so I am trying to use the voice recognition

**Comment by Helixrelic45** [comment]
Also don't worry I didn't plan on sleeping tonight

**Comment by OzzyHelix** [comment]
so in the config.ini file I used these configs just to make sure that what I used was clear
PersisentQueue= yes
SaveVideos = no

**Comment by rdnt** [comment]
The video saving option is exactly what keeps the cache inside the audio_cache folder. Enable it, see results.

**Comment by OzzyHelix** [comment]
I have already tested it it makes PersisentQueue Work correctly however enabling savevideos eats up hard drive space and I turned it off so it wouldn't do that forgive me if i seem like I'm being rude I'm just slightly tired

**Comment by rdnt** [comment]
The video saving option saves the downloaded mp3/webm/m4a files. It is not saving videos. In order to maintain the cache folder it needs to keep audio files. That is why it will indeed eat disk space. I have it on and it keeps audio_cache intact upon restart of the bot.

**Comment by OzzyHelix** [comment]
but I can get a screenshot of the bot running in debug mode in pycham 
![86eb82a92349fc5d769f63e9e7b5b3dc](https://user-images.githubusercontent.com/29835364/27947663-d3b860d0-62c4-11e7-8bad-0091ceb2a808.png)

**Comment by OzzyHelix** [comment]
which in fact that does work I'm mostly trying to find a solution to fix it so it does not need to be dependent
on saving videos

**Comment by OzzyHelix** [comment]
I figured that persisentqueue being dependent on savingvideos should not be like that

**Comment by OzzyHelix** [comment]
I also thought bring this issue up might be good to point out

**Comment by OzzyHelix** [comment]
also I have two accounts on my computer that I use so the jellco account is my brothers account

**Comment by OzzyHelix** [comment]
I'll work on this tomorrow I have to get some sleep
