### ISSUE TITLE
OS Error: running on Win10 32 bit

### ISSUE THREAD

**Issue by boomchekawowow** [Just-Some-Bots/MusicBot#123]
I can run my bot and get it into a server but when i wanna play a song it doesn't work.
it adds the song to the queue, but then it says it can't play it and this comes up on the cmd.exe

```
Connected!

Username: xxxxxxxxx
Bot ID: xxxxxxxxx
Owner ID: xxxxxxxxxxxx

Command prefix is !
Whitelist check is disabled
Skip threshold at 7 votes or 50%
Now Playing message @mentions are disabled
Autosummon is enabled
Auto-playlist is disabled
Downloaded songs will be deleted after playback

--Server List--
Pingaz and Chill
erssdfs

Owner not found in a voice channel, could not autosummon.
[Command] 92166903966994432/xxxxxxxx (!summon)
[Command] 92166903966994432/xxxxxxxx (!play https://www.youtube.com/watch?v=lpIe95cS2JM)
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at D:\Users\xxxxx\Desktop\MusicBot-develop\musicbot\player.py:126> exception=OSError(22, "This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher", None, 216, None)>
Traceback (most recent call last):
  File "D:\Users\xxxxxx\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\Users\xxxxxx\Desktop\MusicBot-develop\musicbot\player.py", line 159, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "D:\Users\xxxxxx\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 412, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE)
  File "D:\Users\xxxxxx\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "D:\Users\xxxxxx\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

```

**Comment by imayhaveborkedit** [comment]
You have 32 bit windows and that version of ffmpeg is 64 bit.  In any case, use https://github.com/SexualRhinoceros/MusicBot/releases/tag/v1.9.5rc3 instead.  The actual update will be pushed soon.
