### ISSUE TITLE
discord music-bot error plz help

### ISSUE THREAD

**Issue by leemg95** [Just-Some-Bots/MusicBot#1261]
Requested Python version (3.5) not installed

C:\Users\Administrator\Desktop\MusicBot-master\MusicBot-master>run.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MusicBot-master\MusicBot-master\run.py", line 163, in main
    m = MusicBot()
  File "C:\Users\Administrator\Desktop\MusicBot-master\MusicBot-master\musicbot\bot.py", line 76, in __init__
    self.permissions = Permissions(perms_file, grant_all=[self.config.owner_id])
  File "C:\Users\Administrator\Desktop\MusicBot-master\MusicBot-master\musicbot\permissions.py", line 30, in __init__
    if not self.config.read(config_file, encoding='utf-8'):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 3220: invalid start byte

C:\Users\Administrator\Desktop\MusicBot-master\MusicBot-master>

**Comment by MeepCastana** [comment]
You need python version 3.5

**Comment by IceViper04** [comment]
You have to download Python 3.5.0 for the bot to be able to function. Why you need Python 3.5.0 is because the bot was made in that program so it has to be ran in the same environment. You can get Python 3.5.0 on these links below:

For Mac operating system: [Click this blue text](https://www.python.org/ftp/python/3.5.0/python-3.5.0-macosx10.6.pkg)
For Windows operating system: [Click this blue text](https://www.python.org/ftp/python/3.5.0/python-3.5.0.exe)

**Comment by jayktaylor** [comment]
Follow the guides properly, rather than directly downloading the bot.
