### ISSUE TITLE
Unable to play any Songs

### ISSUE THREAD

**Issue by cesarubejr** [Just-Some-Bots/MusicBot#1266]
I'm unable to play any songs. I get the following error:

PermissionError: [WinError 5] Access is denied: 'audio_cache'
Failed to get entry.
Traceback (most recent call last):
  File "C:\Users\MusicBot\musicbot\player.py", line 234, in _play
    entry = await self.playlist.get_next_entry()
  File "C:\Users\MusicBot\musicbot\playlist.py", line 245, in get_next_entry
    return await entry.get_ready_future()
  File "C:\Users\junio\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\junio\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\junio\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\MusicBot\musicbot\entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "C:\Users\junio\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'audio_cache'

**Comment by Zenrac** [comment]
PermissionError: [WinError 5] Access is denied: 'audio_cache'

Run run.bat **as admin**, otherwise try to open terminal (as admin) and use a command like `takeown /F path /R`

**Comment by cesarubejr** [comment]
@zenrac Thank you that did it for me
