### ISSUE TITLE
I couldnt run the bot

### ISSUE THREAD

**Issue by Reycid** [Just-Some-Bots/MusicBot#1285]
Im totallt new at this and i dont have any idea.I did everything what guide said to me but somehow i cant run the bot.
`No module named 'discord'
Attempting to install dependencies...
Collecting discord.py[voice]~=0.12.0 (from -r requirements.txt (line 1))
  Using cached discord.py-0.12.0.zip
Collecting youtube-dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2017.7.30.1-py2.py3-none-any.whl
Collecting pip (from -r requirements.txt (line 3))
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting cffi==1.6.0 (from -r requirements.txt (line 4))
  Using cached cffi-1.6.0-cp35-none-win_amd64.whl
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached aiohttp-1.0.5.tar.gz
Collecting websockets<4.0,>=3.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached websockets-3.3-py33.py34.py35.py36-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1-cp35-none-win_amd64.whl
Collecting pycparser (from cffi==1.6.0->-r requirements.txt (line 4))
  Using cached pycparser-2.18.tar.gz
Requirement already up-to-date: chardet in c:\users\mustafa elçin\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: multidict>=2.0 in c:\users\mustafa elçin\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Requirement already up-to-date: async-timeout in c:\users\mustafa elçin\appdata\local\programs\python\python35\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Collecting six (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: aiohttp, websockets, pycparser, cffi, six, PyNaCl, discord.py, youtube-dl, pip
  Running setup.py install for aiohttp
Exception:
Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\compat\__init__.py", line 47, in console_to_str
    return s.decode(sys.__stdout__.encoding)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\encodings\cp65001.py", line 17, in decode
    return codecs.code_page_decode(65001, input, errors, True)
UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 311, in run
    root=options.root_path,
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 646, in install
    **kwargs
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 852, in install
    show_stdout=False,
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 711, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\compat\__init__.py", line 49, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 55: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 344, in run
    requirement_set.cleanup_files()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 591, in cleanup_files
    req.remove_temporary_source()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 923, in remove_temporary_source
    rmtree(self.source_dir)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\six.py", line 659, in reraise
    raise value
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 90, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 387, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor: 'C:\\Users\\MUSTAF~1\\AppData\\Local\\Temp\\pip-build-woqoipd9\\aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 344, in run
    requirement_set.cleanup_files()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\six.py", line 659, in reraise
    raise value
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 90, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 387, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor: 'C:\\Users\\MUSTAF~1\\AppData\\Local\\Temp\\pip-build-woqoipd9\\aiohttp'
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

You may need to run as admin to install dependencies.`

I tried to use that code in python it said syntax error and i dont have dependencies in my bot folder.

**Comment by MeepCastana** [comment]
run the dependencies as administrator

**Comment by Reycid** [comment]
where is it? in the bots folder? i cant find it
i think you mean update_deps right? i clicked it and here is the codes:
`Exception:
Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\compat\__init__.py", line 47, in console_to_str
    return s.decode(sys.__stdout__.encoding)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\encodings\cp857.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0xe7 in position 55: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 311, in run
    root=options.root_path,
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 646, in install
    **kwargs
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 852, in install
    show_stdout=False,
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 711, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\compat\__init__.py", line 49, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 55: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 344, in run
    requirement_set.cleanup_files()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 591, in cleanup_files
    req.remove_temporary_source()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 923, in remove_temporary_source
    rmtree(self.source_dir)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\six.py", line 659, in reraise
    raise value
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 90, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 387, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor: 'C:\\Users\\MUSTAF~1\\AppData\\Local\\Temp\\pip-build-qdxlp5zu\\aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 344, in run
    requirement_set.cleanup_files()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\six.py", line 659, in reraise
    raise value
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 90, in rmtree
    onerror=rmtree_errorhandler)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 387, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\Mustafa Elçin\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 32] Dosya başka bir işlem tarafından kullanıldığından bu işlem dosyaya erişemiyor: 'C:\\Users\\MUSTAF~1\\AppData\\Local\\Temp\\pip-build-qdxlp5zu\\aiohttp'
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by MeepCastana** [comment]
You should consider upgrading via the 'python -m pip install --upgrade pip' command.` 

Do that

**Comment by Reycid** [comment]
>>> python -m pip install --upgrade pip' command
  File "<stdin>", line 1
    python -m pip install --upgrade pip' command
                ^
SyntaxError: invalid syntax

**Comment by MeepCastana** [comment]
python -m pip install --upgrade pip without command
