### ISSUE TITLE
Music Bot Can't Maintain Connection To Voice Channel

### ISSUE THREAD

**Issue by glitterboye** [Just-Some-Bots/MusicBot#1308]
Whenever I summon the bot, It says:

Attempting connection...
Traceback (most recent call last):
  File "/Users/Main/Desktop/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (1/3)...
Attempting connection...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/gateway.py", line 604, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/websockets/protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Main/Desktop/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/voice_client.py", line 256, in connect
    yield from self.ws.poll_event()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/gateway.py", line 607, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..
Failed to connect, retrying (2/3)...
Attempting connection...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/gateway.py", line 604, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/websockets/protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Main/Desktop/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/voice_client.py", line 256, in connect
    yield from self.ws.poll_event()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/gateway.py", line 607, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..
Failed to connect, retrying (3/3)...
Exception in on_ready

An error has occured:

  Problem:  Cannot establish connection to voice chat.  Something may be                    blocking outgoing UDP connections.                                  
  Solution: This may be an issue with a firewall blocking UDP.  Figure out what             is blocking UDP and disable it.  It's most likely a system firewall             or overbearing anti-virus firewall.   

I have no firewall active, and it has never done this before. It does not respond to commands and just keeps leaving and joining the same voice channel

**Comment by LGSK** [comment]
I've got the same problem here.  Tried to update  "python3.5 -m pip install -U -r requirements.txt
" but it doesnt work for me.

**Comment by karb0n13** [comment]
Same here

**Comment by Xerionty** [comment]
Same here for a long time now.

**Comment by GTXSam** [comment]
Same here

**Comment by Zenrac** [comment]
Same

**Comment by toplez** [comment]
same here

**Comment by jayktaylor** [comment]
Try updating the bot and seeing if that helps. Unfortunately this is mostly an issue on Discord's end and we can't do too much to help with it.
