### ISSUE TITLE
Getting a crash heres the stack trace sorry for terrible formatting

### ISSUE THREAD

**Issue by dfletch642** [Just-Some-Bots/MusicBot#131]
[Command] 126493960586657793/Terra (!play https://www.youtube.com/watch?v=pRjOSifI1-k)
[Command] 126493960586657793/Terra (!skip)
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 87, in run
    data = self.buff.read(self.frame_size)
  File "C:\Users\unversedruid\Desktop\MusicBot-1.9.5rc5\musicbot\player.py", line 24, in read
    frame = self.buff.read(frame_size)
ValueError: PyMemoryView_FromBuffer(): info->buf must not be NULL

[Command] 122821659739684867/unversedruid (!play https://www.youtube.com/watch?v=UYZFElaVaAE)
Task was destroyed but it is pending!
task: <Task pending coro=<_run_event() done, defined at C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py:264> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(748)(), Task._wakeup()]>>
Task exception was never retrieved
future: <Task finished coro=<Client.keep_alive_handler() done, defined at C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py:287> exception=InvalidState('Cannot write to a WebSocket in the CLOSING state',)>
Traceback (most recent call last):
  File "C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 298, in keep_alive_handler
    yield from self._send_ws(utils.to_json(payload))
  File "C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 161, in _send_ws
    yield from self.ws.send(data)
  File "C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 261, in send
    yield from self.write_frame(opcode, data)
  File "C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 421, in write_frame
    "in the {} state".format(self.state_name))
websockets.exceptions.InvalidState: Cannot write to a WebSocket in the CLOSING state
Task was destroyed but it is pending!
task: <Task pending coro=<VoiceClient.keep_alive_handler() running at C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py:194> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.run() running at C:\Users\unversedruid\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py:302> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by arunesh90** [comment]
Execute update_deps.bat and see if that fixes it

**Comment by imayhaveborkedit** [comment]
I am told that this is a precondition violation in the CPython source, meaning there's nothing I can do about this.  I don't know what causes this to happen or what to do about it, but unless this happens consistently you'll just have to restart the bot to fix it until I create a reloading/restart function.
