### ISSUE TITLE
[Errno -2] Cannot connect to host discordapp.com:443 ssl:True [Name or service not known]

### ISSUE THREAD

**Issue by GTXSam** [Just-Some-Bots/MusicBot#1323]
I'm not sure if this a DNS issue or something. I read previous Issues on this but that was regarding Certificate mismatches from Comodo (which I have downloaded updated as a root cert)

**What I'm running:**
Debian Jessie 8.7
Python 3.5.2
on an OVH Server

The bot used to work a couple of days ago, it returns this error now.
The error is shown below:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 165, in main
    m.run()
  File "/home/auro/MusicBot/musicbot/bot.py", line 551, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/discord/client.py", line 458, in start
    yield from self.login(*args, **kwargs)
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/discord/client.py", line 384, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/discord/client.py", line 335, in _login_2
    yield from self.http.email_login(email, password)
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/discord/http.py", line 180, in email_login
    data = yield from self.post(self.LOGIN, json=payload, bucket=_func_())
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/site-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno -2] Cannot connect to host discordapp.com:443 ssl:True [Name or service not known]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2da0a09d68>
```

**Comment by GTXSam** [comment]
Had to update DNS nameservers. Fixed :)

**Comment by aiosin** [comment]
I'm encountering the same issue in aiohttp, what exact steps did you perform ?
