### ISSUE TITLE
await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)

### ISSUE THREAD

**Issue by GTXSam** [Just-Some-Bots/MusicBot#1324]
Sorry for creating another thread. Unrelated issue I can't seem to get around.
The bot folder is full permissions to root along with its files (chown root).
Updated dependencies to the latest, to no avail, can anyone help?

**Error below:**
```
Attempting to autojoin 🎶 Music and Voice in UΣ❥ - United Empire
Attempting connection...
Traceback (most recent call last):
  File "/home/auro/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/home/auro/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (1/3)...
Attempting connection...

```

**Comment by Deady99** [comment]
Having the same Problem.... :-(

**Comment by jayktaylor** [comment]
#1326
