### ISSUE TITLE
Bot keeps crashing

### ISSUE THREAD

**Issue by hawicky** [Just-Some-Bots/MusicBot#1326]
These lines of code appear every time it crashes, I don't have much experience so please take it easy. 
Despite it saying "Connected!", it doesn't, it refuses to join by !summon, but still listens to commands such as "!play" etc.
Thanks.

Traceback (most recent call last):
  File "C:\Users\legom\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\legom\MusicBot\musicbot\player.py", line 291, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "C:\Users\legom\MusicBot\musicbot\bot.py", line 310, in reconnect_voice_client
    new_vc = await self.get_voice_client(vc.channel)
  File "C:\Users\legom\MusicBot\musicbot\bot.py", line 237, in get_voice_client
    s_id_data = await asyncio.wait_for(s_id, timeout=10, loop=self.loop)
  File "C:\Users\legom\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Connected!  Musicbot v1.9.5_2

**Comment by jayktaylor** [comment]
This is an occasional issue with Discord. You can try updating the bot to the latest version that was just released to see if that helps.
