### ISSUE TITLE
ClientException('ffmpeg/avconv was not found in your PATH environment variable',)

### ISSUE THREAD

**Issue by arcturus1259** [Just-Some-Bots/MusicBot#1331]
the bot can connect to discord and join the correct channel. it even starts the download on the music. but when it goes to play the music, i get errors (listed below):

```
pi@raspberrypi:~/Musicbot $ sudo python3.6 run.py
Connected!  Musicbot v1.9.5_2

Bot:   335163438776975360/MusicBOT#3449
Owner: 171691421407903744/arcturus125#1892

Server List:
 - ð‘¨ð“»ð“¬ð“´ð“±ð“ªð“¶'ð“¼ ð•¯ð–šð–“ð–Œð–Šð–”ð–“
 - ð‘¨ð“»ð“¬ð“´ð“±ð“ªð“¶'ð“¼ Music

Bound to text channels:
 - ð‘¨ð“»ð“¬ð“´ð“±ð“ªð“¶'ð“¼ ð•¯ð–šð–“ð–Œð–Šð–”ð–“/music_bot
 - ð‘¨ð“»ð“¬ð“´ð“±ð“ªð“¶'ð“¼ Music/music_requests

Autojoining voice chanels:
 - ð‘¨ð“»ð“¬ð“´ð“±ð“ªð“¶'ð“¼ ð•¯ð–šð–“ð–Œð–Šð–”ð–“/Music Room

Options:
  Command prefix: !
  Default volume: 15%
  Skip threshold: 2 votes or 100%
  Now Playing @mentions: Enabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Disabled
  Debug Mode: Disabled
  Downloaded songs will be deleted

Deleting old audio cache
Attempting to autojoin Music Room in ð‘¨ð“»ð“¬ð“´ð“±ð“ªð“¶'ð“¼ ð•¯ð–šð–“ð–Œð–Šð–”ð–“
Attempting connection...
Connection established.

[Download] Started: https://www.youtube.com/watch?v=bpOSxM0rNPM
[Download] Complete: https://www.youtube.com/watch?v=bpOSxM0rNPM
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/pi/Musicbot/musicbot/player.py:221> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/voice_client.py", line 427, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Musicbot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.6/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable
```
on the guide to raspbian, i followed the instructions perfectly on how to install FFmpeg, i even went back and reinstalled it just in case i did something wrong. but i still got errors.

**Comment by jayktaylor** [comment]
Look into https://wiki.debian.org/ffmpeg#Installation for install steps for your system as it seems that ffmpeg isn't installed properly. As this isn't really an issue we can solve, I'm going to close this.
