### ISSUE TITLE
Bot can't connect to Voicechannel

### ISSUE THREAD

**Issue by Deady99** [Just-Some-Bots/MusicBot#1341]
Hi,

after 3-4 months of using this Bot he can't join a voicechannel anymore since a week....

error in putty:

 ```
[Command] 284352420434280449/Deady (/summon)
Attempting connection...
Traceback (most recent call last):
  File "/home/musicbot/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/opt/python-3.5.2/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (1/3)...
Attempting connection...
Traceback (most recent call last):
  File "/home/musicbot/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/opt/python-3.5.2/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (2/3)...
Attempting connection...
Traceback (most recent call last):
  File "/home/musicbot/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/opt/python-3.5.2/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (3/3)...
<class 'musicbot.exceptions.HelpfulError'>:
An error has occured:

  Problem:  Cannot establish connection to voice chat.  Something may be blocking outgoing UDP connections.
  Solution: This may be an issue with a firewall blocking UDP.  Figure out what is blocking UDP and disable it.  It's most likely a system firewall or overbearing anti-virus firewall.
```

I don't know what i should do now.
I removed the bot and switched to an other server, but there was the same problem.

Please help me
Deady

**Comment by loobing** [comment]
Something is blocking the bot from joining voice channel

**Comment by Deady99** [comment]
But i dont know what :-/
I tested the bot on 2 different servers, the group permissions are always good

**Comment by loobing** [comment]
The bottom says Problem:  Cannot establish connection to voice chat.  Something may be blocking outgoing UDP connections.
 Solution: This may be an issue with a firewall blocking UDP.  Figure out what is blocking UDP and disable it.  It's most likely a system firewall or overbearing anti-virus firewall.

**Comment by Deady99** [comment]
I can read thank you... but i don't know to fix this problem...

**Comment by loobing** [comment]
await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)

Try changing the timeout=10 to 30 it might help if you give it some time to load

**Comment by Flegma** [comment]
Im having the same problem.
It may have something to do with this new category/channels permissions that Discord introduced?

**Comment by granlem** [comment]
Same problem here. Since Sunday last Week (17.09.2017). 
Worked for many months an now it fails to establish voice connection.
Bot is able to join to the channel, but cannot play anything. The output is the same as that of deady99.

We're using a nested KVM (Qemu based) on a dedicated Server from the german provider Hetzner.de .
It seems that our Soundboardbot has the same problem, so it is could be a Discord API problem.

Thanks for help!

**Comment by Alloc86** [comment]
Same here. Suppose no one has a solution yet? Interestingly it seemed to stop working only just yesterday or two days ago at most.

**Comment by RageBoy009** [comment]
Finaly some1 with the same Problems! It's working very rarely like one time out of ten.

**Comment by Alloc86** [comment]
Oh, good find. Can you post the link of where that's from?

**Comment by RageBoy009** [comment]
I got it from the Red bot Discord. Dont know the source since its only a picture they posted.

**Comment by Alloc86** [comment]
Ah, ok, too bad. Would have liked to follow that discussion directly :)
One thread I found about this issue on reddit: https://www.reddit.com/r/discordapp/comments/70dwa6/ip_banned_from_discord/ (last update 12 days ago though)

**Comment by jayktaylor** [comment]
Hetzner's servers were IP banned, not a bot issue.
