### ISSUE TITLE
Musicbot not working on linux server

### ISSUE THREAD

**Issue by DeVriesDevelopment** [Just-Some-Bots/MusicBot#1351]
2017-09-27T21:29:10.568826+00:00 app[worker.1]: Traceback (most recent call last):
2017-09-27T21:29:10.568858+00:00 app[worker.1]:   File "bot.py", line 15, in <module>
2017-09-27T21:29:10.569026+00:00 app[worker.1]:     from modules.player import *
2017-09-27T21:29:10.569057+00:00 app[worker.1]:   File "/app/modules/player.py", line 5, in <module>
2017-09-27T21:29:10.569193+00:00 app[worker.1]:     from lib.musicbot.bot import MusicBot
2017-09-27T21:29:10.569197+00:00 app[worker.1]:   File "/app/lib/musicbot/__init__.py", line 1, in <module>
2017-09-27T21:29:10.569338+00:00 app[worker.1]:     from .bot import MusicBot
2017-09-27T21:29:10.569341+00:00 app[worker.1]:   File "/app/lib/musicbot/bot.py", line 39, in <module>
2017-09-27T21:29:10.569502+00:00 app[worker.1]:     load_opus_lib()
2017-09-27T21:29:10.569519+00:00 app[worker.1]:   File "/app/lib/musicbot/opus_loader.py", line 18, in load_opus_lib
2017-09-27T21:29:10.569672+00:00 app[worker.1]:     raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
2017-09-27T21:29:10.569682+00:00 app[worker.1]: RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib

I am getting this error when trying to run the bot on a linux server. What can i do to fix this?

**Comment by agraubert** [comment]
Try installing the package libopus-dev (via `apt-get` or `yum`, depending on your flavor of linux)

**Comment by jayktaylor** [comment]
The above response should fix this. This is mentioned in our Linux guide.
