### ISSUE TITLE
error when i start the bot

### ISSUE THREAD

**Issue by Razorbackfr** [Just-Some-Bots/MusicBot#1385]
Hi,

When i start the bot, i have the following error in log and the bot is not online : 

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.6236658096313477] 2017-11-01 22:54:58,290 - DEBUG - musicbot.bot | In bot.py::MainThread(139895155418880), line 200 in _setup_logging: Set logging level to CRITICAL
[0.6239581108093262] 2017-11-01 22:54:58,290 - WARNING - musicbot.bot | In bot.py::MainThread (139895155418880), line 74 in __init__: Autoplaylist is empty, disabling.
[0.624775648] launcher-INFO: Connecting
[0.636055470] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 589, in _create_direct_connection
    hosts = yield from self._resolve_host(req.host, req.port)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 561, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/resolver.py", line 29, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 351, in main
    m.run()
  File "/root/MusicBot/musicbot/bot.py", line 939, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 456, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 382, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 312, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 195, in static_login
    data = yield from self.get(self.ME)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno -3] Cannot connect to host discordapp.com:443 ssl:True [Temporary failure in name resolution]
[0.649291992] launcher-INFO: All done.

**Comment by jayktaylor** [comment]
This is an issue with your machine not being able to resolve DNS properly. We can't help you with that here. Look into your networking configuration.
