### ISSUE TITLE
!play <link> error

### ISSUE THREAD

**Issue by Pluginsel** [Just-Some-Bots/MusicBot#1387]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflhqxyp7/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflhqxyp7/en_US/base.js'",))

**Comment by rafaelwastaken** [comment]
Update dependencies

**Comment by Pluginsel** [comment]
@fofofofofofofofoXD how to update dependencies?

**Comment by Pluginsel** [comment]
I'm using Windows 10, and I opened update_deps.bat program and youtube-dl is successfully uninstalled.
But I have this error:
```
Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Collecting youtube_dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2017.10.29-py2.py3-none-any.whl
Requirement already up-to-date: pip in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cffi==1.6.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Collecting websockets<4.0,>=3.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached websockets-3.4-cp35-cp35m-win_amd64.whl
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Collecting pycparser (from cffi==1.6.0->-r requirements.txt (line 4))
  Using cached pycparser-2.18.tar.gz
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached multidict-3.3.2-cp35-cp35m-win_amd64.whl
Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached async_timeout-2.0.0-py3-none-any.whl
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: youtube-dl, websockets, pycparser, multidict, async-timeout, chardet, six
  Found existing installation: youtube-dl 2017.2.28
    Uninstalling youtube-dl-2017.2.28:
      Successfully uninstalled youtube-dl-2017.2.28
  Rolling back uninstall of youtube-dl
Exception:
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Accesso negato: 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\youtube_dl\\extractor'
```

**Comment by Pluginsel** [comment]
@fofofofofofofofoXD
I'm using Windows 10, and I opened update_deps.bat program and youtube-dl is successfully uninstalled.
But I have this error:
```
Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Collecting youtube_dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2017.10.29-py2.py3-none-any.whl
Requirement already up-to-date: pip in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cffi==1.6.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Collecting websockets<4.0,>=3.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached websockets-3.4-cp35-cp35m-win_amd64.whl
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Collecting pycparser (from cffi==1.6.0->-r requirements.txt (line 4))
  Using cached pycparser-2.18.tar.gz
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached multidict-3.3.2-cp35-cp35m-win_amd64.whl
Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached async_timeout-2.0.0-py3-none-any.whl
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: youtube-dl, websockets, pycparser, multidict, async-timeout, chardet, six
  Found existing installation: youtube-dl 2017.2.28
    Uninstalling youtube-dl-2017.2.28:
      Successfully uninstalled youtube-dl-2017.2.28
  Rolling back uninstall of youtube-dl
Exception:
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Permission Danied: 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\youtube_dl\\extractor'
```

**Comment by Pluginsel** [comment]
@fofofofofofofofoXD @Sidesplitter @link2110 @imayhaveborkedit @abalabahaha 
I'm using Windows 10, and I opened update_deps.bat program and youtube-dl is successfully uninstalled.
But I have this error:
`Requirement already up-to-date: discord.py[voice]~=0.12.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Collecting youtube_dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2017.10.29-py2.py3-none-any.whl
Requirement already up-to-date: pip in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: cffi==1.6.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: aiohttp<1.1.0,>=1.0.0 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Collecting websockets<4.0,>=3.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached websockets-3.4-cp35-cp35m-win_amd64.whl
Requirement already up-to-date: PyNaCl==1.0.1 in c:\users\lenovo\appdata\local\programs\python\python35\lib\site-packages (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
Collecting pycparser (from cffi==1.6.0->-r requirements.txt (line 4))
  Using cached pycparser-2.18.tar.gz
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached multidict-3.3.2-cp35-cp35m-win_amd64.whl
Collecting async-timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached async_timeout-2.0.0-py3-none-any.whl
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: youtube-dl, websockets, pycparser, multidict, async-timeout, chardet, six
  Found existing installation: youtube-dl 2017.2.28
    Uninstalling youtube-dl-2017.2.28:
      Successfully uninstalled youtube-dl-2017.2.28
  Rolling back uninstall of youtube-dl
Exception:
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Permission Danied: 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python35\\Lib\\site-packages\\youtube_dl\\extractor'`

**Comment by rafaelwastaken** [comment]
Run as admin

**Comment by itsRems** [comment]
Hey, got the same problem, admin run does not work, any update?

**Comment by Pluginsel** [comment]
@fofofofofofofofoXD @RemsWorldMC 
Run as Admin is not worked, but I fixed with another method.

I uninstalled Python and I re-installed with PATH enabled.
After this, I installed PIP.
And with this is worked. :)

For install PIP, search from google 'how to install PIP with Python'
NOTE: My Python version is 3.5.4

Thanks.
