### ISSUE TITLE
Voice server crashed

### ISSUE THREAD

**Issue by dannymichel** [Just-Some-Bots/MusicBot#1425]
`Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:265> exception=ConnectionClosed('WebSocket connection is closed: code = 4015, reason = Voice server crashed..',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 604, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4015, reason = Voice server crashed..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 272, in poll_voice_ws
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 607, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4015, reason = Voice server crashed..
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at /home/ubuntu/MusicBot/musicbot/player.py:280> exception=TimeoutError()>
Traceback (most recent call last):
  File "/home/ubuntu/MusicBot/musicbot/player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/MusicBot/musicbot/player.py", line 291, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "/home/ubuntu/MusicBot/musicbot/bot.py", line 310, in reconnect_voice_client
    new_vc = await self.get_voice_client(vc.channel)
  File "/home/ubuntu/MusicBot/musicbot/bot.py", line 237, in get_voice_client
    s_id_data = await asyncio.wait_for(s_id, timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
^CTraceback (most recent call last):
  File "run.py", line 224, in <module>
    main()
  File "run.py", line 165, in main
    m.run()
  File "/home/ubuntu/MusicBot/musicbot/bot.py", line 551, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)`

**Comment by jayktaylor** [comment]
This is caused by Discord. I recommend updating the bot if you haven't already, and updating your dependencies too, as discord.py may have better handling for this now, and the bot has better support for reconnects.

**Comment by dannymichel** [comment]
I'm in the review branch and just did a git pull. Update my dependencies by doing apt-get update or...?

**Comment by jayktaylor** [comment]
You should switch to the master branch using git checkout master and then git pull. Then you can update your dependencies using the scripts in the bot folder, e.g update_dependencies.bat for Windows.

**Comment by dannymichel** [comment]
@jaydenkieran this is a ubuntu machine

**Comment by dannymichel** [comment]
i used update_dependencies_linux.sh which worked and switched to master and did a git pull
