### ISSUE TITLE
bot offline no command response

### ISSUE THREAD

**Issue by enigma999** [Just-Some-Bots/MusicBot#1432]
so i installed the bot made the options.ini updated the dependencies

i added the token but wen i run the runbot.bat this is all that happens 

[INFO] launcher: Checking for python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right folder
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Syntax error (this is a bug, not your fault)
Traceback (most recent call last):
  File "run.py", line 344, in main
    from musicbot import MusicBot
  File "C:\Users\Gebruiker\Downloads\MusicBot-master\MusicBot-master\musicbot\__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\voice_client.py", line 64, in <module>
    from . import utils, opus
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\opus.py", line 126
    $ef is_loaded():
    ^
SyntaxError: invalid syntax

[INFO] launcher: All done.

C:\Users\Gebruiker\Downloads\MusicBot-master\MusicBot-master>

after this the bot is still offline and will not reponde to any commands
 what to do?

**Comment by jayktaylor** [comment]
Follow the installation guides in <https://github.com/Just-Some-Bots/MusicBot/wiki>. We don't support those that download the ZIP file - which is the incorrect method of installing the bot.
