### ISSUE TITLE
bot doesn't work on windows & linux (same problem in the 2 system's)

### ISSUE THREAD

**Issue by Hexality** [Just-Some-Bots/MusicBot#1439]
Traceback (most recent call last):
  File "run.py", line 345, in main
    m = MusicBot()
  File "C:\Users\user\MusicBot\musicbot\bot.py", line 61, in __init__
    self.config = Config(config_file)
  File "C:\Users\user\MusicBot\musicbot\config.py", line 17, in __init__
    self.find_config()
  File "C:\Users\user\MusicBot\musicbot\config.py", line 226, in find_config
    if not config.read(self.config_file, encoding='utf-8'):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 3326: invalid start byte

[INFO] launcher: All done.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DE35315518>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DE35315B70>

**Comment by jayktaylor** [comment]
Please provide your logs/musicbot.log file.

**Comment by jayktaylor** [comment]
If you're still having this issue, ask for help on our Discord server: http://discord.gg/bots
