### ISSUE TITLE
what is this DeprecationWarning: change_status is deprecated, use change_presence instead.   await self.change_status(game)

### ISSUE THREAD

**Issue by BannanaHero** [Just-Some-Bots/MusicBot#1487]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_2 of MusicBot

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by BannanaHero** [comment]
what is this DeprecationWarning: change_status is deprecated, use change_presence instead.
  await self.change_status(game)
it only happens when I try to play something long, its getting frustrating trying to queue in songs and then try to put in an album and the whole thing breaks
stops playing altogether after the song its playing...

**Comment by AutumnClove** [comment]
You're using the outdated version use git pull to get the new version with fixes for that and more.

**Comment by BannanaHero** [comment]
alright I did that it worked for a while now

WARNING: Failed to get entry, retrying
Traceback (most recent call last):
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1895, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1834, in dl
    return fd.download(name, info)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 286, in real_download
    establish_connection()
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 676, in http_error_302
    self.inf_msg + msg, headers, fp)
urllib.error.HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shagg\MusicBot\musicbot\entry.py", line 224, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Users\shagg\MusicBot\musicbot\downloader.py", line 86, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1622, in process_video_result
    self.process_info(new_info)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1897, in process_info
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 582, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to download video data: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shagg\MusicBot\musicbot\player.py", line 249, in _play
    entry = await self.playlist.get_next_entry()
  File "C:\Users\shagg\MusicBot\musicbot\playlist.py", line 315, in get_next_entry
    return await entry.get_ready_future()
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\shagg\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\shagg\MusicBot\musicbot\entry.py", line 205, in _download
    await self._really_download()
  File "C:\Users\shagg\MusicBot\musicbot\entry.py", line 227, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to download video data: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found

**Comment by AutumnClove** [comment]
did you run update_debs already? That's about all I got for this error.

**Comment by BannanaHero** [comment]
oh, smh, sorry thanks!
Still got the error even after that
