### ISSUE TITLE
Cant connect windows server 2012 R2

### ISSUE THREAD

**Issue by smokedog77** [Just-Some-Bots/MusicBot#1499]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_2 of MusicBot

----

### Description of issue

Cant connect to my Discord server the bot is running from windows server 2012 R2 dedicated box in a German Data Center.

The bot joins the server and the channel
!play "youtube link" i see the !play link in the console 
But the console just keeps trying to connect

Also made sure Pythons path is pointed to its exe in server 2012 R2

I've opened all UDP ports on outgoing traffic and tried  re-authing the bot with Discord still the same issue persists.

### Steps to reproduce

1. opened all UDP ports on outgoing traffic
2. re authing the bot with Discord

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[47.002077103] 2018-02-04 02:21:42,184 - INFO - launcher: Starting sanity checks
[48.002243042] 2018-02-04 02:21:42,185 - INFO - launcher: Checking for Python 3.5+
[48.002243042] 2018-02-04 02:21:42,185 - INFO - launcher: Checking console encoding
[49.001932144] 2018-02-04 02:21:42,186 - INFO - launcher: Setting console encoding to UTF-8
[49.001932144] 2018-02-04 02:21:42,186 - INFO - launcher: Ensuring we're in the right environment
[51.003217697] 2018-02-04 02:21:42,188 - INFO - launcher: Adding local bins/ folder to path
[51.003217697] 2018-02-04 02:21:42,188 - INFO - launcher: Required checks passed.
[52.002429962] 2018-02-04 02:21:42,189 - INFO - launcher: Optional checks passed.
[52.002429962] 2018-02-04 02:21:42,189 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[2.0321047306060791] 2018-02-04 02:21:44,169 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 213 in _setup_logging: Set logging level to INFO
[2.0321047306060791] 2018-02-04 02:21:44,169 - INFO - musicbot.bot | In bot.py::MainThread(364), line 80 in __init__: =========== MusicBot (version 1.9.6_2) ===========
[2.0331065654754639] 2018-02-04 02:21:44,170 - INFO - musicbot.bot | In bot.py::MainThread(364), line 86 in __init__: Loaded autoplaylist with 2531 entries
[2.036109209] launcher-INFO: Connecting
[4.6062393188476562] 2018-02-04 02:21:46,743 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 1011 in on_ready: Connection established, ready to go.
[4.6062393188476562] 2018-02-04 02:21:46,743 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 324 in _cache_app_info: Caching app info
[4.7242450714111328] 2018-02-04 02:21:46,861 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 828 in _scheck_ensure_env: Ensuring data folders exist
[4.7262456417083740] 2018-02-04 02:21:46,863 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 844 in _scheck_server_permissions: Checking server permissions
[4.7272453308105469] 2018-02-04 02:21:46,864 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 848 in _scheck_autoplaylist: Auditing autoplaylist
[4.7272453308105469] 2018-02-04 02:21:46,864 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 852 in _scheck_configs: Validating config
[4.7272453308105469] 2018-02-04 02:21:46,864 - DEBUG - musicbot.config | In config.py::MainThread(364), line 155 in async_validate: Validating options...
[4.7272453308105469] 2018-02-04 02:21:46,864 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 855 in _scheck_configs: Validating permissions config
[4.7272453308105469] 2018-02-04 02:21:46,864 - DEBUG - musicbot.permissions | In permissions.py::MainThread(364), line 59 in async_validate: Validating permissions...
[4.7282450199127197] 2018-02-04 02:21:46,865 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1022 in on_ready: Connected to Discord!
[4.7302451133728027] 2018-02-04 02:21:46,867 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1032 in on_ready: Bot:   409124563717193738/Smokes Music Bot#6058 [BOT]
[4.7312452793121338] 2018-02-04 02:21:46,868 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1040 in on_ready: Owner: 99676399379443712/smokedog77#2953

[4.7332441806793213] 2018-02-04 02:21:46,870 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1043 in on_ready: Server List:
[4.7342445850372314] 2018-02-04 02:21:46,871 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1044 in <listcomp>:  - The Dog House
[4.7362442016601562] 2018-02-04 02:21:46,873 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1088 in on_ready: Not bound to any text channels
[4.7372457981109619] 2018-02-04 02:21:46,874 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1114 in on_ready: Not autojoining any voice channels
[4.7402460575103760] 2018-02-04 02:21:46,877 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1118 in on_ready: Options:
[4.7412462234497070] 2018-02-04 02:21:46,878 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1120 in on_ready:   Command prefix: !
[4.7422456741333008] 2018-02-04 02:21:46,879 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1121 in on_ready:   Default volume: 25%
[4.7432458400726318] 2018-02-04 02:21:46,880 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1123 in on_ready:   Skip threshold: 4 votes or 50%
[4.7442452907562256] 2018-02-04 02:21:46,881 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1124 in on_ready:   Now Playing @mentions: Enabled
[4.7462456226348877] 2018-02-04 02:21:46,883 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1125 in on_ready:   Auto-Summon: Enabled
[4.7472462654113770] 2018-02-04 02:21:46,884 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1126 in on_ready:   Auto-Playlist: Enabled
[4.7482459545135498] 2018-02-04 02:21:46,885 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1127 in on_ready:   Auto-Pause: Enabled
[4.7492463588714600] 2018-02-04 02:21:46,886 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1128 in on_ready:   Delete Messages: Enabled
[4.7512462139129639] 2018-02-04 02:21:46,888 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1130 in on_ready:     Delete Invoking: Disabled
[4.7522461414337158] 2018-02-04 02:21:46,889 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1131 in on_ready:   Debug Mode: Disabled
[4.7532463073730469] 2018-02-04 02:21:46,890 - INFO - musicbot.bot | In bot.py::MainThread(364), line 1132 in on_ready:   Downloaded songs will be saved
[4.7552461624145508] 2018-02-04 02:21:46,892 - INFO - musicbot.bot | In bot.py::MainThread(364), line 258 in _join_startup_channels: Found owner in "streaming Live"
[4.7562460899353027] 2018-02-04 02:21:46,893 - INFO - musicbot.bot | In bot.py::MainThread(364), line 267 in _join_startup_channels: Attempting to join The Dog House/streaming Live
[4.7572464942932129] 2018-02-04 02:21:46,894 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 437 in get_voice_client: Connection attempt 1 to streaming Live
[4.7572464942932129] 2018-02-04 02:21:46,894 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 376 in join_voice_channel: (join_voice_channel) creating futures
[4.7572464942932129] 2018-02-04 02:21:46,894 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 382 in join_voice_channel: (join_voice_channel) setting voice state
[4.7582461833953857] 2018-02-04 02:21:46,895 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 385 in join_voice_channel: (join_voice_channel) waiting for session id
[4.8682525157928467] 2018-02-04 02:21:47,005 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 2564 in on_voice_state_update: Voice state update for 409124563717193738/Smokes Music Bot#6058 on The Dog House/streaming Live -> [JOIN, CONNECT]
[4.8682525157928467] 2018-02-04 02:21:47,005 - INFO - musicbot.bot | In bot.py::MainThread(364), line 2575 in on_voice_state_update: 409124563717193738/Smokes Music Bot#6058 has joined The Dog House/streaming Live
[4.8692538738250732] 2018-02-04 02:21:47,006 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 389 in join_voice_channel: (join_voice_channel) waiting for voice data
[4.9702587127685547] 2018-02-04 02:21:47,107 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 403 in join_voice_channel: (join_voice_channel) connecting...
[19.9770386219024658] 2018-02-04 02:22:02,114 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 408 in join_voice_channel: (join_voice_channel) connection failed, disconnecting
[19.9770386219024658] 2018-02-04 02:22:02,114 - WARNING - musicbot.bot | In bot.py::MainThread(364), line 446 in get_voice_client: Failed to connect, retrying (1/5)
[20.4790618419647217] 2018-02-04 02:22:02,616 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 437 in get_voice_client: Connection attempt 2 to streaming Live
[20.4790618419647217] 2018-02-04 02:22:02,616 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 376 in join_voice_channel: (join_voice_channel) creating futures
[20.4790618419647217] 2018-02-04 02:22:02,616 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 382 in join_voice_channel: (join_voice_channel) setting voice state
[20.4800617694854736] 2018-02-04 02:22:02,617 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 385 in join_voice_channel: (join_voice_channel) waiting for session id
[20.5910675525665283] 2018-02-04 02:22:02,728 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 2552 in on_voice_state_update: Resumed voice connection to The Dog House/streaming Live
[20.5920684337615967] 2018-02-04 02:22:02,729 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 2564 in on_voice_state_update: Voice state update for 409124563717193738/Smokes Music Bot#6058 on The Dog House/streaming Live -> [RESUME, CONNECT]
[20.5920684337615967] 2018-02-04 02:22:02,729 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 389 in join_voice_channel: (join_voice_channel) waiting for voice data
[35.5958468914031982] 2018-02-04 02:22:17,733 - WARNING - musicbot.bot | In bot.py::MainThread(364), line 446 in get_voice_client: Failed to connect, retrying (2/5)
[36.0968723297119141] 2018-02-04 02:22:18,234 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 437 in get_voice_client: Connection attempt 3 to streaming Live
[36.0968723297119141] 2018-02-04 02:22:18,234 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 376 in join_voice_channel: (join_voice_channel) creating futures
[36.0968723297119141] 2018-02-04 02:22:18,234 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 382 in join_voice_channel: (join_voice_channel) setting voice state
[36.0978722572326660] 2018-02-04 02:22:18,235 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 385 in join_voice_channel: (join_voice_channel) waiting for session id
[36.2058780193328857] 2018-02-04 02:22:18,343 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 2552 in on_voice_state_update: Resumed voice connection to The Dog House/streaming Live
[36.2068791389465332] 2018-02-04 02:22:18,344 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 2564 in on_voice_state_update: Voice state update for 409124563717193738/Smokes Music Bot#6058 on The Dog House/streaming Live -> [RESUME, CONNECT]
[36.2068791389465332] 2018-02-04 02:22:18,344 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 389 in join_voice_channel: (join_voice_channel) waiting for voice data
[51.2036557197570801] 2018-02-04 02:22:33,341 - WARNING - musicbot.bot | In bot.py::MainThread(364), line 446 in get_voice_client: Failed to connect, retrying (3/5)
[51.7046825885772705] 2018-02-04 02:22:33,842 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 437 in get_voice_client: Connection attempt 4 to streaming Live
[51.7046825885772705] 2018-02-04 02:22:33,842 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 376 in join_voice_channel: (join_voice_channel) creating futures
[51.7057516574859619] 2018-02-04 02:22:33,843 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 382 in join_voice_channel: (join_voice_channel) setting voice state
[51.7057516574859619] 2018-02-04 02:22:33,843 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 385 in join_voice_channel: (join_voice_channel) waiting for session id
[51.8216905593872070] 2018-02-04 02:22:33,959 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 2552 in on_voice_state_update: Resumed voice connection to The Dog House/streaming Live
[51.8216905593872070] 2018-02-04 02:22:33,959 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 2564 in on_voice_state_update: Voice state update for 409124563717193738/Smokes Music Bot#6058 on The Dog House/streaming Live -> [RESUME, CONNECT]
[51.8226914405822754] 2018-02-04 02:22:33,960 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 389 in join_voice_channel: (join_voice_channel) waiting for voice data
[66.8234667778015137] 2018-02-04 02:22:48,960 - WARNING - musicbot.bot | In bot.py::MainThread(364), line 446 in get_voice_client: Failed to connect, retrying (4/5)
[67.3245284557342529] 2018-02-04 02:22:49,461 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 437 in get_voice_client: Connection attempt 5 to streaming Live
[67.3245284557342529] 2018-02-04 02:22:49,461 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 376 in join_voice_channel: (join_voice_channel) creating futures
[67.3245284557342529] 2018-02-04 02:22:49,461 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 382 in join_voice_channel: (join_voice_channel) setting voice state
[67.3255307674407959] 2018-02-04 02:22:49,462 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 385 in join_voice_channel: (join_voice_channel) waiting for session id
[67.4384982585906982] 2018-02-04 02:22:49,575 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 2552 in on_voice_state_update: Resumed voice connection to The Dog House/streaming Live
[67.4384982585906982] 2018-02-04 02:22:49,575 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 2564 in on_voice_state_update: Voice state update for 409124563717193738/Smokes Music Bot#6058 on The Dog House/streaming Live -> [RESUME, CONNECT]
[67.4384982585906982] 2018-02-04 02:22:49,575 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(364), line 389 in join_voice_channel: (join_voice_channel) waiting for voice data
[82.4402770996093750] 2018-02-04 02:23:04,577 - WARNING - musicbot.bot | In bot.py::MainThread(364), line 446 in get_voice_client: Failed to connect, retrying (5/5)
[82.9413025379180908] 2018-02-04 02:23:05,078 - CRITICAL - musicbot.bot | In bot.py::MainThread(364), line 460 in get_voice_client: Voice client is unable to connect, restarting...
[83.0513083934783936] 2018-02-04 02:23:05,188 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 463 in get_voice_client: Connected in -1517707369.5s
[83.0513083934783936] 2018-02-04 02:23:05,188 - INFO - musicbot.bot | In bot.py::MainThread(364), line 464 in get_voice_client: Connected to The Dog House/streaming Live
[83.0533094406127930] 2018-02-04 02:23:05,190 - DEBUG - musicbot.bot | In bot.py::MainThread(364), line 294 in _join_startup_channels: Error joining The Dog House/streaming Live
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 280, in _join_startup_channels
    player = await self.get_player(channel, create=True, deserialize=self.config.persistent_queue)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 551, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 466, in get_voice_client
    vc.ws._keep_alive.name = 'VoiceClient Keepalive'
AttributeError: 'NoneType' object has no attribute 'ws'
[83.0563085079193115] 2018-02-04 02:23:05,193 - ERROR - musicbot.bot | In bot.py::MainThread(364), line 295 in _join_startup_channels: Failed to join The Dog House/streaming Live
[83.0583083629608154] 2018-02-04 02:23:05,195 - ERROR - musicbot.bot | In bot.py::MainThread(364), line 999 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 2584, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 563, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[83.0653092861175537] 2018-02-04 02:23:05,202 - ERROR - musicbot.bot | In bot.py::MainThread(364), line 999 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 2584, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 563, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[83.0693609714508057] 2018-02-04 02:23:05,206 - ERROR - musicbot.bot | In bot.py::MainThread(364), line 999 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 2584, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 563, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

**Comment by MattBSG** [comment]
Very similar to #1440 

Please feel free to reopen if there are any more updates to this
