### ISSUE TITLE
Python Errors

### ISSUE THREAD

**Issue by diveyez** [Just-Some-Bots/MusicBot#1533]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at /home/diveyez/.local/lib/python3.5/site-packages/discord/voice_client.py:269> exception=ConnectionClosed('WebSocket connection is closed: code = 1001, no reason.',)>
Traceback (most recent call last):
  File "/home/diveyez/.local/lib/python3.5/site-packages/discord/gateway.py", line 676, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/diveyez/.local/lib/python3.5/site-packages/websockets/protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/diveyez/.local/lib/python3.5/site-packages/discord/voice_client.py", line 276, in poll_voice_ws
    yield from self.ws.poll_event()
  File "/home/diveyez/.local/lib/python3.5/site-packages/discord/gateway.py", line 679, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

### Steps to reproduce

1.  Just use it, this python error stuff came out of it

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by diveyez** [comment]
[40.699005127] 2018-03-14 07:45:39,751 - INFO - launcher: Starting sanity checks
[41.127443314] 2018-03-14 07:45:39,751 - INFO - launcher: Checking for Python 3.5+
[41.345119476] 2018-03-14 07:45:39,751 - INFO - launcher: Checking console encoding
[41.606903076] 2018-03-14 07:45:39,752 - INFO - launcher: Ensuring we're in the right environment
[42.125463486] 2018-03-14 07:45:39,752 - INFO - launcher: Required checks passed.
[42.382240295] 2018-03-14 07:45:39,752 - INFO - launcher: Optional checks passed.
[42.535781860] 2018-03-14 07:45:39,753 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.9267072677612305] 2018-03-14 07:45:40,637 - WARNING - musicbot.config | In config.py::MainThread(140402122176256), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.9268965721130371] 2018-03-14 07:45:40,637 - INFO - musicbot.config | In config.py::MainThread(140402122176256), line 123 in run_checks: Using i18n: config/i18n/en.json
[0.9498660564422607] 2018-03-14 07:45:40,660 - DEBUG - musicbot.json | In json.py::MainThread(140402122176256), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.9554579257965088] 2018-03-14 07:45:40,666 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 227 in _setup_logging: Set logging level to INFO
[0.9556119441986084] 2018-03-14 07:45:40,666 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 84 in __init__: Starting MusicBot 1.9.7
[0.9559171199798584] 2018-03-14 07:45:40,666 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 90 in __init__: Loaded autoplaylist with 2531 entries
[1.0846381187438965] 2018-03-14 07:45:40,795 - DEBUG - musicbot.spotify | In spotify.py::MainThread(140402122176256), line 70 in get_token: Created a new access token: {'expires_in': 3600, 'expires_at': 1521031540, 'token_type': 'Bearer', 'access_token': 'BQBqDoRVOWjHNGk67qHqbHZzDdmmIa6HFSH1RQZOQBPEO5_7u_hkldyBCJA_T1T6VWy8J6fVjxLlM5an1Yg', 'scope': ''}
[1.0849137306213379] 2018-03-14 07:45:40,795 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 115 in __init__: Authenticated with Spotify successfully using client ID and secret.
[3.2286980152130127] 2018-03-14 07:45:42,939 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 1074 in on_ready: Connection established, ready to go.
[3.2289686203002930] 2018-03-14 07:45:42,939 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 339 in _cache_app_info: Caching app info
[3.2701349258422852] 2018-03-14 07:45:42,980 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 889 in _scheck_ensure_env: Ensuring data folders exist
[3.2707691192626953] 2018-03-14 07:45:42,981 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 905 in _scheck_server_permissions: Checking server permissions
[3.2709553241729736] 2018-03-14 07:45:42,981 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[3.2710425853729248] 2018-03-14 07:45:42,981 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 913 in _scheck_configs: Validating config
[3.2711100578308105] 2018-03-14 07:45:42,981 - DEBUG - musicbot.config | In config.py::MainThread(140402122176256), line 212 in async_validate: Validating options...
[3.2711777687072754] 2018-03-14 07:45:42,981 - DEBUG - musicbot.config | In config.py::MainThread(140402122176256), line 226 in async_validate: Acquired owner id via API
[3.2712388038635254] 2018-03-14 07:45:42,981 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 916 in _scheck_configs: Validating permissions config
[3.2712986469268799] 2018-03-14 07:45:42,981 - DEBUG - musicbot.permissions | In permissions.py::MainThread(140402122176256), line 64 in async_validate: Validating permissions...
[3.2713689804077148] 2018-03-14 07:45:42,981 - DEBUG - musicbot.permissions | In permissions.py::MainThread(140402122176256), line 68 in async_validate: Fixing automatic owner group
[3.2714631557464600] 2018-03-14 07:45:42,982 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 1091 in on_ready: Connected: 412632069978456064/DJFlyHigh.bot#3878
[3.2717888355255127] 2018-03-14 07:45:42,982 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 1099 in on_ready: Owner:     294510272612139010/Diveyez#1878

[3.2720465660095215] 2018-03-14 07:45:42,982 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 1102 in on_ready: Server List:
[3.2722332477569580] 2018-03-14 07:45:42,982 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 1105 in on_ready:  - R2N Hosting Solutions
[3.2724428176879883] 2018-03-14 07:45:42,983 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 1151 in on_ready: Not bound to any text channels
[3.2726249694824219] 2018-03-14 07:45:42,983 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 1177 in on_ready: Not autojoining any voice channels
[13.8696012496948242] 2018-03-14 07:45:53,580 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 2938 in on_voice_state_update: Voice state update for 294510272612139010/Diveyez#1878 on R2N Hosting Solutions/MusicRoom -> [CONNECT]
[23.0178358554840088] 2018-03-14 07:46:02,728 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 2734 in on_message: 294510272612139010/Diveyez#1878: !summon
[23.0184638500213623] 2018-03-14 07:46:02,729 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 2019 in cmd_summon: Joining R2N Hosting Solutions/MusicRoom
[23.0187423229217529] 2018-03-14 07:46:02,729 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 452 in get_voice_client: Connection attempt 1 to MusicRoom
[23.0188479423522949] 2018-03-14 07:46:02,729 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 391 in join_voice_channel: (join_voice_channel) creating futures
[23.0191407203674316] 2018-03-14 07:46:02,729 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 397 in join_voice_channel: (join_voice_channel) setting voice state
[23.0194072723388672] 2018-03-14 07:46:02,730 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 400 in join_voice_channel: (join_voice_channel) waiting for session id
[23.0471220016479492] 2018-03-14 07:46:02,757 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 2938 in on_voice_state_update: Voice state update for 412632069978456064/DJFlyHigh.bot#3878 on R2N Hosting Solutions/MusicRoom -> [JOIN, CONNECT]
[23.0474023818969727] 2018-03-14 07:46:02,758 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 2949 in on_voice_state_update: 412632069978456064/DJFlyHigh.bot#3878 has joined R2N Hosting Solutions/MusicRoom
[23.0478994846343994] 2018-03-14 07:46:02,758 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 404 in join_voice_channel: (join_voice_channel) waiting for voice data
[23.0789456367492676] 2018-03-14 07:46:02,789 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 418 in join_voice_channel: (join_voice_channel) connecting...
[23.1827967166900635] 2018-03-14 07:46:02,893 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 430 in join_voice_channel: (join_voice_channel) connection successful
[23.1831631660461426] 2018-03-14 07:46:02,893 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 478 in get_voice_client: Connected in 0.2s
[23.1832962036132812] 2018-03-14 07:46:02,893 - INFO - musicbot.bot | In bot.py::MainThread(140402122176256), line 479 in get_voice_client: Connected to R2N Hosting Solutions/MusicRoom
[23.1842305660247803] 2018-03-14 07:46:02,894 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 849 in deserialize_queue: Deserializing queue for 349940473084903427
[23.2911272048950195] 2018-03-14 07:46:03,001 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 570 in get_player: Created player via deserialization for server 349940473084903427 with 1 entries
[23.2928516864776611] 2018-03-14 07:46:03,003 - VOICEDEBUG - musicbot.player | In player.py::MainThread(140402122176256), line 373 in websocket_check: Starting websocket check loop for R2N Hosting Solutions
[23.2932364940643311] 2018-03-14 07:46:03,003 - DEBUG - musicbot.entry | In entry.py::MainThread(140402122176256), line 54 in get_ready_future: Created future for None
[23.2938871383666992] 2018-03-14 07:46:03,004 - INFO - musicbot.entry | In entry.py::MainThread(140402122176256), line 220 in _really_download: Download started: https://youtu.be/rhJz5PZrlzg
[26.6519668102264404] 2018-03-14 07:46:06,362 - INFO - musicbot.entry | In entry.py::MainThread(140402122176256), line 230 in _really_download: Download complete: https://youtu.be/rhJz5PZrlzg
[26.6545827388763428] 2018-03-14 07:46:06,365 - DEBUG - musicbot.player | In player.py::MainThread(140402122176256), line 269 in get_mean_volume: Calculating mean volume of audio_cache/youtube-rhJz5PZrlzg-Makoto_DNB60_on_BBC_Radio_1.webm
[36.2008776664733887] 2018-03-14 07:46:15,911 - DEBUG - musicbot.player | In player.py::MainThread(140402122176256), line 290 in get_mean_volume: Calculated mean volume as -14.2
[36.2011759281158447] 2018-03-14 07:46:15,911 - FFMPEG - musicbot.player | In player.py::MainThread(140402122176256), line 330 in _play: Creating player with options: -nostdin -af "volume=-0.0dB" audio_cache/youtube-rhJz5PZrlzg-Makoto_DNB60_on_BBC_Radio_1.webm
[36.2107980251312256] 2018-03-14 07:46:15,921 - DEBUG - musicbot.bot | In bot.py::MainThread(140402122176256), line 825 in serialize_queue: Serializing queue for 349940473084903427
[40.2498223781585693] 2018-03-14 07:46:19,960 - DEBUG - musicbot.player | In player.py::MainThread(140402122176256), line 202 in _playback_finished: Deleting file: audio_cache/youtube-rhJz5PZrlzg-Makoto_DNB60_on_BBC_Radio_1.webm

**Comment by mojamm11** [comment]
i got the same issue as well. This just happened out of nowhere for me. Clean install did not fix it either.

**Comment by Daztek** [comment]
Try setting 'UseExperimentalEqualization = yes' to no in config.ini

**Comment by AnnsAnns** [comment]
This is actually a problem happening to a lot of people with different bots right now. Discord is saying that this has to do with Cloudflares Balancing System and I haven't found any real solution to it.

**Comment by MattBSG** [comment]
Hey @tom-GER do you have that statement or message? I’d love to pass that along

**Comment by AutumnClove** [comment]
This isn't an issue with python, rather an issue with discord as mentioned by @tumGER, the best solution until dpy rewrite is pushed so far has been to change your server region.

**Comment by diveyez** [comment]
It started again this morning, it does look like dos protection (from a secops perspective)
I thought something was wrong with the bot but it is not.
Daztek that didnt work

**Comment by MattBSG** [comment]
Hi all, I’m gonna go ahead and close this; however please know that we are aware of it. It is a problem with your connection to Discord being severed for one reason or another.
