### ISSUE TITLE
Error musicBot

### ISSUE THREAD

**Issue by asteam52** [Just-Some-Bots/MusicBot#1539]
[ERROR:bot] Failed to join Legionarii/BotTest
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Root\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Root\Desktop\MusicBot\musicbot\bot.py", line 2958, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "C:\Users\Root\Desktop\MusicBot\musicbot\bot.py", line 578, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use |summon to summon it to your voice channel.
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Root\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Root\Desktop\MusicBot\musicbot\bot.py", line 2958, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "C:\Users\Root\Desktop\MusicBot\musicbot\bot.py", line 578, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use |summon to summon it to your voice channel.
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Root\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Root\Desktop\MusicBot\musicbot\bot.py", line 2958, in on_voice_state_update
    player = await self.get_player(state.my_voice_channel)
  File "C:\Users\Root\Desktop\MusicBot\musicbot\bot.py", line 578, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use |summon to summon it to your voice channel.

**Comment by AutumnClove** [comment]
If this is the same error as we've been seeing, changing your server region should fix this.

**Comment by asteam52** [comment]
Thanks man this worked
