### ISSUE TITLE
Errors when trying to start initially - help wanted

### ISSUE THREAD

**Issue by KimberlyDev** [Just-Some-Bots/MusicBot#1553]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [X] Question

----

### Description of issue

I want to start the bot for the first time, but whenever I try this is what the console returns:

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 347, in main
    from musicbot import MusicBot
  File "D:\New Discord Bot\MusicBot\musicbot\__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
ImportError: No module named 'discord'
[INFO] launcher: Attempting to install dependencies...
Traceback (most recent call last):
  File "run.py", line 347, in main
    from musicbot import MusicBot
  File "D:\New Discord Bot\MusicBot\musicbot\__init__.py", line 6, in <module>
    from discord.ext.commands.bot import _get_variable
ImportError: No module named 'discord'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 368, in main
    err = PIP.run_install('--upgrade -r requirements.txt')
  File "run.py", line 81, in run_install
    return cls.run("install %s%s" % ('-q ' if quiet else '', cmd), check_output)
  File "run.py", line 34, in run
    raise RuntimeError("Could not import pip.")
RuntimeError: Could not import pip.

[INFO] launcher: All done.

I've set most of the settings in the .ini files. I used the windows method, to install.
I installed Python, then git. Cloned the repository. 

### Log file
There is no log file in the logs folder.

-------------------------------

-->Can you help me with this?

**Comment by MattBSG** [comment]
Please see if you can run the bot on your `C:` drive and that pip was installed correctly. Run `update.bat` and if it errors post a log

**Comment by MattBSG** [comment]
Closing due to inactivity
