### ISSUE TITLE
Youtube video requires login to be played

### ISSUE THREAD

**Issue by Sphyix** [Just-Some-Bots/MusicBot#157]
That happened with a link in the autoplaylist, and after that the playlist stopped working.
The video is private.

```
ERROR: 5B0KjzeM1o0: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<on_finished_playing() done, defined at C:\Users\PC3\Desktop\musicbot\musicbot\bot.py:274> 
exception=ExtractionError('Could not extract information from www.youtube.com/watch?v=5B0KjzeM1o0',)>
Traceback (most recent call last):
  File "C:\Users\PC3\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\PC3\Desktop\musicbot\musicbot\bot.py", line 290, in on_finished_playing
    await player.playlist.add_entry(song_url, channel=None, author=None)
  File "C:\Users\PC3\Desktop\musicbot\musicbot\playlist.py", line 49, in add_entry
    raise ExtractionError('Could not extract information from %s' % song_url)
musicbot.exceptions.ExtractionError: Could not extract information from www.youtube.com/watch?v=5B0KjzeM1o0
```

**Comment by arunesh90** [comment]
This is a known bug. When the autoplaylist includes an corrupted/not public video, it shows the error
