### ISSUE TITLE
Can not play music in my discord channel

### ISSUE THREAD

**Issue by Noldat** [Just-Some-Bots/MusicBot#1576]
Please tick all applicable boxes.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I can not get the put to play music on my server. I included the errors on the console.

### Steps to reproduce

1. Start Bot
2. !local start streaming

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[13/04/2018 21:05] ERROR red on_command_error 369: Exception in command 'local start'
Traceback (most recent call last):
  File "lib\discord\gateway.py", line 671, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "lib\websockets\protocol.py", line 319, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\audio.py", line 1421, in play_local
    await self._join_voice_channel(voice_channel)
  File "C:\Red-DiscordBot\cogs\audio.py", line 707, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "lib\discord\client.py", line 3210, in join_voice_channel
    yield from voice.connect()
  File "lib\discord\voice_client.py", line 258, in connect
    self.ws = yield from DiscordVoiceWebSocket.from_client(self)
  File "lib\discord\gateway.py", line 586, in from_client
    yield from asyncio.wait_for(ws.poll_event(), timeout=60, loop=client.loop)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "lib\discord\gateway.py", line 674, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..

**Comment by AutumnClove** [comment]
Change your Disccord server region, also this isn't redbot. This is MusicBot.

**Comment by AutumnClove** [comment]
Also this isn't even the right bot

**Comment by jayktaylor** [comment]
Wrong bot.
