### ISSUE TITLE
 Bot does not start

### ISSUE THREAD

**Issue by m8tec** [Just-Some-Bots/MusicBot#1599]
Please tick all applicable boxes.

- [ X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X ] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
https://mega.nz/#!8Gw0zSyB (Log File)
or
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1956276/musicbot.log)

### Steps to reproduce
Hi, I can not start my bot :/
I made it as explained on the website.
But always I run run.bat the bot can not be started.
Can anyone help me please? c:

PS: 
I'm new here, sorry if I did something wrong 😄 
----

### Log file:

[50.504207611] 2018-04-27 20:41:32,540 - INFO - launcher: Starting sanity checks
[51.007270813] 2018-04-27 20:41:32,540 - INFO - launcher: Checking for Python 3.5+
[51.007270813] 2018-04-27 20:41:32,540 - INFO - launcher: Checking console encoding
[51.505327225] 2018-04-27 20:41:32,541 - INFO - launcher: Setting console encoding to UTF-8
[51.505327225] 2018-04-27 20:41:32,541 - INFO - launcher: Ensuring we're in the right environment
[55.505514145] 2018-04-27 20:41:32,545 - INFO - launcher: Adding local bins/ folder to path
[57.044506073] 2018-04-27 20:41:32,546 - INFO - launcher: Required checks passed.
[57.543277740] 2018-04-27 20:41:32,547 - INFO - launcher: Optional checks passed.
[57.543277740] 2018-04-27 20:41:32,547 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[2.588673353] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 348, in main
    m = MusicBot()
  File "C:\Users\User\Documents\DiscordBot\MusicBot\musicbot\bot.py", line 72, in __init__
    self.config = Config(config_file)
  File "C:\Users\User\Documents\DiscordBot\MusicBot\musicbot\config.py", line 17, in __init__
    self.find_config()
  File "C:\Users\User\Documents\DiscordBot\MusicBot\musicbot\config.py", line 263, in find_config
    if not config.read(self.config_file, encoding='utf-8'):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'config/options.ini', line: 18

**Comment by AutumnClove** [comment]
You're going to want to make a new token since you just posted it here for everyone to see. They could control your bot with that token. Also the error is happening because `\n` at the end, assuming you used notepad to edit these, please use a decent text Editor like notepad++ or sublime text 3 or visual studio code, and try again, with the new token.

**Comment by MattBSG** [comment]
Hi,

Two things. Immediately reset your token right now as you just leaked it. Secondly, you edited the file either in a bad text editor such as “Notepad” or you removed a header. Please grab a new config file from the repository and try again in a code editor such as Notepad++ or Atom

**Comment by m8tec** [comment]
How can I grab a new configuration file from the repository?  I already have NotePad ++ and what should I do then? Maybe better for a donkey like me explained 😅 😃

**Comment by MattBSG** [comment]
https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini

**Comment by MattBSG** [comment]
See the docs for config setup at https://just-some-bots.github.io/MusicBot
