### ISSUE TITLE
what am i doing wrong

### ISSUE THREAD

**Issue by Boyo33Gaming2018** [Just-Some-Bots/MusicBot#1642]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 347, in main
    from musicbot import MusicBot
  File "C:\Users\l_bax\OneDrive\Documents\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\Users\l_bax\OneDrive\Documents\MusicBot\musicbot\bot.py", line 17, in <module>
    import colorlog
ImportError: No module named 'colorlog'
[INFO] launcher: Attempting to install dependencies...
Traceback (most recent call last):
  File "C:\Users\l_bax\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\l_bax\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\l_bax\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\__main__.py", line 16, in <module>
    from pip._internal import main as _main  # noqa
  File "C:\Users\l_bax\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\_internal\__init__.py", line 20, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "C:\Users\l_bax\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\_vendor\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "C:\Users\l_bax\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 29, in <module>
    from .connection import (
  File "C:\Users\l_bax\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\_vendor\urllib3\connection.py", line 39, in <module>
    from .util.ssl_ import (
ImportError: No module named 'pip._vendor.urllib3.util'

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

C:\Users\l_bax\OneDrive\Documents\MusicBot>

**Comment by AutumnClove** [comment]
Do you have git installed to path?

**Comment by andre2539** [comment]
try run it as admin

**Comment by AleanaA** [comment]
Before anything, what does `python -m pip --version` output? If it outputs the same error, then you'll need to reinstall python 3.5.4

**Comment by ImthePeach** [comment]
If this issue for you persists join the discord help server and as there: http://discord.gg/bots
