### ISSUE TITLE
error: [WinError 193] %1

### ISSUE THREAD

**Issue by sTaner604** [Just-Some-Bots/MusicBot#1653]
I can not run in a way, give an error 

Error : [WinError 193]

**Comment by mwallis45** [comment]
we need a bit more then that to fix your problem

**Comment by sTaner604** [comment]
Ben pek İngilizce bilmiyorum az biliyorum Türkçe yazsam olur mu?

30 Haz 2018 Cmt 19:31 tarihinde mwallis45 <notifications@github.com> şunu
yazdı:

**Comment by sTaner604** [comment]
Hem daha sorun ile alakalı daha detaylı bilgi verebilirim

30 Haz 2018 Cmt 19:31 tarihinde mwallis45 <notifications@github.com> şunu
yazdı:

**Comment by AleanaA** [comment]
English please. We need the full log in order to provide assistance. What
you've provided isn't enough information to help you in any way.

**Comment by sTaner604** [comment]
OK I'll try to give enough information when the computer screenshot
genius. Thank
you for your attention

30 Haz 2018 Cmt 20:07 tarihinde Conner May <notifications@github.com> şunu
yazdı:

> English please. We need the full log in order to provide assistance. What
> you've provided isn't enough information to help you in any way.
>

**Comment by AutumnClove** [comment]
If you could upload your MusicBot.log and MusicBot.last from the logs folder inside your MusicBot folder, that would help us out. I did a quick Google search of winerror193 looks like you haven't installed python to your path. Please install python 3.5.4 and click on the install to path option.

**Comment by sTaner604** [comment]
Could you give me a Python link to run this bot. And For the required materials download link ?

**Comment by AleanaA** [comment]
https://just-some-bots.github.io/MusicBot/

**Comment by MattBSG** [comment]
Are you still having issues @sTaner604 ?

**Comment by sTaner604** [comment]
Ubuntu kurdum sorun bu   (OS Ubuntu)


[0.754299402] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 348, in main
    m = MusicBot()
  File "/home/ismail/Masaüstü/AyYildizBot/MusicBot/musicbot/bot.py", line 72, in __init__
    self.config = Config(config_file)
  File "/home/ismail/Masaüstü/AyYildizBot/MusicBot/musicbot/config.py", line 17, in __init__
    self.find_config()
  File "/home/ismail/Masaüstü/AyYildizBot/MusicBot/musicbot/config.py", line 263, in find_config
    if not config.read(self.config_file, encoding='utf-8'):
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1107, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'config/options.ini'
	[line 25]: '1L\n'
[0.774900913] launcher-INFO: All done.

**Comment by AutumnClove** [comment]
Don't edit with notepad, use notepad++ or something

**Comment by sTaner604** [comment]
An experience 👍

**Comment by sTaner604** [comment]
Terminal Error 
_______________

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 348, in main
    m = MusicBot()
  File "/home/ismail/Masaüstü/AyYildizBot/MusicBot/musicbot/bot.py", line 72, in __init__
    self.config = Config(config_file)
  File "/home/ismail/Masaüstü/AyYildizBot/MusicBot/musicbot/config.py", line 17, in __init__
    self.find_config()
  File "/home/ismail/Masaüstü/AyYildizBot/MusicBot/musicbot/config.py", line 263, in find_config
    if not config.read(self.config_file, encoding='utf-8'):
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1107, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'config/options.ini'
	[line 25]: '1L\n'

[INFO] launcher: All done.
Exception ignored in: <bound method MusicBot.__del__ of <musicbot.bot.MusicBot object at 0x7f93f6d96c18>>
Traceback (most recent call last):
  File "/home/ismail/Masaüstü/AyYildizBot/MusicBot/musicbot/bot.py", line 125, in __del__
    super().__init__()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 142, in __init__
    self.loop = asyncio.get_event_loop() if loop is None else loop
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-1'.

**Comment by MattBSG** [comment]
You need to get a new copy of your options.ini file from the repository and refill it out in notepad++. Same with permissions.ini if you also edited and saved with notepad

**Comment by ImthePeach** [comment]
This issue is one of your own doing. Please follow our guides at the following url to avoid future issues. https://just-some-bots.github.io/MusicBot/
