### ISSUE TITLE
Server is up but unavailable

### ISSUE THREAD

**Issue by rtrind** [Just-Some-Bots/MusicBot#1696]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Sometimes the bot is up but unresponsive, leading to needing to SSH into the server and restart the service. PM2 sees the service as up and does not restart it when in this state.

### Steps to reproduce
Start the server and have a connection issue when first starting.

----

### Log file
```
[963604.8841652870178223] 2018-08-16 07:02:57,770 - WARNING - musicbot.config | In config.py::MainThread(140393153226496), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[963604.8848228454589844] 2018-08-16 07:02:57,770 - INFO - musicbot.config | In config.py::MainThread(140393153226496), line 123 in run_checks: Using i18n: config/i18n/en.json
[963604.8929119110107422] 2018-08-16 07:02:57,778 - DEBUG - musicbot.json | In json.py::MainThread(140393153226496), line 8 in __init__: Init JSON obj with config/i18n/en.json
[963604.9095804691314697] 2018-08-16 07:02:57,795 - DEBUG - musicbot.bot | In bot.py::MainThread(140393153226496), line 192 in _setup_logging: Skipping logger setup, already set up
[963604.9097659587860107] 2018-08-16 07:02:57,795 - INFO - musicbot.bot | In bot.py::MainThread(140393153226496), line 84 in __init__: Starting MusicBot 1.9.7
[963604.9102001190185547] 2018-08-16 07:02:57,796 - INFO - musicbot.bot | In bot.py::MainThread(140393153226496), line 90 in __init__: Loaded autoplaylist with 2645 entries
[963605.5385830402374268] 2018-08-16 07:02:58,424 - DEBUG - musicbot.spotify | In spotify.py::MainThread(140393153226496), line 70 in get_token: Created a new access token: {'token_type': 'Bearer', 'scope': '', 'access_token': '<my token was here>', 'expires_in': 3600, 'expires_at': 1534406578}
[963605.5388736724853516] 2018-08-16 07:02:58,424 - INFO - musicbot.bot | In bot.py::MainThread(140393153226496), line 115 in __init__: Authenticated with Spotify successfully using client ID and secret.
[963606.735458612] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "/home/rtrind/MusicBot20180729/run.py", line 353, in main
    m.run()
  File "/home/rtrind/MusicBot20180729/musicbot/bot.py", line 1024, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/site-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/site-packages/discord/client.py", line 444, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/site-packages/discord/gateway.py", line 207, in from_client
    timeout=60, loop=client.loop)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/tasks.py", line 406, in wait_for
    return fut.result()
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/tasks.py", line 242, in _step
    result = coro.throw(exc)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/site-packages/discord/gateway.py", line 65, in _ensure_coroutine_connect
    ws = yield from websockets.connect(gateway, loop=loop, klass=klass)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/site-packages/websockets/py35/client.py", line 19, in __await__
    return (yield from self.client)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/site-packages/websockets/client.py", line 210, in connect
    factory, wsuri.host, wsuri.port, **kwds)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/base_events.py", line 802, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/base_events.py", line 828, in _create_connection_transport
    yield from waiter
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/home/rtrind/.pyenv/versions/3.5.4/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[963606.736426830] launcher-INFO: All done.

```

**Comment by AutumnClove** [comment]
Hi there, the bot was recently updated, please update and let us know if your still experiencing issues

**Comment by rtrind** [comment]
Never saw this again on my instance, I think we can close this.
