### ISSUE TITLE
MusicBot 1.9.8 error "on_voice_state_update" and autopause not working

### ISSUE THREAD

**Issue by rtrind** [Just-Some-Bots/MusicBot#1697]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
After installing python 3.6.6 (to circumvent the aiohttp requirement issue) and the latest version of the bot, it installs and runs fine, but there are some exceptions on the on_voice_state_update method (one on the very first time it runs and then periodically afterwards). The bot seems to keep running fine, but the autopause on empty channel stopped working for some reason (it was working on the bot first run). I'm running Ubuntu 16.04.

### Steps to reproduce

1. Start the bot with python 3.6.6 on Ubuntu 16.04 on a fresh install.

----

### Log file

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2299849/musicbot.log)

**Comment by despair86** [comment]
it will wait to pause only if there's no one else on the phone at the time a song finishes playing
tested on:
- OpenBSD 6.4-beta, 32-bit (yes i live on the bleeding edge, side note: fuck linux and its dependency hell orthogonal to distro fragmentation--when you have no concept of a standard base system/no one conforms to it, the worst kind of dep hell occurs 😡 [e.g. why is libc an individual package even on desktop images?])
    - Even the different Solaris distros have a uniform standard base thanks to its UNIX compliance
- python 3.6.6 (from snapshots repo, `RELEASE` still has python 3.6.5)
- all other requirements satisfied either from same ports/snapshots tree or PyPi

Furthermore, I happened to have almost the same exact symptoms half an hour ago, they seemed to have (partially) resolved when i updated unix and fully updated bot dependencies, except for the behaviour specified above (autopause at song end)

Cheers,
-despair86

**Comment by rtrind** [comment]
Confirmed. And after another bot spontaneous restart, the behavior is gone completely except for the pause on end. If this is the expected behavior now, please consider the case closed.

**Comment by jayktaylor** [comment]
It isn’t the expected behaviour - autopausing has notoriously been all over the place for a while, I’ll look into it soon. Thanks

**Comment by rtrind** [comment]
Thanks for looking into it. The exception is happening again on my instance:

```
[43985.4382543563842773] 2018-08-19 06:03:40,067 - DEBUG - musicbot.player | In player.py::Thread-166(140622849627904), line 203 in _playback_finished: Deleting file: audio_cache/youtube-zUwEIt9ez7M-Deep_Purple_-_Smoke_on_the_Water.m4a
[43985.4391448497772217] 2018-08-19 06:03:40,068 - DEBUG - musicbot.player | In player.py::Thread-166(140622849627904), line 208 in _playback_finished: File deleted: audio_cache/youtube-zUwEIt9ez7M-Deep_Purple_-_Smoke_on_the_Water.m4a
[43989.6523661613464355] 2018-08-19 06:03:44,281 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 509 in on_player_finished_playing: Running on_player_finished_playing
[43989.6613433361053467] 2018-08-19 06:03:44,290 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 505 in on_player_stop: Running on_player_stop
[43993.6975543498992920] 2018-08-19 06:03:48,326 - DEBUG - musicbot.entry | In entry.py::MainThread(140623658018560), line 56 in get_ready_future: Created future for None
[43993.6977808475494385] 2018-08-19 06:03:48,326 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 586 in on_player_entry_added: Running on_player_entry_added
[43993.6979486942291260] 2018-08-19 06:03:48,327 - INFO - musicbot.entry | In entry.py::MainThread(140623658018560), line 285 in _really_download: Download started: https://www.youtube.com/watch?v=NoM9ee3vU3s
[43995.6986966133117676] 2018-08-19 06:03:50,327 - DEBUG - musicbot.entry | In entry.py::MainThread(140623658018560), line 56 in get_ready_future: Created future for None
[43995.9258458614349365] 2018-08-19 06:03:50,554 - INFO - musicbot.entry | In entry.py::MainThread(140623658018560), line 295 in _really_download: Download complete: https://www.youtube.com/watch?v=NoM9ee3vU3s
[43995.9278383255004883] 2018-08-19 06:03:50,556 - DEBUG - musicbot.entry | In entry.py::MainThread(140623658018560), line 263 in get_mean_volume: Calculating mean volume of audio_cache/youtube-NoM9ee3vU3s-DJ_Hero_2_-_Where_s_Your_Head_At_vs._Bonkers.m4a
[43995.9330408573150635] 2018-08-19 06:03:50,562 - DEBUG - musicbot.entry | In entry.py::MainThread(140623658018560), line 237 in run_command: Starting asyncio subprocess (<Process 3395>) with command: "/usr/bin/ffmpeg" -i "audio_cache/youtube-NoM9ee3vU3s-DJ_Hero_2_-_Where_s_Your_Head_At_vs._Bonkers.m4a" -af "volumedetect" -f null /dev/null
[43996.2937488555908203] 2018-08-19 06:03:50,922 - DEBUG - musicbot.entry | In entry.py::MainThread(140623658018560), line 280 in get_mean_volume: Calculated mean volume as -11.9
[43996.2940194606781006] 2018-08-19 06:03:50,923 - FFMPEG - musicbot.player | In player.py::MainThread(140623658018560), line 276 in _play: Creating player with options: -nostdin -af "volume=-0.0dB" audio_cache/youtube-NoM9ee3vU3s-DJ_Hero_2_-_Where_s_Your_Head_At_vs._Bonkers.m4a
[43996.2970657348632812] 2018-08-19 06:03:50,926 - DEBUG - musicbot.player | In player.py::MainThread(140623658018560), line 287 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x7fe5645165f8> using <discord.voice_client.VoiceClient object at 0x7fe5757bdf28>
[43996.3022360801696777] 2018-08-19 06:03:50,931 - INFO - musicbot.bot | In bot.py::MainThread(140623658018560), line 512 in _autopause: Player finished playing, autopaused in empty channel
[43996.3026998043060303] 2018-08-19 06:03:50,931 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 452 in on_player_play: Running on_player_play
[43996.3035621643066406] 2018-08-19 06:03:50,932 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 671 in serialize_queue: Serializing queue for 237380793834405888
[43996.3041090965270996] 2018-08-19 06:03:50,933 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 500 in on_player_pause: Running on_player_pause
[83821.7535266876220703] 2018-08-19 17:07:36,382 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 2858 in on_guild_available: Guild "Pumpkin Knights" has become available.
[83821.7590692043304443] 2018-08-19 17:07:36,388 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 2858 in on_guild_available: Guild "NovoMeta +Bot" has become available.
[83821.7592127323150635] 2018-08-19 17:07:36,388 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 2858 in on_guild_available: Guild "Pernoite feat." has become available.
[83823.7511301040649414] 2018-08-19 17:07:38,380 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 913 in on_ready: Connection established, ready to go.
[83821.7592127323150635] 2018-08-19 17:07:36,388 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 2858 in on_guild_available: Guild "Pernoite feat." has become available.
[83823.7511301040649414] 2018-08-19 17:07:38,380 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 913 in on_ready: Connection established, ready to go.
[83823.7513508796691895] 2018-08-19 17:07:38,380 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 918 in on_ready: Received additional READY event, may have failed to resume
[83831.1857213973999023] 2018-08-19 17:07:45,814 - INFO - musicbot.bot | In bot.py::MainThread(140623658018560), line 2829 in on_voice_state_update: Unpausing in Pumpkin Knights/General
[83831.1865148544311523] 2018-08-19 17:07:45,815 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 496 in on_player_resume: Running on_player_resume
[83865.0004534721374512] 2018-08-19 17:08:19,629 - INFO - musicbot.bot | In bot.py::MainThread(140623658018560), line 2829 in on_voice_state_update: Unpausing in NovoMeta +Bot/Com Música
[83865.0014741420745850] 2018-08-19 17:08:19,630 - DEBUG - musicbot.bot | In bot.py::MainThread(140623658018560), line 496 in on_player_resume: Running on_player_resume
[84255.4868469238281250] 2018-08-19 17:14:50,115 - ERROR - musicbot.bot | In bot.py::MainThread(140623658018560), line 901 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/rtrind/.pyenv/versions/3.6.6/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 2796, in on_voice_state_update
    player = await self.get_player(channel)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 425, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[84284.2388119697570801] 2018-08-19 17:15:18,867 - ERROR - musicbot.bot | In bot.py::MainThread(140623658018560), line 901 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/rtrind/.pyenv/versions/3.6.6/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 2796, in on_voice_state_update
    player = await self.get_player(channel)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 425, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[84829.9107680320739746] 2018-08-19 17:24:24,539 - ERROR - musicbot.bot | In bot.py::MainThread(140623658018560), line 901 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/rtrind/.pyenv/versions/3.6.6/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 2796, in on_voice_state_update
    player = await self.get_player(channel)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 425, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
[84843.2815163135528564] 2018-08-19 17:24:37,910 - ERROR - musicbot.bot | In bot.py::MainThread(140623658018560), line 901 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "/home/rtrind/.pyenv/versions/3.6.6/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 2796, in on_voice_state_update
    player = await self.get_player(channel)
  File "/home/rtrind/MusicBot20180818/musicbot/bot.py", line 425, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)

```

**Comment by AutumnClove** [comment]
Should be fixed in review.

**Comment by despair86** [comment]
nice
