### ISSUE TITLE
MusicBot on Discord: Opening run.bat and have an error

### ISSUE THREAD

**Issue by PeeBee23** [Just-Some-Bots/MusicBot#1699]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x]  I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

[143.101215363] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 365, in main
    from musicbot import MusicBot
  File "C:\Users\xy\Desktop\MusicBot-master\MusicBot\musicbot\__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "C:\Users\xy\Desktop\MusicBot-master\MusicBot\musicbot\utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[145.103454590] launcher-INFO: Attempting to install dependencies...
[1423.570394516] launcher-CRITICAL: You may need to run as admin to install dependencies.
[1423.570394516] launcher-INFO: All done.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment]
Please install dependencies by running either the file `update.bat` or the command `python -m pip install -U -r requirements.txt` in the `MusicBot` directory.

It should also be noted that you should not download a zip, as you will receive an error.

**Comment by PeeBee23** [comment]
same 


[95.058441162] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 365, in main
    from musicbot import MusicBot
  File "C:\Users\xy\Desktop\musicbot\MusicBot\musicbot\__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "C:\Users\xy\Desktop\musicbot\MusicBot\musicbot\utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[96.058607101] launcher-INFO: Attempting to install dependencies...
[1816.285133362] launcher-CRITICAL: You may need to run as admin to install dependencies.
[1817.286014557] launcher-INFO: All done.

**Comment by PeeBee23** [comment]
I tried everything like 5 times and I always failed.

**Comment by AleanaA** [comment]
providing the output of `python -m pip install -U -r requirements.txt` is useful

**Comment by PeeBee23** [comment]
It works now. Thank you so much for the help :)
