### ISSUE TITLE
update.py problems

### ISSUE THREAD

**Issue by DarrelDonald** [Just-Some-Bots/MusicBot#1700]
Please tick all applicable boxes.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
update.py isn't working for me. when i try to use it, i get the following messages:

./update.py
./update.py: line 1: import: command not found
./update.py: line 2: import: command not found
./update.py: line 3: import: command not found
./update.py: line 5: syntax error near unexpected token `('
./update.py: line 5: `def y_n(q):'

### Steps to reproduce

1. run update.py

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by HaydenJM** [comment]
First, check your version of Python by using `python --version`

If you're using Python 3.5.*, try using `python3 -m pip install -U -r requirements.txt`
Make sure that you run that within the base directory of your bot.

Since I'm using Python 3.6.*, the command that I use is `python3.6 -m pip install -U -r requirements.txt`

Best of luck, Hayden M.

**Comment by AleanaA** [comment]
These errors are caused by trying to run `update.py` as if it were a bash script. To run `update.py`, use `./update.sh` or `python3 update.py`

**Comment by DarrelDonald** [comment]
This is the problem I am running into now.


./update.sh
Starting...
Passed Git checks...
You have modified files that are tracked by Git (e.g the bot's source files).
Should we try resetting the repo? You will lose local modifications. (y/n): y
HEAD is now at 1adb604 Merge branch 'review'
Checking if we need to update the bot...
Already up-to-date.
Attempting to update dependencies...
Python 3.5.4 (default, Mar  6 2018, 07:16:04) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
There was a problem fetching your current bot version. The installation may not have completed correctly.
Done!

**Comment by DarrelDonald** [comment]
This is what happens when i try using `python3 -m pip install -U -r requirements.txt`

```python3 -m pip install -U -r requirements.txt
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Downloading https://www.piwheels.org/simple/pynacl/PyNaCl-1.2.1-cp35-cp35m-linux_armv7l.whl (422kB)
    100% |████████████████████████████████| 430kB 323kB/s 
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to rewrite) to /tmp/pip-build-0h0zwgpd/discord.py
Collecting pip (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Collecting youtube_dl (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/0c/47/da1b2ce86420312d01dbe2e2362e6491fe2bbac21efb2418729cf72afa42/youtube_dl-2018.8.22-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/69/eb/58ae10d3c46a0195ffdd0e3943d255d0d5029d71e5457785ecd665bcf0f3/colorlog-3.1.4-py2.py3-none-any.whl
Collecting cffi (from -r requirements.txt (line 6))
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.11.5-cp35-cp35m-linux_armv7l.whl
Requirement already up-to-date: six in /home/pi/.local/lib/python3.5/site-packages (from pynacl==1.2.1->-r requirements.txt (line 1))
Collecting aiohttp<3.4.0,>=3.3.0 (from discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/72/6a/5bbf3544fe8de525f4521506b372dc9c3b13070fe34e911c976aa95631d7/aiohttp-3.3.2.tar.gz
Collecting websockets<7.0,>=6.0 (from discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://www.piwheels.org/simple/websockets/websockets-6.0-cp35-cp35m-linux_armv7l.whl
Requirement already up-to-date: pycparser in /home/pi/.local/lib/python3.5/site-packages (from cffi->-r requirements.txt (line 6))
Requirement already up-to-date: attrs>=17.3.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2))
Requirement already up-to-date: chardet<4.0,>=2.0 in /home/pi/.local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2))
Collecting multidict<5.0,>=4.0 (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://www.piwheels.org/simple/multidict/multidict-4.3.1-cp35-cp35m-linux_armv7l.whl
Collecting async_timeout<4.0,>=3.0 (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/96/0f/e6357458c87fb4ed8f3df215773f3caad40968f10e05552cbd8bd28415e4/async_timeout-3.0.0-py3-none-any.whl
Requirement already up-to-date: yarl<2.0,>=1.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2))
Requirement already up-to-date: idna-ssl>=1.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2))
Requirement already up-to-date: idna>=2.0 in /usr/local/lib/python3.5/site-packages (from yarl<2.0,>=1.0->aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2))
Installing collected packages: cffi, pynacl, multidict, async-timeout, aiohttp, websockets, discord.py, pip, youtube-dl, colorlog
  Found existing installation: cffi 1.11.4
    Uninstalling cffi-1.11.4:
      Successfully uninstalled cffi-1.11.4
  Rolling back uninstall of cffi
Exception:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/pi/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/pi/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/pi/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/pi/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/pi/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/pi/.local/lib/python3.5/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages/_cffi_backend.cpython-35m-arm-linux-gnueabihf.so'
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pi@raspberrypi:~/MusicBot $ ./run.sh
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: This version of MusicBot requires a newer version of discord.py (1.0+). Your version is 0.16.12. Try running update.py.
Press enter to continue . . .
```

**Comment by AleanaA** [comment]
Run `sudo python3 -m pip install -U -r requirements.txt` instead.

**Comment by DarrelDonald** [comment]
this is what i'm getting now

```pi@raspberrypi:~/MusicBot $ 
sudo python3 -m pip install sudo python3 -m pip install -U -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pynacl==1.2.1 in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 1)) (1.2.1)
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to /tmp/pip-install-sj8t3ncr/discord.py
Requirement already up-to-date: pip in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 3)) (18.0)
Requirement already up-to-date: youtube_dl in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 4)) (2018.8.22)
Requirement already up-to-date: colorlog in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 5)) (3.1.4)
Requirement already up-to-date: cffi in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 6)) (1.11.5)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.5/site-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied, skipping upgrade: aiohttp<3.4.0,>=3.3.0 in /usr/local/lib/python3.5/site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied, skipping upgrade: websockets<7.0,>=6.0 in /usr/local/lib/python3.5/site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (6.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.5/site-packages (from cffi->-r requirements.txt (line 6)) (2.18)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (18.1.0)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (4.3.1)
Requirement already satisfied, skipping upgrade: async_timeout<4.0,>=3.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.2.6)
Requirement already satisfied, skipping upgrade: idna-ssl>=1.0 in /usr/local/lib/python3.5/site-packages (from aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/local/lib/python3.5/site-packages (from yarl<2.0,>=1.0->aiohttp<3.4.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.7)
Installing collected packages: discord.py
  Found existing installation: discord.py 1.0.0a1540+gbd46708
    Uninstalling discord.py-1.0.0a1540+gbd46708:
      Successfully uninstalled discord.py-1.0.0a1540+gbd46708
  Running setup.py install for discord.py ... done
Successfully installed discord.py-1.0.0a1540+gbd46708
pi@raspberrypi:~/MusicBot $ python3 run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[CRITICAL] launcher: This version of MusicBot requires a newer version of discord.py (1.0+). Your version is 0.16.12. Try running update.py.
Press enter to continue . . .```

**Comment by waterlubber** [comment]
I have the same issue. All packages are installed in `~/.local/lib/python3.5/site-packages`. 

also: you really, really shouldn't need to install *anything* with sudo for this bot, beyond maybe a systemctl script to start it

**Comment by AutumnClove** [comment]
Should be fixed in review?
