### ISSUE TITLE
Unable to get docker build to run

### ISSUE THREAD

**Issue by DerfOh** [Just-Some-Bots/MusicBot#171]
Looks to be having an issue with PyNaCl...
I keep getting the following output when trying to run the docker container built by the Dockerfile:

```

root@e4c8e09faed1:/musicBot# sudo python3.5 run.py
No module named 'discord'
Attempting to install dependencies...
Collecting https://github.com/Rapptz/discord.py/archive/async.zip (from -r requirements.txt (line 1))
  Downloading https://github.com/Rapptz/discord.py/archive/async.zip (120kB)
    100% |################################| 122kB 1.1MB/s 
Collecting youtube-dl>=2016.3.6 (from -r requirements.txt (line 2))
  Using cached youtube_dl-2016.04.01-py2.py3-none-any.whl
Collecting aiohttp<0.22.0,>=0.21.0 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Using cached aiohttp-0.21.5.tar.gz
Collecting websockets==2.7 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Using cached websockets-2.7-py33.py34-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 116, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/bdist_egg.py", line 161, in run
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/bdist_egg.py", line 147, in call_command
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/install_lib.py", line 10, in run
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/build_ext.py", line 49, in run
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/build_ext.py", line 174, in build_extension
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 154, in save_modules
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 243, in run_setup
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 273, in run
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 242, in runner
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 46, in _execfile
      File "/tmp/easy_install-sqei1t1w/cffi-1.5.2/setup.py", line 192, in <module>
        # Check the build library
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/easy_install.py", line 1064, in run_setup
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 246, in run_setup
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 166, in save_modules
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 141, in resume
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/pkg_resources/_vendor/six.py", line 685, in reraise
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 154, in save_modules
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 243, in run_setup
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 273, in run
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 242, in runner
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/sandbox.py", line 46, in _execfile
      File "/tmp/easy_install-sqei1t1w/cffi-1.5.2/setup.py", line 192, in <module>
        # Check the build library
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9l6stn2q/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/dist.py", line 269, in __init__
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/dist.py", line 313, in fetch_build_eggs
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/pkg_resources/__init__.py", line 826, in resolve
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/pkg_resources/__init__.py", line 1071, in best_match
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/pkg_resources/__init__.py", line 1083, in obtain
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/dist.py", line 380, in fetch_build_egg
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/easy_install.py", line 640, in easy_install
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/easy_install.py", line 670, in install_item
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/easy_install.py", line 850, in install_eggs
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/easy_install.py", line 1078, in build_and_install
      File "/usr/local/lib/python3.5/dist-packages/setuptools-20.6.7-py3.5.egg/setuptools/command/easy_install.py", line 1066, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9l6stn2q/PyNaCl/

You may need to use sudo to install dependencies.

```

**Comment by abalabahaha** [comment]
Try to get Docker to install `python3.5-dev`, since it doesn't yet do that

EDIT: RIP I'm blind. Probably libffi then

**Comment by DerfOh** [comment]
Looks like python3.5-dev is installed already. Hmm.

I just tried this with sidesplitter's image from Dockerhub and it seems to be doing the same thing.

**Comment by deansheather** [comment]
We don't manage Sidesplitter's Docker image, sorry. You'll have to ask @Sidesplitter about that...

**Comment by jord-nijhuis** [comment]
This is not actually a Docker-specific issue. A few days ago the Discord library for python added [PyNaCl](https://github.com/Rapptz/discord.py/commit/10cb16a450684e8b98450ed4138968c4060137c1). This caused another dependency to be installed called `libffi`, on Debian/Ubuntu this can be installed by `sudo apt-get install libffi-dev`. I am currently modifying the Dockerfile so that it installs that dependency. Expect to see a new version soon

**Comment by jord-nijhuis** [comment]
The new image is built, so if you now pull sidesplitter/musicbot:review, this issue should be fixed.

**Comment by imayhaveborkedit** [comment]
I've merged the PR to fix this, should be good now.

**Comment by urbels** [comment]
Still failing for me.

**Comment by ciruz** [comment]
I get the same error (ubuntu), but `sudo apt-get install libffi-dev` did the trick for me. Thanks @Sidesplitter you saved me some time.

**Comment by urbels** [comment]
libffi-dev is already the newest version (3.2.1-4).
Not for me. :/
