### ISSUE TITLE
Error.starting bot Traceback (most recent call last)

### ISSUE THREAD

**Issue by Dephtings** [Just-Some-Bots/MusicBot#1716]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?
- I'm using master version (1.9.7)
- [] The latest `master` version (1.9.8) 
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug 
- [ ] Feature request
- [X] Question

----

### Description of issue
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\bot.py", line 71, in __init__
    self.config = Config(config_file)
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\config.py", line 81, in __init__
    self.run_checks()
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\config.py", line 186, in run_checks
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\config.py", line 186, in <genexpr>
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
ValueError: invalid literal for int() with base 10: 'yes'

[INFO] launcher: All done.

I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot>

### Steps to reproduce

1. 

----

### Log file
[Musicbot.txt](https://github.com/Just-Some-Bots/MusicBot/files/2353321/Musicbot.txt)
so i followed a tutorial and i did it all right but when i clicked on run.ini for launching the bot it downloaded me stuff, then after it finished i looked at my discord and saw that the bot wasn't online so i started again the bat.ini but it was saying me that he can't launch the bot and idk how to fix  please help !.

**Comment by AutumnClove** [comment]
Hi there, looking at this quickly I can see you put yes into BindToChannels, however that is done with channel ID's and as such your bot cannot start because it's trying to pass words as numbers, please correct this and if you need help your welcome to join the support server

**Comment by sutbeakappu** [comment]
I have the same problem but mine is
ValueError: invalid literal for int() with base 10: '**no**'

How can I do? It still didn't work!

**Comment by TheerapakG** [comment]
@sutbeakappu You simply don't put 'yes' or 'no' there. You put channel ID you want the bot to join there. You guys need to read stuff more. Above the option said clearly that the option
> Restricts the bot to only listening to certain text channels. To use this, add
> the IDs of the text channels you would like the bot to listen to, seperated by
> a space.

**Comment by sutbeakappu** [comment]
@TheerapakG  I left the blank or text channles IDs and still no working.

**Comment by AutumnClove** [comment]
Did you save the file?

**Comment by AutumnClove** [comment]
Would you mind uploading your options.ini file?

**Comment by AutumnClove** [comment]
Closing due to inactivity.
