### ISSUE TITLE
Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by dannymichel** [Just-Some-Bots/MusicBot#1721]
Please tick all applicable boxes.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1199, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1110, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1171, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 880, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name',))`

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
`[87.266683578] 2018-09-07 23:27:32,279 - INFO - launcher: Starting sanity checks
[95.526695251] 2018-09-07 23:27:32,287 - INFO - launcher: Checking for Python 3.5+
[95.680952072] 2018-09-07 23:27:32,287 - INFO - launcher: Checking console encoding
[95.760583878] 2018-09-07 23:27:32,287 - INFO - launcher: Ensuring we're in the right environment
[96.184015274] 2018-09-07 23:27:32,288 - INFO - launcher: Required checks passed.
[96.296072006] 2018-09-07 23:27:32,288 - INFO - launcher: Optional checks passed.
[99.489212036] 2018-09-07 23:27:32,291 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[2.4898343086242676] 2018-09-07 23:27:34,681 - WARNING - musicbot.config | In config.py::MainThread(140044203202304), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[2.4900300502777100] 2018-09-07 23:27:34,682 - INFO - musicbot.config | In config.py::MainThread(140044203202304), line 123 in run_checks: Using i18n: config/i18n/en.json
[2.5172958374023438] 2018-09-07 23:27:34,709 - DEBUG - musicbot.json | In json.py::MainThread(140044203202304), line 8 in __init__: Init JSON obj with config/i18n/en.json
[2.5268032550811768] 2018-09-07 23:27:34,718 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 227 in _setup_logging: Set logging level to INFO
[2.5269529819488525] 2018-09-07 23:27:34,719 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 84 in __init__: Starting MusicBot 1.9.7
[2.5435607433319092] 2018-09-07 23:27:34,735 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 90 in __init__: Loaded autoplaylist with 1161 entries
[2.8102624416351318] 2018-09-07 23:27:35,002 - DEBUG - musicbot.spotify | In spotify.py::MainThread(140044203202304), line 70 in get_token: Created a new access token: {'expires_in': 3600, 'access_token': 'BQBQ85PlLYT7u3d6mmN8ntA-JGKIDoDgTbCqYyJtKVfSJqaGgz8yyviP_4pqCy7RwQsAF947ItdHmFQ7yw0', 'expires_at': 1536366455, 'scope': '', 'token_type': 'Bearer'}
[2.8105435371398926] 2018-09-07 23:27:35,002 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 115 in __init__: Authenticated with Spotify successfully using client ID and secret.
[14.9416952133178711] 2018-09-07 23:27:47,133 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 1074 in on_ready: Connection established, ready to go.
[14.9419138431549072] 2018-09-07 23:27:47,133 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 339 in _cache_app_info: Caching app info
[14.9950838088989258] 2018-09-07 23:27:47,187 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 889 in _scheck_ensure_env: Ensuring data folders exist
[14.9963030815124512] 2018-09-07 23:27:47,188 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 899 in _scheck_ensure_env: Deleted old audio cache
[14.9964139461517334] 2018-09-07 23:27:47,188 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 905 in _scheck_server_permissions: Checking server permissions
[14.9965362548828125] 2018-09-07 23:27:47,188 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[14.9966058731079102] 2018-09-07 23:27:47,188 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 913 in _scheck_configs: Validating config
[14.9966683387756348] 2018-09-07 23:27:47,188 - DEBUG - musicbot.config | In config.py::MainThread(140044203202304), line 212 in async_validate: Validating options...
[14.9967336654663086] 2018-09-07 23:27:47,188 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 916 in _scheck_configs: Validating permissions config
[14.9967949390411377] 2018-09-07 23:27:47,188 - DEBUG - musicbot.permissions | In permissions.py::MainThread(140044203202304), line 64 in async_validate: Validating permissions...
[14.9968779087066650] 2018-09-07 23:27:47,188 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 1091 in on_ready: Connected: 450906388596785153/chloe#3279
[14.9987168312072754] 2018-09-07 23:27:47,190 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 1099 in on_ready: Owner:     450353275615576104/zsh#1111

[14.9988689422607422] 2018-09-07 23:27:47,190 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 1102 in on_ready: Server List:
[14.9989790916442871] 2018-09-07 23:27:47,191 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 1105 in on_ready:  - Suite 7A
[14.9990904331207275] 2018-09-07 23:27:47,191 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 1151 in on_ready: Not bound to any text channels
[14.9992115497589111] 2018-09-07 23:27:47,191 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 1164 in on_ready: Autojoining voice chanels:
[14.9993147850036621] 2018-09-07 23:27:47,191 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 1165 in <listcomp>:  - Suite 7A/music ➊ ♫
[15.0003018379211426] 2018-09-07 23:27:47,192 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 281 in _join_startup_channels: Attempting to join Suite 7A/music ➊ ♫
[15.0008115768432617] 2018-09-07 23:27:47,192 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 452 in get_voice_client: Connection attempt 1 to music ➊ ♫
[15.0009286403656006] 2018-09-07 23:27:47,193 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 391 in join_voice_channel: (join_voice_channel) creating futures
[15.0012879371643066] 2018-09-07 23:27:47,193 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 397 in join_voice_channel: (join_voice_channel) setting voice state
[15.0015995502471924] 2018-09-07 23:27:47,193 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 400 in join_voice_channel: (join_voice_channel) waiting for session id
[15.0479202270507812] 2018-09-07 23:27:47,240 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 2938 in on_voice_state_update: Voice state update for 450906388596785153/chloe#3279 on Suite 7A/music ➊ ♫ -> [JOIN, CONNECT]
[15.0482001304626465] 2018-09-07 23:27:47,240 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 2949 in on_voice_state_update: 450906388596785153/chloe#3279 has joined Suite 7A/music ➊ ♫
[15.0489623546600342] 2018-09-07 23:27:47,241 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 404 in join_voice_channel: (join_voice_channel) waiting for voice data
[15.0509989261627197] 2018-09-07 23:27:47,243 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 418 in join_voice_channel: (join_voice_channel) connecting...
[15.1234085559844971] 2018-09-07 23:27:47,315 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 430 in join_voice_channel: (join_voice_channel) connection successful
[15.1236479282379150] 2018-09-07 23:27:47,315 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 478 in get_voice_client: Connected in 0.1s
[15.1237568855285645] 2018-09-07 23:27:47,315 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 479 in get_voice_client: Connected to Suite 7A/music ➊ ♫
[15.1244568824768066] 2018-09-07 23:27:47,316 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 849 in deserialize_queue: Deserializing queue for 334487813129109504
[15.3258893489837646] 2018-09-07 23:27:47,517 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 570 in get_player: Created player via deserialization for server 334487813129109504 with 1 entries
[15.3261146545410156] 2018-09-07 23:27:47,518 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 297 in _join_startup_channels: Joined Suite 7A/music ➊ ♫
[15.3276565074920654] 2018-09-07 23:27:47,519 - VOICEDEBUG - musicbot.player | In player.py::MainThread(140044203202304), line 373 in websocket_check: Starting websocket check loop for Suite 7A
[15.3279802799224854] 2018-09-07 23:27:47,520 - DEBUG - musicbot.entry | In entry.py::MainThread(140044203202304), line 54 in get_ready_future: Created future for None
[15.3283531665802002] 2018-09-07 23:27:47,520 - INFO - musicbot.entry | In entry.py::MainThread(140044203202304), line 220 in _really_download: Download started: https://youtube.com/watch?v=L68dP1vxt5k
[15.9583232402801514] 2018-09-07 23:27:48,150 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 2938 in on_voice_state_update: Voice state update for 450909363255771137/sarah#1351 on Suite 7A/music ➍ ♫ -> [CONNECT]
[16.1648263931274414] 2018-09-07 23:27:48,356 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 2938 in on_voice_state_update: Voice state update for 450906078448844800/brook#8810 on Suite 7A/music ➋ ♫ -> [CONNECT]
[16.6577069759368896] 2018-09-07 23:27:48,849 - INFO - musicbot.entry | In entry.py::MainThread(140044203202304), line 230 in _really_download: Download complete: https://youtube.com/watch?v=L68dP1vxt5k
[16.6603946685791016] 2018-09-07 23:27:48,852 - FFMPEG - musicbot.player | In player.py::MainThread(140044203202304), line 330 in _play: Creating player with options: -nostdin -vn audio_cache/youtube-L68dP1vxt5k-Hedwig_and_the_Angry_Inch_-_Wicked_Little_Town_reprise.webm
[16.6870553493499756] 2018-09-07 23:27:48,879 - INFO - musicbot.bot | In bot.py::MainThread(140044203202304), line 256 in _autopause: Initial autopause in empty channel
[16.6885774135589600] 2018-09-07 23:27:48,880 - DEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 825 in serialize_queue: Serializing queue for 334487813129109504
[40.1779782772064209] 2018-09-07 23:28:12,370 - VOICEDEBUG - musicbot.bot | In bot.py::MainThread(140044203202304), line 2938 in on_voice_state_update: Voice state update for 450906209071923212/isabel#0140 on Suite 7A/music ➌ ♫ -> [CONNECT]
`

**Comment by AleanaA** [comment]
This was an issue with yt-dl, update your dependencies and the bot should work fine.
