### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by wsoxfan98** [Just-Some-Bots/MusicBot#1737]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Can't get the bot to start running. Just tried a complete reinstall and manually updated the bot. No success.

### Steps to reproduce
1.) run the command ./sudo.sh

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2390663/musicbot.log)

[39.265632629] 2018-09-18 00:07:40,122 - INFO - launcher: Starting sanity checks
[39.943695068] 2018-09-18 00:07:40,123 - INFO - launcher: Checking for Python 3.5+
[40.208578110] 2018-09-18 00:07:40,123 - INFO - launcher: Checking console encoding
[40.377140045] 2018-09-18 00:07:40,123 - INFO - launcher: Ensuring we're in the right environment
[41.342258453] 2018-09-18 00:07:40,124 - INFO - launcher: Required checks passed.
[41.675090790] 2018-09-18 00:07:40,125 - INFO - launcher: Optional checks passed.
[41.875123978] 2018-09-18 00:07:40,125 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[124.534606934] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/root/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/root/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'
[126.894712448] launcher-INFO: Attempting to install dependencies...
[129.628658295] launcher-INFO: All done.

**Comment by wsoxfan98** [comment]
Figured it out.
Needed to use "python3.6 run.py" to start the bot.
