### ISSUE TITLE
Not Able to Start Bot

### ISSUE THREAD

**Issue by Nia1415** [Just-Some-Bots/MusicBot#1757]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
 
[36.726474762] 2018-10-09 20:23:39,127 - INFO - launcher: Starting sanity checks
[37.258386612] 2018-10-09 20:23:39,127 - INFO - launcher: Checking for Python 3.5+
[37.484884262] 2018-10-09 20:23:39,128 - INFO - launcher: Checking console encoding
[37.696599960] 2018-10-09 20:23:39,128 - INFO - launcher: Ensuring we're in the right environment
[38.790225983] 2018-10-09 20:23:39,129 - INFO - launcher: Required checks passed.
[39.094924927] 2018-10-09 20:23:39,129 - INFO - launcher: Optional checks passed.
[39.294481277] 2018-10-09 20:23:39,129 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[100.049257278] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/home/ubuntu/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/home/ubuntu/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'
[101.437807083] launcher-INFO: Attempting to install dependencies...
[103.332996368] launcher-INFO: All done.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2473250/musicbot.log)

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
Use run.py instead
