### ISSUE TITLE
Error in some songs

### ISSUE THREAD

**Issue by itsfolf** [Just-Some-Bots/MusicBot#179]
Sometimes when a song start after download I get this error and the bot stop:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 127, in run
    super().run()
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 93, in run
    self.player(data)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 676, in play_audio
    sent = self.socket.sendto(packet, (self.endpoint_ip, self.voice_port))
PermissionError: [Errno 1] Operation not permitted
```

Can you solve this, restart the bot always is getting annoying

**Comment by imayhaveborkedit** [comment]
I'm not exactly sure what to tell you on this one.  I can tell you that this isn't a bot issue, its an OS issue.  I was told to refer to this: http://stackoverflow.com/questions/23859164/linux-udp-socket-sendto-operation-not-permitted

**Comment by imayhaveborkedit** [comment]
This has been fixed in discord.py.
