### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by the-darklord** [Just-Some-Bots/MusicBot#1797]
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\bot.py", line 71, in __init__
    self.config = Config(config_file)
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\config.py", line 81, in __init__
    self.run_checks()
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\config.py", line 186, in run_checks
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
  File "I:\Users\Administrator\AppData\Local\Programs\Start BOT pizz\MusicBot\musicbot\config.py", line 186, in <genexpr>
    self.autojoin_channels = set(int(item.replace(',', ' ').strip()) for item in self.autojoin_channels)
ValueError: invalid literal for int() with base 10: 'yes'

[INFO] launcher: All done.

**Comment by the-darklord** [comment]
I am getting this

Help me anyone

**Comment by AleanaA** [comment]
Reading the options you're changing is a good idea before changing them. Change AutoJoinChannels to the ID of the channel you want the bot to join.
