### ISSUE TITLE
Can't add music in queue

### ISSUE THREAD

**Issue by kiwioverflow** [Just-Some-Bots/MusicBot#1825]
Please tick all applicable boxes.

- [v] I am using Python 3.5 or higher (run `python --version` on the command line)
- [v] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [v] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [v] The latest `master` version (1.9.8)
- [] The latest `review` version

What type of issue are you creating?

- [v] Bug
- [] Feature request
- [] Question

----

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

Error:[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'",))

**Comment by AutumnClove** [comment]
Run your update file and try again

**Comment by Migz93** [comment]
I'm getting the same error as above whenever i try to play anything.
Last used the bot maybe about 2 weeks ago and it was fine then, now whenever i try to !play anything it gives me that error and doesn't play.

I run it in a docker, does the same on review, master & 1.9.8_2.

**Comment by AutumnClove** [comment]
Did you run the update file

**Comment by Migz93** [comment]
Hi, thanks for the reply.
Unsure how exactly to run the update file on this container, usually just pulling the latest image down would update whatever is required but that doesn't seem to work.
Running either of the below doesn't work either
docker exec -it musicbot /bin/bash
docker exec -it musicbot python3 update.py

Could you advise how to run the update file with a container?

**Comment by TheerapakG** [comment]
since 1.9.8_2, passing -update flag should start the update script.

**Comment by Migz93** [comment]
Worked out that i could use "docker exec -it musicbot /bin/ash" to get into the container.
I then ran "python3 run.py -update" which gave me the following:

```
/usr/src/musicbot # python3 run.py -update
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot 1.9.8_3
Loaded autoplaylist with 2305 entries
Authenticated with Spotify successfully using client ID and secret.

Connected: xxx/xxx
Owner:     xxx/xxx

Guild List:
 - Glendale

Bound to text channels:
 - Glendale/general
 - Glendale/botchat

Not autojoining any voice channels

Found resumable voice channel Glendale/Voice-Chat
Attempting to join Glendale/Voice-Chat
Joined 

Glendale/Voice-Chat
```

But again once trying to !play a song i get
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1231, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1139, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1206, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'",))
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1231, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1139, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1206, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'",))
^CTraceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 373, in main
    m.run()
  File "/usr/src/musicbot/musicbot/bot.py", line 866, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 460, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1404, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
```

**Comment by AleanaA** [comment]
you ran the run script, not the update script.

**Comment by Migz93** [comment]
TheerapakG seemed to advise that passing the "-update" flag would start the update script?

Running "python3 update.py" gives the following:
```
/usr/src/musicbot # python3 update.py
Starting...
Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 35, in main
    raise EnvironmentError("This isn't a Git repository.")
OSError: This isn't a Git repository.
```

Trying to run the update.sh directly gives:
```
/bin/ash: ./update.sh: Permission denied
```

**Comment by kiwioverflow** [comment]
> root@discord-bot:/home/_myaccountname_/MusicBot# ./update.sh

`-bash: ./update.sh: Permission denied`

> root@discord-bot:/home/_myaccountname_/MusicBot# sh update.sh

`update.sh: 4: update.sh: Syntax error: "(" unexpected`

> root@discord-bot:/home/_myaccountname_/MusicBot# python update.py

`Starting...
Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 40, in main
    subprocess.check_call('git --version', shell=True, stdout=subprocess.DEVNULL)
AttributeError: 'module' object has no attribute 'DEVNULL'`

> root@discord-bot:/home/_myaccountname_/MusicBot# 

=================================================================

So I downloaded and updated it directly, but the problem still exists and still can't add music in queue.

**Comment by AleanaA** [comment]
`sh update.sh` is the improper way to run the update bash script. Either run `bash update.sh` or make it executable with `sudo chmod +x ./update.sh` and then run it with `./run.sh`

You also really shouldn't be on the root user if you have a user account. That's the whole point of `sudo`, and in this case `sudo` shouldn't be needed at any point.

**Comment by kiwioverflow** [comment]
I entered sudo habitually.
So i updated ./update.sh permissions, but there is more problem..
 
> parkkw472@discord-bot:~/MusicBot$ ./update.sh

```
`./update.sh: line 7: python3.6: command not found
./update.sh: line 8: python3.7: command not found
Starting...
Passed Git checks...
You have modified files that are tracked by Git (e.g the bot's source files).
Should we try resetting the repo? You will lose local modifications. (y/n): y
HEAD is now at b068250 Merge pull request #1800 from Just-Some-Bots/review
Checking if we need to update the bot...
Already up-to-date.
Attempting to update dependencies...
Requirement already up-to-date: pynacl==1.2.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.2.1)
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to /tmp/pip-install-fbag8uqd/discord.py
Branch rewrite set up to track remote branch rewrite from origin.
Switched to a new branch 'rewrite'
Collecting pip (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl
Collecting youtube_dl (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a4/18/4839e0d7f1d1d7be081e8f9a423b60bba3d7da77b18ea7c58d9a48abe4fd/youtube_dl-2019.1.24-py2.py3-none-any.whl
Requirement already up-to-date: colorlog in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5)) (4.0.2)
Requirement already up-to-date: cffi in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6)) (1.11.5)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.10.0)
Requirement already satisfied, skipping upgrade: aiohttp<3.5.0,>=3.3.0 in /usr/local/lib/python3.5/dist-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.4.4)
Requirement already satisfied, skipping upgrade: websockets<7.0,>=6.0 in /usr/local/lib/python3.5/dist-packages (from discord.py[voice]->-r requirements.txt (line 2)) (6.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi->-r requirements.txt (line 6)) (2.19)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (18.2.0)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (4.5.2)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied, skipping upgrade: idna-ssl>=1.0; python_version < "3.7" in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.3.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.2)
Building wheels for collected packages: discord.py
  Running setup.py bdist_wheel for discord.py ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-buvafn9z/wheels/ed/b6/9f/539955db4b120b117ac6f797f4c0619b896bf296bff7c712ac
Successfully built discord.py
Installing collected packages: discord.py, pip, youtube-dl
  Found existing installation: discord.py 1.0.0a1630+g26bb6c6
    Uninstalling discord.py-1.0.0a1630+g26bb6c6:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/discord.py-1.0.0a1630+g26bb6c6.dist-info/DESCRIPTION.rst'
Consider using the `--user` option or check the permissions.

You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install -U -r requirements.txt'.format(sys.executable), shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/usr/bin/python3" -m pip install -U -r requirements.txt' returned non-zero exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\" -m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"/usr/bin/python3" -m pip install -U -r requirements.txt' yourself.`
```
==================================================================
Is there a difference between downloading and updating directly from Github or using update.sh?

**Comment by AleanaA** [comment]
downloading directly from github will result in an error, and also won't fix anything as it's not the bot that's having an issue. Run `python3 -m pip install --user -U -r requirements.txt` and your issue should be fixed.

**Comment by TheerapakG** [comment]
@Migz93 Use command `docker run [image] -update`, this will update dependencies and start the bot.

**Comment by kiwioverflow** [comment]
```
parkkw472@discord-bot:~/MusicBot$ python3 -m pip --user -U -r requirements.txt

Usage:   
  /usr/bin/python3 -m pip <command> [options]

no such option: --user
parkkw472@discord-bot:~/MusicBot$ /usr/bin/python3 -m pip --user -U -r requirements.txt

Usage:   
  /usr/bin/python3 -m pip <command> [options]

no such option: --user
```

**Comment by AleanaA** [comment]
Fixed the above command to include the actual pip command.

**Comment by kiwioverflow** [comment]
```
parkkw472@discord-bot:~/MusicBot$ /usr/bin/python3 -m pip requirements.txt -U -r  --user
ERROR: unknown command "requirements.txt"
parkkw472@discord-bot:~/MusicBot$ /usr/bin/python3 -m pip "requirements.txt" -U -r  --user
ERROR: unknown command "requirements.txt"
parkkw472@discord-bot:~/MusicBot$ /usr/bin/python3 -m pip "./requirements.txt" -U -r  --user
ERROR: unknown command "./requirements.txt"
parkkw472@discord-bot:~/MusicBot$ /usr/bin/python3 -m pip -r "requirements.txt" -U -r  --user
Usage:   
  /usr/bin/python3 -m pip <command> [options]
no such option: -r
parkkw472@discord-bot:~/MusicBot$
```
Am I typing the wrong? :(

**Comment by AleanaA** [comment]
`python3 -m pip install --user -U -r requirements.txt`

**Comment by kiwioverflow** [comment]
```
parkkw472@discord-bot:~/MusicBot$ python3 -m pip install --user -U -r requirements.txt
Requirement already up-to-date: pynacl==1.2.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.2.1)
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line
 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to /tmp/pip-install-afy3c6tk/discord.py
Branch rewrite set up to track remote branch rewrite from origin.
Switched to a new branch 'rewrite'
Collecting pip (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2
.py3-none-any.whl
Collecting youtube_dl (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a4/18/4839e0d7f1d1d7be081e8f9a423b60bba3d7da77b18ea7c58d9a48abe4fd/youtube_dl-201
9.1.24-py2.py3-none-any.whl
Requirement already up-to-date: colorlog in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5)) (4.0.2)
Requirement already up-to-date: cffi in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6)) (1.11.5)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from pynacl==1.2.1->-r requirements.txt (line 1)
) (1.10.0)
Requirement already satisfied, skipping upgrade: aiohttp<3.5.0,>=3.3.0 in /usr/local/lib/python3.5/dist-packages (from discord.py[voice]
->-r requirements.txt (line 2)) (3.4.4)
Requirement already satisfied, skipping upgrade: websockets<7.0,>=6.0 in /usr/local/lib/python3.5/dist-packages (from discord.py[voice]-
>-r requirements.txt (line 2)) (6.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi->-r requirements.txt (li
ne 6)) (2.19)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<3.5.0,>=3.3.0->discor
d.py[voice]->-r requirements.txt (line 2)) (2.3.0)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>
=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3
.0->discord.py[voice]->-r requirements.txt (line 2)) (4.5.2)
Requirement already satisfied, skipping upgrade: idna-ssl>=1.0; python_version < "3.7" in /usr/local/lib/python3.5/dist-packages (from a
iohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3.0->di
scord.py[voice]->-r requirements.txt (line 2)) (18.2.0)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp<3.5.0,>=3.3.0->d
iscord.py[voice]->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/lib/python3/dist-packages (from idna-ssl>=1.0; python_version < "3.7"
->aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.2)
Building wheels for collected packages: discord.py
  Running setup.py bdist_wheel for discord.py ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-9q1vhgfw/wheels/ed/b6/9f/539955db4b120b117ac6f797f4c0619b896bf296bff7c712ac
Successfully built discord.py
Installing collected packages: discord.py, pip, youtube-dl
  The script youtube-dl is installed in '/home/parkkw472/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed discord.py-1.0.0a1634+g7f4c57d pip-19.0.1 youtube-dl-2019.1.24
parkkw472@discord-bot:~/MusicBot$ screen bash
---new screen---
parkkw472@discord-bot:~/MusicBot$ sudo ./run.sh
./run.sh: line 7: python3.6: command not found
./run.sh: line 8: python3.7: command not found
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[Owner (auto)] section not found, falling back to permissive default
Starting MusicBot 1.9.8_3
Loaded autoplaylist with 2531 entries
Authenticated with Spotify successfully using client ID and secret.
Connected: 518741158751502358/Xeon BOT-01#8270
Owner:     348689024669712394/KeonWoo PARK#6974
Guild List:
 - ???1
 - ???2
 - ???3
 - ???4
 - ???5
 - ???6
 - ???7
 - ???8
 - ???9
 - ???10
 - ???11
 - ???12
Not bound to any text channels
Not autojoining any voice channels
Found owner in "일반"
Attempting to join ???6/test
Joined ???6/test
WARNING: Your config file is missing some options. If you have recently updated, check the example_options.ini file to see if there are 
new options available to you. The options missing are: {'queuelength', 'leaveserverswithoutowner', 'showconfigonlaunch', 'removefromapon
error', 'autoplaylistrandom', 'useembeds', 'allowauthorskip', 'autojoinchannels', 'i18nfile', 'bindtochannels', 'writecurrentsong', 'use
experimentalequalization', 'allowunboundservers', 'legacyskip'}
000000000000000/KeonWoo PARK#????: ?play shape of you
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'",))
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'",))

---detach screen---
[detached from 32402.pts-0.discord-bot]
```
Same problem over again.

**Comment by AleanaA** [comment]
`The script youtube-dl is installed in '/home/parkkw472/.local/bin' which is not on PATH` would be the issue there

just run `sudo python3 -m pip install -U youtube-dl`

**Comment by 4472thtm** [comment]
IT WORKS! (YEAHHHH)
Thank you @AleanaA for helping fix error 👍👍👍

**Comment by Migz93** [comment]
Thanks for the help so far, reran with the correct update command and it looks to have updated correctly as i get this:
```
Requirement already satisfied: pynacl==1.2.1 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (1.2.1),
Requirement already satisfied: discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (1.0.0a1634+g7f4c57d),
Requirement already satisfied: pip in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (10.0.1),
Requirement already satisfied: youtube_dl in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (2019.1.10),
Requirement already satisfied: colorlog in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (4.0.2),
Requirement already satisfied: cffi in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (1.11.5),
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.12.0),
Requirement already satisfied: aiohttp<3.5.0,>=3.3.0 in /usr/lib/python3.6/site-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.4.4),
Collecting websockets<7.0,>=6.0 (from discord.py[voice]->-r requirements.txt (line 2)),
  Downloading https://files.pythonhosted.org/packages/4e/2a/56e60bb4c3696bc736998cc13c3fa1a36210609d7e1a3f2519857b420245/websockets-6.0.tar.gz (70kB),
Requirement already satisfied: pycparser in /usr/lib/python3.6/site-packages (from cffi->-r requirements.txt (line 6)) (2.19),
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3.6/site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (18.2.0),
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/lib/python3.6/site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.4),
Requirement already satisfied: multidict<5.0,>=4.0 in /usr/lib/python3.6/site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (4.5.2),
Requirement already satisfied: async_timeout<4.0,>=3.0 in /usr/lib/python3.6/site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (3.0.1),
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/lib/python3.6/site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.3.0),
Requirement already satisfied: idna-ssl>=1.0 in /usr/lib/python3.6/site-packages (from aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (1.1.0),
Requirement already satisfied: idna>=2.0 in /usr/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp<3.5.0,>=3.3.0->discord.py[voice]->-r requirements.txt (line 2)) (2.8),
Installing collected packages: websockets,
  Found existing installation: websockets 4.0.1,
    Uninstalling websockets-4.0.1:,
      Successfully uninstalled websockets-4.0.1,
  Running setup.py install for websockets: started,
    Running setup.py install for websockets: finished with status 'done',
Successfully installed websockets-6.0,
You are using pip version 10.0.1, however version 19.0.1 is available.,
You should consider upgrading via the 'pip install --upgrade pip' command.,
[INFO] launcher: Starting sanity checks,
[INFO] launcher: Checking for Python 3.5+,
[INFO] launcher: Checking console encoding,
[INFO] launcher: Ensuring we're in the right environment,
[INFO] launcher: Required checks passed.,
[INFO] launcher: Optional checks passed.,
]2;MusicBot 1.9.8_3,
Starting MusicBot 1.9.8_3,
Loaded autoplaylist with 2305 entries,
Authenticated with Spotify successfully using client ID and secret.,
,
Connected: xxx/xxx,
Owner:     xxx/xxx,
,
Guild List:,
 - Glendale,
,
Bound to text channels:,
 - Glendale/general,
 - Glendale/botchat,
,
Not autojoining any voice channels,
,
Found resumable voice channel Glendale/Voice-Chat,
Attempting to join Glendale/Voice-Chat,
Joined Glendale/Voice-Chat,
```

But unfortunately i still get the error when trying to play anything. What specifically needs to be updated?

**Comment by AleanaA** [comment]
`youtube-dl` @Migz93

**Comment by Migz93** [comment]
@AleanaA awesome thank you, worked out that my youtube-dl was stuck on 2019.1.10 and wouldn't update to 2019.1.24. Ran "pip3 install --upgrade youtube_dl` which forced youtube-dl to update. All sorted now and back in action, thanks everyone.
