### ISSUE TITLE
not working and crushing few times

### ISSUE THREAD

**Issue by Tazo83** [Just-Some-Bots/MusicBot#1844]
Please tick all applicable boxes.

- [ x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [ ] The latest `review` version
Starting MusicBot 1.9.8_4
What type of issue are you creating?

- [ x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

older version was working great did update it 2 days again and now am having issue every few hours sometime bots join channel and no voice  cannot play any song from cached 

and sometime the sound just burst and then nothing is working

### Steps to reproduce

1. 
 updated the bot
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[41.137456894] 2019-02-23 12:50:57,663 - INFO - launcher: Starting sanity checks
[42.136430740] 2019-02-23 12:50:57,664 - INFO - launcher: Checking for Python 3.5+
[42.136430740] 2019-02-23 12:50:57,664 - INFO - launcher: Checking console encoding
[42.136430740] 2019-02-23 12:50:57,664 - INFO - launcher: Setting console encoding to UTF-8
[42.136430740] 2019-02-23 12:50:57,664 - INFO - launcher: Ensuring we're in the right environment
[44.135808945] 2019-02-23 12:50:57,666 - INFO - launcher: Adding local bins/ folder to path
[734.310865402] 2019-02-23 12:50:58,356 - INFO - launcher: Required checks passed.
[734.310865402] 2019-02-23 12:50:58,356 - INFO - launcher: Optional checks passed.
[735.311269760] 2019-02-23 12:50:58,358 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.6832387447357178] 2019-02-23 12:50:59,305 - WARNING - musicbot.config | In config.py::MainThread(17592), line 116 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.6832387447357178] 2019-02-23 12:50:59,305 - INFO - musicbot.config | In config.py::MainThread(17592), line 127 in run_checks: Using i18n: config/i18n/en.json
[1.6862380504608154] 2019-02-23 12:50:59,308 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 226 in _setup_logging: Set logging level to INFO
[1.6892371177673340] 2019-02-23 12:50:59,311 - DEBUG - musicbot.json | In json.py::MainThread(17592), line 8 in __init__: Init JSON obj with config/i18n/en.json
[2.4190487861633301] 2019-02-23 12:51:00,041 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 91 in __init__: Starting MusicBot 1.9.8_4
[2.4300458431243896] 2019-02-23 12:51:00,052 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 97 in __init__: Loaded autoplaylist with 37 entries
[7.9075984954833984] 2019-02-23 12:51:05,530 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 922 in on_ready: Connection established, ready to go.
[7.9075984954833984] 2019-02-23 12:51:05,530 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 340 in _cache_app_info: Caching app info
[8.1545252799987793] 2019-02-23 12:51:05,777 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 744 in _scheck_ensure_env: Ensuring data folders exist
[8.1555252075195312] 2019-02-23 12:51:05,778 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 760 in _scheck_server_permissions: Checking server permissions
[8.1565468311309814] 2019-02-23 12:51:05,779 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 764 in _scheck_autoplaylist: Auditing autoplaylist
[8.1565468311309814] 2019-02-23 12:51:05,779 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 768 in _scheck_configs: Validating config
[8.1565468311309814] 2019-02-23 12:51:05,779 - DEBUG - musicbot.config | In config.py::MainThread(17592), line 217 in async_validate: Validating options...
[8.1565468311309814] 2019-02-23 12:51:05,779 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 771 in _scheck_configs: Validating permissions config
[8.1565468311309814] 2019-02-23 12:51:05,779 - DEBUG - musicbot.permissions | In permissions.py::MainThread(17592), line 94 in async_validate: Validating permissions...
[8.1575248241424561] 2019-02-23 12:51:05,780 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 939 in on_ready: Connected: 518067075151822848/Tazo Weed Lab#8253
[8.1575248241424561] 2019-02-23 12:51:05,780 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 947 in on_ready: Owner:     129608074410459136/tazo#0589

[8.1585252285003662] 2019-02-23 12:51:05,781 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 950 in on_ready: Guild List:
[8.1585252285003662] 2019-02-23 12:51:05,781 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 954 in on_ready:  - Topdark
[8.1595234870910645] 2019-02-23 12:51:05,782 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 954 in on_ready:  - Pain and Pleasure
[8.1595234870910645] 2019-02-23 12:51:05,782 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 1010 in on_ready: Not bound to any text channels
[8.1605231761932373] 2019-02-23 12:51:05,783 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 1036 in on_ready: Not autojoining any voice channels
[8.1605231761932373] 2019-02-23 12:51:05,783 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 264 in _join_startup_channels: Found resumable voice channel Pain and Pleasure/music-and-chill
[8.1615240573883057] 2019-02-23 12:51:05,784 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 270 in _join_startup_channels: Found owner in "music-and-chill"
[8.1615240573883057] 2019-02-23 12:51:05,784 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 279 in _join_startup_channels: Attempting to join Pain and Pleasure/music-and-chill
[9.5885000228881836] 2019-02-23 12:51:07,211 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 704 in deserialize_queue: Deserializing queue for 152691091110363146
[9.8227791786193848] 2019-02-23 12:51:07,445 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 423 in get_player: Created player via deserialization for guild 152691091110363146 with 1 entries
[9.8227791786193848] 2019-02-23 12:51:07,445 - INFO - musicbot.bot | In bot.py::MainThread(17592), line 295 in _join_startup_channels: Joined Pain and Pleasure/music-and-chill
[9.8237798213958740] 2019-02-23 12:51:07,446 - DEBUG - musicbot.entry | In entry.py::MainThread(17592), line 56 in get_ready_future: Created future for audio_cache\youtube-pVLmZMjxfjw-Eiffel_65_-_Blue_KNY_Factory_Remix.webm
[9.8237798213958740] 2019-02-23 12:51:07,446 - FFMPEG - musicbot.player | In player.py::MainThread(17592), line 273 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-pVLmZMjxfjw-Eiffel_65_-_Blue_KNY_Factory_Remix.webm
[9.8287787437438965] 2019-02-23 12:51:07,451 - DEBUG - musicbot.player | In player.py::MainThread(17592), line 284 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x000001CC0F9859E8> using <discord.voice_client.VoiceClient object at 0x000001CC0E7BF908>
[9.8297777175903320] 2019-02-23 12:51:07,452 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 458 in on_player_play: Running on_player_play
[9.8307774066925049] 2019-02-23 12:51:07,453 - DEBUG - musicbot.bot | In bot.py::MainThread(17592), line 680 in serialize_queue: Serializing queue for 152691091110363146

**Comment by AutumnClove** [comment]
This log shows everything showing fine, your bug description is lackadaisical, I've read it several times and still am at a loss as to what exactly is happening to you, it appears English is not your first language as such I might suggest you come to the [discord server](https://www.discord.gg/bots)

**Comment by Tazo83** [comment]
suddenly the voice get very high and then its all gone 

and shutting down the bot and run it up again wont fix it only fix is i have to run the updater everytime this happen to fix it

**Comment by AutumnClove** [comment]
This sounds like an internet issue, I'd suggest getting a vps

**Comment by Tazo83** [comment]
its not internet issue all the songs are already cached in the musicbot folder

**Comment by AleanaA** [comment]
Still has to send the audio to discord, regardless of whether it has to download the songs or not.

**Comment by Tazo83** [comment]
never had the issue before on previous version i was running it for more thank 5 month without even 1 issue

**Comment by AleanaA** [comment]
Regardless of the cause, if running the update script solves the issue, the next time the error occurs, you'll need to provide the output of the update script.

**Comment by Tazo83** [comment]
i will once it happens again

**Comment by Tazo83** [comment]
got this error am not sure if its releated to same issue or this is another one Fatal read error on pipe transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001F6A240ED68>
transport: <_ProactorSocketTransport fd=808>
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\proactor_events.py", line 189, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 697, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 437, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired
Error in data transfer
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "C:\Program Files\Python35\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "C:\Program Files\Python35\lib\asyncio\streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "C:\Program Files\Python35\lib\asyncio\streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 310, in _wakeup
    future.result()
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Program Files\Python35\lib\asyncio\proactor_events.py", line 189, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 697, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 437, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired
Fatal read error on pipe transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001F6A25AA780>
transport: <_ProactorSocketTransport fd=900>
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\proactor_events.py", line 189, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 697, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 437, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired
Error in data transfer
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Program Files\Python35\lib\site-packages\websockets\protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "C:\Program Files\Python35\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "C:\Program Files\Python35\lib\asyncio\streams.py", line 668, in readexactly
    yield from self._wait_for_data('readexactly')
  File "C:\Program Files\Python35\lib\asyncio\streams.py", line 458, in _wait_for_data
    yield from self._waiter
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 310, in _wakeup
    future.result()
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Program Files\Python35\lib\asyncio\proactor_events.py", line 189, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 697, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 437, in finish_recv
    return ov.getresult()
OSError: [WinError 121] The semaphore timeout period has expired

**Comment by Tazo83** [comment]
ot autojoining any voice channels

[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\discord\client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Taz.DESKTOP-BPGRUJ4\Music\MusicBot-master\MusicBot\musicbot\bot.py", line 2842, in on_voice_state_update
    player = await self.get_player(channel)
  File "C:\Users\Taz.DESKTOP-BPGRUJ4\Music\MusicBot-master\MusicBot\musicbot\bot.py", line 431, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.


[52.984714508] 2019-02-24 12:58:06,905 - INFO - launcher: Starting sanity checks
[52.984714508] 2019-02-24 12:58:06,905 - INFO - launcher: Checking for Python 3.5+
[52.984714508] 2019-02-24 12:58:06,905 - INFO - launcher: Checking console encoding
[52.984714508] 2019-02-24 12:58:06,905 - INFO - launcher: Setting console encoding to UTF-8
[52.984714508] 2019-02-24 12:58:06,905 - INFO - launcher: Ensuring we're in the right environment
[54.985046387] 2019-02-24 12:58:06,907 - INFO - launcher: Adding local bins/ folder to path
[841.754674911] 2019-02-24 12:58:07,693 - INFO - launcher: Required checks passed.
[842.754602432] 2019-02-24 12:58:07,694 - INFO - launcher: Optional checks passed.
[842.754602432] 2019-02-24 12:58:07,694 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[2.0873911380767822] 2019-02-24 12:58:08,939 - WARNING - musicbot.config | In config.py::MainThread(23592), line 116 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[2.0873911380767822] 2019-02-24 12:58:08,939 - INFO - musicbot.config | In config.py::MainThread(23592), line 127 in run_checks: Using i18n: config/i18n/en.json
[2.0903909206390381] 2019-02-24 12:58:08,942 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 226 in _setup_logging: Set logging level to INFO
[2.0943906307220459] 2019-02-24 12:58:08,946 - DEBUG - musicbot.json | In json.py::MainThread(23592), line 8 in __init__: Init JSON obj with config/i18n/en.json
[2.6662225723266602] 2019-02-24 12:58:09,518 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 91 in __init__: Starting MusicBot 1.9.8_4
[2.6672222614288330] 2019-02-24 12:58:09,519 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 97 in __init__: Loaded autoplaylist with 37 entries
[8.1396267414093018] 2019-02-24 12:58:14,991 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 922 in on_ready: Connection established, ready to go.
[8.1396267414093018] 2019-02-24 12:58:14,991 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 340 in _cache_app_info: Caching app info
[8.4115471839904785] 2019-02-24 12:58:15,263 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 744 in _scheck_ensure_env: Ensuring data folders exist
[8.4125478267669678] 2019-02-24 12:58:15,264 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 760 in _scheck_server_permissions: Checking server permissions
[8.4125478267669678] 2019-02-24 12:58:15,264 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 764 in _scheck_autoplaylist: Auditing autoplaylist
[8.4125478267669678] 2019-02-24 12:58:15,264 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 768 in _scheck_configs: Validating config
[8.4125478267669678] 2019-02-24 12:58:15,264 - DEBUG - musicbot.config | In config.py::MainThread(23592), line 217 in async_validate: Validating options...
[8.4125478267669678] 2019-02-24 12:58:15,264 - DEBUG - musicbot.bot | In bot.py::MainThread(23592), line 771 in _scheck_configs: Validating permissions config
[8.4135470390319824] 2019-02-24 12:58:15,265 - DEBUG - musicbot.permissions | In permissions.py::MainThread(23592), line 94 in async_validate: Validating permissions...
[8.4135470390319824] 2019-02-24 12:58:15,265 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 939 in on_ready: Connected: 518067075151822848/Tazo Weed Lab#8253
[8.4135470390319824] 2019-02-24 12:58:15,265 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 947 in on_ready: Owner:     129608074410459136/tazo#0589

[8.4145479202270508] 2019-02-24 12:58:15,266 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 950 in on_ready: Guild List:
[8.4145479202270508] 2019-02-24 12:58:15,266 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 954 in on_ready:  - Topdark
[8.4145479202270508] 2019-02-24 12:58:15,266 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 954 in on_ready:  - Pain and Pleasure
[8.4145479202270508] 2019-02-24 12:58:15,266 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 1010 in on_ready: Not bound to any text channels
[8.4155464172363281] 2019-02-24 12:58:15,267 - INFO - musicbot.bot | In bot.py::MainThread(23592), line 1036 in on_ready: Not autojoining any voice channels
[12.2294340133666992] 2019-02-24 12:58:19,081 - ERROR - musicbot.bot | In bot.py::MainThread(23592), line 910 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\discord\client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Taz.DESKTOP-BPGRUJ4\Music\MusicBot-master\MusicBot\musicbot\bot.py", line 2842, in on_voice_state_update
    player = await self.get_player(channel)
  File "C:\Users\Taz.DESKTOP-BPGRUJ4\Music\MusicBot-master\MusicBot\musicbot\bot.py", line 431, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

**Comment by Tazo83** [comment]
sounds is gone now am tryin to fix it 

[38.990020752] 2019-02-24 13:01:48,798 - INFO - launcher: Starting sanity checks
[38.990020752] 2019-02-24 13:01:48,798 - INFO - launcher: Checking for Python 3.5+
[38.990020752] 2019-02-24 13:01:48,798 - INFO - launcher: Checking console encoding
[38.990020752] 2019-02-24 13:01:48,798 - INFO - launcher: Setting console encoding to UTF-8
[39.988040924] 2019-02-24 13:01:48,799 - INFO - launcher: Ensuring we're in the right environment
[40.987253189] 2019-02-24 13:01:48,800 - INFO - launcher: Adding local bins/ folder to path
[671.073675156] 2019-02-24 13:01:49,430 - INFO - launcher: Required checks passed.
[671.073675156] 2019-02-24 13:01:49,430 - INFO - launcher: Optional checks passed.
[671.073675156] 2019-02-24 13:01:49,430 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.5178010463714600] 2019-02-24 13:01:50,276 - WARNING - musicbot.config | In config.py::MainThread(23512), line 116 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.5188100337982178] 2019-02-24 13:01:50,277 - INFO - musicbot.config | In config.py::MainThread(23512), line 127 in run_checks: Using i18n: config/i18n/en.json
[1.5198030471801758] 2019-02-24 13:01:50,278 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 226 in _setup_logging: Set logging level to INFO
[1.5218021869659424] 2019-02-24 13:01:50,280 - DEBUG - musicbot.json | In json.py::MainThread(23512), line 8 in __init__: Init JSON obj with config/i18n/en.json
[2.2373538017272949] 2019-02-24 13:01:50,996 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 91 in __init__: Starting MusicBot 1.9.8_4
[2.2383544445037842] 2019-02-24 13:01:50,997 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 97 in __init__: Loaded autoplaylist with 37 entries
[7.7496633529663086] 2019-02-24 13:01:56,508 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 922 in on_ready: Connection established, ready to go.
[7.7506630420684814] 2019-02-24 13:01:56,509 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 340 in _cache_app_info: Caching app info
[8.0105872154235840] 2019-02-24 13:01:56,769 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 744 in _scheck_ensure_env: Ensuring data folders exist
[8.0115866661071777] 2019-02-24 13:01:56,770 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 760 in _scheck_server_permissions: Checking server permissions
[8.0115866661071777] 2019-02-24 13:01:56,770 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 764 in _scheck_autoplaylist: Auditing autoplaylist
[8.0115866661071777] 2019-02-24 13:01:56,770 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 768 in _scheck_configs: Validating config
[8.0115866661071777] 2019-02-24 13:01:56,770 - DEBUG - musicbot.config | In config.py::MainThread(23512), line 217 in async_validate: Validating options...
[8.0125865936279297] 2019-02-24 13:01:56,771 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 771 in _scheck_configs: Validating permissions config
[8.0125865936279297] 2019-02-24 13:01:56,771 - DEBUG - musicbot.permissions | In permissions.py::MainThread(23512), line 94 in async_validate: Validating permissions...
[8.0125865936279297] 2019-02-24 13:01:56,771 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 939 in on_ready: Connected: 518067075151822848/Tazo Weed Lab#8253
[8.0135869979858398] 2019-02-24 13:01:56,772 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 947 in on_ready: Owner:     129608074410459136/tazo#0589

[8.0135869979858398] 2019-02-24 13:01:56,772 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 950 in on_ready: Guild List:
[8.0135869979858398] 2019-02-24 13:01:56,772 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 954 in on_ready:  - Topdark
[8.0145871639251709] 2019-02-24 13:01:56,773 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 954 in on_ready:  - Pain and Pleasure
[8.0145871639251709] 2019-02-24 13:01:56,773 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 1010 in on_ready: Not bound to any text channels
[8.0155863761901855] 2019-02-24 13:01:56,774 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 1036 in on_ready: Not autojoining any voice channels
[8.0155863761901855] 2019-02-24 13:01:56,774 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 264 in _join_startup_channels: Found resumable voice channel Pain and Pleasure/music-and-chill
[8.0155863761901855] 2019-02-24 13:01:56,774 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 270 in _join_startup_channels: Found owner in "music-and-chill"
[8.0165851116180420] 2019-02-24 13:01:56,775 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 279 in _join_startup_channels: Attempting to join Pain and Pleasure/music-and-chill
[9.4194648265838623] 2019-02-24 13:01:58,178 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 704 in deserialize_queue: Deserializing queue for 152691091110363146
[9.7062425613403320] 2019-02-24 13:01:58,465 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 423 in get_player: Created player via deserialization for guild 152691091110363146 with 1 entries
[9.7062425613403320] 2019-02-24 13:01:58,465 - INFO - musicbot.bot | In bot.py::MainThread(23512), line 295 in _join_startup_channels: Joined Pain and Pleasure/music-and-chill
[9.7072432041168213] 2019-02-24 13:01:58,466 - DEBUG - musicbot.entry | In entry.py::MainThread(23512), line 56 in get_ready_future: Created future for audio_cache\youtube-7MeKzmoHNTk-Dynamic_PVP_MIX_Playlist_Metalstep_industrial_melodic_drum_and_bass_electro_mix.m4a
[9.7072432041168213] 2019-02-24 13:01:58,466 - FFMPEG - musicbot.player | In player.py::MainThread(23512), line 273 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-7MeKzmoHNTk-Dynamic_PVP_MIX_Playlist_Metalstep_industrial_melodic_drum_and_bass_electro_mix.m4a
[9.7112417221069336] 2019-02-24 13:01:58,470 - DEBUG - musicbot.player | In player.py::MainThread(23512), line 284 in _play: Playing <discord.player.PCMVolumeTransformer object at 0x000001A352948400> using <discord.voice_client.VoiceClient object at 0x000001A35290E5C0>
[9.7122416496276855] 2019-02-24 13:01:58,471 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 458 in on_player_play: Running on_player_play
[9.7122416496276855] 2019-02-24 13:01:58,471 - DEBUG - musicbot.bot | In bot.py::MainThread(23512), line 680 in serialize_queue: Serializing queue for 152691091110363146

**Comment by Tazo83** [comment]
update did fix the voice is back now i dunno what is the issue but its keep happening

**Comment by AleanaA** [comment]
As requested, whenever it happens again, please provide the output of the _update_ script.

**Comment by AutumnClove** [comment]
Hello looked into the  the winerror121, it appears to do with outdated network drivers, please check your network drivers are properly up to date. But as @AleanaA said please provide the output of the update script

**Comment by jayktaylor** [comment]
Closing due to inactivity.
