### ISSUE TITLE
Can’t start bot music 

### ISSUE THREAD

**Issue by Aleksandar58** [Just-Some-Bots/MusicBot#1846]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Aco\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Aco\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1133, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Aco\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1200, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Aco\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'",))

**Comment by AleanaA** [comment]
Run update.bat
