### ISSUE TITLE
Bot won't run after following all steps in guide

### ISSUE THREAD

**Issue by realitytime1** [Just-Some-Bots/MusicBot#1853]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [X] Question

----

### Description of issue
[14.959812164] 2019-03-11 18:12:18,683 - INFO - launcher: Starting sanity checks
[14.959812164] 2019-03-11 18:12:18,683 - INFO - launcher: Checking for Python 3.5+
[14.959812164] 2019-03-11 18:12:18,683 - INFO - launcher: Checking console encoding
[15.957117081] 2019-03-11 18:12:18,684 - INFO - launcher: Setting console encoding to UTF-8
[15.957117081] 2019-03-11 18:12:18,684 - INFO - launcher: Ensuring we're in the right environment
[15.957117081] 2019-03-11 18:12:18,684 - INFO - launcher: Adding local bins/ folder to path
[272.927284241] 2019-03-11 18:12:18,941 - INFO - launcher: Required checks passed.
[274.889230728] 2019-03-11 18:12:18,943 - INFO - launcher: Optional checks passed.
[274.889230728] 2019-03-11 18:12:18,943 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.5629410743713379] 2019-03-11 18:12:19,231 - WARNING - musicbot.config | In config.py::MainThread(4968), line 116 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.5629410743713379] 2019-03-11 18:12:19,231 - INFO - musicbot.config | In config.py::MainThread(4968), line 127 in run_checks: Using i18n: config/i18n/en.json
[0.562941074] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "E:\MusicBot\musicbot\bot.py", line 75, in __init__
    self.config = Config(config_file)
  File "E:\MusicBot\musicbot\config.py", line 84, in __init__
    self.run_checks()
  File "E:\MusicBot\musicbot\config.py", line 188, in run_checks
    self.bound_channels = set(int(item) for item in self.bound_channels)
  File "E:\MusicBot\musicbot\config.py", line 188, in <genexpr>
    self.bound_channels = set(int(item) for item in self.bound_channels)
ValueError: invalid literal for int() with base 10: 'bot'
[0.563938141] launcher-INFO: All done

### Log file

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2954790/musicbot.log)

Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
BindToChannels is Id's not names.

**Comment by realitytime1** [comment]
Ah my bad. Yes, this fixed the issue at hand. Thank you!
