### ISSUE TITLE
How to use the bot in pm2?

### ISSUE THREAD

**Issue by reborndec** [Just-Some-Bots/MusicBot#1858]
I would like to know how to use the bot in pm2, as I tried to run the command with run.py and it is giving error.

```
6|run      |     def pyexec(pycom, *args, pycom2=None):
6|run      |                                   ^
6|run      | SyntaxError: invalid syntax
6|run      |   File "/root/MusicBot/run.py", line 336
6|run      |     def pyexec(pycom, *args, pycom2=None):
6|run      |                                   ^
6|run      | SyntaxError: invalid syntax
6|run      |   File "/root/MusicBot/run.py", line 336
6|run      |     def pyexec(pycom, *args, pycom2=None):
6|run      |                                   ^
6|run      | SyntaxError: invalid syntax
6|run      |   File "/root/MusicBot/run.py", line 336
6|run      |     def pyexec(pycom, *args, pycom2=None):
6|run      |                                   ^
6|run      | SyntaxError: invalid syntax
```

**Comment by AutumnClove** [comment]
You're using a python version Lower than 3, please install a higher version.

Once you have a higher version, `python3 run.py`

**Comment by AleanaA** [comment]
https://aleanaazure.xyz/doku.php?id=musicbot:pm2

**Comment by reborndec** [comment]
but is already installed

```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by reborndec** [comment]
```
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "/root/MusicBot/musicbot/__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "/root/MusicBot/musicbot/utils.py", line 3, in <module>
    import aiohttp
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 12, in <module>
    from typing import (  # noqa
ImportError: cannot import name 'Coroutine'
[INFO] launcher: Attempting to install dependencies...
Requirement already up-to-date: pynacl==1.2.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.2.1)
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] (from -r requirements.txt (line 2))
  Cloning https://github.com/Rapptz/discord.py (to revision rewrite) to /tmp/pip-install-0ezkmyn5/discord.py
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3)) (19.0.3)
Collecting youtube_dl (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a1/19/ce240e0dd775f0861db51c36a293c8b24d5a66a639e7836601ec0640ec18/youtube_dl-2019.3.18-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/68/4d/892728b0c14547224f0ac40884e722a3d00cb54e7a146aea0b3186806c9e/colorlog-4.0.2-py2.py3-none-any.whl
Requirement already up-to-date: cffi in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6)) (1.12.2)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.5/dist-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied, skipping upgrade: aiohttp<3.6.0,>=3.3.0 in /usr/local/lib/python3.5/dist-packages (from discord.py[voice]->-r requirements.txt (line 2)) (3.5.4)
aiohttp requires Python '>=3.5.3' but the running Python is 3.5.2

[CRITICAL] launcher: You may need to use sudo to install dependencies.

[INFO] launcher: All done.

```

**Comment by AutumnClove** [comment]
As the traceback says, you're using 3.5.2, it needs to be ran using 3.5.3 or higher

**Comment by reborndec** [comment]
I have already installed python 3.7 but it still continues in 3.5.2

```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
```
Python 3.7.2 (default, Jan 11 2019, 21:31:15)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

I tried to uninstall version 3.5, but it still continues

**Comment by AutumnClove** [comment]
You can do python3.7 run.py

**Comment by reborndec** [comment]
I managed to make it run on pm2, thank you!
![image](https://user-images.githubusercontent.com/36338360/54869292-36f44000-4d75-11e9-9cb5-6a6e2059c5d5.png)
