### ISSUE TITLE
Bot disconnected from the voice channel

### ISSUE THREAD

**Issue by UnrealPinguin** [Just-Some-Bots/MusicBot#1952]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [X] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Bot just disconnects from the voice channel, and doesn't want to rejoin the channel. Bot only works when I restart it.

This is the error message it gave me;

Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/container/musicbot/player.py:259> exception=ClientException('Not connected to voice.',)>
Traceback (most recent call last):
File "/home/container/musicbot/player.py", line 307, in _play
self.voice_client.play(self._source, after=self._playback_finished)
File "/home/container/.local/lib/python3.6/site-packages/discord/voice_client.py", line 363, in play
raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.

### Steps to reproduce

1. Start the bot
2. After a day or 2 days the bot will leave the channel and gives me this error message

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3690947/musicbot.log)

**Comment by amit177** [comment]
If this is still an issue, please retry on the latest version and let us know.

I'll open this again if there is any update.

**Comment by henryjiang88** [comment]
The same issue is occurring for me. My bot will do this every few hours and would need a complete restart to work. Attached please find the log file. All dependencies have been updated and am on latest version.

On the console, this is the error message:

`Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/pi/Music                                                                                                                                                             Bot/musicbot/player.py:259> exception=ClientException('Not connected to voice.')                                                                                                                                                             >
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/player.py", line 307, in _play
    self.voice_client.play(self._source, after=self._playback_finished)
  File "/usr/local/lib/python3.7/dist-packages/discord/voice_client.py", line 36                                                                                                                                                             3, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
^CTraceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 373, in main
    m.run()
  File "/home/pi/MusicBot/musicbot/bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_compl                                                                                                                                                             ete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
`

Any help appreciated...


[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4434616/musicbot.log)
