### ISSUE TITLE
Can't star the musicbot

### ISSUE THREAD

**Issue by lwcasss** [Just-Some-Bots/MusicBot#1953]
This is the error when I try to start it.
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\LUCAS\Desktop\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\Users\LUCAS\Desktop\MusicBot\musicbot\bot.py", line 28, in <module>
    from . import downloader
  File "C:\Users\LUCAS\Desktop\MusicBot\musicbot\downloader.py", line 5, in <module>
    import youtube_dl
  File "C:\Users\LUCAS\AppData\Roaming\Python\Python37\site-packages\youtube_dl\__init__.py", line 15, in <module>
    from .options import (
  File "C:\Users\LUCAS\AppData\Roaming\Python\Python37\site-packages\youtube_dl\options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "C:\Users\LUCAS\AppData\Roaming\Python\Python37\site-packages\youtube_dl\downloader\__init__.py", line 5, in <module>
    from .hls import HlsFD
  File "C:\Users\LUCAS\AppData\Roaming\Python\Python37\site-packages\youtube_dl\downloader\hls.py", line 12, in <module>
    from .external import FFmpegFD
  File "C:\Users\LUCAS\AppData\Roaming\Python\Python37\site-packages\youtube_dl\downloader\external.py", line 14, in <module>
    from ..postprocessor.ffmpeg import FFmpegPostProcessor, EXT_TO_OUT_FORMATS
ModuleNotFoundError: No module named 'youtube_dl.postprocessor'

**Comment by k1m0ch1** [comment]
do you install the requirements ?

**Comment by lwcasss** [comment]
Which requeriments?

**Comment by k1m0ch1** [comment]
the file requirements.txt, do you follow the guide ?

**Comment by lwcasss** [comment]
Oh these one, well, I followed a video on youtube actually, but these file requeriments just say

pynacl==1.2.1
discord.py[voice]
pip
youtube_dl
colorlog
cffi --only-binary all; sys_platform == 'win32'


What does that mean?

**Comment by notyourbusiness9484** [comment]
You have to install those

**Comment by lwcasss** [comment]
Where do I do that?

**Comment by notyourbusiness9484** [comment]
I rly hope that you are smarter tham you sound.
Just cd to the place where the bot is then just install them there

**Comment by notyourbusiness9484** [comment]
And you get them from internet

**Comment by lwcasss** [comment]
Come on man, I have no experience in programming, I'm just a guy trying to make a music bot for my discord server, just because I don't know programming, doesn't mean I'm dumb. Also I have no idea what cd means, so yeah, you'll have to be a little more specific.

**Comment by notyourbusiness9484** [comment]
I know Iknow sorry but maybe just get some music bot that you don't have to host by your self

**Comment by lwcasss** [comment]
Aww, but I wanted to name and give a picture to my bot, that's really the only reason I'm trying to make a bot instead of getting one already done.

**Comment by notyourbusiness9484** [comment]
I can help you in couple of hours just tell me windows or linux  and your discord

**Comment by lwcasss** [comment]
I use windows 10 and my discord is lwcasss#0505

**Comment by k1m0ch1** [comment]
@lwcasss try to follow this https://just-some-bots.github.io/MusicBot/installing/windows/
this thread better to be closed

**Comment by MattBSG** [comment]
Our installation instructions are as follows above ^. We don't support using anything but our intended guide. If you have further issues please visit our [discord server](https://discord.gg/bots) or reopen this issue.
