### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by RobWaterhouse95** [Just-Some-Bots/MusicBot#1960]
- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260819)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I get the following response when requesting any song.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rob/musicBot/musicbot/bot.py", line 1400, in cmd_play
    info = await self.downloader.extract_info(player.playlist.loop, song_url, download=False, process=False)
  File "/home/rob/musicBot/musicbot/downloader.py", line 84, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rob/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/rob/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/home/rob/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many `Requests'>
```

### Steps to reproduce

1. Start the bot
2. Ensure the queue is cleared
3. Request a song with !play <yt link>
4. Observe error

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3726400/musicbot.log)

**Comment by srhinos** [comment]
see https://github.com/Just-Some-Bots/MusicBot/issues/1947
