### ISSUE TITLE
Bot doesn't work anymore, has been updated and all

### ISSUE THREAD

**Issue by Crafteri** [Just-Some-Bots/MusicBot#1981]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
I bot comes online, responds to help, but not play or search commands. I don't know what's causing the issue, but it seems like the discord.py is not working

### Steps to reproduce

1. I dunno, I start the bot and it doesn't work anymore

----

### Log file

  File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/pi/MusicBot/logs/discord.l                                                                                                                                                             og'

[INFO] launcher: All done.
pi@raspberrypi:~/MusicBot $ python --version
Python 2.7.13
pi@raspberrypi:~/MusicBot $ python3 --version
Python 3.5.3
pi@raspberrypi:~/MusicBot $ cd
pi@raspberrypi:~ $ cd MusicBot
pi@raspberrypi:~/MusicBot $ ls
bin  bootstrap.py  config  data  dockerentry.py  Dockerfile  LICENSE  logs  musicbot  README.md  requirements.txt  requirements.txt.save  run.bat  run.py  run.sh  update.bat  update.py  update.sh
pi@raspberrypi:~/MusicBot $ logs
-bash: logs: command not found
pi@raspberrypi:~/MusicBot $ cd logs
pi@raspberrypi:~/MusicBot/logs $ ls
discord.log  musicbot.log  musicbot.log.last
pi@raspberrypi:~/MusicBot/logs $ sudo nano musicbot.log.last
  GNU nano 2.7.4                                                                                              File: musicbot.log.last

  File "/home/pi/MusicBot/musicbot/bot.py", line 419, in get_player
    async with self.aiolocks[_func_() + ':' + str(guild.id)]:
  File "/usr/lib/python3.5/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/lib/python3.5/asyncio/locks.py", line 176, in acquire
    yield from fut
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError
[124.0164918899536133] 2019-11-05 17:48:19,015 - ERROR - musicbot.bot | In bot.py::MainThread(1996236352), line 2858 in on_message: Exception in on_message
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/bot.py", line 2813, in on_message
    response = await handler(**handler_kwargs)
  File "/home/pi/MusicBot/musicbot/bot.py", line 1927, in cmd_summon
    player = await self.get_player(author.voice.channel, create=True, deserialize=self.config.persistent_queue)
  File "/home/pi/MusicBot/musicbot/bot.py", line 435, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/pi/MusicBot/musicbot/bot.py", line 386, in get_voice_client
    return await channel.connect(timeout=60, reconnect=True)
  File "/usr/local/lib/python3.5/dist-packages/discord/abc.py", line 1033, in connect
    await voice.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 224, in connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 735, in poll_event
    await self.received_message(json.loads(msg))
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 681, in received_message
    await self.initial_connection(data)
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 703, in initial_connection
    recv = await self.loop.sock_recv(state.socket, 70)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError
[124.040657997] launcher-INFO: All done.

**Comment by NeckDu** [comment]
Same issue here dunno what happend.

**Comment by RealWolvesUnited** [comment]
discord updated docs i assume

**Comment by SternRowboat** [comment]
Also having the same issue on a rasberry Pi

**Comment by G3VV** [comment]
I had this problem, I dunno how i fixed it just i fixed it.

**Comment by SternRowboat** [comment]
restarted the pi, solved my issue.
