### ISSUE TITLE
SSL CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jochenkurzschluss** [Just-Some-Bots/MusicBot#1988]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [# ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [# ] I have updated my dependencies to the latest version using the appropriate `update` script

My python3.6 --version > Python 3.6.9

Which version are you using?

- [# ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [# ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The bot don´t work please See the logfile.

`[20.254135132] 2019-11-16 01:29:38,263 - INFO - launcher: Starting sanity checks
[20.432233810] 2019-11-16 01:29:38,264 - INFO - launcher: Checking for Python 3.5+
[20.508766174] 2019-11-16 01:29:38,264 - INFO - launcher: Checking console encoding
[20.573139191] 2019-11-16 01:29:38,264 - INFO - launcher: Ensuring we're in the right environment
[266.124248505] 2019-11-16 01:29:38,509 - INFO - launcher: Required checks passed.
[266.414880753] 2019-11-16 01:29:38,510 - INFO - launcher: Optional checks passed.
[266.576528549] 2019-11-16 01:29:38,510 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.5483522415161133] 2019-11-16 01:29:38,791 - WARNING - musicbot.config | In config.py::MainThread(140531888002816), line 121 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.5485181808471680] 2019-11-16 01:29:38,792 - INFO - musicbot.config | In config.py::MainThread(140531888002816), line 132 in run_checks: Using i18n: config/i18n/en.json
[0.5494840145111084] 2019-11-16 01:29:38,793 - DEBUG - musicbot.bot | In bot.py::MainThread(140531888002816), line 225 in _setup_logging: Set logging level to INFO
[0.5507335662841797] 2019-11-16 01:29:38,794 - DEBUG - musicbot.json | In json.py::MainThread(140531888002816), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.5553040504455566] 2019-11-16 01:29:38,798 - INFO - musicbot.bot | In bot.py::MainThread(140531888002816), line 90 in __init__: Starting MusicBot release-260819-3-gcb7ccd8
[0.5554349422454834] 2019-11-16 01:29:38,799 - INFO - musicbot.bot | In bot.py::MainThread(140531888002816), line 96 in __init__: Loaded autoplaylist with 2531 entries
[0.591702223] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 820, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 846, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "/home/musikbot/MusicBot/musicbot/bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 929, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host discordapp.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)]
[0.594467163] launcher-INFO: All done.
`

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by jochenkurzschluss** [comment]
My server is Ubuntu 16.04.6 LTS‬ from Strato i think this is usefull for more information.

**Comment by amit177** [comment]
I know it's a bit delayed but, if you're still having this issue, could you try reinstalling the SSL module for python?

I'll reopen if it's still an issue.
