### ISSUE TITLE
Errors After Updating, Bot went offline 

### ISSUE THREAD

**Issue by AviatorVence** [Just-Some-Bots/MusicBot#1997]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Updated the bot after it stopped responding to commands only for it to go offline

### Steps to reproduce

1.  Updated Bot to Latest version

----

### Log file
[46.874284744] 2019-12-05 01:05:26,159 - INFO - launcher: Starting sanity checks
[46.874284744] 2019-12-05 01:05:26,159 - INFO - launcher: Checking for Python 3.5+
[46.874284744] 2019-12-05 01:05:26,159 - INFO - launcher: Checking console encoding
[46.874284744] 2019-12-05 01:05:26,159 - INFO - launcher: Setting console encoding to UTF-8
[46.874284744] 2019-12-05 01:05:26,159 - INFO - launcher: Ensuring we're in the right environment
[46.874284744] 2019-12-05 01:05:26,159 - INFO - launcher: Adding local bins/ folder to path
[971.318960190] 2019-12-05 01:05:27,084 - INFO - launcher: Required checks passed.
[971.318960190] 2019-12-05 01:05:27,084 - INFO - launcher: Optional checks passed.
[971.318960190] 2019-12-05 01:05:27,084 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1393.261909485] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\bot.py", line 28, in <module>
    from . import downloader
  File "C:\Users\Administrator\Desktop\MusicBot\musicbot\downloader.py", line 5, in <module>
    import youtube_dl
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\youtube_dl\__init__.py", line 15, in <module>
    from .options import (
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\youtube_dl\options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\youtube_dl\downloader\__init__.py", line 5, in <module>
    from .hls import HlsFD
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\youtube_dl\downloader\hls.py", line 12, in <module>
    from .external import FFmpegFD
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\youtube_dl\downloader\external.py", line 14, in <module>
    from ..postprocessor.ffmpeg import FFmpegPostProcessor, EXT_TO_OUT_FORMATS
ModuleNotFoundError: No module named 'youtube_dl.postprocessor'
[1487.017393112] launcher-INFO: Attempting to install dependencies...
[4808.297157288] launcher-INFO: Ok lets hope it worked
[4808.297157288] launcher-INFO: All done.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3924630/musicbot.log)

**Comment by amit177** [comment]
If this is still an issue (I know, the reply is a bit delayed...)
Go to `%appdata%` --> `Python` --> `Python37` --> `site-packages`.
Delete the folder `youtube_dl` and run `update.bat`, that should fix the issue.

**Comment by Stefan8888** [comment]
Nope, that didnt work for me.

**Comment by amit177** [comment]
Please attach the log files

**Comment by Stefan8888** [comment]
C:\Users\Domov\Desktop\testos\MusicBot>python run.py
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 368, in main
    m = MusicBot()
  File "C:\Users\Domov\Desktop\testos\MusicBot\musicbot\bot.py", line 74, in __i
nit__
    self.config = Config(config_file)
  File "C:\Users\Domov\Desktop\testos\MusicBot\musicbot\config.py", line 89, in
__init__
    self.run_checks()
  File "C:\Users\Domov\Desktop\testos\MusicBot\musicbot\config.py", line 207, in
 run_checks
    self.bound_channels = set(int(item) for item in self.bound_channels)
  File "C:\Users\Domov\Desktop\testos\MusicBot\musicbot\config.py", line 207, in
 <genexpr>
    self.bound_channels = set(int(item) for item in self.bound_channels)
ValueError: invalid literal for int() with base 10: 'test'

[INFO] launcher: All done.

C:\Users\Domov\Desktop\testos\MusicBot>

**Comment by Stefan8888** [comment]
Maybe it is something different.

**Comment by Stefan8888** [comment]
I edited log, sorry. But config files are right I think.

**Comment by amit177** [comment]
In the bound channels config option you wrote 'test', however it needs to be IDs not names.
see here: https://just-some-bots.github.io/MusicBot/using/faq/

**Comment by Stefan8888** [comment]
Yes, sorry guy, thx.
