### ISSUE TITLE
Soundcloud: ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)

### ISSUE THREAD

**Issue by Chipsnet** [Just-Some-Bots/MusicBot#2004]
When I performed an command `/p [Soundcloud URL]` on the Bot, I got the following error

```
Traceback (most recent call last):
  File "/home/minato86/data/MusicBot/MusicBot/musicbot/bot.py", line 2813, in on_message
    response = await handler(**handler_kwargs)
  File "/home/minato86/data/MusicBot/MusicBot/musicbot/bot.py", line 1427, in cmd_play
    raise exceptions.CommandError(e, expire_in=30)
musicbot.exceptions.CommandError: ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)
```

how i do fix?

**Comment by TheerapakG** [comment]
https://github.com/ytdl-org/youtube-dl/issues/23236
Wait for the next ytdl release (I don't know when) and run the update script, should solve the issue.
