### ISSUE TITLE
Python 3.8.1 update.bat error with enum

### ISSUE THREAD

**Issue by JulianS-Uni** [Just-Some-Bots/MusicBot#2007]
Please tick all applicable boxes.

- [x] I am using Python 3.8.1 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I have the Bot running under Python 3.7 but I also tried to use it with with Pyth 3.8.1 which gives me an error when executing update.bat (on Win 10)

### Steps to reproduce

1. Follow [the install guide](https://just-some-bots.github.io/MusicBot/installing/windows/) and execute `update.bat`

----

### Log file
Not adding a Log file because thats pre operational i guess.
But here is the error:

```
Starting...
Passed Git checks...
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Collecting pynacl==1.2.1
  Using cached https://files.pythonhosted.org/packages/08/19/cf56e60efd122fa6d2228118a9b345455b13ffe16a14be81d025b03b261f/PyNaCl-1.2.1.tar.gz
Collecting discord.py[voice]==1.2.5
  Using cached https://files.pythonhosted.org/packages/7c/93/30fa8b5307328e5f37a37d13afb33677ef68e4cb4e98646427d6b400958c/discord.py-1.2.5-py3-none-any.whl
Requirement already up-to-date: pip in c:\users\julian\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 3)) (19.3.1)
Collecting youtube_dl
  Using cached https://files.pythonhosted.org/packages/ef/f8/3424069c6d1e285fda98a83c48470578d2df4047e6e77e1b16fc28cf95d3/youtube_dl-2020.1.15-py2.py3-none-any.whl
Collecting colorlog
  Using cached https://files.pythonhosted.org/packages/00/0d/22c73c2eccb21dd3498df7d22c0b1d4a30f5a5fb3feb64e1ce06bc247747/colorlog-4.1.0-py2.py3-none-any.whl
Collecting cffi
  Using cached https://files.pythonhosted.org/packages/4f/c9/135197be2a44f8dbe59373a55018843aa586e14af23e813897f40b6689f6/cffi-1.13.2-cp38-cp38-win_amd64.whl
Requirement already satisfied, skipping upgrade: six in c:\users\julian\appdata\roaming\python\python38\site-packages (from pynacl==1.2.1->-r requirements.txt (line 1)) (1.13.0)
Collecting websockets<7.0,>=6.0
  Using cached https://files.pythonhosted.org/packages/4e/2a/56e60bb4c3696bc736998cc13c3fa1a36210609d7e1a3f2519857b420245/websockets-6.0.tar.gz
Collecting aiohttp<3.6.0,>=3.3.0
  Using cached https://files.pythonhosted.org/packages/0f/58/c8b83f999da3b13e66249ea32f325be923791c0c10aee6cf16002a3effc1/aiohttp-3.5.4.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Julian\AppData\Local\Programs\Python\Python38\python.exe' 'C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Julian\AppData\Local\Temp\pip-build-env-u4yqmj44\overlay' --no-warn-script-location --no-binary :none: --only-binary 'all;' -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\__main__.py", line 16, in <module>
      from pip._internal.main import main as _main  # isort:skip # noqa
    File "C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\main.py", line 8, in <module>
      import locale
    File "C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\locale.py", line 16, in <module>
      import re
    File "C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Julian\AppData\Local\Programs\Python\Python38\python.exe' 'C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Julian\AppData\Local\Temp\pip-build-env-u4yqmj44\overlay' --no-warn-script-location --no-binary :none: --only-binary 'all;' -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install --no-warn-script-location --user -U -r requirements.txt'.format(sys.executable), shell=True)
  File "C:\Users\Julian\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\Julian\AppData\Local\Programs\Python\Python38\python.exe" -m pip install --no-warn-script-location --user -U -r requirements.txt' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\" -m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"C:\Users\Julian\AppData\Local\Programs\Python\Python38\python.exe" -m pip install -U -r requirements.txt' yourself.
```

**Comment by amit177** [comment]
Python 3.8 is not supported in the master branch yet.
