### ISSUE TITLE
Loading update.bat and error

### ISSUE THREAD

**Issue by Kaiser5507** [Just-Some-Bots/MusicBot#2029]
while i was loading the update.bat with administrator,this error appeared.How can i fix this? i tried to featured it out in a week but still can't.I will be thankful if u can help me QWQ

Starting...
Passed Git checks...
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Collecting pynacl==1.2.1
  Using cached PyNaCl-1.2.1.tar.gz (3.3 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\俊逸\AppData\Local\Programs\Python\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\俊逸\\AppData\\Local\\Temp\\pip-install-5gqqchq5\\pynacl\\setup.py'"'"'; __file__='"'"'C:\\Users\\俊逸\\AppData\\Local\\Temp\\pip-install-5gqqchq5\\pynacl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\俊逸\AppData\Local\Temp\pip-install-5gqqchq5\pynacl\pip-egg-info'
         cwd: C:\Users\俊逸\AppData\Local\Temp\pip-install-5gqqchq5\pynacl\
    Complete output (111 lines):
    Traceback (most recent call last):
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\\u4fca\u9038\AppData\Local\Temp\easy_install-gg518doa\cffi-1.14.0\setup.py", line 127, in <module>

      File "C:\Users\\u4fca\u9038\AppData\Local\Temp\easy_install-gg518doa\cffi-1.14.0\setup.py", line 105, in uses_msvc

      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\\u4fca\u9038\AppData\Local\Temp\pip-install-5gqqchq5\pynacl\setup.py", line 205, in <module>
        setup(
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\\u4fca\u9038\AppData\Local\Temp\easy_install-gg518doa\cffi-1.14.0\setup.py", line 127, in <module>

      File "C:\Users\\u4fca\u9038\AppData\Local\Temp\easy_install-gg518doa\cffi-1.14.0\setup.py", line 105, in uses_msvc

      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "C:\Users\\u4fca\u9038\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install --no-warn-script-location --user -U -r requirements.txt'.format(sys.executable), shell=True)
  File "C:\Users\俊逸\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\俊逸\AppData\Local\Programs\Python\Python38-32\python.exe" -m pip install --no-warn-script-location --user -U -r requirements.txt' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\" -m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"C:\Users\俊逸\AppData\Local\Programs\Python\Python38-32\python.exe" -m pip install -U -r requirements.txt' yourself.

**Comment by Alestroyer** [comment]
If I remember right my friend had this same issue, it ended up being he had installed the latest version of python as opposed to 3.7.0 as I believe the guide says

**Comment by AleanaA** [comment]
See the pinned issue, MusicBot does not currently support Python 3.8
