### ISSUE TITLE
[Linux/Xubuntu] ffmpeg/avconv not found.

### ISSUE THREAD

**Issue by Martmists-GH** [Just-Some-Bots/MusicBot#203]
As a (partially) linux user, I'd prefer to have the bot run on linux as well.
It seems to work, but when I try to have it play music it says:

```
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/smits/Martijn/MusicBot-1.9.5rc7/musicbot/player.py:154> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/smits/Martijn/MusicBot-1.9.5rc7/musicbot/player.py", line 184, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 433, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable
```

Is there any way to fix this? I've installed ffmpeg (or at least I think I did) and it still won't work.

**Comment by hendrikbl** [comment]
Same here on my Raspberry Pi with Raspbian Jessie. Did you find a way to fix this?

**Comment by p0thi** [comment]
Same error here. No idea what the problem is? :(

**Comment by arunesh90** [comment]
make a seperate issue, @dp-t-rex

**Comment by imayhaveborkedit** [comment]
This issue is as stated.  You simply need to install ffmpeg correctly.
