### ISSUE TITLE
Trouble installing PyNaCl on Windows 10, Python 3.8.2

### ISSUE THREAD

**Issue by SamM** [Just-Some-Bots/MusicBot#2040]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
I am trying to install the dependencies but the process gets stuck when trying to install PyNaCl 1.2.1

I get the following error when I run `"C:\Users\user\AppData\Local\Programs\Python\Python38\python.exe" -m pip install -U -r requirements.txt` :
```
...
Installing collected packages: pynacl, websockets, async-timeout, idna, multidict, yarl, chardet, attrs, aiohttp, discord.py, youtube-dl, colorama, colorlog
  Attempting uninstall: pynacl
    Found existing installation: pynacl 1.3.0
    Uninstalling pynacl-1.3.0:
      Successfully uninstalled pynacl-1.3.0
    Running setup.py install for pynacl ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-qyicxdg_\\pynacl\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-qyicxdg_\\pynacl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-izqczzrk\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\user\AppData\Local\Programs\Python\Python38\Include\pynacl'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-qyicxdg_\pynacl\
    Complete output (64 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\nacl
    copying src\nacl\encoding.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\exceptions.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\hash.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\hashlib.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\public.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\secret.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\signing.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\utils.py -> build\lib.win-amd64-3.8\nacl
    copying src\nacl\__init__.py -> build\lib.win-amd64-3.8\nacl
    creating build\lib.win-amd64-3.8\nacl\pwhash
    copying src\nacl\pwhash\argon2i.py -> build\lib.win-amd64-3.8\nacl\pwhash
    copying src\nacl\pwhash\argon2id.py -> build\lib.win-amd64-3.8\nacl\pwhash
    copying src\nacl\pwhash\scrypt.py -> build\lib.win-amd64-3.8\nacl\pwhash
    copying src\nacl\pwhash\_argon2.py -> build\lib.win-amd64-3.8\nacl\pwhash
    copying src\nacl\pwhash\__init__.py -> build\lib.win-amd64-3.8\nacl\pwhash
    creating build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_box.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_generichash.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_hash.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_pwhash.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_scalarmult.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_secretbox.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_shorthash.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\crypto_sign.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\randombytes.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\sodium_core.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\utils.py -> build\lib.win-amd64-3.8\nacl\bindings
    copying src\nacl\bindings\__init__.py -> build\lib.win-amd64-3.8\nacl\bindings
    running build_clib
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-qyicxdg_\pynacl\setup.py", line 205, in <module>
        setup(
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\user\AppData\Local\Temp\pip-install-qyicxdg_\pynacl\setup.py", line 159, in run
        raise Exception("ERROR: The 'make' utility is missing from PATH")
    Exception: ERROR: The 'make' utility is missing from PATH
    ----------------------------------------
  Rolling back uninstall of pynacl
  Moving to c:\users\user\appdata\local\programs\python\python38\lib\site-packages\nacl\
   from C:\Users\user\AppData\Local\Programs\Python\Python38\Lib\site-packages\~acl
  Moving to c:\users\user\appdata\local\programs\python\python38\lib\site-packages\pynacl-1.3.0.dist-info\
   from C:\Users\user\AppData\Local\Programs\Python\Python38\Lib\site-packages\~ynacl-1.3.0.dist-info
ERROR: Command errored out with exit status 1: 'C:\Users\user\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-qyicxdg_\\pynacl\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-qyicxdg_\\pynacl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\user\AppData\Local\Temp\pip-record-izqczzrk\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\user\AppData\Local\Programs\Python\Python38\Include\pynacl' Check the logs for full command output.
```

### Steps to reproduce

1. My version of windows is Windows 10 : Version 1903 (OS Build 18352,720)
2. My version of Python is `Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32`
3. Run `./update.sh`
4. Get error so run `"C:\Users\user\AppData\Local\Programs\Python\Python38\python.exe" -m pip install -U -r requirements.txt`  as suggested

**Comment by SamM** [comment]
I saw the pinned issue saying that it is not supported with Python 3.8
