### ISSUE TITLE
Hey! I need help with running update.bat.

### ISSUE THREAD

**Issue by infofbnr** [Just-Some-Bots/MusicBot#2056]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version
- [x] The latest `clone` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
I can't run update.bat. I have an error which says "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output."
I wanted to know how to fix that.

### Steps to reproduce

1. Fix update.bat

----

### Log file
[63.830852509] 2020-04-20 08:52:05,327 - INFO - launcher: Starting sanity checks
[63.830852509] 2020-04-20 08:52:05,327 - INFO - launcher: Checking for Python 3.5+
[64.827919006] 2020-04-20 08:52:05,328 - INFO - launcher: Checking console encoding
[64.827919006] 2020-04-20 08:52:05,328 - INFO - launcher: Setting console encoding to UTF-8
[65.831422806] 2020-04-20 08:52:05,329 - INFO - launcher: Ensuring we're in the right environment
[70.811033249] 2020-04-20 08:52:05,334 - INFO - launcher: Adding local bins/ folder to path
[73.803424835] 2020-04-20 08:52:05,337 - INFO - launcher: Required checks passed.
[73.803424835] 2020-04-20 08:52:05,337 - INFO - launcher: Optional checks passed.
[74.800968170] 2020-04-20 08:52:05,338 - INFO - launcher: Moving old musicbot log

**Comment by AleanaA** [comment]
Need more information, such as a full log of the update scripts output.

**Comment by infofbnr** [comment]
Starting...
Passed Git checks...
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Collecting pynacl==1.2.1
  Using cached PyNaCl-1.2.1.tar.gz (3.3 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HAGOPIAN\\AppData\\Local\\Temp\\pip-install-pw8dn29t\\pynacl\\setup.py'"'"'; __file__='"'"'C:\\Users\\HAGOPIAN\\AppData\\Local\\Temp\\pip-install-pw8dn29t\\pynacl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HAGOPIAN\AppData\Local\Temp\pip-install-pw8dn29t\pynacl\pip-egg-info'
         cwd: C:\Users\HAGOPIAN\AppData\Local\Temp\pip-install-pw8dn29t\pynacl\
    Complete output (39 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HAGOPIAN\AppData\Local\Temp\pip-install-pw8dn29t\pynacl\setup.py", line 205, in <module>
        setup(
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        dist = self.package_index.fetch_distribution(
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\package_index.py", line 654, in fetch_distribution
        self.find_packages(requirement)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\package_index.py", line 487, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name + '/')
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\package_index.py", line 827, in scan_url
        self.process_url(url, True)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\package_index.py", line 357, in process_url
        page = f.read()
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 467, in read
        s = self._safe_read(self.length)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 608, in _safe_read
        data = self.fp.read(amt)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
        return self._sock.recv_into(b)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1241, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
        return self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install --no-warn-script-location --user -U -r requirements.txt'.format(sys.executable), shell=True)
  File "C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\python.exe" -m pip install --no-warn-script-location --user -U -r requirements.txt' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\" -m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"C:\Users\HAGOPIAN\AppData\Local\Programs\Python\Python38-32\python.exe" -m pip install -U -r requirements.txt' yourself.

**Comment by AleanaA** [comment]
See the pinned issue regarding Python 3.8
