### ISSUE TITLE
Bot stops playing music after some time / tracks from autoplaylist

### ISSUE THREAD

**Issue by daranto** [Just-Some-Bots/MusicBot#2065]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
yes
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
yes. I tried on debian and docker
- [x] I have updated my dependencies to the latest version using the appropriate `update` script
Which version are you using?

- [x] The latest `master` version (release-260419)
- [x] The latest `review` version

I have tried both versions.

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

After some time the bot stops playing music. In the logfiles are error messages.

### Steps to reproduce

1. Put youtube links into the autoplaylist and wait.

----

### Log file

```
This is the error in the log:

ConnectionRefusedError: [Errno 111] Connection refused




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info


    success = dl(filename, info_dict)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl


    return fd.download(name, info)


  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download


    return self.real_download(filename, info_dict)


  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/dash.py", line 48, in real_download


    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)


  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/fragment.py", line 100, in _download_fragment


    success = ctx['dl'].download(fragment_filename, {


  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/common.py", line 366, in download


    return self.real_download(filename, info_dict)


  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 341, in real_download


    establish_connection()


  File "/usr/lib/python3.8/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection


    ctx.data = self.ydl.urlopen(request)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen


    return self._opener.open(req, timeout=self._socket_timeout)


  File "/usr/lib/python3.8/urllib/request.py", line 531, in open


    response = meth(req, response)


  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response


    response = self.parent.error(


  File "/usr/lib/python3.8/urllib/request.py", line 563, in error


    result = self._call_chain(*args)


  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain


    result = func(*args)


  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302


    return self.parent.open(new, timeout=req.timeout)


  File "/usr/lib/python3.8/urllib/request.py", line 525, in open


    response = self._open(req, data)


  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open


    result = self._call_chain(self.handle_open, protocol, protocol +


  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain


    result = func(*args)


  File "/usr/lib/python3.8/site-packages/youtube_dl/utils.py", line 2726, in https_open


    return self.do_open(functools.partial(


  File "/usr/lib/python3.8/urllib/request.py", line 1322, in do_open


    raise URLError(err)


urllib.error.URLError: <urlopen error [Errno 111] Connection refused>




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


  File "/usr/src/musicbot/musicbot/entry.py", line 371, in _really_download


    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)


  File "/usr/src/musicbot/musicbot/downloader.py", line 84, in extract_info


    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))


  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run


    result = self.fn(*self.args, **self.kwargs)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info


    return self.process_ie_result(ie_result, download, extra_info)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 867, in process_ie_result


    return self.extract_info(ie_result['url'],


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info


    return self.process_ie_result(ie_result, download, extra_info)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result


    return self.process_video_result(ie_result, download=download)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result


    self.process_info(new_info)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1928, in process_info


    self.report_error('unable to download video data: %s' % error_to_compat_str(err))


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error


    self.trouble(error_message, tb)


  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble


    raise DownloadError(message, exc_info)


youtube_dl.utils.DownloadError: ERROR: unable to download video data: <urlopen error [Errno 111] Connection refused>




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


  File "/usr/src/musicbot/musicbot/player.py", line 272, in _play


    entry = await self.playlist.get_next_entry()


  File "/usr/src/musicbot/musicbot/playlist.py", line 334, in get_next_entry


    return await entry.get_ready_future()


  File "/usr/src/musicbot/musicbot/entry.py", line 228, in _download


    await self._really_download()


  File "/usr/src/musicbot/musicbot/entry.py", line 374, in _really_download


    raise ExtractionError(e)


musicbot.exceptions.ExtractionError: ERROR: unable to download video data: <urlopen error [Errno 111] Connection refused>


```

**Comment by AleanaA** [comment]
Error provided is an issue with your connection to the video's host.
It's recommended that you contact your server's host, or ISP, regarding this if you're also unable to connect with things other than MusicBot.
