### ISSUE TITLE
Unknown Error when bot joins a voice channel

### ISSUE THREAD

**Issue by aGrilledBanana** [Just-Some-Bots/MusicBot#2067]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot is having trouble connecting to the voice channel I am in. It would join the channel and after a few seconds leave and come back. The error message I got is below:

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4553119/musicbot.log)
[ERROR:bot] Unknown error attempting to connect to voice
Traceback (most recent call last):
  File "C:\Users\micro\MusicBot\musicbot\bot.py", line 431, in get_voice_client
    vc = await self.join_voice_channel(channel)
  File "C:\Users\micro\MusicBot\musicbot\bot.py", line 395, in join_voice_channel
    await voice.connect()
  File "C:\Users\micro\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\voice_client.py", line 258, in connect
    self.ws = yield from DiscordVoiceWebSocket.from_client(self)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 568, in from_client
    timeout=60, loop=client.loop)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python36\lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "C:\Users\micro\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 65, in _ensure_coroutine_connect
    ws = yield from websockets.connect(gateway, loop=loop, klass=klass)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\py35\client.py", line 19, in __await__
    return (yield from self.client)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\client.py", line 215, in connect
    extra_headers=extra_headers)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\client.py", line 125, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 403
WARNING: Failed to connect, retrying (2/5)
WARNING: Failed to connect, retrying (3/5)
WARNING: Failed to connect, retrying (4/5)
WARNING: Failed to connect, retrying (5/5)
[CRITICAL:bot] Voice client is unable to connect, restarting...

Any help would be appreciated. Thank you.

### Steps to reproduce

1. Running "runbot.bat"
2. Summoning the bot to the selected voice channel

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AutumnClove** [comment]
Could you do `python -m pip install -U discord.py[voice]`and report back?
