### ISSUE TITLE
Dockerfile build dependency help please!

### ISSUE THREAD

**Issue by adamja** [Just-Some-Bots/MusicBot#2087]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
I am trying to run the music bot using docker. I've managed to get the dependencies to the point that they will build the image and the bot will connect to the server and receive commands. However, I am now stuck when it comes to getting the bot to play a song...

### Steps to reproduce

1. I have cloned the project repo from github

2. I updated the "requirements.txt" file to get some latest versions because it was failing to build some of the existing ones:
```
pynacl==1.4.0
discord.py[voice]
pip
youtube_dl
colorlog
cffi --only-binary all; sys_platform == 'win32'
```

3. Then I have edited the Dockerfile to the following because the pip command wasn't working, so I changed the base image to "python:3.7.7-alpine":
```
FROM python:3.7.7-alpine

# Add project source
WORKDIR /usr/src/musicbot
COPY . ./

# Echo
# RUN python3 -V
# RUN python3 adam_script.py

# Install dependencies
RUN apk update \
&& apk add --no-cache \
  ca-certificates \
  ffmpeg \
  opus \
  libsodium-dev \
\
# Install build dependencies
&& apk add --no-cache --virtual .build-deps \
  gcc \
  git \
  libffi-dev \
  make \
  musl-dev \
  opus \
\
# Install pip dependencies
&& pip3 install --no-cache-dir -r requirements.txt \
&& pip3 install --upgrade --force-reinstall --version websockets==4.0.1 \
\
# Clean up build dependencies
&& apk del .build-deps

# Create volume for mapping the config
VOLUME /usr/src/musicbot/config

ENV APP_ENV=docker

ENTRYPOINT ["python3", "dockerentry.py"]
```

4. Then I built the image:
```
docker build -t musicbot:latest . 
```

5. I run the container with a link to my configuration for the bot and the -update flag to get the latest dependency versions:
```
docker run -v /my_file_location/musicbot/config:/usr/src/musicbot/config -it musicbot -update
```

6. I get the following error in the console for the running app:
```
x/AJ#1041: !play in the end
Task exception was never retrieved
future: <Task finished coro=<MusicBot.on_player_entry_added() done, defined at /usr/src/musicbot/musicbot/bot.py:623> exception=AttributeError("'NoneType' object has no attribute '_player'")>
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/bot.py", line 626, in on_player_entry_added
    await self.serialize_queue(player.voice_client.channel.guild)
  File "/usr/src/musicbot/musicbot/bot.py", line 712, in serialize_queue
    f.write(player.serialize(sort_keys=True))
  File "/usr/src/musicbot/musicbot/constructs.py", line 116, in serialize
    return json.dumps(self, cls=cls, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/src/musicbot/musicbot/constructs.py", line 67, in default
    return o.__json__()
  File "/usr/src/musicbot/musicbot/player.py", line 332, in __json__
    'progress_frames': self._current_player._player.loops if self.progress is not None else None
AttributeError: 'NoneType' object has no attribute '_player'
Download started: https://www.youtube.com/watch?v=eVTXPUF4Oz4
Download complete: https://www.youtube.com/watch?v=eVTXPUF4Oz4
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /usr/src/musicbot/musicbot/player.py:259> exception=OpusNotLoaded()>
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/player.py", line 307, in _play
    self.voice_client.play(self._source, after=self._playback_finished)
  File "/usr/local/lib/python3.7/site-packages/discord/voice_client.py", line 385, in play
    self.encoder = opus.Encoder()
  File "/usr/local/lib/python3.7/site-packages/discord/opus.py", line 231, in __init__
    raise OpusNotLoaded()
discord.opus.OpusNotLoaded

```
----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4777797/musicbot.log)

**Comment by kairat1115** [comment]
Hi! My Dockerfile
```
FROM python:3.5-buster

RUN apt update && apt install -y build-essential unzip software-properties-common \
    git ffmpeg libopus-dev libffi-dev libsodium-dev python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /MusicBot
COPY MusicBot/ ./

RUN python3 -m pip install -U pip \
 && python3 -m pip install -U -r requirements.txt

CMD [ "./run.sh" ]
```

And start with loading config
```
docker run --rm --name discord_music_bot \
        -v `pwd`/config/options.ini:/MusicBot/config/options.ini \
        -v `pwd`/config/permissions.ini:/MusicBot/config/permissions.ini \
        kkairat/musicbot
```

**Comment by adamja** [comment]
Thanks @kairat1115 I finally got it working. You gave me a different approach to get in running, greatly appreciated!

I did have a bit of trouble with it not running at first, but it ended up being the line endings from Windows stopping it from running I think:
https://forums.docker.com/t/standard-init-linux-go-175-exec-user-process-caused-no-such-file/20025

My final commands are below for anyone that is interested...

Dockerfile
```
FROM python:3.5-buster

# Update system repositories
RUN apt-get update -y \
&& apt-get upgrade -y

# Install dependencies
RUN apt-get install git libopus-dev libffi-dev libsodium-dev ffmpeg -y \
&& apt-get install build-essential libncursesw5-dev libgdbm-dev libc6-dev zlib1g-dev libsqlite3-dev tk-dev libssl-dev openssl -y

# Add project source
WORKDIR /musicbot
COPY . ./

VOLUME [ "/musicbot/config/" ]

# Install dependencies
RUN python3 -m pip install --upgrade pip \
&& python3 -m pip install --upgrade -r requirements.txt

ENV APP_ENV=docker

ENTRYPOINT [ "python3", "dockerentry.py" ]
```

Build command
```
sudo docker build -t adamja/musicbot:latest .
```

Run test command
```
sudo docker run \
  --rm \
  --name=musicbot \
  -v /volume2/Docker_Volumes/musicbot/config:/musicbot/config \
  --log-opt max-size=10m \
  adamja/musicbot:latest
```

Run deploy command
```
sudo docker run \
  -d \
  --restart=unless-stopped \
  --name=musicbot \
  -v /volume2/Docker_Volumes/musicbot/config:/musicbot/config \
  --log-opt max-size=10m \
  adamja/musicbot:latest
```
