### ISSUE TITLE
Music bot doesn't want to go online/error

### ISSUE THREAD

**Issue by Mezdow** [Just-Some-Bots/MusicBot#2108]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----
So I wanna set up my own music bot for discord so I dont have to use those other ones where I have to be a detonator to use some music commands. No matter what I do I keep getting this error, the bot goes online for a millisecond then goes back offline, I have the right python 3.7.0, I updated and installed all the pys and im just clueless as to what to do at this point.
----

### Log file
[1.537375212] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "D:\Musicbotplswokr\MusicBot\musicbot\bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\Jorda\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\guild.py", line 391, in _from_data
    self._sync(guild)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\guild.py", line 422, in _sync
    self._add_channel(CategoryChannel(guild=self, data=c, state=self._state))
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\channel.py", line 651, in __init__
    self._update(guild, data)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\channel.py", line 662, in _update
    self._fill_overwrites(data)
  File "C:\Users\Jorda\AppData\Roaming\Python\Python37\site-packages\discord\abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
[1.544254303] launcher-INFO: All done.

**Comment by Jcodeerd** [comment]
#2107

**Comment by Mezdow** [comment]
I figured it out already
