### ISSUE TITLE
Starting error

### ISSUE THREAD

**Issue by Sar-1124** [Just-Some-Bots/MusicBot#2120]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [X] Question

----

### Description of issue
Now, if you do this with another PC, the same error will occur. What can I do?

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819-5-gc87dc05
Loaded autoplaylist with 2531 entries
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "D:\MusicBot\musicbot\bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\guild.py", line 391, in _from_data
    self._sync(guild)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\channel.py", line 107, in __init__
    self._update(guild, data)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "C:\Users\CROW\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

[INFO] launcher: All done.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Tachykir** [comment]
change versions in your requirements.txt to : 
pynacl==1.4.0
discord.py[voice]==1.3.4

Then run python -m pip install -U -r requirements.txt

**Comment by AutumnClove** [comment]
As suggested you must update your requirements.txt or manually pull the new requirements and don't run update.bat again.
