### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by LiderKonmils** [Just-Some-Bots/MusicBot#2127]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The release-260819-5-gc87dc05 (updated by the update.bat file)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Since many months, the bot don't star and give me the error listed below in the log file.

### Steps to reproduce

1. Launch the bot

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[26.949882507] 2020-09-05 07:15:25,824 - INFO - launcher: Starting sanity checks
[26.949882507] 2020-09-05 07:15:25,824 - INFO - launcher: Checking for Python 3.5+
[26.949882507] 2020-09-05 07:15:25,824 - INFO - launcher: Checking console encoding
[27.947902679] 2020-09-05 07:15:25,825 - INFO - launcher: Setting console encoding to UTF-8
[27.947902679] 2020-09-05 07:15:25,825 - INFO - launcher: Ensuring we're in the right environment
[28.944969177] 2020-09-05 07:15:25,826 - INFO - launcher: Adding local bins/ folder to path
[486.232280731] 2020-09-05 07:15:26,284 - INFO - launcher: Required checks passed.
[496.376276016] 2020-09-05 07:15:26,294 - INFO - launcher: Optional checks passed.
[496.376276016] 2020-09-05 07:15:26,294 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.3432137966156006] 2020-09-05 07:15:27,140 - WARNING - musicbot.config | In config.py::MainThread(11548), line 121 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.3432137966156006] 2020-09-05 07:15:27,140 - INFO - musicbot.config | In config.py::MainThread(11548), line 132 in run_checks: Using i18n: config/i18n/en.json
[1.3600735664367676] 2020-09-05 07:15:27,157 - DEBUG - musicbot.bot | In bot.py::MainThread(11548), line 225 in _setup_logging: Set logging level to INFO
[1.3700916767120361] 2020-09-05 07:15:27,167 - DEBUG - musicbot.json | In json.py::MainThread(11548), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.4342172145843506] 2020-09-05 07:15:27,231 - INFO - musicbot.bot | In bot.py::MainThread(11548), line 90 in __init__: Starting MusicBot release-260819-5-gc87dc05
[1.4351871013641357] 2020-09-05 07:15:27,232 - INFO - musicbot.bot | In bot.py::MainThread(11548), line 96 in __init__: Loaded autoplaylist with 2521 entries
[1.682364225] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "C:\Users\simondkiller\MusicBotDec2018\musicbot\bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\aiohttp\connector.py", line 927, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discordapp.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')]
[1.713842869] launcher-INFO: All done.

---

What did you tried to resolve the problem?
-I've reinstalled Python, Git and the bot - No results.

---
P.S.: Sorry if this issue has already be send by others, by i can't decript the log file and don't know where the differeces are from other issues.

**Comment by Jcodeerd** [comment]
Maybe this:

Unable to get local issuer certificate
getting an error like 
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host discordapp.com:443 ssl:None
on windows?
Just go to discord in Internet Explorer and accept / trust the new certificates.

?

**Comment by SimonDKiller** [comment]
And how do i do that?

**Comment by LiderKonmils** [comment]
I've open discord on Edge (W10) and i don't see anything to accept /trust any certificate.

**Comment by AutumnClove** [comment]
Sectigo (cert vendor) also provides this link to download the cert manually: https://crt.sh/?id=2835394 <- gotten from the link below
---> How to find the download link: https://beans-took-my-kids.reeee.ee/38qB2n.png
---> This shouldn't need said, but you need to install the certificate after you download it.

For those curious, it was caused by this:
https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT

**Comment by LiderKonmils** [comment]
@AutumnClove 
I've downloaded the certificate, installed it and it seems the is no differences.

`[24.068355560] 2020-09-05 11:04:49,088 - INFO - launcher: Starting sanity checks
[25.066137314] 2020-09-05 11:04:49,089 - INFO - launcher: Checking for Python 3.5+
[25.066137314] 2020-09-05 11:04:49,089 - INFO - launcher: Checking console encoding
[26.063203812] 2020-09-05 11:04:49,090 - INFO - launcher: Setting console encoding to UTF-8
[26.063203812] 2020-09-05 11:04:49,090 - INFO - launcher: Ensuring we're in the right environment
[27.060270309] 2020-09-05 11:04:49,091 - INFO - launcher: Adding local bins/ folder to path
[472.335577011] 2020-09-05 11:04:49,536 - INFO - launcher: Required checks passed.
[473.330259323] 2020-09-05 11:04:49,537 - INFO - launcher: Optional checks passed.
[473.330259323] 2020-09-05 11:04:49,537 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.1573421955108643] 2020-09-05 11:04:50,221 - WARNING - musicbot.config | In config.py::MainThread(15108), line 121 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.1573421955108643] 2020-09-05 11:04:50,221 - INFO - musicbot.config | In config.py::MainThread(15108), line 132 in run_checks: Using i18n: config/i18n/en.json
[1.1603353023529053] 2020-09-05 11:04:50,224 - DEBUG - musicbot.bot | In bot.py::MainThread(15108), line 225 in _setup_logging: Set logging level to INFO
[1.1623296737670898] 2020-09-05 11:04:50,226 - DEBUG - musicbot.json | In json.py::MainThread(15108), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.2021024227142334] 2020-09-05 11:04:50,266 - INFO - musicbot.bot | In bot.py::MainThread(15108), line 90 in __init__: Starting MusicBot release-260819-5-gc87dc05
[1.2021024227142334] 2020-09-05 11:04:50,266 - INFO - musicbot.bot | In bot.py::MainThread(15108), line 96 in __init__: Loaded autoplaylist with 2521 entries
[1.759917498] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "C:\Users\simondkiller\MusicBotDec2018\musicbot\bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\guild.py", line 391, in _from_data
    self._sync(guild)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\guild.py", line 420, in _sync
    self._add_channel(VoiceChannel(guild=self, data=c, state=self._state))
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\channel.py", line 504, in __init__
    self._update(guild, data)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\channel.py", line 535, in _update
    self._fill_overwrites(data)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\discord\abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
[1.767506123] launcher-INFO: All done.
`

**Comment by AutumnClove** [comment]
That's a totally different error lol

**Comment by AutumnClove** [comment]
**I started my bot, but there's and error!**
 
```__new__() got an unexpected keyword argument: 'deny_new'```


If you are on windows, simply do `py -m pip install -U discord.py[voice]` and that should fix it.
If you are on linux or mac os, do `pythonx.x -m pip install -U discord.py[voice]` and replace x.x with your python version, for example python3.7 and your error should be gone aswell.

You can also change the requirements.txt file so that it looks like this: 
```text
pynacl==1.4.0
discord.py[voice]==1.3.4
pip
youtube_dl
colorlog
```


Then run update.bat(if your on windows, if not chose the appropriate update file for your system OS) once it's all up to date, then do run.bat(same note as before). Make sure to press n and then y so it doesn't reset your requirements file.

**Comment by AutumnClove** [comment]
Aaaah why is GitHub markdown not working for meee
