### ISSUE TITLE
Unable to play any song in voice chat

### ISSUE THREAD

**Issue by riley-hayes** [Just-Some-Bots/MusicBot#2134]
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Unable to play any song in any chat, will timeout after about 15 seconds after trying to play song. Has been working previously but has stopped working

After reading logs, seems to be a connection issue to Discord, but the server does have a working internet connection and shell script is being ran with sudo so not sure what is blocking it.

### Steps to reproduce

1. Run Bot
2. Wait 15 seconds

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

The log file and the console show two different errors so I will include both.
Console Log

./run.sh: line 9: python3.5: command not found
./run.sh: line 10: python3.6: command not found
./run.sh: line 11: python3.7: command not found
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819-72-g2350384
Loaded autoplaylist with 2531 entries
WARNING: The config did not have Spotify app credentials, attempting to use guest mode.
Authenticated with Spotify successfully using guest mode.

Connected: 755674298663960588/NeX Net Music Bot#4974
WARNING: Owner could not be found on any guild (id: 755674235526971464)

Guild List:
 - Nex Network

Bound to text channels:
 - Nex Network/music

Autojoining voice channels:
 - Nex Network/Party Music+Chat

Attempting to join Nex Network/Party Music+Chat
Task exception was never retrieved
future: <Task finished name='Task-24' coro=<VoiceClient._create_socket() done, defined at /root/.local/lib/python3.8/site-packages/discord/voice_client.py:172> exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/discord/voice_client.py", line 191, in _create_socket
    self.endpoint_ip = socket.gethostbyname(self.endpoint)
socket.gaierror: [Errno -2] Name or service not known
[ERROR:bot] Failed to join Nex Network/Party Music+Chat
138857195788828672/vapouR#0001: .shutdown

[INFO] launcher: All done.

logs/musicbot.txt

[11.313915253] 2020-09-25 01:42:32,915 - INFO - launcher: Starting sanity checks
[11.505842209] 2020-09-25 01:42:32,915 - INFO - launcher: Checking for Python 3.5+
[11.580944061] 2020-09-25 01:42:32,915 - INFO - launcher: Checking console encoding
[11.652946472] 2020-09-25 01:42:32,915 - INFO - launcher: Ensuring we're in the right environment
[158.206701279] 2020-09-25 01:42:33,062 - INFO - launcher: Required checks passed.
[158.379793167] 2020-09-25 01:42:33,062 - INFO - launcher: Optional checks passed.
[158.468008041] 2020-09-25 01:42:33,062 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.4060745239257812] 2020-09-25 01:42:33,309 - WARNING - musicbot.config | In config.py::MainThread(140593158629184), line 123 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.4062123298645020] 2020-09-25 01:42:33,310 - INFO - musicbot.config | In config.py::MainThread(140593158629184), line 134 in run_checks: Using i18n: config/i18n/en.json
[0.4071471691131592] 2020-09-25 01:42:33,310 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 239 in _setup_logging: Set logging level to INFO
[0.4084064960479736] 2020-09-25 01:42:33,312 - DEBUG - musicbot.json | In json.py::MainThread(140593158629184), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.4138333797454834] 2020-09-25 01:42:33,317 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 90 in __init__: Starting MusicBot release-260819-72-g2350384
[0.4139759540557861] 2020-09-25 01:42:33,317 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 96 in __init__: Loaded autoplaylist with 2531 entries
[0.4312374591827393] 2020-09-25 01:42:33,335 - WARNING - musicbot.bot | In bot.py::MainThread(140593158629184), line 128 in __init__: The config did not have Spotify app credentials, attempting to use guest mode.
[0.5294680595397949] 2020-09-25 01:42:33,433 - DEBUG - musicbot.spotify | In spotify.py::MainThread(140593158629184), line 81 in get_token: Created a new guest access token: {'access_token': 'BQAYcd_mi0uZXy1yXtQw0_4Tj0E8ueQC1WvhtGfJXVr2b7NLVP5Jli_IuzhKlUIL7DDB-C7HUvNacFRZ3-k', 'expires_at': 1601016685.463}
[0.5296251773834229] 2020-09-25 01:42:33,433 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 134 in __init__: Authenticated with Spotify successfully using guest mode.
[2.9869320392608643] 2020-09-25 01:42:35,890 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 965 in on_ready: Connection established, ready to go.
[2.9870760440826416] 2020-09-25 01:42:35,890 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 356 in _cache_app_info: Caching app info
[3.0826051235198975] 2020-09-25 01:42:35,986 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 787 in _scheck_ensure_env: Ensuring data folders exist
[3.0829486846923828] 2020-09-25 01:42:35,986 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 803 in _scheck_server_permissions: Checking server permissions
[3.0830147266387939] 2020-09-25 01:42:35,986 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 807 in _scheck_autoplaylist: Auditing autoplaylist
[3.0830736160278320] 2020-09-25 01:42:35,986 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 811 in _scheck_configs: Validating config
[3.0831365585327148] 2020-09-25 01:42:35,986 - DEBUG - musicbot.config | In config.py::MainThread(140593158629184), line 237 in async_validate: Validating options...
[3.0831925868988037] 2020-09-25 01:42:35,987 - DEBUG - musicbot.config | In config.py::MainThread(140593158629184), line 251 in async_validate: Acquired owner id via API
[3.0832455158233643] 2020-09-25 01:42:35,987 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 814 in _scheck_configs: Validating permissions config
[3.0833103656768799] 2020-09-25 01:42:35,987 - DEBUG - musicbot.permissions | In permissions.py::MainThread(140593158629184), line 94 in async_validate: Validating permissions...
[3.0833785533905029] 2020-09-25 01:42:35,987 - DEBUG - musicbot.permissions | In permissions.py::MainThread(140593158629184), line 98 in async_validate: Fixing automatic owner group
[3.0834386348724365] 2020-09-25 01:42:35,987 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 979 in on_ready: Connected: 755674298663960588/NeX Net Music Bot#4974
[3.0836081504821777] 2020-09-25 01:42:35,987 - WARNING - musicbot.bot | In bot.py::MainThread(140593158629184), line 1010 in on_ready: Owner could not be found on any guild (id: 755674235526971464)

[3.0837128162384033] 2020-09-25 01:42:35,987 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 1012 in on_ready: Guild List:
[3.0838203430175781] 2020-09-25 01:42:35,987 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 1015 in on_ready:  - Nex Network
[3.0839767456054688] 2020-09-25 01:42:35,987 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 1040 in on_ready: Bound to text channels:
[3.0840888023376465] 2020-09-25 01:42:35,987 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 1041 in <listcomp>:  - Nex Network/music
[3.0842239856719971] 2020-09-25 01:42:35,988 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 1066 in on_ready: Autojoining voice channels:
[3.0843284130096436] 2020-09-25 01:42:35,988 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 1067 in <listcomp>:  - Nex Network/Party Music+Chat
[3.0844771862030029] 2020-09-25 01:42:35,988 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 295 in _join_startup_channels: Attempting to join Nex Network/Party Music+Chat
[63.1053261756896973] 2020-09-25 01:43:36,009 - DEBUG - musicbot.bot | In bot.py::MainThread(140593158629184), line 323 in _join_startup_channels: Error joining Nex Network/Party Music+Chat
Traceback (most recent call last):
  File "/home/nate/MusicBot/musicbot/bot.py", line 308, in _join_startup_channels
    player = await self.get_player(channel, create=True, deserialize=self.config.persistent_queue)
  File "/home/nate/MusicBot/musicbot/bot.py", line 435, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/nate/MusicBot/musicbot/bot.py", line 400, in get_voice_client
    return await channel.connect(timeout=60, reconnect=True)
  File "/root/.local/lib/python3.8/site-packages/discord/abc.py", line 1080, in connect
    await voice.connect(reconnect=reconnect)
  File "/root/.local/lib/python3.8/site-packages/discord/voice_client.py", line 218, in connect
    await self.start_handshake()
  File "/root/.local/lib/python3.8/site-packages/discord/voice_client.py", line 154, in start_handshake
    await asyncio.wait_for(self._handshake_complete.wait(), timeout=self.timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
[63.1066436767578125] 2020-09-25 01:43:36,010 - ERROR - musicbot.bot | In bot.py::MainThread(140593158629184), line 324 in _join_startup_channels: Failed to join Nex Network/Party Music+Chat
[102.5388445854187012] 2020-09-25 01:44:15,442 - INFO - musicbot.bot | In bot.py::MainThread(140593158629184), line 2716 in on_message: 138857195788828672/vapouR#0001: .shutdown
[102.792178154] launcher-INFO: All done.

**Comment by Jcodeerd** [comment]
try this:

`py -3.8 -m pip install websockets`

**Comment by Jeroeni** [comment]
change discord.py version in requirements.txt to discord.py[voice]==1.4.1
update dependencies. That fixed it for me :)

**Comment by riley-hayes** [comment]
> change discord.py version in requirements.txt to discord.py[voice]==1.4.1
> update dependencies. That fixed it for me :)

This also resolved my issue :)
