### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Loafabreadly** [Just-Some-Bots/MusicBot#214]
Bot in launched sucessfully, auto summons to correct channel and then downloads and completes the download of a song off the auto playlist.

Error is as follow:

`[Download] Started: https://www.youtube.com/watch?v=QKnqgx1Ytsk
[Download] Complete: https://www.youtube.com/watch?v=QKnqgx1Ytsk
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /root/MusicBot-main/MusicBot/musicbot/player.py:209> exception=TypeError("create_ffmpeg_player() got an unexpected keyword argument 'before_options'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/root/MusicBot-main/MusicBot/musicbot/player.py", line 240, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
TypeError: create_ffmpeg_player() got an unexpected keyword argument 'before_options'
`

To me it looks like an ffmpeg player error but I don't know what to do to fix, restarting bot doesnt fix. Running review branch and is up to date as of 16:10 on Apr 21.

**Comment by Loafabreadly** [comment]
Update:

Reinstalling doesn't solve issue either. I deleted repo on my Ubuntu server and fetched from origin to make sure I had newest stuff. Still getting same error.

Running Ubuntu Ubuntu 14.04.4 x64 512 mb Memory 20gb disk from Digital Ocean

**Comment by Loafabreadly** [comment]
Issues were solved by talking to the people in the discord. Thanks for the help those two lovely people!
