### ISSUE TITLE
Can you tell me how to fix the error?

### ISSUE THREAD

**Issue by Xzeeu** [Just-Some-Bots/MusicBot#2160]
Can you tell me how to fix the error?

Starting MusicBot release-260819-5-gc87dc05
Loaded autoplaylist with 2531 entries
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "C:\Users\katpa\MusicBot\MusicBot\musicbot\bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\guild.py", line 391, in _from_data
    self._sync(guild)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\channel.py", line 107, in __init__
    self._update(guild, data)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "C:\Users\katpa\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by AleanaA** [comment]
Run the command `py -3.7 -m pip install -U discord.py[voice]`
