### ISSUE TITLE
Error updating bot

### ISSUE THREAD

**Issue by tommyruen** [Just-Some-Bots/MusicBot#2176]
Please tick all applicable boxes.

- [*] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [*] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [*] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [*] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [*] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
When I tried to update the file, it says Error: cannot install discord-py[voice] == 1.2.5 and pynacl==1.2.1 because theses package versions have conflicting dependencies, as well as ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
which I have tried and cannot solve the issue of the conflicting dependencies. I have since reverted it into the master version, and below is the whole message.

Checking if we need to update the bot...
Already up-to-date.
Attempting to update dependencies...
Requirement already satisfied: pip in e:\botting\python\lib\site-packages (from -r requirements.txt (line 3)) (20.3.3)
Requirement already satisfied: youtube_dl in c:\users\owner\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 4)) (2020.12.14)
Requirement already satisfied: colorlog in c:\users\owner\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 5)) (4.6.2)
Requirement already satisfied: cffi in c:\users\owner\appdata\roaming\python\python37\site-packages (from -r requirements.txt (line 6)) (1.14.4)
Collecting discord.py[voice]==1.2.5
  Using cached discord.py-1.2.5-py3-none-any.whl (655 kB)
Requirement already satisfied: websockets<7.0,>=6.0 in e:\botting\python\lib\site-packages (from discord.py[voice]==1.2.5->-r requirements.txt (line 2)) (6.0)
ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pynacl==1.2.1
    discord-py[voice] 1.2.5 depends on PyNaCl==1.3.0; extra == "voice"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install --no-warn-script-location --user -U -r requirements.txt'.format(sys.executable), shell=True)
  File "E:\Botting\Python\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"E:\Botting\Python\python.exe" -m pip install --no-warn-script-location --user -U -r requirements.txt' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\" -m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"E:\Botting\Python\python.exe" -m pip install -U -r requirements.txt' yourself.

When I run the bot, it would not detect me in any servers and autojoin like how the setting is configured. I cannot shut down, restart or send any commands to the bot in any channels when there is no channels bound to the bot. Is there a resolution to this?

### Steps to reproduce

1. run update.bat

----

### Log file
[42.887210846] 2020-12-21 22:06:04,215 - INFO - launcher: Starting sanity checks
[42.887210846] 2020-12-21 22:06:04,215 - INFO - launcher: Checking for Python 3.5+
[43.884992599] 2020-12-21 22:06:04,216 - INFO - launcher: Checking console encoding
[43.884992599] 2020-12-21 22:06:04,216 - INFO - launcher: Setting console encoding to UTF-8
[44.880867004] 2020-12-21 22:06:04,217 - INFO - launcher: Ensuring we're in the right environment
[45.878648758] 2020-12-21 22:06:04,218 - INFO - launcher: Adding local bins/ folder to path
[629.316568375] 2020-12-21 22:06:04,802 - INFO - launcher: Required checks passed.
[629.316568375] 2020-12-21 22:06:04,802 - INFO - launcher: Optional checks passed.
[629.316568375] 2020-12-21 22:06:04,802 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.4020454883575439] 2020-12-21 22:06:05,575 - WARNING - musicbot.config | In config.py::MainThread(17040), line 121 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.4030420780181885] 2020-12-21 22:06:05,576 - INFO - musicbot.config | In config.py::MainThread(17040), line 132 in run_checks: Using i18n: config/i18n/en.json
[1.4050369262695312] 2020-12-21 22:06:05,578 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 225 in _setup_logging: Set logging level to INFO
[1.4060344696044922] 2020-12-21 22:06:05,579 - DEBUG - musicbot.json | In json.py::MainThread(17040), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.4269778728485107] 2020-12-21 22:06:05,600 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 90 in __init__: Starting MusicBot release-260819-5-gc87dc05
[1.4269778728485107] 2020-12-21 22:06:05,600 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 96 in __init__: Loaded autoplaylist with 104 entries
[4.6043620109558105] 2020-12-21 22:06:08,777 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 951 in on_ready: Connection established, ready to go.
[4.6043620109558105] 2020-12-21 22:06:08,777 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 342 in _cache_app_info: Caching app info
[4.8858032226562500] 2020-12-21 22:06:09,058 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 773 in _scheck_ensure_env: Ensuring data folders exist
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 789 in _scheck_server_permissions: Checking server permissions
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 793 in _scheck_autoplaylist: Auditing autoplaylist
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 797 in _scheck_configs: Validating config
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.config | In config.py::MainThread(17040), line 236 in async_validate: Validating options...
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.config | In config.py::MainThread(17040), line 250 in async_validate: Acquired owner id via API
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.bot | In bot.py::MainThread(17040), line 800 in _scheck_configs: Validating permissions config
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.permissions | In permissions.py::MainThread(17040), line 94 in async_validate: Validating permissions...
[4.8877985477447510] 2020-12-21 22:06:09,060 - DEBUG - musicbot.permissions | In permissions.py::MainThread(17040), line 98 in async_validate: Fixing automatic owner group
[4.8877985477447510] 2020-12-21 22:06:09,060 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 968 in on_ready: Connected: 526679690870521856/MusicBot#4620
[4.8887948989868164] 2020-12-21 22:06:09,061 - WARNING - musicbot.bot | In bot.py::MainThread(17040), line 996 in on_ready: Owner could not be found on any guild (id: 151166069845917696)

[4.8897943496704102] 2020-12-21 22:06:09,062 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 998 in on_ready: Guild List:
[4.8897943496704102] 2020-12-21 22:06:09,062 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 1001 in on_ready:  - Harambe Memorial
[4.8907966613769531] 2020-12-21 22:06:09,063 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 1001 in on_ready:  - BOI
[4.8907966613769531] 2020-12-21 22:06:09,063 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 1001 in on_ready:  - Music
[4.8907966613769531] 2020-12-21 22:06:09,063 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 1001 in on_ready:  - ChowChow Memorials
[4.8917868137359619] 2020-12-21 22:06:09,064 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 1001 in on_ready:  - Projects
[4.8917868137359619] 2020-12-21 22:06:09,064 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 1039 in on_ready: Not bound to any text channels
[4.8927845954895020] 2020-12-21 22:06:09,065 - INFO - musicbot.bot | In bot.py::MainThread(17040), line 1065 in on_ready: Not autojoining any voice channels
****

**Comment by Jcodeerd** [comment]
`"E:\Botting\Python\python.exe" -m pip install -U discord.py discord.py[voice] pynacl`

**Comment by tommyruen** [comment]
> `"E:\Botting\Python\python.exe" -m pip install -U discord.py discord.py[voice] pynacl`

After running this, the cmd prompt shows this:
Requirement already satisfied: discord.py in c:\users\owner\appdata\roaming\python\python37\site-packages (1.5.1)
Requirement already satisfied: pynacl in e:\botting\python\lib\site-packages (1.3.0)
Requirement already satisfied: aiohttp<3.7.0,>=3.6.0 in e:\botting\python\lib\site-packages (from discord.py) (3.6.2)
Requirement already satisfied: attrs>=17.3.0 in e:\botting\python\lib\site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (19.1.0)
Requirement already satisfied: chardet<4.0,>=2.0 in e:\botting\python\lib\site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (3.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in e:\botting\python\lib\site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (1.3.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in e:\botting\python\lib\site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (3.0.1)
Requirement already satisfied: multidict<5.0,>=4.5 in e:\botting\python\lib\site-packages (from aiohttp<3.7.0,>=3.6.0->discord.py) (4.5.2)
Requirement already satisfied: idna>=2.0 in e:\botting\python\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<3.7.0,>=3.6.0->discord.py) (2.8)
Requirement already satisfied: six in e:\botting\python\lib\site-packages (from pynacl) (1.12.0)
Requirement already satisfied: cffi>=1.4.1 in c:\users\owner\appdata\roaming\python\python37\site-packages (from pynacl) (1.14.4)
Requirement already satisfied: pycparser in e:\botting\python\lib\site-packages (from cffi>=1.4.1->pynacl) (2.19)

**Comment by Jcodeerd** [comment]
does it run now?

**Comment by tommyruen** [comment]
It still does not detect anyone in the server when there are 4 of us in the chatroom.

**Comment by Jcodeerd** [comment]
any errors or warnings in the console?

**Comment by tommyruen** [comment]
no errors or anything when I run it, but when I try to update it again, it has the same error quoted above regarding "ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these package versions have conflicting dependencies.",  "ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies" and "OSError: Could not update dependencies. You will need to run '"E:\Botting\Python\python.exe" -m pip install -U -r requirements.txt' yourself."

**Comment by Jcodeerd** [comment]
`"E:\Botting\Python\python.exe" -m pip uninstall  discord.py discord.py[voice] pynacl && "E:\Botting\Python\python.exe" -m pip install -U discord.py discord.py[voice]==1.5.1 pynacl`
and this (one long command)

**Comment by tommyruen** [comment]
doesn't work, still having the same issue of the bot not detecting anyone in the server.

**Comment by Jcodeerd** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/2175#issuecomment-748600084

 can you try this?

**Comment by tommyruen** [comment]
I have included both options for the bot, but it does not solve the issue.

**Comment by Jcodeerd** [comment]
weird

**Comment by Veritas546** [comment]
Yeah, saw this recently, change the requirements.txt so that it uses pynacl==1.3.0 instead of pynacl==1.2.1
then give the update a run (you will need to tell the update to use the changes in the repo when running)
you may need to install discord.py afterwards
py -m pip install -U discord.py

**Comment by tommyruen** [comment]
> Yeah, saw this recently, change the requirements.txt so that it uses pynacl==1.3.0 instead of pynacl==1.2.1
> then give the update a run (you will need to tell the update to use the changes in the repo when running)
> you may need to install discord.py afterwards
> py -m pip install -U discord.py

Thanks, I've tried this and the error disappeared. However, the bot is still not detecting anyone in the server channel when there are people in the voice chat. Whenever I try to summon it, it would auto-pause as it deems that the voice chat is empty. May I know if there is a solution to that?

**Comment by Veritas546** [comment]
> > Yeah, saw this recently, change the requirements.txt so that it uses pynacl==1.3.0 instead of pynacl==1.2.1
> > then give the update a run (you will need to tell the update to use the changes in the repo when running)
> > you may need to install discord.py afterwards
> > py -m pip install -U discord.py
> 
> Thanks, I've tried this and the error disappeared. However, the bot is still not detecting anyone in the server channel when there are people in the voice chat. Whenever I try to summon it, it would auto-pause as it deems that the voice chat is empty. May I know if there is a solution to that?

Can't say I have the same issue, mine plays just fine, but a quick workaround for that would be to change "AutoPause" from yes to no in the options.ini and then it won't pause

**Comment by AutumnClove** [comment]
Updated by srhino after adding intents to the bot, use review branch for now.

**Comment by AutumnClove** [comment]
Also please make sure to go to [Discord Developer Portal](https://discord.com/developers/docs/intro) and to your application then to bot and find the setting intents and enable both.
