### ISSUE TITLE
Error starting bot

### ISSUE THREAD

**Issue by HMxBLOOD** [Just-Some-Bots/MusicBot#2202]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

- Error starting bot

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.8+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log

Starting MusicBot release-260819-94-g59bbe52
Loaded autoplaylist with 2531 entries
Authenticated with Spotify successfully using client ID and secret.
[ERROR:bot] Error in cleanup
Traceback (most recent call last):
  File "C:\Users\nawaz\Documents\music-bot1\MusicBot\musicbot\bot.py", line 944, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\nawaz\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 661, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\nawaz\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 596, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nawaz\Documents\music-bot1\MusicBot\musicbot\bot.py", line 955, in run
    self._cleanup()
  File "C:\Users\nawaz\Documents\music-bot1\MusicBot\musicbot\bot.py", line 931, in _cleanup
    pending = asyncio.Task.all_tasks()
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "C:\Users\nawaz\Documents\music-bot1\MusicBot\run.py", line 385, in main
    m.run()
  File "C:\Users\nawaz\Documents\music-bot1\MusicBot\musicbot\bot.py", line 944, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\nawaz\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\nawaz\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 661, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\nawaz\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 596, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

[INFO] launcher: All done.
![error](https://user-images.githubusercontent.com/75079289/111856809-4b16ac00-8953-11eb-8406-b51a9081bae9.png)

### Steps to reproduce

1. 

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/6174764/musicbot.log)

Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
![image](https://user-images.githubusercontent.com/68161666/111866646-3516e480-896f-11eb-996c-6b096a798002.png)

**Comment by AutumnClove** [comment]
As shown in the above image Please enable intents also strongly recommend using review for now
