### ISSUE TITLE
Youtube : Age-restricted videos

### ISSUE THREAD

**Issue by LiderKonmils** [Just-Some-Bots/MusicBot#2220]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
Is there a way to play age-restricted videos from youtube?
I'Ve seen someone talking about using cookies, but i don't know at all how to do that.

### Steps to reproduce

1. Try to play an age-restricted video (ex: !play https://www.youtube.com/watch?v=syy_IoW92XE (Why did i say okie doki - Stupendium, original version))
2. Getting the errors: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[ERROR:bot] Error in play: CommandError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1713, in _real_extract
    raise ExtractorError(reason, expected=True)
youtube_dl.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\simondkiller\Documents\ZikBot\MusicBot\musicbot\bot.py", line 1400, in cmd_play
    info = await self.downloader.extract_info(player.playlist.loop, song_url, download=False, process=False)
  File "C:\Users\simondkiller\Documents\ZikBot\MusicBot\musicbot\downloader.py", line 85, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\simondkiller\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\simondkiller\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\simondkiller\Documents\ZikBot\MusicBot\musicbot\bot.py", line 2813, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\simondkiller\Documents\ZikBot\MusicBot\musicbot\bot.py", line 1427, in cmd_play
    raise exceptions.CommandError(e, expire_in=30)
musicbot.exceptions.CommandError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.

**Comment by DestinyofYeet** [comment]
[This here](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl) is the official way described on the youtube-dl repository. I can't really tell you anything about it since i haven't done it myself, but it sounds pretty easy.

**Comment by LiderKonmils** [comment]
Ok, I know nothing about coding or playing with config files if this is not explained clearly. This --cookies, where is it, what file on which folder?

**Comment by DestinyofYeet** [comment]
Ah yeah, i just realised that the --cookies option has to be applied when running youtube-dl directly, but we use a library that makes life easier for us when using youtube-dl. Currently there is no way for you (except if you modify the source code) to supply the --cookies flag and thus can't use the cookie file. Sorry for that.

**Comment by LiderKonmils** [comment]
So what now? I Just wait for an update of the bot that may never happen?

**Comment by DestinyofYeet** [comment]
As harsh as it may sound, essentially yes.

**Comment by LiderKonmils** [comment]
*sigh* ... Thank you YouTube to ruining everything you touch. I'll let this thread open. With chance, devs will pass here, see this and add an option in the next update. I am anything but confident about that.

**Comment by DestinyofYeet** [comment]
You could open an additional thread for a feature request and well request youtube-dl cookie file support.

> I am anything but confident about that.

(me too)

**Comment by LiderKonmils** [comment]
Ok, I'll do that. Thanks for the help.
