### ISSUE TITLE
ImportError: libsodium.so.13: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TheOkayMan** [Just-Some-Bots/MusicBot#223]
Hi,
I have installed MusicBot onto Ubuntu 16.04 as per the instructions @ https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions

When I try and tun it (python3.5 run.py) I get the following error:

```
libsodium.so.13: cannot open shared object file: No such file or directory
Attempting to install dependencies...
Collecting https://github.com/Rapptz/discord.py/archive/async.zip (from -r requirements.txt (line 1))
  Downloading https://github.com/Rapptz/discord.py/archive/async.zip (122kB)
    100% |████████████████████████████████| 122kB 64kB/s 
  Requirement already satisfied (use --upgrade to upgrade): discord.py==0.10.0a0 from https://github.com/Rapptz/discord.py/archive/async.zip in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): youtube-dl>=2016.3.6 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): aiohttp<0.22.0,>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): websockets==2.7 in /usr/local/lib/python3.5/dist-packages (from discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): PyNaCl==1.0.1 in /usr/local/lib/python3.5/dist-packages (from discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): chardet in /usr/lib/python3/dist-packages (from aiohttp<0.22.0,>=0.21.0->discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py==0.10.0a0->-r requirements.txt (line 1))

Ok lets hope it worked

Traceback (most recent call last):
  File "run.py", line 164, in main
    from musicbot import MusicBot
  File "/home/alex/MusicBot/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/home/alex/MusicBot/musicbot/bot.py", line 7, in <module>
    import discord
  File "/usr/local/lib/python3.5/dist-packages/discord/__init__.py", line 20, in <module>
    from .client import Client
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 43, in <module>
    from .voice_client import VoiceClient
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 53, in <module>
    import nacl.secret
  File "/usr/local/lib/python3.5/dist-packages/nacl/secret.py", line 18, in <module>
    import nacl.bindings
  File "/usr/local/lib/python3.5/dist-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/usr/local/lib/python3.5/dist-packages/nacl/bindings/crypto_box.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ImportError: libsodium.so.13: cannot open shared object file: No such file or directory
Unknown ImportError, exiting.
```

**Comment by imayhaveborkedit** [comment]
You need to install libsodium, `sudo apt-get install libsodium-dev`

**Comment by shrx** [comment]
Same issue, `sudo apt-get install libsodium-dev` does not help.

**Comment by coyotte508** [comment]
Same issue, it happened after I upgraded my distribution (from 15.04 to 16.04)

I have a libsodium installed but the filename is now:

```
/usr/lib/x86_64-linux-gnu/libsodium.so
/usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
```

This solved it:

`sudo cp /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1 /usr/lib/x86_64-linux-gnu/libsodium.so.13`

**Comment by imayhaveborkedit** [comment]
For the record, you typically symlink libs in this situation, with `ln -s`.  Copying the file means the copied file isn't updated when the lib is updated.

**Comment by richhamseth** [comment]
> Same issue, it happened after I upgraded my distribution (from 15.04 to 16.04)
> 
> I have a libsodium installed but the filename is now:
> 
> ```
> /usr/lib/x86_64-linux-gnu/libsodium.so
> /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
> ```
> This solved it:
> 
> `sudo cp /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1 /usr/lib/x86_64-linux-gnu/libsodium.so.13`

This (sudo cp /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1 /usr/lib/x86_64-linux-gnu/libsodium.so.13`
) worked
