### ISSUE TITLE
Unable to activate

### ISSUE THREAD

**Issue by Orsopoeta74** [Just-Some-Bots/MusicBot#2255]
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x ] Question

----

### Description of issue
Good day. I have followed all your steps but when I start run.bat the bot does not activate. I am attaching a screenshot. 
Thanks in advance for any help.

![screenshot](https://user-images.githubusercontent.com/66994464/135427780-57d2eae5-bf05-40e4-9061-fb3c6430a7b2.jpg)

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[34.002065659] 2021-09-30 11:32:20,762 - INFO - launcher: Starting sanity checks
[35.001993179] 2021-09-30 11:32:20,763 - INFO - launcher: Checking for Python 3.5+
[35.001993179] 2021-09-30 11:32:20,763 - INFO - launcher: Checking console encoding
[35.001993179] 2021-09-30 11:32:20,763 - INFO - launcher: Setting console encoding to UTF-8
[36.002159119] 2021-09-30 11:32:20,764 - INFO - launcher: Ensuring we're in the right environment
[38.002490997] 2021-09-30 11:32:20,766 - INFO - launcher: Adding local bins/ folder to path
[40.002346039] 2021-09-30 11:32:20,768 - INFO - launcher: Required checks passed.
[41.002511978] 2021-09-30 11:32:20,769 - INFO - launcher: Optional checks passed.
[41.002511978] 2021-09-30 11:32:20,769 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[128.007411957] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 367, in main
    from musicbot import MusicBot
  File "C:\Users\USERNAME\Desktop\botdiscord\MusicBot\musicbot\__init__.py", line 7, in <module>
    from .utils import _get_variable
  File "C:\Users\USERNAME\Desktop\botdiscord\MusicBot\musicbot\utils.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[130.007505417] launcher-INFO: Attempting to install dependencies...
[135.007858276] launcher-INFO: All done.

**Comment by DestinyofYeet** [comment]
What python version are you using?

**Comment by BabyBoySnow** [comment]
Please re-run the python install file, it should give you an option to modify install settings. 
[Correct](https://prnt.sc/bMB0mwiySlf_)
Make sure pip is checked.
