### ISSUE TITLE
Bot isnt working im at a loss

### ISSUE THREAD

**Issue by rickmd1991** [Just-Some-Bots/MusicBot#2259]
Please tick all applicable boxes.

- [ x] I am using Python 3.5.3 or higher (run `python --version` on the command line) Python 3.10.0
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x ] Question

----

### Description of issue
I was able to get the bot into the discord channel but nothing played with the commands. Now the bot doesn't join stays offline. the dependencies are fully updated no errors. Spent the whole day on this I'm legit at a loss. Please help.

### Steps to reproduce

1. run the bat

----

### Log file
[16.935110092] 2021-10-07 04:35:29,385 - INFO - launcher: Starting sanity checks
[17.330646515] 2021-10-07 04:35:29,386 - INFO - launcher: Checking for Python 3.5+
[17.330646515] 2021-10-07 04:35:29,386 - INFO - launcher: Checking console encoding
[17.652511597] 2021-10-07 04:35:29,386 - INFO - launcher: Setting console encoding to UTF-8
[17.831087112] 2021-10-07 04:35:29,386 - INFO - launcher: Ensuring we're in the right environment
[18.323421478] 2021-10-07 04:35:29,387 - INFO - launcher: Adding local bins/ folder to path
[195.013761520] 2021-10-07 04:35:29,563 - INFO - launcher: Required checks passed.
[196.011304855] 2021-10-07 04:35:29,564 - INFO - launcher: Optional checks passed.
[196.011304855] 2021-10-07 04:35:29,564 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

                       'WHAT THE CMD SHOWS'
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "C:\Users\rickm\Desktop\bot\MusicBot\run.py", line 438, in <module>
    main()
  File "C:\Users\rickm\Desktop\bot\MusicBot\run.py", line 347, in main
    finalize_logging()
  File "C:\Users\rickm\Desktop\bot\MusicBot\run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 589, in __init__
    self._style.validate()
  File "C:\Program Files\Python310\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style

**Comment by AleanaA** [comment]
This specific error is resolved in review, the master branch is not compatible with Python 3.8+
This being said, review has not been tested with Python 3.10, should you have issues with the review branch using it, consider downgrading to 3.9 or 3.8
