### ISSUE TITLE
[BUG] Windows - Bot won't run

### ISSUE THREAD

**Issue by kubo6472** [Just-Some-Bots/MusicBot#2263]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

Some packages error out.

### Steps to reproduce

1. Follow the guide @ https://just-some-bots.github.io/MusicBot/installing/windows/

----

### Log file
```
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 373, in main
    m.run()
  File "D:\Downloads\MusicBot\musicbot\bot.py", line 902, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Program Files (x86)\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\state.py", line 663, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\state.py", line 638, in _get_create_guild
    guild._from_data(data)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\guild.py", line 391, in _from_data
    self._sync(guild)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\guild.py", line 418, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\channel.py", line 107, in __init__
    self._update(guild, data)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\abc.py", line 271, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

[INFO] launcher: All done.
```
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7384801/musicbot.log)
[musicbot (2).log](https://github.com/Just-Some-Bots/MusicBot/files/7384804/musicbot.2.log)

**Comment by AleanaA** [comment]
`py -m pip install -U discord.py[voice]`
