### ISSUE TITLE
Another weird issue

### ISSUE THREAD

**Issue by kubo6472** [Just-Some-Bots/MusicBot#2267]
Sry in advance for not using the template:
```
[ERROR:bot] Error in cleanup
Traceback (most recent call last):
  File "/home/container/musicbot/bot.py", line 1068, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/container/musicbot/bot.py", line 1080, in run
    self._cleanup()
  File "/home/container/musicbot/bot.py", line 1055, in _cleanup
    pending = asyncio.all_tasks()
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 44, in all_tasks
    loop = events.get_running_loop()
RuntimeError: no running event loop
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "/home/container/run.py", line 416, in main
    m.run()
  File "/home/container/musicbot/bot.py", line 1068, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

[INFO] launcher: All done.
```

**Comment by AleanaA** [comment]
Enable intents in the developer dashboard.
![image](https://user-images.githubusercontent.com/8583835/138352385-7d8e7575-2f4b-40f0-b7b7-00605056a327.png)

**Comment by kubo6472** [comment]
thank you!

**Comment by VictorLzm** [comment]
> Enable intents in the developer dashboard.


It doesn't help me through my ongoing version of this error. 
See the screenshots:
<img width="983" alt="Capture d’écran 2022-01-27 à 20 53 51" src="https://user-images.githubusercontent.com/6512397/151433831-8407038f-b144-48a2-8e64-a487942949a5.png">
<img width="1392" alt="Capture d’écran 2022-01-27 à 20 53 21" src="https://user-images.githubusercontent.com/6512397/151433842-b748943d-b98d-4309-b3a4-3f562516e3f1.png">

**Comment by DestinyofYeet** [comment]
You pressed ctrl+c while the bot was starting / running.
![image](https://user-images.githubusercontent.com/57575330/151434424-be1bd4b4-119a-4bc3-b796-339550fe1c6d.png)

**Comment by VictorLzm** [comment]
Yes I know that but don't you see all the following lines?
I had to press ctrl-c to reproduce easily
If I `!shutdown` it does the same

**Comment by AleanaA** [comment]
@VictorLzm Please don't clutter existing resolved issues, make your own.
Regardless, this is entirely user error, the lines following the ctrl-c are a result of the ctrl-c, and are entirely intentional.
`!shutdown` results in the same because shutdown is interrupting the bot in a similar way.
