### ISSUE TITLE
run.py does not start

### ISSUE THREAD

**Issue by aaa0101** [Just-Some-Bots/MusicBot#2289]
### What went wrong?

I added my Bot to my channel and clicked run.py to add it to voice channel.
But run.py is shut down without any error message, and Bot is not added successfully.
I am using python 3.10.2 which is an up-to-date version.

### How do we reproduce this?

1. I copied example_options.ini to options.ini in config folder and modified this file according to the manual via visual studio code.
2. I created an application in Discord and made a bot.
3. I gave all three Privileged Gateway Intents to the bot.
4. I authorized the bot and it was added to my own server.
5. I ran run.py to add the bot to voice channel in my server.
6. run.py is shut down 2~3 seconds after I double-click it without warning message.
7. Here is my log file:
[75.974464417] 2022-01-26 06:11:52,471 - INFO - launcher: Starting sanity checks
[75.974464417] 2022-01-26 06:11:52,471 - INFO - launcher: Checking for Python 3.8+
[76.925754547] 2022-01-26 06:11:52,472 - INFO - launcher: Checking console encoding
[76.925754547] 2022-01-26 06:11:52,472 - INFO - launcher: Setting console encoding to UTF-8
[77.922821045] 2022-01-26 06:11:52,473 - INFO - launcher: Ensuring we're in the right environment
[80.914974213] 2022-01-26 06:11:52,476 - INFO - launcher: Adding local bins/ folder to path
[790.172338486] 2022-01-26 06:11:53,185 - INFO - launcher: Required checks passed.
[790.986061096] 2022-01-26 06:11:53,186 - INFO - launcher: Optional checks passed.
[791.986465454] 2022-01-26 06:11:53,187 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1549.963474274] launcher-ERROR: Syntax error (this is a bug, not your fault)
Traceback (most recent call last):
  File "C:\Users\dhrbd\Desktop\새 폴더\MusicBot\run.py", line 409, in main
    from musicbot import MusicBot
  File "C:\Users\dhrbd\Desktop\새 폴더\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\Users\dhrbd\Desktop\새 폴더\MusicBot\musicbot\bot.py", line 28, in <module>
    from . import downloader
  File "C:\Users\dhrbd\Desktop\새 폴더\MusicBot\musicbot\downloader.py", line 5, in <module>
    import yt_dlp as youtube_dl
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\__init__.py", line 16, in <module>
    from .options import (
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\options.py", line 27, in <module>
    from .downloader.external import list_external_downloaders
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\__init__.py", line 40, in <module>
    from .websocket import WebSocketFragmentFD
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\websocket.py", line 7, in <module>
    import websockets
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "C:\Users\dhrbd\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                    ^^^^^
SyntaxError: invalid syntax
[1575.823545456] launcher-INFO: All done.

### Which version of the bot are you using?

release-260419

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [x] I have updated my Python dependencies.

**Comment by aaa0101** [comment]
It was a problem of python whose version is higher than 3.7. If someone gets the same error, find compatibility.py in C:\Users\ [username]\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets (or websockets folder in somewhere you installed python) and edit asyncio.async in the code to getattr(asyncio, 'async'). This error is caused by the name of 'async' which is newly defined to be a critical keyword, but not revised in the source code.
