### ISSUE TITLE
Bot does not move on when it fails to autojoin a voice channel

### ISSUE THREAD

**Issue by rrbailey89** [Just-Some-Bots/MusicBot#230]
Assuming you are attempting to autojoin 5 differnt voice channels some of which may be in other server regions than others. Bot COULD possibly join servers 1-3 just fine but IF it fails to join server 4 due to an error similar to this (which will NOT show in terminal log during the autojoining cycle) 

```
Traceback (most recent call last):
  File "/root/musicbot/musicbot/bot.py", line 260, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=6, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/musicbot/musicbot/bot.py", line 1710, in on_message
    response = await handler(**handler_kwargs)
  File "/root/musicbot/musicbot/bot.py", line 1250, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "/root/musicbot/musicbot/bot.py", line 343, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/root/musicbot/musicbot/bot.py", line 262, in get_voice_client
    voice_client.keep_alive.cancel()
AttributeError: 'VoiceClient' object has no attribute 'keep_alive'
```

the bot will not move on and attempt to autojoin server 5 and so on but instead await commands.

**Comment by imayhaveborkedit** [comment]
This should be fixed now in review.
