### ISSUE TITLE
Can't get bot to start on windows

### ISSUE THREAD

**Issue by bjarkeh14** [Just-Some-Bots/MusicBot#2307]
### What went wrong?

I can't get the bot to work at all, have had it running on windows before. But this time I can't get it to work.

Have followed the guide and tried with python version **3.7.0**, **3.7.1**, **3.8.0**, **3.9.0** (In 32 and 64 bit) and the newest python aswell.
**Currently running version 3.9.0 32bit**

This is the last line i get when I run the update.bat
**There was a problem fetching your current bot version. The installation may not have completed correctly.**

**Here is my log**
`
[31.189441681] 2022-07-01 09:44:32,086 - INFO - launcher: Starting sanity checks
[31.189441681] 2022-07-01 09:44:32,086 - INFO - launcher: Checking for Python 3.8+
[31.189441681] 2022-07-01 09:44:32,086 - INFO - launcher: Checking console encoding
[31.189441681] 2022-07-01 09:44:32,086 - INFO - launcher: Setting console encoding to UTF-8
[31.189441681] 2022-07-01 09:44:32,086 - INFO - launcher: Ensuring we're in the right environment
[31.189441681] 2022-07-01 09:44:32,086 - INFO - launcher: Adding local bins/ folder to path
[369.543075562] 2022-07-01 09:44:32,424 - INFO - launcher: Required checks passed.
[369.543075562] 2022-07-01 09:44:32,424 - INFO - launcher: Optional checks passed.
[369.543075562] 2022-07-01 09:44:32,424 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[548.178195953] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "C:\MusicBot\run.py", line 409, in main
    from musicbot import MusicBot
  File "C:\MusicBot\musicbot\__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "C:\MusicBot\musicbot\bot.py", line 28, in <module>
    from . import downloader
  File "C:\MusicBot\musicbot\downloader.py", line 5, in <module>
    import yt_dlp as youtube_dl
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\yt_dlp\__init__.py", line 13, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\yt_dlp\cookies.py", line 17, in <module>
    from .aes import (
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\yt_dlp\aes.py", line 5, in <module>
    from .dependencies import Cryptodome_AES
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\yt_dlp\dependencies.py", line 27, in <module>
    from Cryptodome.Cipher import AES as Cryptodome_AES
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\Cryptodome\Cipher\__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\Cryptodome\Util\_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Not found '_raw_ecb.cp39-win32.pyd', Cannot load '_raw_ecb.pyd': cannot load library 'C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\Cryptodome\Util\..\Cipher\_raw_ecb.pyd': error 0xc1
[548.178195953] launcher-INFO: All done.
`

### How do we reproduce this?

When i try to start the bot

### Which version of the bot are you using?

release-260419

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by bjarkeh14** [comment]
Any help?

**Comment by BabyBoySnow** [comment]
P

> Any help?

https://github.com/pyinstaller/pyinstaller/issues/2125
