### ISSUE TITLE
Can get bot to join voice channel, but does not work.

### ISSUE THREAD

**Issue by Zelioom** [Just-Some-Bots/MusicBot#231]
When I summon the bot I get this. `Traceback (most recent call last):
  File "C:\Users\Jacob\Desktop\MusicBot-develop\musicbot\bot.py", line 760, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Jacob\Desktop\MusicBot-develop\musicbot\bot.py", line 487, in handle_summon
    player = await self.get_player(channel, create=True)
  File "C:\Users\Jacob\Desktop\MusicBot-develop\musicbot\bot.py", line 129, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\Jacob\Desktop\MusicBot-develop\musicbot\bot.py", line 96, in get_voice_client
    await asyncio.wait_for(self._session_id_found.wait(), timeout=5.0, loop=self.loop)
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 234, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute '_session_id_found'` It will still join the voice server. Then if I get the bot to play something, I get this. `Player does not exist. It has not been summoned yet into a voice channel.  Use $summon to summon it to your voice channel.`

**Comment by Zelioom** [comment]
Oh, I guess I need to use the review branch.

**Comment by ghost** [comment]
I'm having the same problem with the review branch... 

It seems that even though it joins it's not detecting that it was successful?

**Comment by ghost** [comment]
Forgive me. Running update_deps.bat and updating another package (didn't see which) resolved my issue.
