### ISSUE TITLE
Error on bot startup

### ISSUE THREAD

**Issue by Azsunyx** [Just-Some-Bots/MusicBot#2313]
### What went wrong?

I get multiple errors on bot startup following running an update, see text below

### How do we reproduce this?

I tried updating an old version and initially encountered the error, so I tried to do a fresh install and encountered the same error. 

Here is the full startup error:

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.8+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.

WARNING: Aliases file not found, copying example_aliases.json
Starting MusicBot release-151221-1-g1df26df
Loaded autoplaylist with 2531 entries
Authenticated with Spotify successfully using client ID and secret.
[ERROR:bot] Error in cleanup
Traceback (most recent call last):
  File "C:\Users\zexyn\OneDrive\Documents\MusicBot\musicbot\bot.py", line 1070, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\zexyn\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\zexyn\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 658, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\zexyn\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 599, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zexyn\OneDrive\Documents\MusicBot\musicbot\bot.py", line 1082, in run
    self._cleanup()
  File "C:\Users\zexyn\OneDrive\Documents\MusicBot\musicbot\bot.py", line 1057, in _cleanup
    pending = asyncio.all_tasks()
  File "C:\Users\zexyn\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 45, in all_tasks
    loop = events.get_running_loop()
RuntimeError: no running event loop
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "C:\Users\zexyn\OneDrive\Documents\MusicBot\run.py", line 416, in main
    m.run()
  File "C:\Users\zexyn\OneDrive\Documents\MusicBot\musicbot\bot.py", line 1070, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\zexyn\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\zexyn\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 658, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\zexyn\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 599, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

[INFO] launcher: All done.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/9689320/musicbot.log)

I'm running Python 3.10.7

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by Alllen95Wei** [comment]
@Azsunyx 
Did you turn on all the "Privileged Gateway Intents"?
![image](https://user-images.githubusercontent.com/49893966/193386540-ffe6ae02-c0c6-411c-9847-581c85fa2921.png)

https://discord.com/developers/applications/ → Click the bot → "Bot" → Scroll down → "Privileged Gateway Intents" → Turn on all switchs

**Comment by Azsunyx** [comment]
That fixed it, thank you, not sure how one of the options got deselected, but it appears to be working now, thank you
