### ISSUE TITLE
Bot can't start

### ISSUE THREAD

**Issue by Razorbackfr** [Just-Some-Bots/MusicBot#2319]
### What went wrong?

I can't start the bot.

Here the musicbot.log:  

The bot c'ant start, 

musicbot.log : 

[30.875444412] 2022-11-30 14:55:40,416 - INFO - launcher: Starting sanity checks
[31.711101532] 2022-11-30 14:55:40,417 - INFO - launcher: Checking for Python 3.8+
[32.217025757] 2022-11-30 14:55:40,417 - INFO - launcher: Checking console encoding
[32.748937607] 2022-11-30 14:55:40,418 - INFO - launcher: Ensuring we're in the right environment
[375.282287598] 2022-11-30 14:55:40,760 - INFO - launcher: Required checks passed.
[376.074314117] 2022-11-30 14:55:40,761 - INFO - launcher: Optional checks passed.
[376.513004303] 2022-11-30 14:55:40,761 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.7837531566619873] 2022-11-30 14:55:41,169 - INFO - musicbot.config | In config.py::MainThread(140478287841088), line 250 in run_checks: Using i18n: config/i18n/fr.json
[0.7858223915100098] 2022-11-30 14:55:41,171 - DEBUG - musicbot.bot | In bot.py::MainThread(140478287841088), line 281 in _setup_logging: Set logging level to EVERYTHING
[0.7914841175079346] 2022-11-30 14:55:41,176 - DEBUG - musicbot.json | In json.py::MainThread(140478287841088), line 9 in __init__: Init JSON obj with config/i18n/fr.json
[1.0448503494262695] 2022-11-30 14:55:41,430 - INFO - musicbot.bot | In bot.py::MainThread(140478287841088), line 105 in __init__: Starting MusicBot release-151221-10-g8e4ed91
[1.0452392101287842] 2022-11-30 14:55:41,430 - INFO - musicbot.bot | In bot.py::MainThread(140478287841088), line 111 in __init__: Loaded autoplaylist with 3628 entries
[1.063107252] launcher-ERROR: Error starting bot
Traceback (most recent call last):
  File "run.py", line 411, in main
    m = MusicBot()
  File "/home/valentin/MusicBot/musicbot/bot.py", line 128, in __init__
    self.aiosession = aiohttp.ClientSession(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 225, in __init__
    loop = get_running_loop(loop)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/helpers.py", line 284, in get_running_loop
    if not loop.is_running():
  File "/home/valentin/.local/lib/python3.8/site-packages/discord/client.py", line 108, in __getattr__
    raise AttributeError(msg)
AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook
[1.080822468] launcher-INFO: All done.

### How do we reproduce this?

Start the bot using review branch with Python 3.8.10

### Which version of the bot are you using?

I am using the "review" branch

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by TJ2005** [comment]
Same Issue

**Comment by jayktaylor** [comment]
Likely resolved in https://github.com/Just-Some-Bots/MusicBot/commit/710164eefb145777b10bbfcb8b1b65c37a283a78
