### ISSUE TITLE
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute '_session_id_found'

### ISSUE THREAD

**Issue by iPhoKing** [Just-Some-Bots/MusicBot#232]
```
Connected!

Bot:   xxxxxxxxxxxxxxxxxx/iPhoKing
Owner: xxxxxxxxxxxxxxxxxx/iPhoKing

Server List:
 - iPhoKing's Server

Not bound to any channels

Command prefix is !
Whitelist check is disabled
Skip threshold at 4 votes or 50%
Now Playing message @mentions are disabled
Autosummon is enabled
Auto-playlist is enabled
Downloaded songs will be saved after playback

Attempting to autosummon...
Ignoring exception in on_ready
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py", line 245, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\xxxxxxxxxxxxxxxxxx\Desktop\MusicBot-1.9.5rc7\musicbot\bot.py", line 451, in on_ready
    as_ok = await self._auto_summon()
  File "C:\Users\xxxxxxxxxxxxxxxxxx\Desktop\MusicBot-1.9.5rc7\musicbot\bot.py", line 145, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "C:\Users\xxxxxxxxxxxxxxxxxx\Desktop\MusicBot-1.9.5rc7\musicbot\bot.py", line 997, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "C:\Users\xxxxxxxxxxxxxxxxxx\Desktop\MusicBot-1.9.5rc7\musicbot\bot.py", line 246, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\xxxxxxxxxxxxxxxxxx\Desktop\MusicBot-1.9.5rc7\musicbot\bot.py", line 187, in get_voice_client
    await asyncio.wait_for(self._session_id_found.wait(), timeout=5.0, loop=self.loop)
  File "D:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py", line 234, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute '_session_id_found'
```

**Comment by iPhoKing** [comment]
Can anyone help me with this please? I've tried to lookup everywhere for a solution to this problem, but I couldn't find anything :(

**Comment by iPhoKing** [comment]
The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

It's clearly in the same channel as me :(

**Comment by RedHammerZ** [comment]
I resolved this by using the review version. https://github.com/SexualRhinoceros/MusicBot/tree/review

**Comment by iPhoKing** [comment]
I tried redownloading the MusicBot - 1.9.5rc7 and setting it up again, the problem is still there :(

**Comment by iPhoKing** [comment]
Oh wait, ima try something else :)

**Comment by RedHammerZ** [comment]
No i meant that you need to download the review version, this one fixed the problem for me

**Comment by iPhoKing** [comment]
Thanks! It solved the problem! You're a savior! I didn't see the download button on the review version's page. Dx
