### ISSUE TITLE
Newly created application/bot in 

### ISSUE THREAD

**Issue by DemonFire7** [Just-Some-Bots/MusicBot#2320]
### What went wrong?

traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 1074, in run
    raise exceptions.HelpfulError(
musicbot.exceptions.HelpfulError: ('Bot cannot login, bad credentials.', 'Fix your token in the options file.  Remember that each field should be on their own line.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 1082, in run
    self._cleanup()
  File "/root/MusicBot/musicbot/bot.py", line 1057, in _cleanup
    pending = asyncio.all_tasks()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 44, in all_tasks

The new discord bot tokens are much longer, so they can allow more bots in their system.
"the length of the discord tokens has changes over the time because of the decoded timestamp in the Base64 format in the token."

Example:
MTA0ODM0MTA0MTk2ODg1NzEyOA.GDoWzA.rn4-oX7-rYJB_FTG-vBkrWzq3Hyn1TUY1214512
(I changed some of the characters at the end, and this was previously before I generated a new token anyway)

Is there a way to make it authenticate with the longer/newer discord bot tokens?

All of my old apps/bots created in discord developer work, but this new one with new token I am using will not work.

### How do we reproduce this?

Make a new application and add a bot in discord developer and use one of the newer tokens.

### Which version of the bot are you using?

release-260419

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by DemonFire7** [comment]
You can close this, it was an issue with writing to the file options.ini, I just noticed the token was much longer than any of the older bot/apps in discord development and thought that may have been it.
