### ISSUE TITLE
bot failed to join a voice channel

### ISSUE THREAD

**Issue by narrundo** [Just-Some-Bots/MusicBot#252]
I'm trying to use AutojoinChannels parameter on option.ini but ended up having issue the bot can't join a voice channel. I'm using the review-branch running on linux server. here is the log :

```
Failed to join Music Corner

Traceback (most recent call last):
  File "run.py", line 221, in <module>
    main()
  File "run.py", line 165, in main
    m.run()
  File "/root/musicbot_rev/musicbot/bot.py", line 506, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 325, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 295, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1218, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 432, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending coro=<Client.keep_alive_handler() running at /usr/local/lib/python3.5/dist-packages/discord/client.py:299> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback(0)() at /usr/lib/python3.5/asyncio/tasks.py:627]>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe5fadb0cc0>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.run() running at /usr/local/lib/python3.5/dist-packages/websockets/protocol.py:302> wait_for=<Future cancelled> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:408, gather.<locals>._done_callback(5)() at /usr/lib/python3.5/asyncio/tasks.py:627]>
Task was destroyed but it is pending!
task: <Task pending coro=<Queue.get() running at /usr/lib/python3.5/asyncio/queues.py:168> wait_for=<Future cancelled> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:408, gather.<locals>._done_callback(3)() at /usr/lib/python3.5/asyncio/tasks.py:627]>

```

**Comment by Echoskope** [comment]
Try  `pip3.5 install -r requirements.txt --upgrade`

**Comment by narrundo** [comment]
thanks that fixed my problem ;)
