### ISSUE TITLE
not runing?

### ISSUE THREAD

**Issue by SloppierKitty7** [Just-Some-Bots/MusicBot#265]
Traceback (most recent call last):
  File "run.py", line 202, in <module>
    main()
  File "run.py", line 182, in main
    MusicBot().run()
  File "E:\Sloppers bot\MusicBot-develop\musicbot\bot.py", line 63, in **init**
    self.voice_clients = {}
  File "C:\Users\SloppierKitty7\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 237, in **setattr**
    return setattr(self.connection, name, value)
AttributeError: can't set attribute
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00B0FA30>

**Comment by imayhaveborkedit** [comment]
You have downloaded an outdated version of the bot.  The current download link is in the tutorial.  https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Windows-7-and-up#2a-download-musicbot
