### ISSUE TITLE
summon command exception

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#273]
Just calling `!mb_summon` after `!mb_disconnect`

Log:
https://gist.github.com/DaFri-Nochiterov/0a1a64f74874b1a9d74ea094265110fd

**Comment by brawaru** [comment]
This exception has gone.
But new exception has come..

```
Traceback (most recent call last):
  File "/media/dafri/Additional Disk/Main/Dev/Python/MusicBot3/musicbot/bot.py", line 1913, in on_message
    response = await handler(**handler_kwargs)
  File "/media/dafri/Additional Disk/Main/Dev/Python/MusicBot3/musicbot/bot.py", line 1310, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "/media/dafri/Additional Disk/Main/Dev/Python/MusicBot3/musicbot/bot.py", line 363, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/media/dafri/Additional Disk/Main/Dev/Python/MusicBot3/musicbot/bot.py", line 241, in get_voice_client
    voice_data = await asyncio.wait_for(_voice_data, timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 397, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by jayktaylor** [comment]
This is probably resolved. Regardless, it doesn't seem to be the bot's issue and is more an issue with Discord itself or the way that discord.py handles this shit.
