### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by Augustaeum** [Just-Some-Bots/MusicBot#281]
So I get this error and I do not know if the issue is on my end or Discord's.

```

Connecting...Traceback (most recent call last):
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 581, in _create_connection
    local_addr=self._local_addr)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 663, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 686, in _create_connection_transport
    yield from waiter
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\sslproto.py", line 492, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\sslproto.py", line 200, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 310, in connect
    transport, proto = yield from self._create_connection(req)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 604, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 165, in main
    m.run()
  File "C:\Users\Operator\Desktop\Lukaas MusicBot\musicbot\bot.py", line 557, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 437, in start
    yield from self.login(*args)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 367, in login
    yield from getattr(self, '_login_' + str(n))(*args)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 312, in _login_2
    resp = yield from self.session.post(endpoints.LOGIN, data=data, headers=self.headers)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\client.py", line 529, in __iter__
    resp = yield from self._coro
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\client.py", line 183, in _request
    conn = yield from self._connector.connect(req)
  File "C:\Users\Operator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 320, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]]
Cleaning up... Done.
Restarting in 2 seconds...
```

After this it repeats with increasing periods before restarts.

This is running on Windows Server 2016 with Python 3.5.1.

**Comment by jayktaylor** [comment]
You can try installing this SSL certificate and seeing if it makes a difference: https://support.comodo.com/index.php?/Knowledgebase/Article/GetAttachment/969/821026

**Comment by Augustaeum** [comment]
That solved the issue, thank you very much.

So that means that it was on my end then?

**Comment by arunesh90** [comment]
Yeah that means that it was on your end.
Your server was lacking a certificate from a major certificate authority

**Comment by Augustaeum** [comment]
How would I solve this issue in the future?

**Comment by imayhaveborkedit** [comment]
You install that cert again if whatever system you're using has this issue.
