### ISSUE TITLE
Unable to connect to channel

### ISSUE THREAD

**Issue by yoitsho** [Just-Some-Bots/MusicBot#283]
Anyone got a issue to this? The bot keeps trying to connect to the channel and then leaves repeatedly.
And sometimes I get that error.

An error has occured:

  Problem:  Cannot establish connection to voice chat.  Something may be                    blocking outgoing UDP connections.  
  Solution: This may be an issue with a firewall blocking UDP.  Figure out what             is blocking UDP and disable it.  It's most likely a system firewall             or overbearing anti-virus firewall.

**Comment by yoitsho** [comment]
Ive also tried disabling antivirus and firewall already

**Comment by Figworth** [comment]
@@Did you resolve this issue? My bot has started having the same issue. Running on a DigitalOcean Ubuntu server. Was working fine a month ago.

Tried wiping the bot and reinstalling, then wiped the server and went through the reinstall process. Same issue.

I can connect the bot to the server manually, and disabled UFW.

**Comment by Figworth** [comment]
New update: created a new server and the bot's able to join. Just one server that isn't working. Tried rescinding the invite and reissuing, no effect. Channel doesn't matter. Bot can join server via web app.

**Comment by Figworth** [comment]
Seems to have fixed itself? No idea what the problem solution was. Fixed seemed to happen when I created a new server > invited bot to new server > went back to old server > deleted new server > summoned bot. But who really knows.

**Comment by kizeren** [comment]
Started receiving this message today for one of the servers my bot is on.  Correctly connects to two other servers.  I can manually summon the bot but when trying to play music on the broken "server" it just outputs: 
`The bot is not in a voice channel.  Use !summon to summon it to your voice channel.`

`The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 386, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 234, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 600, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4004, reason = not found.`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 174, in _autojoin_channels
    player = await self.get_player(channel, create=True)
  File "/root/MusicBot/musicbot/bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/root/MusicBot/musicbot/bot.py", line 271, in get_voice_client
    "This may be an issue with a firewall blocking UDP.  "
musicbot.exceptions.HelpfulError: ('Cannot establish connection to voice chat.  Something may be blocking outgoing UDP connections.', "This may be an issue with a firewall blocking UDP.  Figure out what is blocking UDP and disable it.  It's most likely a system firewall or overbearing anti-virus firewall.  ")
Failed to join Music room`

This bot is running on a VPS with ample disk space and 1Gb connection to internet.   The server is running
`Linux ClouAtCost1 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

No firewalls are installed.

**Comment by strongestFairy** [comment]
Have just the same problem under Ubuntu.
After several re-invites and restarts of bot got the following in log:

> An error has occured:
> 
>   Problem:  Cannot establish connection to voice chat.  Something may be blocking outgoing UDP connections.
>   Solution: This may be an issue with a firewall blocking UDP.  Figure out what is blocking UDP and disable it.  It's most likely a system firewall or overbearing anti-virus firewall.
> 
> **Unclosed client session**
> **client_session: <aiohttp.client.ClientSession object at 0x7fd593521358>**
> **Cleaning up... Done.**
> **Restarting in 2 seconds...**
> **Connected!  Musicbot v1.9.5_1**

After that bot successfully reconnected

**Comment by Darx3104** [comment]
when you go into the music bot's folder if there is an windows batch filed named update_deps update it and try runbot again it worked for me but if it doesnt work or you dont have it i cant help much
