### ISSUE TITLE
Error when using ~summon

### ISSUE THREAD

**Issue by CoryManson** [Just-Some-Bots/MusicBot#285]
Just updated to the latest version of review, was a few weeks behind. Bot now throws an error when summoning. Anything I'm doing wrong?

```
[Command] 99258832047341568/Bryce (~summon)
Traceback (most recent call last):
  File "/home/musicbot/MusicBot/musicbot/bot.py", line 1913, in on_message
    response = await handler(**handler_kwargs)
  File "/home/musicbot/MusicBot/musicbot/bot.py", line 1310, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "/home/musicbot/MusicBot/musicbot/bot.py", line 363, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/musicbot/MusicBot/musicbot/bot.py", line 235, in get_voice_client
    s_id = self.ws.wait_for('VOICE_STATE_UPDATE', lambda d: d.get('user_id') == self.user.id)
AttributeError: 'WebSocketClientProtocol' object has no attribute 'wait_for'
```

**Comment by jayktaylor** [comment]
Update your dependencies.

**Comment by CoryManson** [comment]
Thanks Matey Potatey! All sorted.
