### ISSUE TITLE
Bot randomly skips tracks and crashes

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#286]
Bot randomly skips tracks without any errors and sometimes crashes and restarts

```
Task was destroyed but it is pending!
task: <Task pending coro=<_run_event() running at /usr/local/lib/python3.5/dist-packages/discord/client.py:245> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[gather.<locals>._done_callback(2)() at /usr/lib/python3.5/asyncio/tasks.py:634]>
Task was destroyed but it is pending!
task: <Task pending coro=<_run_event() running at /usr/local/lib/python3.5/dist-packages/discord/client.py:245> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.5/asyncio/futures.py:431, Task._wakeup()]> cb=[gather.<locals>._done_callback(5)() at /usr/lib/python3.5/asyncio/tasks.py:634]>
Cleaning up... Done.
Restarting in 2 seconds...
Connected!  Musicbot v1.9.5-review-2016.5.19

Bot:   987654321908765/meow#1234
Owner: 123456789012345/meow#4321

Server List:
- meow

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !mb_
  Default volume: 100%
  Skip threshold: 2 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

Attempting to autosummon...
Found owner in "📻 Radio", attempting to join...
Attempting connection...
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 69, in run
    f = compat.run_coroutine_threadsafe(coro, loop=self.ws.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 734, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 518, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 492, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 320, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Connection established.
Done!
Starting auto-playlist


```

And... After restart he not changes him status

**Comment by jayktaylor** [comment]
This is probably resolved. Regardless, it doesn't seem to be the bot's issue and is more an issue with Discord itself or the way that discord.py handles this shit.
