### ISSUE TITLE
Bot died after DS server changed region.

### ISSUE THREAD

**Issue by strongestFairy** [Just-Some-Bots/MusicBot#293]
Console output:

[### Servers] "PRAVDA Kantai Yo!~" changed regions: singapore -> frankfurt
[Debug] Voice websocket is CLOSING, reconnecting
[Debug] Voice websocket is CLOSING, reconnecting
[Debug] Voice websocket is CLOSING, reconnecting
[config:autopause] Unpausing
Exception in thread Thread-248:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 142, in run
    super().run()
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 100, in run
    self.player(data)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 621, in play_audio
    sent = self.socket.sendto(packet, (self.endpoint_ip, self.voice_port))
OSError: [Errno 9] Bad file descriptor

[Debug] Voice websocket is CLOSING, reconnecting
[Debug] Voice websocket is CLOSING, reconnecting

**Comment by strongestFairy** [comment]
Issue was resolved only after restart of bot.

**Comment by sameer** [comment]
Pleas close this issue if it has been resolved. Thanks!

**Comment by ImthePeach** [comment]
@strongestFairy can you close this issue please since you figured it out.
