### ISSUE TITLE
issued !mb_restart 

### ISSUE THREAD

**Issue by bdogrulz** [Just-Some-Bots/MusicBot#299]
i issued the command to restart the bot and now im stuck in a loop of `Traceback (most recent call last):

```
  File "run.py", line 163, in main
    m = MusicBot()
  File "/root/MusicBot/musicbot/bot.py", line 77, in __init__
    self.config = Config(config_file)
  File "/root/MusicBot/musicbot/config.py", line 79, in __init__
    self.delete_invoking = config.getboolean('MusicBot', 'DeleteInvoking', fallback=ConfigDefaults.delete_invoking)
  File "/usr/lib/python3.5/configparser.py", line 826, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 1152, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: yew
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbbfd2841d0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbbfd281ef0>
Cleaning up... Done.
Restarting in 10 seconds...
```

**Comment by jayktaylor** [comment]
Your `options.ini` has `DeleteInvoking = yew`. It should be `DeleteInvoking = yes`.
