### ISSUE TITLE
Unable to summon

### ISSUE THREAD

**Issue by ArmaWizard** [Just-Some-Bots/MusicBot#304]
Hello I have updated the bot to the most recent version and i've redone the config files, now when me, the owner, tries to summon the bot, I get the following error.

[Command] 100279965274116096/Merlijn (!summon)
Traceback (most recent call last):
  File "/schijf2/MusicBot/musicbot/bot.py", line 1913, in on_message
    response = await handler(**handler_kwargs)
  File "/schijf2/MusicBot/musicbot/bot.py", line 1310, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "/schijf2/MusicBot/musicbot/bot.py", line 363, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/schijf2/MusicBot/musicbot/bot.py", line 235, in get_voice_client
    s_id = self.ws.wait_for('VOICE_STATE_UPDATE', lambda d: d.get('user_id') == self.user.id)
AttributeError: 'WebSocketClientProtocol' object has no attribute 'wait_for'

**Comment by ArmaWizard** [comment]
ok im retarded already fixed it
