### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by daysofsummer** [Just-Some-Bots/MusicBot#308]
After being active for some hours, the bot crashes and goes offline, leaving this error:

```
RuntimeError: Event loop is closed
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe0f35842e8>
Traceback (most recent call last):
  File "run.py", line 157, in main
    MusicBot().run()
  File "/musicBot/musicbot/bot.py", line 409, in run
    return super().run(self.config.username, self.config.password)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line
602, in run
    self.loop.run_until_complete(self.start(email, password))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 314, in
run_until_complete
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 284, in
_check_closed
    raise RuntimeError('Event loop is closed')
```

**Comment by jayktaylor** [comment]
Closing this as it doesn't seem to be an issue anymore. Problems like this are usually down to Discord playing up, which will be looked at again in the next release version.
