### ISSUE TITLE
Failing to summon/join

### ISSUE THREAD

**Issue by dinckelman** [Just-Some-Bots/MusicBot#312]
When i try to summon the bot it spits out this in the channel 

`Traceback (most recent call last):
  File "D:\APPLICATIONS\Discord MusicBot\musicbot\bot.py", line 1913, in on_message
    response = await handler(**handler_kwargs)
  File "D:\APPLICATIONS\Discord MusicBot\musicbot\bot.py", line 1310, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "D:\APPLICATIONS\Discord MusicBot\musicbot\bot.py", line 363, in get_player
    voice_client = await self.get_voice_client(channel)
  File "D:\APPLICATIONS\Discord MusicBot\musicbot\bot.py", line 235, in get_voice_client
    s_id = self.ws.wait_for('VOICE_STATE_UPDATE', lambda d: d.get('user_id') == self.user.id)
AttributeError: 'WebSocketClientProtocol' object has no attribute 'wait_for'`

**Comment by link2110** [comment]
Please update your bot to the newest version. 

**Latest release 1.9.5.**
    `https://github.com/SexualRhinoceros/MusicBot/archive/1.9.5.zip`

**Comment by imayhaveborkedit** [comment]
Update your deps too.
