### ISSUE TITLE
 Python.h: No such file or directory

### ISSUE THREAD

**Issue by sideh** [Just-Some-Bots/MusicBot#317]
After following the instructions for Linux, I got to the test part and this happened. 3 hours later I have made no progress. From what I've googled, its seem to be a header issue or something wrong with PyNaCl?

Have removed and re-installed, python3-dev libpython and a few other things that some forums and sites have pointed out would fix the issue but has not for me.

```
ubuntu@ip-172-31-34-228:~/MusicBot$ sudo python3.5 run.py                                                                                                                            
No module named 'aiohttp'
Attempting to install dependencies...
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://github.com/Rapptz/discord.py/archive/async.zip (from -r requirements.txt (line 1))
  Downloading https://github.com/Rapptz/discord.py/archive/async.zip (441kB)
    100% |ââââââââââââââââââââââââââââââââ| 450kB 423kB/s                                                            
Collecting youtube_dl>=2016.4.24 (from -r requirements.txt (line 2))
  Downloading youtube_dl-2016.6.3-py2.py3-none-any.whl (1.3MB)
    100% |ââââââââââââââââââââââââââââââââ| 1.3MB 1.2MB/s                                                            
Collecting aiohttp<0.22.0,>=0.21.0 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Downloading aiohttp-0.21.6.tar.gz (528kB)
    100% |ââââââââââââââââââââââââââââââââ| 532kB 2.8MB/s                                                            
Collecting websockets==3.1 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Downloading websockets-3.1.tar.gz
Collecting PyNaCl==1.0.1 (from discord.py==0.10.0a0->-r requirements.txt (line 1))
  Downloading PyNaCl-1.0.1.tar.gz (2.7MB)
    100% |ââââââââââââââââââââââââââââââââ| 2.7MB 567kB/s                                                            
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 116, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/bdist_egg.py", line 161, in run
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/bdist_egg.py", line 147, in call_command
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/install_lib.py", line 10, in run
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/build_ext.py", line 66, in run
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/build_ext.py", line 178, in build_extension
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 154, in save_modules
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 243, in run_setup
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 273, in run
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 242, in runner
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 46, in _execfile
      File "/tmp/easy_install-29qubpfm/cffi-1.6.0/setup.py", line 192, in <module>
        # Check the build library
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/easy_install.py", line 1101, in run_setup
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 246, in run_setup
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 166, in save_modules
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 141, in resume
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 154, in save_modules
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 243, in run_setup
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 273, in run
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 242, in runner
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/sandbox.py", line 46, in _execfile
      File "/tmp/easy_install-29qubpfm/cffi-1.6.0/setup.py", line 192, in <module>
        # Check the build library
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-013jtq20/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/dist.py", line 269, in __init__
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/dist.py", line 313, in fetch_build_eggs
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/pkg_resources/__init__.py", line 826, in resolve
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/pkg_resources/__init__.py", line 1092, in best_match
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/pkg_resources/__init__.py", line 1104, in obtain
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/dist.py", line 380, in fetch_build_egg
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/easy_install.py", line 665, in easy_install
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/easy_install.py", line 695, in install_item
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/easy_install.py", line 876, in install_eggs
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/easy_install.py", line 1115, in build_and_install
      File "/usr/local/lib/python3.5/dist-packages/setuptools-22.0.5-py3.5.egg/setuptools/command/easy_install.py", line 1103, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-013jtq20/PyNaCl/

You may need to use sudo to install dependencies.
```

**Comment by sideh** [comment]
I'm using an AWS with Ubuntu 14.04 LTS. When I ran this it loaded

`sudo apt-get install libpython3.5-dev`

 but fails with loading the Opus lib's from what I can tell?

```
Cleaning up... Done.
Restarting in 2 seconds...
Traceback (most recent call last):
  File "run.py", line 161, in main
    from musicbot import MusicBot
  File "/home/ubuntu/MusicBot/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/home/ubuntu/MusicBot/musicbot/bot.py", line 37, in <module>
    load_opus_lib()
  File "/home/ubuntu/MusicBot/musicbot/opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
```

**Comment by link2110** [comment]
You seem to be missing an opus lib. 

`sudo apt-get install libopus0`

**Comment by girugamoz** [comment]
FYI: I'm getting the error message from OP when using the docker image. Image home page states it was last changed 2 months ago, so I guess it needs updating.

**Comment by arunesh90** [comment]
We're aware that the docker image is very outdated.
@Sidesplitter said that he would make a pr for it(#275). But he seems inactive

**Comment by sideh** [comment]
This is fixed now. 

Thanks @link2110 for your input, helped me out!
