### ISSUE TITLE
!play command send_typing exception

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#326]
Sometimes bot returns exception and cancels adding song to queue

``` python
Traceback (most recent call last):
  File "/MusicBot3/musicbot/bot.py", line 1916, in on_message
    response = await handler(**handler_kwargs)
  File "/MusicBot3/musicbot/bot.py", line 851, in cmd_play
    await self.send_typing(channel)
  File "/MusicBot3/musicbot/bot.py", line 520, in send_typing
    return await super().send_typing(destination)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 894, in send_typing
    yield from utils._verify_successful_response(response)
  File "/usr/local/lib/python3.5/dist-packages/discord/utils.py", line 238, in _verify_successful_response
    raise HTTPException(response, message, text)
discord.errors.HTTPException: Bad Gateway (status code: 502)
```

I updated discord.py, but it's not helps.

Latest version from `review` branch

**Comment by brawaru** [comment]
Yes, I see `Bad Gateway`, but I think it's should be handled

**Comment by imayhaveborkedit** [comment]
This is partially a lib issue for not handling 502 errors on all requests, but I can fix this in the bot.

**Comment by imayhaveborkedit** [comment]
This should be resolved with a recent discord.py update.
