### ISSUE TITLE
Can't start bots after update

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#342]
```
Traceback (most recent call last):
  File "run.py", line 163, in main
    m = MusicBot()
  File "/media/dafri/Additional Disk/Main/Dev/Python/Tasher/musicbot/bot.py", line 91, in __init__
    self.headers['user-agent'] += ' MusicBot/%s' % BOTVERSION
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 244, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'headers'
```

**Comment by imayhaveborkedit** [comment]
Update your bot.

**Comment by brawaru** [comment]
Oh, found the problem, conflicts in `./musicbot/bot.py` when trying to do `git pull`. I had to reset local repository to remote state..
Yes, I did it! Now all works. Thanks! 😊
