### ISSUE TITLE
Traceback?

### ISSUE THREAD

**Issue by mitch619911** [Just-Some-Bots/MusicBot#344]
```
Traceback (most recent call last):
  File "run.py", line 161, in main
    from musicbot import MusicBot
  File "C:\Users\Mitch\Desktop\Eclipse Java Coding\Discord\boo\music bot 2222222222222222222\g\MusicBot\musicbot\__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "C:\Users\Mitch\Desktop\Eclipse Java Coding\Discord\boo\music bot 2222222222222222222\g\MusicBot\musicbot\bot.py", line 38, in <module>
    load_opus_lib()
  File "C:\Users\Mitch\Desktop\Eclipse Java Coding\Discord\boo\music bot 2222222222222222222\g\MusicBot\musicbot\opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
Cleaning up... Done.
Restarting in 2 seconds...
```

**Comment by imayhaveborkedit** [comment]
This shouldn't happen as discord.py comes with libopus on windows now.  Run update_deps.bat to make sure you have a recent version.

**Comment by mitch619911** [comment]
Yep have ran that still error.

`Traceback (most recent call last):
  File "run.py", line 161, in main
    from musicbot import MusicBot
  File "C:\Users\Mitch\Desktop\Eclipse Java Coding\Discord\boo\music bot 2222222222222222222\g\MusicBot\musicbot\__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "C:\Users\Mitch\Desktop\Eclipse Java Coding\Discord\boo\music bot 2222222222222222222\g\MusicBot\musicbot\bot.py", line 38, in <module>
    load_opus_lib()
  File "C:\Users\Mitch\Desktop\Eclipse Java Coding\Discord\boo\music bot 2222222222222222222\g\MusicBot\musicbot\opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
Cleaning up... Done.
Restarting in 8 seconds...`

**Comment by mitch619911** [comment]
discord.py? - I can't seem to find that file, maybe thats why it errors? O.o

**Comment by imayhaveborkedit** [comment]
Its not a file, its the discord library the bot uses.  Like I told you before, run `update_deps.bat`.  Opus comes with the library so you shouldn't be getting that error.

**Comment by mitch619911** [comment]
I have ran `update_deps.bat` :/

**Comment by kingcatdaan** [comment]
im running on linux and after i updated i got client session still active restarting in ...

**Comment by ValeTheVioletMote** [comment]
From the help channel -

Jayden - Today at 1:05 PM
I have no idea tbh. You can try manually putting one of the opus dlls into the main musicbot folder though:

64 bit https://github.com/SexualRhinoceros/MusicBot/blob/ea5e0daebd384ec8a14c9a585da399934e2a6252/libopus-0.x64.dll?raw=true

32 bit https://github.com/SexualRhinoceros/MusicBot/blob/ea5e0daebd384ec8a14c9a585da399934e2a6252/libopus-0.x86.dll?raw=true
(or both)

**Comment by jayktaylor** [comment]
By the inactivity, assuming @mitch619911 has solved their problem. Updating (the bot +) dependencies should give you the required opus dlls.
