### ISSUE TITLE
This comes in the console and then the music stops

### ISSUE THREAD

**Issue by omerbadawy11** [Just-Some-Bots/MusicBot#345]
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\bot.py", line 412, in on_player_finished_playing
    info = await self.downloader.safe_extract_info(player.playlist.loop, song_url, download=False, process=False)
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\downloader.py", line 85, in safe_extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.safe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 691, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 550, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 503, in trouble
    self.to_stderr(message)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 457, in to_stderr
    self._write_string(output, self._err_file)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 436, in _write_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 1257, in write_string
    if _windows_write_string(s, out):
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 1241, in _windows_write_string
    raise OSError('Failed to write string')
OSError: Failed to write string
```

**Comment by imayhaveborkedit** [comment]
This happens rarely and i'm not sure why.  Its youtube-dl's fault but i'll see if I can hide this error since its just from failing to write something to the console.

**Comment by omerbadawy11** [comment]
I just got this and the music stopped .. again . this errors comes a lot

```
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py:230> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 237, in poll_voice_ws
    yield from self.ws.poll_event()
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\gateway.py", line 562, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[Debug] Voice websocket is CLOSED, reconnecting
Error disconnecting during reconnect
Traceback (most recent call last):
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\player.py", line 286, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\bot.py", line 294, in reconnect_voice_client
    await vc.disconnect()
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 258, in disconnect
    yield from self.ws.close()
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\gateway.py", line 572, in close
    yield from super().close(code, reason)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 239, in close
    self.worker, self.timeout, loop=self.loop)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 386, in wait_for
    return fut.result()
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 411, in run
    msg = yield from self.read_message()
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 433, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 488, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 523, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 509, in readexactly
    block = yield from self.read(n)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 482, in read
    yield from self._wait_for_data('read')
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 423, in _wait_for_data
    yield from self._waiter
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\selector_events.py", line 664, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\player.py:279> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\player.py", line 286, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\player.py", line 290, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\bot.py", line 302, in reconnect_voice_client
    new_vc = await self.get_voice_client(vc.channel)
  File "C:\Users\AsRock\Desktop\MusicBot-master\MusicBot-master\musicbot\bot.py", line 230, in get_voice_client
    voice_data = await asyncio.wait_for(_voice_data, timeout=10, loop=self.loop)
  File "C:\Users\AsRock\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by imayhaveborkedit** [comment]
This seems to be a library issue with handling disconnecting from voice.  The bot hasn't properly disconnected from voice chat so trying to reconnect to it fails.

**Comment by imayhaveborkedit** [comment]
Update your deps, this should be fixed now.
