### ISSUE TITLE
Can't run bot.

### ISSUE THREAD

**Issue by Kiliope** [Just-Some-Bots/MusicBot#357]
No module named 'aiohttp'
Attempting to install dependencies...
Traceback (most recent call last):
  File "run.py", line 161, in main
    from musicbot import MusicBot
  File "C:\Users\Lewis\Desktop\New folder (2)\MusicBot\musicbot__init__.py", li
ne 1, in <module>
    from .bot import MusicBot
  File "C:\Users\Lewis\Desktop\New folder (2)\MusicBot\musicbot\bot.py", line 7,
 in <module>
    import aiohttp
ImportError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 221, in <module>
    main()
  File "run.py", line 179, in main
    err = PIP.run_install('--upgrade -r requirements.txt')
  File "run.py", line 71, in run_install
    return cls.run("install %s%s" % ('-q ' if quiet else '', cmd), check_output)

  File "run.py", line 24, in run
    raise RuntimeError("Could not import pip.")
RuntimeError: Could not import pip.

C:\Users\Lewis\Desktop\New folder (2)\MusicBot>

**Comment by gfrewqpoiu** [comment]
pip doesn't seem to be installed on your Windows Machine. This is a package manager for python. You need to reinstall Python3.5 with Pip

**Comment by Kiliope** [comment]
I did check that and it said it was installed, I'll uninstall and reinstall Python tomorrow and see if that works, Thanks.

**Comment by Kiliope** [comment]
It works now thanks
