### ISSUE TITLE
Bot randomly has stopped working

### ISSUE THREAD

**Issue by FineNerds** [Just-Some-Bots/MusicBot#365]
The bot was working fine until someone added another song, and it randomly spit this error, and now it won't do anything but return this error... I tried updating youtube_dl, nothing changed. Tried redownloading the bot and nothing changed.

Error: 

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\FineNerds\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\FineNerds\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\FineNerds\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\FineNerds\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
 (caused by ExtractorError("Could not find JS function 'ur'",))
```

**Comment by Eufranio** [comment]
Same here.

**Comment by huntintiger1004** [comment]
Getting essentially the same error as well.

**Comment by imayhaveborkedit** [comment]
Youtube changed something and youtube-dl needs to be updated to fix it.

**Comment by rbxcbd** [comment]
You can try manually updating youtube-dl by downloading its source then pasting it into the Lib\site-packages. It worked for me.

**Comment by imayhaveborkedit** [comment]
^ Please no one do this.  Update youtube-dl properly, run update-deps.bat, or `pip install --upgrade youtube-dl` (may be `pip3` or `pip3.5` on some systems)

**Comment by yoczed** [comment]
same error as well, i have no idea how to update youtube-dl despite the instructions

**Comment by FineNerds** [comment]
run update_deps.bat
