### ISSUE TITLE
Error with Youtube

### ISSUE THREAD

**Issue by Walven** [Just-Some-Bots/MusicBot#372]
Hi !

When I try to play a Youtube video, an error occurs :

`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Killian\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Killian\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Killian\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Killian\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 239, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
 (caused by ExtractorError("Could not find JS function 'ur'",))`

How can i fix it ?

**Comment by rome1245** [comment]
I am having the same issue, I wonder if this is a widespread issue? Any help would be appreciated.

**Comment by rome1245** [comment]
FIXED IT, run update deps as admin and it will update and fix it

**Comment by Bomberlux** [comment]
This did not help me at all. I updated the bot with update deps, but now my bots don't even log in anymore...

**Comment by rome1245** [comment]
Are you getting a new error?

**Comment by Bomberlux** [comment]
```
Traceback (most recent call last):
  File "run.py", line 204, in <module>
    main()
  File "run.py", line 182, in main
    MusicBot().run()
  File "C:\Users\Kevin\Desktop\Minecraft\Transformice\Bot LMR\MusicBot-1.9.5rc5\musicbot\bot.py", line 67, in __init__
    self.voice_clients = {}
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 258, in __setattr__
    return setattr(self.connection, name, value)
AttributeError: can't set attribute
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x01B767B0>

C:\Users\Kevin\Desktop\Minecraft\Transformice\Bot LMR\MusicBot-1.9.5rc5>
```

**Comment by rome1245** [comment]
Hmmm, not too familiar with that error, double check the options file, you may need to re create the bot to ensure it didnt go change the original files

**Comment by Bomberlux** [comment]
I checked the options file, nothing changed there, and I even rebooted my pc, since it said that the client session was unclosed...
Does it have to do with the fact that I upgraded my python to the latest version?

**Comment by Bomberlux** [comment]
I completely remade the bots, it works now. It works completely differently than before now, lol. At least it works and I copied the options/permissions

**Comment by jayktaylor** [comment]
**Resolved.** Fixed by updating your dependencies.

**Comment by Simondd50** [comment]
rome1245 OMG i just made a user on the page just to write to you WTF the is DEPS ?!?!?!?! "update deps" pleas mate more info plx

**Comment by jayktaylor** [comment]
@Simondd50 this is an old issue. This may be relevant to you: #1072
