### ISSUE TITLE
did something change in the way that it plays from autoplaylist

### ISSUE THREAD

**Issue by bdogrulz** [Just-Some-Bots/MusicBot#374]
so i updated the bot and the requirements  and now my bot will only play a handfull of songs and this is what i get from the bot `ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
 (caused by ExtractorError("Could not find JS function 'ur'",))
[Info] Removing unplayable song from autoplaylist: http://www.youtube.com/watch?v=mhsf7K6h7SY
` this is running on linux

**Comment by arunesh90** [comment]
![image](https://cloud.githubusercontent.com/assets/5787588/16335849/51a01b7c-3a09-11e6-9f88-3a5ddac69f41.png)

**Comment by jayktaylor** [comment]
**Resolved.** Fix by updating your dependencies.
