### ISSUE TITLE
Music Bot does not realize its in voice channel

### ISSUE THREAD

**Issue by kchoe147** [Just-Some-Bots/MusicBot#386]
Attempting to autosummon...
Found owner in "pls work", attempting to join...
Traceback (most recent call last):
  File "C:\Users\kchoe\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "C:\Users\kchoe\Desktop\MusicBot\musicbot\bot.py", line 696, in on_ready
    owner_vc = await self._auto_summon()
  File "C:\Users\kchoe\Desktop\MusicBot\musicbot\bot.py", line 148, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "C:\Users\kchoe\Desktop\MusicBot\musicbot\bot.py", line 1311, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "C:\Users\kchoe\Desktop\MusicBot\musicbot\bot.py", line 354, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\kchoe\Desktop\MusicBot\musicbot\bot.py", line 241, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "C:\Users\kchoe\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 191, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

^^this is when i first turn on the bot
then when i try to play a song it says 
[Command] 116106111936888835/Kevin (!play kill yourself)
<class 'musicbot.exceptions.CommandError'>: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

**Comment by shmanginator** [comment]
This just started happening to me tonight as well.

Attempting to autosummon...
Found owner in "League", attempting to join...
Traceback (most recent call last):
  File "C:\Users\Collin\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Collin\Desktop\MusicBot-review\MusicBot\musicbot\bot.py", line 696, in on_ready
    owner_vc = await self._auto_summon()
  File "C:\Users\Collin\Desktop\MusicBot-review\MusicBot\musicbot\bot.py", line 148, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "C:\Users\Collin\Desktop\MusicBot-review\MusicBot\musicbot\bot.py", line 1311, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "C:\Users\Collin\Desktop\MusicBot-review\MusicBot\musicbot\bot.py", line 354, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\Collin\Desktop\MusicBot-review\MusicBot\musicbot\bot.py", line 241, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "C:\Users\Collin\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 191, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

**Comment by sbdonslaught** [comment]
Change the zip link in requirements.txt to `discord.py[voice]` and update deps

**Comment by kchoe147** [comment]
copying cffi\ffiplatform.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\lock.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\model.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\recompiler.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\setuptools_ext.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_cpy.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\vengine_gen.py -> build\lib.win-amd64-3.5\cffi
    copying cffi\verifier.py -> build\lib.win-amd64-3.5\cffi
    copying cffi__init__.py -> build\lib.win-amd64-3.5\cffi
    copying cffi_cffi_include.h -> build\lib.win-amd64-3.5\cffi
    copying cffi\parse_c_type.h -> build\lib.win-amd64-3.5\cffi
    copying cffi_embedding.h -> build\lib.win-amd64-3.5\cffi
    running build_ext
    building '_cffi_backend' extension
    error: Unable to find vcvarsall.bat

```
----------------------------------------
```

Command "C:\Users\kchoe\AppData\Local\Programs\Python\Python35\python.exe -c "import setuptools, tokenize;**file**='C:\Users\kchoe\AppData\Local\Temp\pip-build-62lt64z7\cffi\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record C:\Users\kchoe\AppData\Local\Temp\pip-sq1qmzoa-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\kchoe\AppData\Local\Temp\pip-build-62lt64z7\cffi
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\kchoe\Desktop\MusicBot>

**Comment by kchoe147** [comment]
this is what i got when i did that

**Comment by sbdonslaught** [comment]
Add 'cffi==1.6.0' on a new line

**Comment by kchoe147** [comment]
onto requirements?

**Comment by sbdonslaught** [comment]
Yea

**Comment by kchoe147** [comment]
it worked! thank you so much

**Comment by SgtZombie870** [comment]
dab

**Comment by z1xy** [comment]
Change link to what?
