### ISSUE TITLE
RuntimeError: Could not import pip.

### ISSUE THREAD

**Issue by EinSystemFehler** [Just-Some-Bots/MusicBot#387]
Please Help me

```
root@vps:~/MusicBot# python3.5 run.py
No module named 'aiohttp'
Attempting to install dependencies...
Traceback (most recent call last):
  File "run.py", line 161, in main
    from musicbot import MusicBot
  File "/root/MusicBot/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/root/MusicBot/musicbot/bot.py", line 7, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 221, in <module>
    main()
  File "run.py", line 179, in main
    err = PIP.run_install('--upgrade -r requirements.txt')
  File "run.py", line 71, in run_install
    return cls.run("install %s%s" % ('-q ' if quiet else '', cmd), check_output)
  File "run.py", line 24, in run
    raise RuntimeError("Could not import pip.")
RuntimeError: Could not import pip.

```

**Comment by jayktaylor** [comment]
Update your dependencies. Make sure pip is actually installed, too.
