### ISSUE TITLE
Error playing certain songs

### ISSUE THREAD

**Issue by suuoh** [Just-Some-Bots/MusicBot#392]
I get the following error when I try to play certain videos. It does not always happen but I cannot determine which videos cause it and which do not. I have also updated the bot and dependencies as well (unless I used the incorrect commands to do so).

`[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'vr'
 (caused by ExtractorError("Could not find JS function 'vr'",))`

**Comment by arunesh90** [comment]
![image](https://cloud.githubusercontent.com/assets/5787588/16449157/017ced3c-3df6-11e6-9cba-9eff2fe876a3.png)

**Comment by suuoh** [comment]
Apparently I didnt update dependencies with the correct Python version...
