### ISSUE TITLE
Whenever I request a song with !play, this error is sent in chat

### ISSUE THREAD

**Issue by AgrippaDaRippa** [Just-Some-Bots/MusicBot#396]
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\George\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\George\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\George\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\George\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 239, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'wr'
 (caused by ExtractorError("Could not find JS function 'wr'",))
```

help me please

**Comment by nardavin** [comment]
I am getting the same error. This is a recent problem, as it wasn't happening the last time I used the bot (maybe a week ago). Possibly some change in youtube's side of things?

**Comment by jayktaylor** [comment]
**Solution:** Update your dependencies (`update_deps.bat`)

**Comment by AgrippaDaRippa** [comment]
thanks, cutie; if anybody has this issue, go into the music bot folder and look for update_deps.bat and run it as administrator.
