### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by dolph1nn** [Just-Some-Bots/MusicBot#407]
Upon starting the bot, I get this:

Traceback (most recent call last):
  File "run.py", line 163, in main
    m = MusicBot()
  File "C:\Users\madbo_000\Desktop\Discord Music Bot\musicbot\bot.py", line 75, in **init**
    self.config = Config(config_file)
  File "C:\Users\madbo_000\Desktop\Discord Music Bot\musicbot\config.py", line 14, in **init**
    if not config.read(config_file, encoding='utf-8'):
  File "C:\Users\madbo_000\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:\Users\madbo_000\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 1107, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'config/options.ini'
        [line 18]: 'MjAwMDcyMjAxNzU0NTA5MzEy.Cl39vQ.GqB2hSdduDZ5XK6eFOC-SJ6UypI\n'

C:\Users\madbo_000\Desktop\Discord Music Bot>

I tried reinstalling, but it still happens. Any help is appreciated.

**Comment by dan2wik** [comment]
What are you using to edit the config?

**Comment by jayktaylor** [comment]
Check line 18 of your options.ini. You have a parsing error, meaning you've done something wrong on that line that is making `configparser` throw a fit.

**Comment by ghost** [comment]
You may want to remove your access token, I believe that is a access token for your discord bot. If it is your access token, re-copy and paste the access token that Discord gave you.

**Comment by vladfrangu** [comment]
Its probably the \n at the end that causes everything. Remove that, and try again
