### ISSUE TITLE
Problem at starting

### ISSUE THREAD

**Issue by Maarian** [Just-Some-Bots/MusicBot#414]
Traceback (most recent call last):
  File "run.py", line 163, in main
    m = MusicBot()
  File "C:\Users\Mariano PC\MusicBot-master\musicbot\bot.py", line 96, in **init**
    self.http.user_agent += ' MusicBot/%s' % BOTVERSION
  File "C:\Users\Mariano PC\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 234, in **getattr**
    raise AttributeError(msg.format(self.**class**, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'http'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x047B4750>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x047C9570>

C:\Users\Mariano PC\MusicBot-master>

This issue after updating, thx for the help

**Comment by imayhaveborkedit** [comment]
You need to update your dependencies.  That would be running `update_deps.bat` in the musicbot folder.
