### ISSUE TITLE
ERROR: Signature extraction failed: Traceback

### ISSUE THREAD

**Issue by Nato9393** [Just-Some-Bots/MusicBot#425]
Certain songs that the bot has played before no longer play it always sends back this ERROR messege.

Could not extract information from https://www.youtube.com/watch?v=I5iYFMIbUec&index=2&list=FLhtCWkoi-y2tui26mwLDxRw

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Nato\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Nato\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Nato\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Nato\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'tr'
 (caused by ExtractorError("Could not find JS function 'tr'",))

I try to go to this "C" location but it does not exist. Any help or advice is ggreatly appreciated. Thanks!

**Comment by jayktaylor** [comment]
Use version 1.9.5_2 and then update your dependencies.
