### ISSUE TITLE
subprocess and posixsubprocess aren't importing and bot isn't starting

### ISSUE THREAD

**Issue by spiral6** [Just-Some-Bots/MusicBot#429]
Running `python3 run.py` gives me this issue. Python version is 3.5.1, running on Raspbian Jessie, FFmpeg and x264 is installed. 

```
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import subprocess
  File "/usr/local/lib/python3.5/subprocess.py", line 437, in <module>
    import _posixsubprocess
ImportError: /usr/local/lib/python3.5/lib-dynload/_posixsubprocess.cpython-35m-arm-linux-gnueabihf.so: file too short
```

**Comment by spiral6** [comment]
Fixed it by fixing perms... however, there seems to be a new issue. Depending on where the user is currently located, the bot will try to find and execute on that location.

i.e. the bot is located on /home/pi/musicbot

`pi@raspberrypi:~ $ python3 

Fixing this by changing to directory in run.sh.
