### ISSUE TITLE
Anyone managed to get working on Centos / Redhat?

### ISSUE THREAD

**Issue by m8wtf** [Just-Some-Bots/MusicBot#456]
I'm trying to get this to work on a Centos 7 VPS, I've managed to install python 3.5.2, latest pip version, git, ffmpeg, opus, libffi, and libsodium and the odd dev package but now I'm stumped as to what the problem may be. 

I had a google search for the error that came up and it said it was due to not having the python dev package, I searched for the dev kit/package but couldn't find a new version of it, could someone give some advice.

I get the same error when trying to run 'pip3.5 install --upgrade -r requirements.txt' and 'python3.5 run.py' 

> [root@centos MusicBot]# pip3.5 install --upgrade -r requirements.txt
> Ignoring cffi: markers "sys_platform == 'win32'" don't match your environment
> Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
>   Using cached discord.py-0.10.0.zip
> Collecting youtube_dl (from -r requirements.txt (line 2))
>   Using cached youtube_dl-2016.7.26.2-py2.py3-none-any.whl
> Requirement already up-to-date: pip in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
> Collecting aiohttp<0.22.0,>=0.21.0 (from discord.py[voice]->-r requirements.txt (line 1))
>   Using cached aiohttp-0.21.6.tar.gz
> Collecting websockets==3.1 (from discord.py[voice]->-r requirements.txt (line 1))
>   Using cached websockets-3.1.tar.gz
> Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 1))
>   Using cached PyNaCl-1.0.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing`libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing`libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     Package libffi was not found in the pkg-config search path.
>     Perhaps you should add the directory containing `libffi.pc'
>     to the PKG_CONFIG_PATH environment variable
>     No package 'libffi' found
>     c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
>      #include <ffi.h>
>                      ^
>     compilation terminated.
>     Traceback (most recent call last):
>       File "/usr/local/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
>         extra_postargs)
>       File "/usr/local/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
>         spawn(cmd, dry_run=self.dry_run)
>       File "/usr/local/lib/python3.5/distutils/spawn.py", line 36, in spawn
>         _spawn_posix(cmd, search_path, dry_run=dry_run)
>       File "/usr/local/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
>         % (cmd, exit_status))
>     distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/usr/local/lib/python3.5/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 174, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/usr/local/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-uuec_bhm/cffi-1.7.0/setup.py", line 192, in <module>
    # Check the build library
  File "/usr/local/lib/python3.5/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1064, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-uuec_bhm/cffi-1.7.0/setup.py", line 192, in <module>
    # Check the build library
  File "/usr/local/lib/python3.5/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-7pviivd4/PyNaCl/setup.py", line 259, in <module>
    "Programming Language :: Python :: 3.5",
  File "/usr/local/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 640, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 670, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 850, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1066, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7pviivd4/PyNaCl/
You have mail in /var/spool/mail/root
[root@centos MusicBot]# python3.5 run.py
No module named 'aiohttp'
Attempting to install dependencies...
Ignoring cffi: markers "sys_platform == 'win32'" don't match your environment
Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
  Using cached discord.py-0.10.0.zip
Collecting youtube_dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2016.7.26.2-py2.py3-none-any.whl
Requirement already up-to-date: pip in /usr/local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Collecting aiohttp<0.22.0,>=0.21.0 (from discord.py[voice]->-r requirements.txt (line 1))
  Using cached aiohttp-0.21.6.tar.gz
Collecting websockets==3.1 (from discord.py[voice]->-r requirements.txt (line 1))
  Using cached websockets-3.1.tar.gz
Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing`libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing`libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/local/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/local/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/local/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/usr/local/lib/python3.5/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 174, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/usr/local/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-9enlvgsw/cffi-1.7.0/setup.py", line 192, in <module>
    # Check the build library
  File "/usr/local/lib/python3.5/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1064, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in run_setup
    raise
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 273, in run
    return func()
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-9enlvgsw/cffi-1.7.0/setup.py", line 192, in <module>
    # Check the build library
  File "/usr/local/lib/python3.5/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-t2uv_5ir/PyNaCl/setup.py", line 259, in <module>
    "Programming Language :: Python :: 3.5",
  File "/usr/local/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 640, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 670, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 850, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1066, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t2uv_5ir/PyNaCl/

*edit, suddenly a lot easier to read now and can see it's not finding libfii. Still curious if anyone else has it running though and can help me.

**Comment by m8wtf** [comment]
I've pretty much got it working now :smiley: only the 429 error for too many requests which I think is due youtube blocking the IP on my VPS.

The problem was mostly with libfii and all the dependencies earlier and it installing in the wrong place, after reconfiguring and installing a bunch of shit my bot is online http://i.imgur.com/hutNgOQ.png

**Comment by dreamloud-zz** [comment]
I fixed this in my revision https://github.com/jadissa/MusicBot/commit/92a3f29194ddbed458a9b8e5a796bfa1f42cb686

**Comment by jadissa** [comment]
Grr... wrong link. Check this one: https://github.com/jadissa/MusicBot/commit/c6f862b567cbd5fe79527a93d45b3caa4d092892
