### ISSUE TITLE
MusicBot not starting under Ubuntu 16.04

### ISSUE THREAD

**Issue by foxt** [Just-Some-Bots/MusicBot#474]
I run `python3 run.py` under the terminal, and it says
`lmgn@blackandwhite:~/Documents/musicBot/MusicBot$ python3 run.py`
`No module named 'aiohttp'`
`Attempting to install dependencies...`
`lmgn@blackandwhite:~/Documents/musicBot/MusicBot$`

I'm on Python 3.5.2 under Ubuntu 16.04 LTS

EDIT: I've just decided to scrap running Ubuntu. It works fine now (under W8.1)

**Comment by jayktaylor** [comment]
Follow the [Installation Guide for Ubuntu](https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions) properly.

**Comment by foxt** [comment]
`
`Deleting` old audio cache
Attempting to autojoin Music Lobby [96kbps] in LMGN Lounge
Attempting connection...
Traceback (most recent call last):
  File "/home/lmgn/Documents/musicBot/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (1/3)...
Attempting connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 602, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4002, reason = invalid server.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lmgn/Documents/musicBot/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 234, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 605, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4002, reason = invalid server.
Failed to connect, retrying (2/3)...
Attempting connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 602, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4002, reason = invalid server.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lmgn/Documents/musicBot/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 234, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 605, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4002, reason = invalid server.
Failed to connect, retrying (3/3)...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 602, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4002, reason = invalid server.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lmgn/Documents/musicBot/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 234, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 605, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4002, reason = invalid server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lmgn/Documents/musicBot/MusicBot/musicbot/bot.py", line 174, in _autojoin_channels
    player = await self.get_player(channel, create=True)
  File "/home/lmgn/Documents/musicBot/MusicBot/musicbot/bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/lmgn/Documents/musicBot/MusicBot/musicbot/bot.py", line 271, in get_voice_client
    "This may be an issue with a firewall blocking UDP.  "
musicbot.exceptions.HelpfulError: ('Cannot establish connection to voice chat.  Something may be blocking outgoing UDP connections.', "This may be an issue with a firewall blocking UDP.  Figure out what is blocking UDP and disable it.  It's most likely a system firewall or overbearing anti-virus firewall.  ")
Failed to join Music Lobby [96kbps]

^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[Aheeeeeeeeeeeeeeeelp^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^A^A
`

**Comment by pogoKA** [comment]
are u fix? i same get error

**Comment by kingcatdaan** [comment]
this is my error log in the non expert mode
Connecting...
An error has occured:

  Problem:  Bot cannot login, bad credentials.
  Solution: Fix your Email or Password or Token in the options file.  Remember              that each field should be on their own line.

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9ece701518>
root@debian-512mb-ams2-01:/usr/MusicBotNoToken# tmux
[exited]
root@debian-512mb-ams2-01:/usr/MusicBotNoToken# tmux new -s bot
[exited]
root@debian-512mb-ams2-01:/usr/MusicBotNoToken# python3.5 run.py
Connecting...
An error has occured:

  Problem:  Bot cannot login, bad credentials.
  Solution: Fix your Email or Password or Token in the options file.  Remember              that each field should be on their own line.

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f02076f6518>

**Comment by kingcatdaan** [comment]
it sais debian but it is ubuntu 16.04

**Comment by jayktaylor** [comment]
@kingcatdaan The issue here is unrelated to yours. If you have an issue, make a new one, rather than hijack this thread.

**Comment by jayktaylor** [comment]
This should fix itself by changing your server's voice region.
