### ISSUE TITLE
Error sys_platform

### ISSUE THREAD

**Issue by dente** [Just-Some-Bots/MusicBot#483]
Hello,
I followed scrupulously "Installation guide for Ubuntu 14.04 and other versions" but I get an error that appears is the second time that the manipulations and each time the same mistake. Does he have there a solution?

I use an OVH server Ubuntu 16.04 Server (64-bit)

:~/MusicBot# python3.5 run.py
No module named 'aiohttp'
Attempting to install dependencies...
Ignoring cffi: markers "sys_platform == 'win32'" don't match your environment
Collecting discord.py[voice](from -r requirements.txt %28line 1%29)
  Using cached discord.py-0.11.0.zip
Collecting youtube_dl (from -r requirements.txt (line 2))
  Using cached youtube_dl-2016.8.1-py2.py3-none-any.whl
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (f                                                                                                                                                             rom -r requirements.txt (line 3))
Collecting aiohttp<0.22.0,>=0.21.0 (from discord.py[voice]->-r requirements.txt                                                                                                                                                              (line 1))
  Using cached aiohttp-0.21.6.tar.gz
Collecting websockets==3.1 (from discord.py[voice]->-r requirements.txt (line 1)                                                                                                                                                             )
  Using cached websockets-3.1.tar.gz
Collecting PyNaCl==1.0.1 (from discord.py[voice]->-r requirements.txt (line 1))
  Using cached PyNaCl-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:

```
    No working compiler found, or bogus compiler options
    passed to the compiler from Python's distutils module.
    See the error messages above.
    (If they are about -mno-fused-madd and you are on OS/X 10.8,
    see http://stackoverflow.com/questions/22313407/ .)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              156, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              197, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              246, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              276, in run
    return func()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              245, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-3vzxh1xi/cffi-1.7.0/setup.py", line 111, in <modul                                                                                                                                                             e>

  File "/tmp/easy_install-3vzxh1xi/cffi-1.7.0/setup.py", line 65, in ask_sup                                                                                                                                                             ports_thread

  File "/tmp/easy_install-3vzxh1xi/cffi-1.7.0/setup.py", line 52, in no_work                                                                                                                                                             ing_compiler_found

SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_insta                                                                                                                                                             ll.py", line 1100, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              249, in run_setup
    raise
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              197, in setup_context
    yield
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              168, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              143, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/_vendor/six.py"                                                                                                                                                             , line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              156, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              197, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              246, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              276, in run
    return func()
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              245, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line                                                                                                                                                              47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-3vzxh1xi/cffi-1.7.0/setup.py", line 111, in <modul                                                                                                                                                             e>

  File "/tmp/easy_install-3vzxh1xi/cffi-1.7.0/setup.py", line 65, in ask_sup                                                                                                                                                             ports_thread

  File "/tmp/easy_install-3vzxh1xi/cffi-1.7.0/setup.py", line 52, in no_work                                                                                                                                                             ing_compiler_found

SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-nu6ysvdp/PyNaCl/setup.py", line 259, in <module>
    "Programming Language :: Python :: 3.5",
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 348                                                                                                                                                             , in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 394                                                                                                                                                             , in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", l                                                                                                                                                             ine 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", l                                                                                                                                                             ine 1098, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", l                                                                                                                                                             ine 1110, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 461                                                                                                                                                             , in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_insta                                                                                                                                                             ll.py", line 664, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_insta                                                                                                                                                             ll.py", line 694, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_insta                                                                                                                                                             ll.py", line 875, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_insta                                                                                                                                                             ll.py", line 1114, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_insta                                                                                                                                                             ll.py", line 1102, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with 1

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nu                                                                                                                                                             6ysvdp/PyNaCl/t

**Comment by imayhaveborkedit** [comment]
```
No working compiler found
```

You don't have a compiler bub.  The instructions have you install one, which you seem to have failed to do properly.  `build-essential` has that, its the first line in the tutorial with installing the system dependencies.

**Comment by dente** [comment]
OK thanks ! It's very strange I had half the order yet. Thank you so much for your help it works perfectly!
