### ISSUE TITLE
Only able to play one song before the bot stops working correctly.

### ISSUE THREAD

**Issue by Lutezify** [Just-Some-Bots/MusicBot#494]
I am able to play a single song from YouTube. but as soon as that song ends, the bot will not longer play any other songs afterwards (regardless of there being a few songs left in the queue). The only way I am able to get another song to play is by restarting the bot, but the issue continues to occur. Hopefully you guys can help me out!

**Comment by jayktaylor** [comment]
Can you screenshot any stack traces / errors that appear in your console / cmd?

**Comment by Lutezify** [comment]
After a while of waiting, this appeared in cmd.exe

```
[Download] Started: https://www.youtube.com/watch?v=A6Thn9Gp0T4
[Download] Complete: https://www.youtube.com/watch?v=A6Thn9Gp0T4
[Command] 116054003904806919/Lutezify (!skip)
The next song will be played shortly.  Please wait.
[Command] 116054003904806919/Lutezify (!pause)
[Command] 116054003904806919/Lutezify (!resume)
[Command] 116054003904806919/Lutezify (!play dr dre)
[Command] 116054003904806919/Lutezify (!queue)
[Command] 116054003904806919/Lutezify (!play)
ERROR: unable to download video data: The read operation timed out
Traceback (most recent call last):
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 162, in real_download
    data_block = data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 693, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 739, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1421, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1685, in process_info
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 556, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 526, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to download video data: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to download video data: The read operation timed out
Future exception was never retrieved
future: <Future finished exception=ExtractionError(DownloadError('ERROR: unable to download video data: The read operation timed out',),)>
Traceback (most recent call last):
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 162, in real_download
    data_block = data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 693, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 739, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1421, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1685, in process_info
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 556, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 526, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to download video data: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to download video data: The read operation timed out
Failed to get entry.
Traceback (most recent call last):
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\downloader\http.py", line 162, in real_download
    data_block = data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 693, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 739, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1421, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1685, in process_info
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 556, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 526, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to download video data: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\player.py", line 234, in _play
    entry = await self.playlist.get_next_entry()
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\playlist.py", line 245, in get_next_entry
    return await entry.get_ready_future()
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Lutezify\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 196, in _download
    await self._really_download()
  File "C:\Users\Lutezify\Desktop\MusicBot\musicbot\entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to download video data: The read operation timed out
```

**Comment by kingcatdaan** [comment]
are you using the latest version with the latest requirements? maybe do a restart?

**Comment by Lutezify** [comment]
I just reinstalled everything last night, so everything should be up to date. I could try restarting my PC.

Also @jaydenkieran is what I posted what you were asking for?

**Comment by jayktaylor** [comment]
This issue appears to be caused by `youtube-dl` failing to handle timeouts properly (https://github.com/rg3/youtube-dl/issues/4240)
