### ISSUE TITLE
Do not know what is this

### ISSUE THREAD

**Issue by ooinic** [Just-Some-Bots/MusicBot#505]
Found this in my console

Exception in thread Thread-59:
Traceback (most recent call last):
  File "C:\Users-\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users-\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 73, in run
    f = compat.run_coroutine_threadsafe(coro, loop=self.ws.loop)
  File "C:\Users-\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 727, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "C:\Users-\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 482, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "C:\Users-\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 456, in _call_soon
    self._check_closed()
  File "C:\Users-\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 284, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by jayktaylor** [comment]
Just try running the bot again, not sure why that is happening. Make sure you're using the latest `master` version.
