### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by izzyra** [Just-Some-Bots/MusicBot#507]
I keep getting this error everytime I try to run the bot

Connecting...Traceback (most recent call last):
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\aiohttp\connector.py", line 581, in _create_connection
    local_addr=self._local_addr)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\bas
e_events.py", line 663, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\bas
e_events.py", line 686, in _create_connection_transport
    yield from waiter
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\fut
ures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tas
ks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\fut
ures.py", line 274, in result
    raise self._exception
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\ssl
proto.py", line 492, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\ssl
proto.py", line 200, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", li
ne 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:645)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\aiohttp\connector.py", line 310, in connect
    transport, proto = yield from self._create_connection(req)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\aiohttp\connector.py", line 604, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Can not connect to discordapp.com:443 [[
SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 165, in main
    m.run()
  File "C:\Users\Birty\MusicBot\musicbot\bot.py", line 551, in run
    self.loop.run_until_complete(self.start(_self.config.auth))
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\bas
e_events.py", line 337, in run_until_complete
    return future.result()
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\fut
ures.py", line 274, in result
    raise self._exception
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tas
ks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\discord\client.py", line 458, in start
    yield from self.login(_args, *_kwargs)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\discord\client.py", line 384, in login
    yield from getattr(self, '_login_' + str(n))(_args, *_kwargs)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\discord\client.py", line 314, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\discord\http.py", line 195, in static_login
    data = yield from self.get(self.ME)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\discord\http.py", line 105, in request
    r = yield from self.session.request(method, url, *_kwargs)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\aiohttp\client.py", line 529, in **iter**
    resp = yield from self._coro
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\aiohttp\client.py", line 183, in _request
    conn = yield from self._connector.connect(req)
  File "C:\Users\Birty\AppData\Local\Programs\Python\Python35-32\lib\site-packag
es\aiohttp\connector.py", line 320, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:44
3 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAIL
ED] certificate verify failed (_ssl.c:645)]]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0319E630>

I've tried installing the certificate but that hasn't helped.

**Comment by jayktaylor** [comment]
Try installing this certificate on your system and restarting the bot - https://support.comodo.com/index.php?/Knowledgebase/Article/GetAttachment/969/821026

**Comment by izzyra** [comment]
Nope, I've already tried that, still gives the same error.
