### ISSUE TITLE
Discord music bot

### ISSUE THREAD

**Issue by shaleval** [Just-Some-Bots/MusicBot#525]
when i press run bot and i do !summon to move the bot to my channel to its say
Traceback (most recent call last):
  File "C:\Users\Shalev\Desktop\MusicBot-master\musicbot\bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Shalev\Desktop\MusicBot-master\musicbot\bot.py", line 1325, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "C:\Users\Shalev\Desktop\MusicBot-master\musicbot\bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\Shalev\Desktop\MusicBot-master\musicbot\bot.py", line 249, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "C:\Users\Shalev\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 191, in **init**
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

**Comment by jayktaylor** [comment]
**Windows** - Open `update_deps.bat`
**Linux** - In your console, run `python3.5 -m pip install --upgrade -r requirements.txt`
**Mac** - Open `update_macdeps.command` in Terminal

**Comment by shrx** [comment]
Doesn't fix the issue for me. Ubuntu 16.04
