### ISSUE TITLE
Running Bot for Extended Periods Breaks It

### ISSUE THREAD

**Issue by alexisblack** [Just-Some-Bots/MusicBot#542]
```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\gateway.py", line 73, in run
    f = compat.run_coroutine_threadsafe(coro, loop=self.ws.loop)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 727, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 482, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 456, in _call_soon
    self._check_closed()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 284, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py:243> exception=ConnectionClosed('WebSocket connection is closed: code = 1006, no reason.',)>
Traceback (most recent call last):
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\gateway.py", line 602, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 386, in wait_for
    return fut.result()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 250, in poll_voice_ws
    yield from self.ws.poll_event()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\gateway.py", line 605, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
Error disconnecting during reconnect
Traceback (most recent call last):
  File "C:\Users\Omar\Desktop\MusicBot-master\musicbot\player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Omar\Desktop\MusicBot-master\musicbot\bot.py", line 302, in reconnect_voice_client
    await vc.disconnect()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 271, in disconnect
    yield from self.ws.close()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\gateway.py", line 612, in close
    yield from super().close(code, reason)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 239, in close
    self.worker, self.timeout, loop=self.loop)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 386, in wait_for
    return fut.result()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 411, in run
    msg = yield from self.read_message()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 433, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 488, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\protocol.py", line 523, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\site-packages\websockets\framing.py", line 80, in read_frame
    data = yield from reader(2)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 509, in readexactly
    block = yield from self.read(n)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 482, in read
    yield from self._wait_for_data('read')
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\streams.py", line 423, in _wait_for_data
    yield from self._waiter
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\selector_events.py", line 664, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at C:\Users\Omar\Desktop\MusicBot-master\musicbot\player.py:280> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\Users\Omar\Desktop\MusicBot-master\musicbot\player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Omar\Desktop\MusicBot-master\musicbot\player.py", line 291, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "C:\Users\Omar\Desktop\MusicBot-master\musicbot\bot.py", line 310, in reconnect_voice_client
    new_vc = await self.get_voice_client(vc.channel)
  File "C:\Users\Omar\Desktop\MusicBot-master\musicbot\bot.py", line 238, in get_voice_client
    voice_data = await asyncio.wait_for(_voice_data, timeout=10, loop=self.loop)
  File "D:\Users\Omar\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError`
```

**Comment by jayktaylor** [comment]
This is some Discord related stuff. Try changing voice region if this happens often.
