### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by SaubereSacheLP** [Just-Some-Bots/MusicBot#575]
Hi,
I tried to setup the bot on my Debian 8 Server (its working on my Linux Mint PC) but if I try to start pip3 install --upgrade -r requirements.txt its telling me Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 274, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in **init**
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", "cffi==1.6.0; sys_platform == 'win32'", 'at', "; sys_platform == 'win32'")

Storing debug log for failure in /root/.pip/pip.log

Please help me!

**Comment by gibbly** [comment]
~~https://github.com/SexualRhinoceros/MusicBot/wiki/Guide-for-Debian  
install it via this guide (note that you will need to enable backports)~~

Ignore me, I'm stupid

**Comment by imayhaveborkedit** [comment]
Looks like you need to update pip.
