### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by Eufranio** [Just-Some-Bots/MusicBot#581]
```
root@vps284033:~/Transferências/MusicBot# Connecting...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 371, in poll_event
    msg = yield from self.recv()
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4004, reason = Authentication failed..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 165, in main
    m.run()
  File "/root/Transferências/MusicBot/musicbot/bot.py", line 551, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 448, in start
    yield from self.connect()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 405, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 378, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4004, reason = Authentication failed..
```

**Comment by ghost** [comment]
Okay so I'm not the only one.. Must be a Discord issue! 

#582

**Comment by Unkn0wnAssassin** [comment]
I have the same problem. I just restarted the bot  to change the auto save option and it didn't start again. It probably is some discord sided problem :/ Can someone comment when it's working again?

**Comment by Eufranio** [comment]
They are working in it, dont worry xD

**Comment by Unkn0wnAssassin** [comment]
Working now :)

**Comment by jayktaylor** [comment]
This issue has been resolved.
