### ISSUE TITLE
Ubuntu Authentication failed

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#582]
Hey friends,
I've been running my bot on a Ubuntu 14.04 VPS for a few weeks and today it randomly disconnected and now says `discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4004, reason = Authentication failed..`

I'll attach the entire exception at the bottom of this issue. I've also reset my token and updated it in the options.ini. Now I don't know if it's an issue with my server, or my bot, or my settings, or if Discord is updating..

Here is my entire exception that was thrown:

```
root@ubuntu-512mb-tor1-01:~/MusicBot# python3.5 run.py
Connecting...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 384, in poll_event
    msg = yield from self.recv()
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4004, reason = Authentication failed..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 165, in main
    m.run()
  File "/root/MusicBot/musicbot/bot.py", line 551, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 459, in start
    yield from self.connect()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 416, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 391, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4004, reason = Authentication failed..

```

**Comment by EnumC** [comment]
Dup Of #581 . Problem on Discord gateway. Should be fixed shortly.

**Comment by jayktaylor** [comment]
This issue has been resolved.
