### ISSUE TITLE
Piping output produces errors

### ISSUE THREAD

**Issue by brawaru** [Just-Some-Bots/MusicBot#585]
Piping output produces many 🔥  errors
## Steps to reproduce:
1. Start PowerShell
2. Type these commands:

``` ps
filter timestamp {"$(Get-Date -Format 'dd/MM/yyyy hh:mm:ss tt'): $_"}
./runbot.cmd | timestamp
```
## Excepted behavior

No errors
## Actual behavior

Many errors in output
## Log

```
--- Logging error ---
Traceback (most recent call last):
  File "D:\Main\Programs\Python\Python_3.5\lib\logging\__init__.py", line 982, in emit
    stream.write(msg)
  File "D:\Main\Programs\Python\Python_3.5\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "D:\Main\Programs\Python\Python_3.5\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "D:\Main\Programs\Python\Python_3.5\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\Main\Programs\Python\Python_3.5\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "D:\Main\Programs\Python\Python_3.5\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 44: character maps to <undefined>
Call stack:
  File "run.py", line 265, in <module>
    main()
  File "run.py", line 200, in main
    m.run()
  File "D:\Main\Dev\Python\Rocky_TheRacoon\musicbot\bot.py", line 733, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "D:\Main\Programs\Python\Python_3.5\lib\asyncio\base_events.py", line 325, in run_until_complete
    self.run_forever()
  File "D:\Main\Programs\Python\Python_3.5\lib\asyncio\base_events.py", line 295, in run_forever
    self._run_once()
  File "D:\Main\Programs\Python\Python_3.5\lib\asyncio\base_events.py", line 1254, in _run_once
    handle._run()
  File "D:\Main\Programs\Python\Python_3.5\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "D:\Main\Programs\Python\Python_3.5\lib\asyncio\tasks.py", line 301, in _wakeup
    self._step()
  File "D:\Main\Programs\Python\Python_3.5\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\Main\Programs\Python\Python_3.5\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\Main\Dev\Python\Rocky_TheRacoon\musicbot\bot.py", line 909, in on_ready
    await self._join_startup_channels(autojoin_channels, autosummon=self.config.auto_summon)
  File "D:\Main\Dev\Python\Rocky_TheRacoon\musicbot\bot.py", line 258, in _join_startup_channels
    log.info("Joined {0.server.name}/{0.name}".format(channel))
```

**Comment by brawaru** [comment]
Fixed. Thanks you! 🎉

**Comment by yldn** [comment]
how did you get this issue fixed?? ,i got the same .
