### ISSUE TITLE
Errno 13 (Solved: Installation didn't create audio_cache folder)

### ISSUE THREAD

**Issue by spyman5959** [Just-Some-Bots/MusicBot#621]
This keeps popping up whenever I try to play a song. Mac OSX 10.11.6

[Command] 186503680944635905/spyman5959 (!play https://soundcloud.com/ma-l-guillerm/baten-kaitos-ost-feudal-guardian)
Traceback (most recent call last):
  File "/Users/spyman5959/Desktop/MusicBot/musicbot/entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache'
Future exception was never retrieved
future: <Future finished exception=PermissionError(13, 'Permission denied')>
Traceback (most recent call last):
  File "/Users/spyman5959/Desktop/MusicBot/musicbot/entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache'
Traceback (most recent call last):
  File "/Users/spyman5959/Desktop/MusicBot/musicbot/entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache'
Failed to get entry.
Traceback (most recent call last):
  File "/Users/spyman5959/Desktop/MusicBot/musicbot/player.py", line 234, in _play
    entry = await self.playlist.get_next_entry()
  File "/Users/spyman5959/Desktop/MusicBot/musicbot/playlist.py", line 245, in get_next_entry
    return await entry.get_ready_future()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Users/spyman5959/Desktop/MusicBot/musicbot/entry.py", line 138, in _download
    os.makedirs(self.download_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'audio_cache'

**Comment by Akuba-** [comment]
the bot is not allowed to write into (or create) the `audio_cache` folder. Change the permission of the folder to 0666 (does MAC have these? no clue) / allow writing into the folder.

**Comment by spyman5959** [comment]
Issue resolved. Made the folder myself and assigned everyone permission to r/w.  

The installation didn't create the `audio_cache` folder for some reason. Thanks!
