### ISSUE TITLE
Timeout/Command Error?

### ISSUE THREAD

**Issue by LXGaming** [Just-Some-Bots/MusicBot#622]
Ubuntu Server 16.04.1
any help would be great!

```
<class 'musicbot.exceptions.CommandError'>: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.
Traceback (most recent call last):
  File "/home/user/MusicBot/musicbot/bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "/home/user/MusicBot/musicbot/bot.py", line 1325, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "/home/user/MusicBot/musicbot/bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/user/MusicBot/musicbot/bot.py", line 238, in get_voice_client
    voice_data = await asyncio.wait_for(_voice_data, timeout=10, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

[UPDATE] After try to fix the issue we have ended up with this error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/user/MusicBot/musicbot/bot.py", line 710, in on_ready
    owner_vc = await self._auto_summon()
  File "/home/user/MusicBot/musicbot/bot.py", line 149, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "/home/user/MusicBot/musicbot/bot.py", line 1325, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "/home/user/MusicBot/musicbot/bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/user/MusicBot/musicbot/bot.py", line 249, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 191, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
```

But I have it installed?

```
aiohttp (0.21.6)
cffi (1.8.3)
chardet (2.3.0)
command-not-found (0.3)
discord.py (0.11.0)
language-selector (0.1)
pip (8.1.2)
pycparser (2.14)
pycurl (7.43.0)
pygobject (3.20.0)
PyNaCl (1.0.1) <- It's installed!?
python-apt (1.1.0b1)
python-systemd (231)
requests (2.9.1)
setuptools (23.0.0)
six (1.10.0)
ssh-import-id (5.5)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.13.1)
websockets (3.1)
wheel (0.29.0)
youtube-dl (2016.9.24)
```

**Comment by MattBSG** [comment]
Can you verify this is still happening on the latest update?

**Comment by LXGaming** [comment]
No sorry, We no longer use MusicBot
