### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by kaxonomy** [Just-Some-Bots/MusicBot#625]
```
Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "/root/MusicBot/musicbot/__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "/root/MusicBot/musicbot/bot.py", line 38, in <module>
    load_opus_lib()
  File "/root/MusicBot/musicbot/opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
```

I'm running Centos 7 Linux.

**Comment by jayktaylor** [comment]
Looks like you haven't installed opus. On CentOS 7, these packages would probably fix it:
http://centos-packages.com/7/package/opus/
http://centos-packages.com/7/package/opus-devel/

**Comment by kaxonomy** [comment]
Thanks. That seemed to have worked.
