### ISSUE TITLE
Bot crashed with this error after some time

### ISSUE THREAD

**Issue by Unkn0wnAssassin** [Just-Some-Bots/MusicBot#626]
`Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:243> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 250, in poll_voice_ws
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 602, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
`

**Comment by deansheather** [comment]
This appears to be an issue with the underlying discord.py library. If this is a recurring issue, please report it on discord.py's issues page.
