### ISSUE TITLE
Traceback, bot crashed after a skip and a pause/resume.

### ISSUE THREAD

**Issue by LaxSlash** [Just-Some-Bots/MusicBot#64]
Console log:

```
[Command] 114144075736678404/Ä´ÃÎ Ð–ÎžÃÆ©ÏˆÂ£ (!play https://soundcloud.com/lo
urescentreams/sets/big-bang-made-album)
Processed 7 songs in 34.46 seconds at 4.92s/song, +3.7/song from expected (8.4s)

[Command] 114144075736678404/Ä´ÃÎ Ð–ÎžÃÆ©ÏˆÂ£ (!play https://soundcloud.com/k2
nblog22/ikon-rhythm-ta)
[Command] 114144075736678404/Ä´ÃÎ Ð–ÎžÃÆ©ÏˆÂ£ (!shuffle)
[Command] 114144075736678404/Ä´ÃÎ Ð–ÎžÃÆ©ÏˆÂ£ (!skip)
Traceback (most recent call last):
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 760, in o
n_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 571, in h
andle_skip
    player.current_entry.title,
AttributeError: 'NoneType' object has no attribute 'title'
[Command] 114144075736678404/Ä´ÃÎ Ð–ÎžÃÆ©ÏˆÂ£ (!pause)
[Command] 114144075736678404/Ä´ÃÎ Ð–ÎžÃÆ©ÏˆÂ£ (!resume)
Traceback (most recent call last):
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 760, in o
n_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 510, in h
andle_resume
    player.resume()
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\player.py", line 85, in
 resume
    raise ValueError('Cannot resume playback from state %s' % self.state)
ValueError: Cannot resume playback from state PAUSED
[Command] 114144075736678404/Ä´ÃÎ Ð–ÎžÃÆ©ÏˆÂ£ (!clear)
ERROR: unable to download video data: The read operation timed out
Future exception was never retrieved
future: <Future finished exception=FileNotFoundError(2, 'The system cannot find
the file specified')>
Traceback (most recent call last):
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\playlist.py", line 203,
 in _download
    os.rename(result['id'], self.filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '2082
77230' -> 'C:\\Users\\Keith\\Desktop\\MusicBot-develop\\audio_cache\\208277230-b
ang-bang-bang-big-bang-made-series-a.mp3'
Failed to get entry.
Traceback (most recent call last):
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\player.py", line 136, i
n _play
    entry = await self.playlist.get_next_entry()
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\playlist.py", line 127,
 in get_next_entry
    return await entry.get_ready_future()
  File "S:\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "S:\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "S:\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\playlist.py", line 203,
 in _download
    os.rename(result['id'], self.filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '2082
77230' -> 'C:\\Users\\Keith\\Desktop\\MusicBot-develop\\audio_cache\\208277230-b
ang-bang-bang-big-bang-made-series-a.mp3'
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at C:\Users\Keith
\Desktop\MusicBot-develop\musicbot\player.py:126> exception=ValueError('Cannot r
esume playback from state PAUSED',)>
Traceback (most recent call last):
  File "S:\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\player.py", line 131, i
n _play
    return self.resume()
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\player.py", line 85, in
 resume
    raise ValueError('Cannot resume playback from state %s' % self.state)
ValueError: Cannot resume playback from state PAUSED
[Command] 118801995296407552/Welsh (!queue)
[Command] 118801995296407552/Welsh (!play https://www.youtube.com/watch?v=ETfiUY
ij5UE)
Traceback (most recent call last):
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 433, in h
andle_play
    time_until = await player.playlist.estimate_time_until(position, player)
  File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\playlist.py", line 144,
 in estimate_time_until
    estimated_time += player.current_entry.duration - player.progress
AttributeError: 'NoneType' object has no attribute 'duration'
[Command] 118801995296407552/Welsh (!queue)
```

Chat log in Discord:

> !play https://soundcloud.com/lourescentreams/sets/big-bang-made-album
> SoundCloud
> Big Bang- MADE Album
> Listen to Big Bang- MADE Album by FlourescentDreams #np on #SoundCloud
> 
> !play https://soundcloud.com/k2nblog22/ikon-rhythm-ta
> SoundCloud
> iKON - 리듬 타 (RHYTHM TA)
> [Album] #iKON - WELCOME BACK [DEBUT HALF ALBUM](MP3) ►Download: http://k2nblog.com/ikon-welcome-back-debut-half-album/ Buy Album: http://bit.ly/ikon-welcome-back iKON - WELCOME BACK Release Date: 20
> 
> JinxedBot - Today at 4:58 PM
> @ĴÏΠЖΞÐƩψ£ - your song Big Bang - Loser is now playing in Music!(edited)
> ĴÏΠЖΞÐƩψ£ - Today at 5:12 PM
> !shuffle
> !skip
> JinxedBot - Today at 5:14 PM
> Traceback (most recent call last):
>   File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 760, in on_message
>     response = await handler(**handler_kwargs)
>   File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 571, in handle_skip
>     player.current_entry.title,
> AttributeError: 'NoneType' object has no attribute 'title'
> ĴÏΠЖΞÐƩψ£ - Today at 5:14 PM
> !pause
> !resume
> JinxedBot - Today at 5:14 PM
> Traceback (most recent call last):
>   File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 760, in on_message
>     response = await handler(**handler_kwargs)
>   File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\bot.py", line 510, in handle_resume
>     player.resume()
>   File "C:\Users\Keith\Desktop\MusicBot-develop\musicbot\player.py", line 85, in resume
>     raise ValueError('Cannot resume playback from state %s' % self.state)
> ValueError: Cannot resume playback from state PAUSED
> ĴÏΠЖΞÐƩψ£ - Today at 5:14 PM
> ....
> !clear
> hogs -.-

**Comment by imayhaveborkedit** [comment]
Yeah there's about 4 different bugs in that entire thing.  I know what most of them are but the pause resume bug and the renaming file bug still elude me.

**Comment by imayhaveborkedit** [comment]
I've messed with this code so much it should be fixed now.
