### ISSUE TITLE
"Could not load an opus lib." on Heroku Server

### ISSUE THREAD

**Issue by neeleythere** [Just-Some-Bots/MusicBot#662]
Trying to get MusicBot running on a Heroku web server, keep receiving "Could not load an opus lib.".

I have installed the discord library using `python -m pip install -U discord.py[voice]` while powershell was running in the server's root folder, is that sufficient?

discord.py is in the same directory as run.py, I have also added "libopus-0.x64.dll" and its 32 bit counterpart to the same directory as "opus_loader.py" yet somehow it doesn't work as I'd want it to.

Heroku's logs read:

```
2016-10-10T21:43:28.831448+00:00 heroku[web.1]: Starting process with command 'python run.py'
2016-10-10T21:43:32.427026+00:00 heroku[web.1]: Process exited with status 0
2016-10-10T21:43:32.444177+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-10T21:43:32.314715+00:00 app[web.1]: Traceback (most recent call last):
2016-10-10T21:43:32.314733+00:00 app[web.1]:   File "run.py", line 162, in main
2016-10-10T21:43:32.314734+00:00 app[web.1]:     from musicbot import MusicBot
2016-10-10T21:43:32.314751+00:00 app[web.1]:   File "/app/musicbot/__init__.py", line 1, in <module>
2016-10-10T21:43:32.314753+00:00 app[web.1]:     from .bot import MusicBot
2016-10-10T21:43:32.314798+00:00 app[web.1]:   File "/app/musicbot/bot.py", line 38, in <module>
2016-10-10T21:43:32.314799+00:00 app[web.1]:     load_opus_lib()
2016-10-10T21:43:32.314803+00:00 app[web.1]:   File "/app/musicbot/opus_loader.py", line 17, in load_opus_lib
2016-10-10T21:43:32.314803+00:00 app[web.1]:     raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
2016-10-10T21:43:32.314865+00:00 app[web.1]: RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
```

What can I do to resolve the issue?

Thanks

**Comment by deansheather** [comment]
Don't run it on Heroku. Use an actual server that doesn't go offline every 3 hours, or you'll have lots of problems down the track. Also, `.dll` files won't work on Linux - you need to install the opus library yourself using command line.

**Comment by ghost** [comment]
Has anyone found a workaround to this? It's getting on my nerves and this solution isn't very good.

**Comment by AleanaA** [comment]
@ImJustTatan No workaround was found because we don't support heroku.
