### ISSUE TITLE
bot will not join chat

### ISSUE THREAD

**Issue by killersaw42** [Just-Some-Bots/MusicBot#668]
each time i try and run the runbot.bat it gives me the same error every time i have followed the instructions word for word about 3 times now to try and fix the issue even deleting and re installing python an""d git just to be 100% sure they werent the issue yet each time i get this error 
""Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "C:\Users\Admin\MusicBot\musicbot__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "C:\Users\Admin\MusicBot\musicbot\bot.py", line 7, in <module>
    import aiohttp
ValueError: source code string cannot contain null bytes""

i know it is not the files either as my friend has the bot and it is running but he gave me his files on a usb and i changed the option.ini file yet the same error and i am unaware of what to do to get this bot working i am currently running windows 10 if that has anything to do with it (as he runs windows 7)

**Comment by deansheather** [comment]
What Python version are you using? MusicBot requires Python 3.5.

**Comment by killersaw42** [comment]
that is currently what im running is python 3.5 64 bit

**Comment by killersaw42** [comment]
as mentioned i deleted python and git from my computer and redownloaded it twice just to be sure it wasnt a issue with python

**Comment by killersaw42** [comment]
(issue is resolved thanks to peach the issue was caused by a issue with pip i beleive deleted that along with python redownloaded it ran the update_deps.bat then ran the runbot.bat and works fine thank you everyone who helped
