### ISSUE TITLE
Bot hangs when !shutdown on Ubuntu 16.04

### ISSUE THREAD

**Issue by Lillecarl** [Just-Some-Bots/MusicBot#699]
How to reproduce:
!shutdown in chat channel with bot running ubuntu 16.04 (Ubuntu 16.04 in a LXC container, though this shouldn't matter to the bot).

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "/root/MusicBot/musicbot/bot.py", line 870, in cmd_play
    raise exceptions.CommandError(e, expire_in=30)
musicbot.exceptions.CommandError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/root/MusicBot/musicbot/bot.py", line 1953, in on_message
    also_delete=alsodelete
  File "/root/MusicBot/musicbot/bot.py", line 473, in safe_send_message
    msg = await self.send_message(dest, content, tts=tts)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 831, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 161, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
ERROR: Unable to download webpage: <urlopen error [Errno -9] Address family for hostname not supported> (caused by URLError(gaierror(-9, 'Address family for hostname not supported'),))
exception calling callback for <Future at 0x7f9f74157358 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 39, in _python_exit
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

Revision:

> commit 3519ee88bb4b2ed67d23c8f075710c8f88de2392
> Author: Daniel imayhaveborkedit@users.noreply.github.com
> Date:   Thu Sep 29 02:47:43 2016 -0400
> 
> ```
> Lock discord.py version
> ```

**Comment by Lillecarl** [comment]
The real issue for me is i have it running in an infinite bash loop, to autorestart itself, but it hangs here instead of logging crash to disk and exiting.

**Comment by amit177** [comment]
If this is still an issue in the latest version, please open a new issue.
