### ISSUE TITLE
Can install requirements.txt on Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by dyanakiev** [Just-Some-Bots/MusicBot#712]
```
sudo python3.5 get-pip.py
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 588kB/s
Collecting setuptools
  Downloading setuptools-28.8.0-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 1.5MB/s
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 5.3MB/s
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-28.8.0 wheel-0.29.0
root@dedibox:~# python3.5 -m pip install -U -r requirements.txt
Ignoring cffi: markers 'sys_platform == "win32"' don't match your environment
Collecting discord.py[voice]~=0.12.0 (from -r requirements.txt (line 1))
  Downloading discord.py-0.12.0.zip (440kB)
    100% |████████████████████████████████| 450kB 1.5MB/s
Collecting youtube_dl (from -r requirements.txt (line 2))
  Downloading youtube_dl-2016.11.8.1-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 507kB/s
Requirement already up-to-date: pip in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Downloading aiohttp-1.0.5-cp35-cp35m-manylinux1_x86_64.whl (150kB)
    100% |████████████████████████████████| 153kB 3.9MB/s
Collecting websockets<4.0,>=3.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Downloading websockets-3.2-py33.py34.py35-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Downloading PyNaCl-1.0.1.tar.gz (2.7MB)
    100% |████████████████████████████████| 2.7MB 272kB/s
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-x_kwwi3r/cffi-1.9.1/setup.py", line 202, in <module>
        if self.distribution.has_c_libraries():
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 251, in run_setup
        raise
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-x_kwwi3r/cffi-1.9.1/setup.py", line 202, in <module>
        if self.distribution.has_c_libraries():
      File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ida5gye9/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ida5gye9/PyNaCl/

```

**Comment by dyanakiev** [comment]
... My bad fixed :D

**Comment by itslewiswatson** [comment]
Sorry to bump old issues, but please be considerate and tell us how you fixed it.
