### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by adokic208** [Just-Some-Bots/MusicBot#713]
I get the following error when i try to run the musicbot. I use Ubuntu 14.04.

Connecting...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 713, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 736, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in iter
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 492, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 200, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 624, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "run.py", line 165, in main
    m.run()
  File "/root/MusicBot/musicbot/bot.py", line 551, in run
    self.loop.run_until_complete(self.start(self.config.auth))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 458, in start
    yield from self.login(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 384, in login
    yield from getattr(self, 'login' + str(n))(*args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 314, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 195, in static_login
    data = yield from self.get(self.ME)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 555, in iter
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)]]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4b83ff18d0>

**Comment by arunesh90** [comment]
Install this certificate: https://support.comodo.com/index.php?/Knowledgebase/Article/GetAttachment/969/821026

And then try again

**Comment by adokic208** [comment]
Thank you for your response.
The problem is that i can't figure out how to install the certificate. Every tutorial on installing the certificates asks for some key. Do you know a tutorial i can follow to install the certificate with only the .crt file?

**Comment by arunesh90** [comment]
http://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line

**Comment by adokic208** [comment]
I tried it, the certificate was added but i get the same error when i try to run the bot again.  
If you have any other ideas I would like to try them. Thank you for your response.

**Comment by adokic208** [comment]
It looks like my server had some issues with it. I put it on my friends server(same provider and server level) and it works just fine. Thank you for your time.
