### ISSUE TITLE
Problems With Music (10060 Error)

### ISSUE THREAD

**Issue by Shadow3636** [Just-Some-Bots/MusicBot#718]
I installed and initialized the bot after configuring the settings. Now when ever I queue a song to play after the first video is downloaded I get this error...

Connected!  Musicbot v1.9.5_2

Bot:   (Censored)
Owner:  (Censored)

Server List:
 - Test

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: !
  Default volume: 15%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Enabled
  Auto-Playlist: Disabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

Attempting to autosummon...
Found owner in "General", attempting to join...
Attempting connection...
Connection established.
Done!

[Command] (Censored) (!play ROS Mac Miller)
[Download] Started: https://www.youtube.com/watch?v=32dH--xXaw8
[Command] (Censored) (!resume)
<class 'musicbot.exceptions.CommandError'>: Player is not paused.
[Download] Complete: https://www.youtube.com/watch?v=32dH--xXaw8
[Command] (Censored) (!play what I got Sublime)
ERROR: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None),))
Traceback (most recent call last):
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1252, in connect
    super().connect()
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 1036, in https_open
    req, **kwargs)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 357, in extract
    return self._real_extract(url)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1226, in _real_extract
    video_webpage = self._download_webpage(url, video_id)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 413, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Karlor Jr\Desktop\MusicBot\musicbot\bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Karlor Jr\Desktop\MusicBot\musicbot\bot.py", line 900, in cmd_play
    info = await self.downloader.extract_info(player.playlist.loop, song_url, download=False, process=False)
  File "C:\Users\Karlor Jr\Desktop\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 709, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Karlor Jr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 538, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> (caused by URLError(TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None),))

This happens everytime I use the bot...

Thanks for looking

**Comment by Lumb-Chul** [comment]
I'm having a similar problem only i get WinError 5

**Comment by ElectronicWar** [comment]
try using youtube-dl on the same system directly, it's failing for you.

**Comment by jayktaylor** [comment]
Are you still having this issue?
