### ISSUE TITLE
Error on Bot start

### ISSUE THREAD

**Issue by TideSinger** [Just-Some-Bots/MusicBot#752]
XXXXX@XXXXX:~$ cd MusicBot
XXXXX@XXXXX:~/MusicBot$ python3.5 run.py
Connected!  Musicbot v1.9.5_2

Bot:   XXXXXXXXXXXXXXX/XXXXXXXX#XXXX
Owner: XXXXXXXXXXXXX/XXXXXX#XXXX

Server List:
 - XXXXXXXXXX
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/XXXXXX/MusicBot/musicbot/bot.py", line 615, in on_ready
    [self.safe_print(' - ' + s.name) for s in self.servers]
  File "/home/XXXXXX/MusicBot/musicbot/bot.py", line 615, in <listcomp>
    [self.safe_print(' - ' + s.name) for s in self.servers]
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by KingGold171** [comment]
The information you attempted to censor is public knowledge sooo yea, nothing bad can come from us knowing it.

But in regards to your issue...

Have you modified the bot in any way?
Is the bot even connected to any servers?

**Comment by TideSinger** [comment]
The bot was connected to two servers, and it was unmodified. I did a fresh install of Linux, and got this same error

**Comment by Manifold0** [comment]
Also seeing this error after updating a bunch of my packages and applying some security updates to Ubuntu. I tried updated all of my MusicBot python dependencies and everything.

```
Server List:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/opt/MusicBot/musicbot/bot.py", line 621, in on_ready
    [self.safe_print(' - ' + s.name) for s in self.servers]
  File "/opt/MusicBot/musicbot/bot.py", line 621, in <listcomp>
    [self.safe_print(' - ' + s.name) for s in self.servers]
TypeError: Can't convert 'NoneType' object to str implicitly
```
