### ISSUE TITLE
Unable to download video data: The read operation timed out

### ISSUE THREAD

**Issue by ScorchRaserik** [Just-Some-Bots/MusicBot#774]
I've had this bot running on a Raspberry Pi 3B since July with no problems, but yesterday and today, it hasn't been able to play any music.  Checking the logs give me these 4 error messages in various amounts:

```
ERROR: unable to download video data: The read operation timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/downloader/http.py", line 165, in real_download
    data_block = data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "/usr/local/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/MusicBot2/musicbot/entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "/home/pi/MusicBot2/musicbot/downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 705, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 751, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1435, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1701, in process_info
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 538, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: unable to download video data: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/MusicBot2/musicbot/entry.py", line 196, in _download
    await self._really_download()
  File "/home/pi/MusicBot2/musicbot/entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to download video data: The read operation timed out
Future exception was never retrieved
future: <Future finished exception=ExtractionError(DownloadError('\x1b[0;31mERROR:\x1b[0m unable to download video data: The read operation timed out',),)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/downloader/http.py", line 165, in real_download
    data_block = data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "/usr/local/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.5/socket.py", line 571, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/MusicBot2/musicbot/player.py", line 234, in _play
    entry = await self.playlist.get_next_entry()
  File "/home/pi/MusicBot2/musicbot/playlist.py", line 245, in get_next_entry
    return await entry.get_ready_future()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/home/pi/MusicBot2/musicbot/entry.py", line 196, in _download
    await self._really_download()
  File "/home/pi/MusicBot2/musicbot/entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: unable to download video data: The read operation timed out
```

I tried downloading a fresh copy of the bot into a new folder (hence the MusicBot2 folder) to no avail.  Same issue.

My internet connection on the pi is fine.  I can ping google.com with about a 20ms ping, youtube.com with about a 30ms ping.  Also tried switching between my ISP's provided DNS and Google's DNS, both have the same above result.

**Comment by ScorchRaserik** [comment]
Restarting router fixed the issue
