### ISSUE TITLE
I need help piz 

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#780]
my music bot will not do play music join in the channel

**Comment by ghost** [comment]
it say 

Traceback (most recent call last):
  File "C:\Users\Robbie\Desktop\MUSIC bot\MusicBot-master\musicbot\bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "C:\Users\Robbie\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by Daniel7689** [comment]
a
