### ISSUE TITLE
I am getting errors trying to run 'runbot.bat'

### ISSUE THREAD

**Issue by Sxra** [Just-Some-Bots/MusicBot#784]
```
Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "C:\Users\Sora\Desktop\OniiChan Bot\musicbot\__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "C:\Users\Sora\Desktop\OniiChan Bot\musicbot\bot.py", line 38, in <module>
    load_opus_lib()
  File "C:\Users\Sora\Desktop\OniiChan Bot\musicbot\opus_loader.py", line 17, in load_opus_lib
    raise RuntimeError('Could not load an opus lib. Tried %s' % (', '.join(opus_libs)))
RuntimeError: Could not load an opus lib. Tried libopus-0.x86.dll, libopus-0.x64.dll, libopus-0.dll, libopus.so.0, libopus.0.dylib
```

What do I do with this?

**Comment by MattBSG** [comment]
Please run update_deps.bat and let me know if that fixed it

**Comment by Sxra** [comment]
I still get the same error. I still need some assistance. Anyone out here that can help?

**Comment by Sxra** [comment]
I still need some assistance. Anyone out here that can help?

**Comment by ImthePeach** [comment]
Solved on discord help server.

**Comment by Deleoel** [comment]
I get the same error, have downloaded the libopus-0.x64, still not working ;(
any help?

**Comment by MattBSG** [comment]
Please do not necropost on old, and closed issues. Make your own, or seek help on our discord server https://discord.gg/bots
