### ISSUE TITLE
Bot Drops Out of Voice Channel and Stops Working at random

### ISSUE THREAD

**Issue by chuushi** [Just-Some-Bots/MusicBot#805]
The bot has been randomly dropping out of the voice channel, and it can be fixed by summoning it again in a voice channel using `summon` command.

However, today, `play` stopped working (or showing indication that it's working). The command registered on the log, but it didn't play anything, so I shut down the bot.

Multiple errors were logged upon shutdown, so I pasted it below in hopes that it helps anyone.

After running `shutdown` command
```
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/usr/src/MusicBot/musicbot/bot.py", line 2464, in on_message
    response = await handler(**handler_kwargs)
  File "/usr/src/MusicBot/musicbot/bot.py", line 1768, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True, deserialize=self.config.persistent_queue)
  File "/usr/src/MusicBot/musicbot/bot.py", line 561, in get_player
    await self.reconnect_voice_client(server, channel=channel)
  File "/usr/src/MusicBot/musicbot/bot.py", line 461, in reconnect_voice_client
    async with self.aiolocks[_func_() + ':' + server.id]:
  File "/usr/lib/python3.5/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/lib/python3.5/asyncio/locks.py", line 176, in acquire
    yield from fut
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/usr/src/MusicBot/musicbot/bot.py", line 2385, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "/usr/src/MusicBot/musicbot/bot.py", line 536, in get_player
    async with self.aiolocks[_func_() + ':' + server.id]:
  File "/usr/lib/python3.5/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/lib/python3.5/asyncio/locks.py", line 176, in acquire
    yield from fut
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/usr/src/MusicBot/musicbot/bot.py", line 2385, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "/usr/src/MusicBot/musicbot/bot.py", line 536, in get_player
    async with self.aiolocks[_func_() + ':' + server.id]:
  File "/usr/lib/python3.5/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/lib/python3.5/asyncio/locks.py", line 176, in acquire
    yield from fut
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/usr/src/MusicBot/musicbot/bot.py", line 2385, in on_message
    handler_kwargs['player'] = await self.get_player(message.channel)
  File "/usr/src/MusicBot/musicbot/bot.py", line 536, in get_player
    async with self.aiolocks[_func_() + ':' + server.id]:
  File "/usr/lib/python3.5/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/lib/python3.5/asyncio/locks.py", line 176, in acquire
    yield from fut
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

[INFO] launcher: All done.
Fatal write error on socket transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f359baa2e10>
transport: <_SelectorSocketTransport fd=11>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 707, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <bound method _SSLProtocolTransport.__del__ of <asyncio.sslproto._SSLProtocolTransport object at 0x7f359baa2ac8>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 328, in __del__
    self.close()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 319, in close
    self._ssl_protocol._start_shutdown()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 542, in _start_shutdown
    self._write_appdata(b'')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 547, in _write_appdata
    self._process_write_backlog()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 651, in _process_write_backlog
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 658, in _fatal_error
    if isinstance(exc, base_events._FATAL_ERROR_IGNORE):
NameError: name 'base_events' is not defined
```

**Comment by srhinos** [comment]
run the "update_deps.bat" in the MusicBot folder.

**Comment by chuushi** [comment]
I tried to do that, but `pip` is just getting me errors after downloading all the deps.  I'll try to see how I can update dependencies, but for now, I'm stuck with old dependencies.

Also, I'm on Ubuntu.

**Comment by chuushi** [comment]
I got to update the dependencies. The bot still occasionally drops out of the voice channel, but it hasn't broken down yet, so it's a good sign.
