### ISSUE TITLE
YTDL library bug, KeyError: 'qC'

### ISSUE THREAD

**Issue by Burdues** [Just-Some-Bots/MusicBot#806]
When requesting some songs, the bot gives an error, while some others are fine.

Tried reinstalling both phyton and music bot, doesn't work. Can't seem to get any help.

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "MYFILEDESTINATION\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "MYFILEDESTINATION\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "MYFILEDESTINATION\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "MYFILEDESTINATION\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "MYFILEDESTINATION\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "MYFILEDESTINATION\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))

MYFILEDESTINATION is replaced over HardDisk:\Letter\Users\Username to keep my privacy of my computer safe :P

**Comment by ImthePeach** [comment]
Library bug with ytdl, see issue [#11663](https://github.com/rg3/youtube-dl/issues/11663) on their page. ~~This will have to be fixed on their end.~~
This has been fixed. If you are experiencing this issue please **update your dependencies**

Windows - Run **`update_deps.bat`**
Linux - In your console, run **`python3.5 -m pip install --upgrade -r requirements.txt`**
Mac - Run **`update_macdeps.command`** in Terminal

**Comment by arunesh90** [comment]
@Burdues update your dependencies with updatedeps.bat and you should be good to go, the bug got fixed and released with a new version 9 minutes ago.
