### ISSUE TITLE
Error While Searching For Video

### ISSUE THREAD

**Issue by KillerFusky** [Just-Some-Bots/MusicBot#808]
Every time either I or someone tries to play a song it will give an error back that looks like this:
`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Program Files\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Program Files\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Program Files\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Program Files\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Program Files\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Program Files\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))`
![kndjerror](https://cloud.githubusercontent.com/assets/20845555/21823941/3443c88c-d74b-11e6-8945-9d10ce3f8152.PNG)

**Comment by KillerFusky** [comment]
Solved - DEP UPDATE
