### ISSUE TITLE
What is this? PLEASE HELP

### ISSUE THREAD

**Issue by Benjoi4231** [Just-Some-Bots/MusicBot#811]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 924, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 976, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))

Please leave answer in comments! thanks!

**Comment by kudfs** [comment]
I made an account just to reply to you. I just fixed it by running the "update_deps.bat" in the MusicBot folder.

**Comment by ImthePeach** [comment]
#806
