### ISSUE TITLE
Youtube extractor / dll not functioning (youtube did a nasty "update"?)

### ISSUE THREAD

**Issue by Jerokun** [Just-Some-Bots/MusicBot#815]
I wish that I had the skill to understand this sort of thing so I could contribute. I'm quite sure it's not really the MusicBot but youtube. The reason that I'm reporting this is to be of some kind of help to the community because there is simply (in my eyes) no better musicbot for discord out there that just does what it's supposed to do like this one. And I want to keep it that way.

Consistency: Since yesterday I noticed that it keeps making these errors unless I search for i.e. "pokemon". Seems to have no problems with that one. But newer videos seem to have problems. So it's not 100% occurring.

So... is this youtube or are my libraries not in order?
Win10: x64
Python: 3.5.1

Using !search
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1001, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 928, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 980, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))
```
Using !search
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1001, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 928, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 980, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))
```
Using !play https://www.youtube.com/watch?v=D_JxMb8RLEY
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1001, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 928, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 980, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\jerok\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))
```

**Comment by ImthePeach** [comment]
#806
