### ISSUE TITLE
Signature extraction failed error when attempting to play a song

### ISSUE THREAD

**Issue by shahzebqazi** [Just-Some-Bots/MusicBot#816]
This happens everytime someone tries playing a song

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Shahzeb\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Shahzeb\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Shahzeb\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Shahzeb\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Shahzeb\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Shahzeb\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))

**Comment by KingGold171** [comment]
Hello all, If you are recieving the following error on your music bots, this is caused by a bug in the Youtube-DL library. They will need to fix it on their end for this to be fixed. We will update you here if you will need to run the update_deps.bat file for the fix.
References: https://github.com/rg3/youtube-dl/issues/11663

deps: :inbox_tray: Updating your MusicBot dependencies
Windows - Open update_deps.bat
Linux - In your console, run python3.5 -m pip install --upgrade -r requirements.txt
Mac - Open update_macdeps.command in Terminal

**Comment by jayktaylor** [comment]
This is a `youtube_dl` bug (https://github.com/rg3/youtube-dl/issues/11663) and is fixed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
