### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by b-reich** [Just-Some-Bots/MusicBot#817]
Hi when I try "play spaceman hardwell"

this happen
`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))`

**Comment by b-reich** [comment]
Do you have any idea? 
I am not very familiar with python.

**Comment by b-reich** [comment]
Maybe the rebuild of the docker image helped

**Comment by jayktaylor** [comment]
This is a `youtube_dl` bug (https://github.com/rg3/youtube-dl/issues/11663) and is fixed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
