### ISSUE TITLE
Cannot play any song: [Signature extraction failed: Traceback]

### ISSUE THREAD

**Issue by RobWaterhouse95** [Just-Some-Bots/MusicBot#820]
One day the bot works, the next day, it doesn't.
No configuration was changed, The files are up to date
> [1:12 AM] User: !play https://www.youtube.com/watch?v=SVKKRzemX_w
[1:12 AM] BOT: 
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))

**Comment by JalinRio42** [comment]
There was a similar issue like this. Should look at the older issues before asking yo.

This is a `youtube_dl` bug (rg3/youtube-dl#11663) and is fixed. You need to update ytdl using our dependency update scripts:

Windows: Open `update_deps.bat`
Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
Mac: Open `update_macdeps.command` in Terminal

**Comment by RobWaterhouse95** [comment]
Sorry, I only searched this project for bugs, I didn't think to search ytdl

I updated ytdl (Linux) and now I have a slightly different error:

> [0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 518, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflsagga9/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflsagga9/base.js'",))

**Comment by jayktaylor** [comment]
We're unaware of that issue. If it persists, leave an issue on [youtube-dl's repo](https://github.com/rg3/youtube-dl/issues). It may be fixed with a full restart of the bot.
