### ISSUE TITLE
Music bot breaking when requesting a song. 

### ISSUE THREAD

**Issue by naTlatsyrC** [Just-Some-Bots/MusicBot#821]
The music bot has worked for a few months now perfectly fine but as of today it dosen't seem to want to accept songs. It accepts maybe 1/6th of the songs requested? 

This is the error it spouts out in chat when requesting a song. 

`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Cryst\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 987, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Cryst\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 914, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Cryst\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 966, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Cryst\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Cryst\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Cryst\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))`

**Comment by junhui-f** [comment]
Check out #812

**Comment by jayktaylor** [comment]
This is a `youtube_dl` bug (https://github.com/rg3/youtube-dl/issues/11663) and is fixed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
