### ISSUE TITLE
Error when playing any song

### ISSUE THREAD

**Issue by marceloclp** [Just-Some-Bots/MusicBot#823]
Everytime anyone tries to use the command !play, the bot logs this error:

`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Marcelo Perrella\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Marcelo Perrella\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Marcelo Perrella\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Marcelo Perrella\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Marcelo Perrella\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Marcelo Perrella\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))`

It used to work just fine, and it suddendly stopped working.

**Comment by KingGold171** [comment]
This is a youtube_dl bug ([rg3/youtube-dl#11663](url)) and is fixed. You need to update ytdl using our dependency update scripts:

-     Windows: Open update_deps.bat
-     Linux: Run python3.5 -m pip install --upgrade -r requirements.txt
-     Mac: Open update_macdeps.command in Terminal

**Comment by jayktaylor** [comment]
This is a `youtube_dl` bug (https://github.com/rg3/youtube-dl/issues/11663) and is fixed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
