### ISSUE TITLE
Error when updating dependencies!

### ISSUE THREAD

**Issue by justinjameslee** [Just-Some-Bots/MusicBot#826]
Hi, I'm stuck with this problem I'm not sure where to start..

Collecting discord.py[voice]~=0.13.0 (from -r requirements.txt (line 1))
  Using cached discord.py-0.13.0.zip
Collecting pip (from -r requirements.txt (line 2))
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting youtube-dl (from -r requirements.txt (line 3))
  Using cached youtube_dl-2017.1.10-py2.py3-none-any.whl
Collecting colorlog (from -r requirements.txt (line 4))
  Using cached colorlog-2.10.0-py2.py3-none-any.whl
Collecting cffi (from -r requirements.txt (line 5))
  Using cached cffi-1.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Justin\AppData\Local\Temp\pip-build-qt_lpn1w\cffi\setup.py", line 98, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\Justin\AppData\Local\Temp\pip-build-qt_lpn1w\cffi\setup.py", line 76, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "C:\Users\Justin\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\config.py", line 227, in try_comp
ile
        self._compile(body, headers, include_dirs, lang)
      File "C:\Users\Justin\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\config.py", line 133, in _compile

        self.compiler.compile([src], include_dirs=include_dirs)
      File "C:\Users\Justin\AppData\Local\Programs\Python\Python35-32\lib\distutils\_msvccompiler.py", line 317, in compile
        self.initialize()
      File "C:\Users\Justin\AppData\Local\Programs\Python\Python35-32\lib\distutils\_msvccompiler.py", line 210, in initializ
e
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\Justin\AppData\Local\Programs\Python\Python35-32\lib\distutils\_msvccompiler.py", line 85, in _get_vc_en
v
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Justin\AppData\Local\Temp\pip-build-qt_lpn1w\cffi

**Comment by jayktaylor** [comment]
Update pip first. Open a command prompt and run `pip install --upgrade pip`. If that fails, try installing the Visual C++ Redist manually on your system, or the [Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)

**Comment by justinjameslee** [comment]
When I try that command this happens.
Requirement already up-to-date: pip in c:\users\justin\appdata\local\programs\py
thon\python36-32\lib\site-packages

Is there a specific Visual C++ Redist I need to install? 
@jaydenkieran

**Comment by jayktaylor** [comment]
Install the aforementioned Build Tools that I linked.
