### ISSUE TITLE
Youtub_dl

### ISSUE THREAD

**Issue by MRJR123** [Just-Some-Bots/MusicBot#830]
this happens when i start up the bot

```
Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "D:\Discord music bot\MusicBot\musicbot\__init__.py", line 1, in <module>
    from .bot import MusicBot
  File "D:\Discord music bot\MusicBot\musicbot\bot.py", line 32, in <module>
    from . import downloader
  File "D:\Discord music bot\MusicBot\musicbot\downloader.py", line 25, in <module>
    youtube_dl.utils.bug_reports_message = lambda: ''
AttributeError: module 'youtube_dl' has no attribute 'utils'

D:\Discord music bot\MusicBot>
```

**Comment by MRJR123** [comment]
ok i found the issue for got to run the  update_debs command

**Comment by jayktaylor** [comment]
You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
