### ISSUE TITLE
RuntimeError: PyNaCl library needed in order to use voice

### ISSUE THREAD

**Issue by FireFrostLike** [Just-Some-Bots/MusicBot#841]
Attempting to autosummon...
Found owner in "AAN", attempting to join...
Traceback (most recent call last):
  File "E:\Programs\Python\D\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "E:\Programs\Python\sed\MusicBot-master\musicbot\bot.py", line 710, in on_ready
    owner_vc = await self._auto_summon()
  File "E:\Programs\Python\sed\MusicBot-master\musicbot\bot.py", line 149, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "E:\Programs\Python\sed\MusicBot-master\musicbot\bot.py", line 1325, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "E:\Programs\Python\sed\MusicBot-master\musicbot\bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "E:\Programs\Python\sed\MusicBot-master\musicbot\bot.py", line 249, in get_voice_client
    voice_client = VoiceClient(**kwargs)
  File "E:\Programs\Python\D\lib\site-packages\discord\voice_client.py", line 213, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice

**Comment by ghost** [comment]
not an issue, install PyNaCl

**Comment by LazyHatGuy** [comment]
Tried that
 pip install pynacl
Requirement already satisfied: pynacl in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: six in /usr/local/lib/python3.5/dist-packages (from pynacl)
Requirement already satisfied: cffi>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from pynacl)
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.1.0->pynacl)
Still getting the error

**Comment by ghost** [comment]
well, it probably isn't installing in the right place, or there is a different traceback, ask in the API Discord

**Comment by hansmok** [comment]
Did you try "pip list" and see if it's with the other modules?
