### ISSUE TITLE
Bot hanging and crashing randomly?

### ISSUE THREAD

**Issue by brandonhenness** [Just-Some-Bots/MusicBot#842]
The bot randomly doesn't respond to commands and pressing any key in the command prompt some how refreshes it allowing it to responds to commands again. When this happens the command prompt doesn't say anything, until you refresh it by pressing a any key.

Also unknown if it's related or not the bot sometimes crashes with this error:

```
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py:265> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 272, in poll_voice_ws
    yield from self.ws.poll_event()
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 604, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Error disconnecting during reconnect
Traceback (most recent call last):
  File "C:\Users\HENNESS_SERVER\MusicBot\musicbot\player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 403, in send_as_json
    yield from super().send(utils.to_json(data))
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 309, in send
    yield from self.ensure_open()
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 393, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HENNESS_SERVER\MusicBot\musicbot\bot.py", line 302, in reconnect_voice_client
    await vc.disconnect()
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 294, in disconnect
    yield from self.main_ws.voice_state(self.guild_id, None, self_mute=True)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 457, in voice_state
    yield from self.send_as_json(payload)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 406, in send_as_json
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
Task exception was never retrieved
future: <Task finished coro=<on_player_pause() done, defined at C:\Users\HENNESS_SERVER\MusicBot\musicbot\bot.py:410> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\HENNESS_SERVER\MusicBot\musicbot\bot.py", line 411, in on_player_pause
    await self.update_now_playing(entry, True)
  File "C:\Users\HENNESS_SERVER\MusicBot\musicbot\bot.py", line 467, in update_now_playing
    await self.change_status(game)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 1557, in change_status
    yield from self.ws.change_presence(game=game, idle=idle)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 426, in change_presence
    yield from self.send(sent)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\gateway.py", line 398, in send
    yield from super().send(data)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 309, in send
    yield from self.ensure_open()
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\websockets\protocol.py", line 401, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
Traceback (most recent call last):
  File "C:\Users\HENNESS_SERVER\MusicBot\musicbot\bot.py", line 1940, in on_message
    also_delete=message if self.config.delete_invoking else None
  File "C:\Users\HENNESS_SERVER\MusicBot\musicbot\bot.py", line 473, in safe_send_message
    msg = await self.send_message(dest, content, tts=tts)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 831, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\client.py", line 555, in __iter__
    resp = yield from self._coro
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 663, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 686, in _create_connection_transport
    yield from waiter
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\HENNESS_SERVER\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
Cleaning up... Done.
Restarting in 8 seconds...
Connected!  Musicbot v1.9.5_2
```

**Comment by jayktaylor** [comment]
That error is a result of the connection to Discord being wonky. Blame CloudFlare.
