### ISSUE TITLE
Error critical

### ISSUE THREAD

**Issue by Owned67** [Just-Some-Bots/MusicBot#859]
Attempting connection...
Connection established.
[Debug] Creating websocket check loop
Traceback (most recent call last):
  File "D:\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "D:\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 359, in extract
    return self._real_extract(url)
  File "D:\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1330, in _real_e
xtract
    expected=True)
youtube_dl.utils.ExtractorError: YouTube said: This video is available in Andorra, United Arab Emira
tes, Afghanistan, Antigua and Barbuda, Anguilla, Albania, Armenia, Angola, Antarctica, Argentina, Am
erican Samoa, Australia, Aruba, Ã…land Islands, Azerbaijan, Bosnia and Herzegovina, Barbados, Bangla
desh, Burkina Faso, Bahrain, Burundi, Benin, Saint BarthÃ©lemy, Bermuda, Brunei Darussalam, Bolivia,
 Plurinational State of, Bonaire, Sint Eustatius and Saba, Brazil, Bahamas, Bhutan, Bouvet Island, B
otswana, Belarus, Belize, Canada, Cocos (Keeling) Islands, Congo, the Democratic Republic of the, Ce
ntral African Republic, Congo, Switzerland, CÃ´te d'Ivoire, Cook Islands, Chile, Cameroon, China, Co
lombia, Costa Rica, Cuba, Cape Verde, CuraÃ§ao, Christmas Island, Djibouti, Dominica, Dominican Repu
blic, Algeria, Ecuador, Egypt, Western Sahara, Eritrea, Spain, Ethiopia, Fiji, Falkland Islands (Mal
vinas), Micronesia, Federated States of, Faroe Islands, Gabon, Grenada, Georgia, French Guiana, Guer
nsey, Ghana, Gibraltar, Greenland, Gambia, Guinea, Guadeloupe, Equatorial Guinea, South Georgia and
the South Sandwich Islands, Guatemala, Guam, Guinea-Bissau, Guyana, Hong Kong, Heard Island and McDo
nald Islands, Honduras, Croatia, Haiti, Indonesia, Israel, Isle of Man, India, British Indian Ocean
Territory, Iraq, Iran, Islamic Republic of, Iceland, Jersey, Jamaica, Jordan, Japan, Kenya, Kyrgyzst
an, Cambodia, Kiribati, Comoros, Saint Kitts and Nevis, Korea, Democratic People's Republic of, Kore
a, Republic of, Kuwait, Cayman Islands, Kazakhstan, Lao People's Democratic Republic, Lebanon, Saint
 Lucia, Liechtenstein, Sri Lanka, Liberia, Lesotho, Libya, Morocco, Monaco, Moldova, Republic of, Mo
ntenegro, Saint Martin (French part), Madagascar, Marshall Islands, Macedonia, the Former Yugoslav R
epublic of, Mali, Myanmar, Mongolia, Macao, Northern Mariana Islands, Martinique, Mauritania, Montse
rrat, Mauritius, Maldives, Malawi, Mexico, Malaysia, Mozambique, Namibia, New Caledonia, Niger, Norf
olk Island, Nigeria, Nicaragua, Norway, Nepal, Nauru, Niue, New Zealand, Oman, Panama, Peru, French
Polynesia, Papua New Guinea, Philippines, Pakistan, Saint Pierre and Miquelon, Pitcairn, Puerto Rico
, Palestine, State of, Palau, Paraguay, Qatar, RÃ©union, Serbia, Russian Federation, Rwanda, Saudi A
rabia, Solomon Islands, Seychelles, Sudan, Singapore, Saint Helena, Ascension and Tristan da Cunha,
Svalbard and Jan Mayen, Sierra Leone, San Marino, Senegal, Somalia, Suriname, South Sudan, Sao Tome
and Principe, El Salvador, Sint Maarten (Dutch part), Syrian Arab Republic, Swaziland, Turks and Cai
cos Islands, Chad, French Southern Territories, Togo, Thailand, Tajikistan, Tokelau, Timor-Leste, Tu
rkmenistan, Tunisia, Tonga, Turkey, Trinidad and Tobago, Tuvalu, Taiwan, Province of China, Tanzania
, United Republic of, Ukraine, Uganda, United States Minor Outlying Islands, United States, Uruguay,
 Uzbekistan, Saint Vincent and the Grenadines, Venezuela, Bolivarian Republic of, Virgin Islands, Br
itish, Virgin Islands, U.S., Viet Nam, Vanuatu, Wallis and Futuna, Samoa, Yemen, Mayotte, South Afri
ca, Zambia, Zimbabwe only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\CSSource\Logiciel\MusicBot-master\musicbot\bot.py", line 180, in _autojoin_channels
    await self.on_player_finished_playing(player)
  File "G:\CSSource\Logiciel\MusicBot-master\musicbot\bot.py", line 420, in on_player_finished_playi
ng
    info = await self.downloader.safe_extract_info(player.playlist.loop, song_url, download=False, p
rocess=False)
  File "G:\CSSource\Logiciel\MusicBot-master\musicbot\downloader.py", line 85, in safe_extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.safe_ytdl.extract_inf
o, *args, **kwargs))
  File "D:\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "D:\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "D:\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "D:\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 709, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "D:\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "D:\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 521, in trouble
    self.to_stderr(message)
  File "D:\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 475, in to_stderr
    self._write_string(output, self._err_file)
  File "D:\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 454, in _write_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "D:\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 1344, in write_string
    if _windows_write_string(s, out):
  File "D:\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 1328, in _windows_write_stri
ng
    raise OSError('Failed to write string')
OSError: Failed to write string
Failed to join Musique

**Comment by Zenrac** [comment]
Maybe your video isn't avaible in your country (france?)

**Comment by Owned67** [comment]
If not available, i get a error in chat... i don't know with this bot doesn't work, i use sinusbot now
