### ISSUE TITLE
Random timing out

### ISSUE THREAD

**Issue by ProfessorShroom** [Just-Some-Bots/MusicBot#867]
The bot is randomly timing out, when idle and when playing music.
This is what comes up in cmd:

Task exception was never retrieved
future: <Task finished coro=<MusicPlayer.websocket_check() done, defined at D:\H
osting\MusicBOT\musicbot\player.py:280> exception=TimeoutError()>
Traceback (most recent call last):
  File "D:\Hosting\MusicBOT\musicbot\player.py", line 287, in websocket_check
    assert self.voice_client.ws.open
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\asy
ncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\Hosting\MusicBOT\musicbot\player.py", line 291, in websocket_check
    await self.bot.reconnect_voice_client(self.voice_client.channel.server)
  File "D:\Hosting\MusicBOT\musicbot\bot.py", line 310, in reconnect_voice_clien
t
    new_vc = await self.get_voice_client(vc.channel)
  File "D:\Hosting\MusicBOT\musicbot\bot.py", line 237, in get_voice_client
    s_id_data = await asyncio.wait_for(s_id, timeout=10, loop=self.loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\asy
ncio\tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by Zenrac** [comment]
Same problem, maybe a youtube-dl issue ?
I tried to update (in the terminal)
pip3 install -U youtube-dl
But didn't fix.

**Comment by jayktaylor** [comment]
This is usually down to Discord/CloudFlare being wonky and is beyond our control. If it happens regularly, try using the `review` branch (`git checkout review`).
