### ISSUE TITLE
Signature extraction failed as of 1/29

### ISSUE THREAD

**Issue by husos** [Just-Some-Bots/MusicBot#873]
All was working normaly on my Raspberry Pi and today... I've uninstall/reinstall Youtube-dl too.

[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 524, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 268, in __init__
    self.full_url = url
  File "/usr/local/lib/python3.5/urllib/request.py", line 294, in full_url
    self._parse()
  File "/usr/local/lib/python3.5/urllib/request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))

**Comment by gogromat** [comment]
+1

**Comment by roeming** [comment]
+1 just started happening too

**Comment by Skepller** [comment]
+1 Also just started happening!

**Comment by husos** [comment]
I was reading on Youtube-dl Github... Some people with 2017.01.29 update have same issue we probably need to downgrade or wait for a fix.

**Comment by Skepller** [comment]
Any tutorial on how to downgrade? :(

**Comment by DaAwesomeRazor** [comment]
Getting same problem

**Comment by ImthePeach** [comment]
This is a known bug on YTDL's end, wait for them to fix it.
Reference: [#11890](https://github.com/rg3/youtube-dl/issues/11890)

We will let you know when to update_deps for the fix. thnx

**Comment by jayktaylor** [comment]
As of `youtube_dl` release [2017.1.31](https://github.com/rg3/youtube-dl/releases/tag/2017.01.31), this issue has been resolved. If you're still having this problem, update your dependencies.
