### ISSUE TITLE
I get errors after running the runbot.bat

### ISSUE THREAD

**Issue by real-jayden-proctor** [Just-Some-Bots/MusicBot#874]
Whenever I run the runbot.bat I get this

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=cimoNqiulUE
ERROR: 2TPCUXN4-xI: YouTube said: This video contains content from UMG, who has blocked it on copyright grounds.
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=2TPCUXN4-xI
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\legoa\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))

**Comment by kolatra** [comment]
#873

**Comment by shiftybitshiftr** [comment]
[Per ImThePeach](https://github.com/Just-Some-Bots/MusicBot/issues/873#issuecomment-276267951) "This is a known bug on YTDL's end ... We will let you know when to update_deps for the fix." 

If you're impatient like me, you can just go to wherever youtube_dl lives (mine is at /usr/local/lib/python3.5/site-packages/youtube_dl/extractor) and replace youtube.py with [this hotfix](https://github.com/rg3/youtube-dl/blob/f729f1ceed92b24380805685d071ec99519ddeac/youtube_dl/extractor/youtube.py) or just [edit the three lines](https://github.com/rg3/youtube-dl/pull/11892/files) yourself.

Thanks to [Khang-NT](https://github.com/rg3/youtube-dl/issues/11890#issuecomment-276278605) for figuring it out so quickly.
