### ISSUE TITLE
New Youtube Error?

### ISSUE THREAD

**Issue by thomasaarholt** [Just-Some-Bots/MusicBot#879]
I'm currently getting an error when using the MusicBot. I'm unsure whether it is due to Youtube having changed something or something with my system.

Are others having similar trouble? Please see the error below.

```python
[Command] 264487063926079489/Tom (!play https://www.youtube.com/watch?v=79DijItQXMM)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/utils.py", line 518, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/Users/thomas/miniconda3/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/Users/thomas/miniconda3/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/Users/thomas/miniconda3/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))
<class 'musicbot.exceptions.CommandError'>: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/Users/thomas/miniconda3/lib/python3.5/site-packages/youtube_dl/utils.py", line 518, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/Users/thomas/miniconda3/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/Users/thomas/miniconda3/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/Users/thomas/miniconda3/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))

```

**Comment by thomasaarholt** [comment]
Ignore. Should have checked closed errors. My bad. Fixed by `pip install -U youtube_dl`
