### ISSUE TITLE
Unable  to download?

### ISSUE THREAD

**Issue by Gabiru420** [Just-Some-Bots/MusicBot#881]
today i sarted having some issueds playing some musics there is the error that i get in the command line. any clue how to solve it?

> 

[Command] 214839857179000833/Gabiru420 (!play berg bayaka)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 518, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 269, in __init__
    self.full_url = url
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 295, in full_url
    self._parse()
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))
Task exception was never retrieved
future: <Task finished coro=<MusicBot.safe_send_message() done, defined at C:\Users\norul\Desktop\MusicBot-master\musicbot\bot.py:470> exception=HTTPException('BAD REQUEST (status code: 400)',)>
Traceback (most recent call last):
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\norul\Desktop\MusicBot-master\musicbot\bot.py", line 473, in safe_send_message
    msg = await self.send_message(dest, content, tts=tts)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 831, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 518, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 269, in __init__
    self.full_url = url
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 295, in full_url
    self._parse()
  File "C:\Users\norul\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))

>

**Comment by adamcvj** [comment]
Same here only started today, possibly youtube or google problem? 
                                                                     [Command] 197783126972432385/Addy Zoom (!play)
[Command] 197783126972432385/Addy Zoom (!play Human - Rag n bone man)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 524, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))
Task exception was never retrieved
future: <Task finished coro=<MusicBot.safe_send_message() done, defined at C:\Users\Adam Cvjetan\Desktop\MusicBot-master\musicbot\bot.py:470> exception=HTTPException('BAD REQUEST (status code: 400)',)>
Traceback (most recent call last):
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Adam Cvjetan\Desktop\MusicBot-master\musicbot\bot.py", line 473, in safe_send_message
    msg = await self.send_message(dest, content, tts=tts)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 831, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 524, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Adam Cvjetan\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))

**Comment by adamcvj** [comment]
Gotcha Fix:
Run update_deps.bat - find it in the Music bot master folder. It will uninstall youtube-dl.
Run, runbot.bat it will re-install youtube-dl.
Close then run, runbot.bat again and you should be working!

**Comment by arunesh90** [comment]
Duplicate of #873
