### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Puggeh** [Just-Some-Bots/MusicBot#882]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Program Files\Python 3.5\lib\site-packages\youtube_dl\extractor\youtube.py", line 1035, in _decrypt_signature
    video_id, player_url, s
  File "C:\Program Files\Python 3.5\lib\site-packages\youtube_dl\extractor\youtube.py", line 949, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Program Files\Python 3.5\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Program Files\Python 3.5\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Program Files\Python 3.5\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Program Files\Python 3.5\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Program Files\Python 3.5\lib\site-packages\youtube_dl\utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Program Files\Python 3.5\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Program Files\Python 3.5\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Program Files\Python 3.5\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))

Running Windows 10 pro

Can anyone slap me with some help?

**Comment by crtxz** [comment]
I have the same problem on raspbian

**Comment by KappaKiddie** [comment]
Same problem here

**Comment by zotoli** [comment]
Had the same problem, updated youtube.dl and it fixed it.
try
sudo pip install --upgrade youtube-dl

**Comment by Puggeh** [comment]
@zotoli I just type in "sudo pip install --upgrade youtube-dl" (With out the quotes of course) and i get a "Invalid syntax" error

**Comment by Zenrac** [comment]
Zotoli is right, it looks like a youtube-dl's issue. Just open the file update_deps, or maybe try this on the terminal 
pip3 install -U youtube-dl

**Comment by crtxz** [comment]
@zotoli thanks!! it's working again!

**Comment by Zenrac** [comment]
Sudo is not available on Windows 10. By the way, you have to install pip in order to use pip in the terminal

**Comment by adamcvj** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/881

**Comment by Puggeh** [comment]
@zenrac Thank you

Solution: Open Update_deps.bat and enter in pip3 install -U youtube-dl
