### ISSUE TITLE
Signature extraction failed: Traceback (most recent call last) - youtube_dl

### ISSUE THREAD

**Issue by nicholas-petropoulos** [Just-Some-Bots/MusicBot#883]
Here is the error I am experiencing. I am on Ubuntu 16.04. I haven't done anything, it just stopped working one day. Happens when you try to play any music/youtube video. Soundcloud works fine. Thanks

`[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",))`

**Comment by jayktaylor** [comment]
This is a `youtube_dl` bug and is fixed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.

**Comment by nicholas-petropoulos** [comment]
`Requirement already up-to-date: youtube_dl in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))`

I've run that command and its saying its up to date but still its not working. Also the manual update says the same thing.

**Comment by jayktaylor** [comment]
Give `sudo python -m pip install -U youtube-dl --force-reinstall` a go. You may need to use `python3.5` instead of `python`.
