### ISSUE TITLE
Music is not playing at all

### ISSUE THREAD

**Issue by Sxra** [Just-Some-Bots/MusicBot#885]
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",))
Task exception was never retrieved
future: <Task finished coro=<MusicBot.safe_send_message() done, defined at C:\Users\Steezy\MusicBot\musicbot\bot.py:470> exception=HTTPException('BAD REQUEST (status code: 400)',)>
Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Steezy\MusicBot\musicbot\bot.py", line 473, in safe_send_message
    msg = await self.send_message(dest, content, tts=tts)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 831, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",))
```

This is the error I get.

**Comment by RuneDemomn** [comment]
Update your dependencies.

**Comment by Sxra** [comment]
Updating the dependencies does not fix this issue, I am still encountering this issue.

**Comment by ImthePeach** [comment]
This was a known bug on YTDL's end.
Reference: [#11890](https://github.com/rg3/youtube-dl/issues/11890)
As of `youtube_dl` release [2017.1.31](https://github.com/rg3/youtube-dl/releases/tag/2017.01.31), this issue has been resolved. If you're still having this problem, update your dependencies **and** restart your bot.

**Windows** - Open `update_deps.bat`
**Linux** - In your console, run `python3.5 -m pip install --upgrade -r requirements.txt`
**Mac** - Open `update_macdeps.command` in Terminal

**Comment by Sxra** [comment]
Running the update_deps.bat only tells me that all my files are already up-to-date. When trying to start the bot, I still get the same result.

**Comment by bbyyw** [comment]
i had the same issue before, but resolved after updating

**Comment by ImthePeach** [comment]
Try switching to the review branch then updating_deps
If you're already using MusicBot and want to switch to the review branch, use this command when git bashing into the music bot folder: `git checkout review`
If you are installing from fresh, use `git clone https://github.com/Just-Some-Bots/MusicBot.git ~/MusicBot -b review`

**Comment by cmsiss** [comment]
Traceback error is resolved by running update_deps.. youtube-dl lib needed new update

**Comment by xorima** [comment]
If anyone is having trouble updating their docker image I have updated my one at https://hub.docker.com/r/jasonfield/musicbot/ fyi
