### ISSUE TITLE
Most YouTube songs give an error

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#886]
When trying to play or search YouTube videos with the bot, I run into this error. Certain videos do work: https://www.youtube.com/watch?v=GDpmVUEjagg
Others like https://www.youtube.com/watch?v=UqyT8IEBkvY do not. This is using the latest version from the review branch. The same issue occurs with the master branch.

```
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/lib/python3.5/site-packages/youtube_dl/utils.py", line 524, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib64/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib64/python3.5/urllib/request.py", line 295, in full_url
    self._**...**
```

**Comment by ImthePeach** [comment]
This was a known bug on YTDL's end.
Reference: [#11890](https://github.com/rg3/youtube-dl/issues/11890)
As of `youtube_dl` release [2017.1.31](https://github.com/rg3/youtube-dl/releases/tag/2017.01.31), this issue has been resolved. If you're still having this problem, update your dependencies.

**Windows** - Open `update_deps.bat`
**Linux** - In your console, run `python3.5 -m pip install --upgrade -r requirements.txt`
**Mac** - Open `update_macdeps.command` in Terminal
