### ISSUE TITLE
Impossible to play any music

### ISSUE THREAD

**Issue by HeySora** [Just-Some-Bots/MusicBot#887]
```ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 524, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/local/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/local/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",))
```

**Comment by cmsiss** [comment]
Try running update_deps. YouTube-dl had a new lib update

**Comment by HeySora** [comment]
Thanks for your answer.
Sorry, I wanted to add some details in my message, but I failed somehow.

I'm running the bot on a Debian 8 machine. This issue is happening since a few days.
I already ran `python3.5 -m pip install --upgrade -r requirements.txt` but nothing happened, the problem is still happening.

**Comment by BaiqingL** [comment]
I also have the same problem, however updating YouTube-dl made it work again. You might want to run that command with sudo if it didn't do anything.

**Comment by jayktaylor** [comment]
If updating via the `requirements.txt` doesn't work, I'd give a variation of this command a go (substituting `python` for your correct alias):

```
sudo python -m pip install -U youtube-dl --force-reinstall
```

**You will need to hard restart the bot after doing this.**

**Comment by Trustmega** [comment]
> if updating via the requirements.txt doesn't work, I'd give a variation of this command a go (substituting python for your correct alias):
sudo python -m pip install -U youtube-dl --force-reinstall
You will need to hard restart the bot after doing this.

This seemed to do the trick for me!

**Comment by HeySora** [comment]
> if updating via the requirements.txt doesn't work, I'd give a variation of this command a go (substituting python for your correct alias):
sudo python -m pip install -U youtube-dl --force-reinstall
You will need to hard restart the bot after doing this.

Nice, it works well now, thanks !
