### ISSUE TITLE
Cannot clean messages

### ISSUE THREAD

**Issue by Selkea** [Just-Some-Bots/MusicBot#889]
I've ensured the bot has either Manage Messages or Administrator permissions on my Discord Server (both in my case) however attempting to use the !clean command returns the following error:

```
Traceback (most recent call last):
  File "C:\Users\vc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 1052, in purge_from
    msg = yield from iterator.iterate()
  File "C:\Users\vc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\iterators.py", line 85, in iterate
    return self.messages.get_nowait()
  File "C:\Users\vc\AppData\Local\Programs\Python\Python35-32\lib\asyncio\queues.py", line 184, in get_nowait
    raise QueueEmpty
asyncio.queues.QueueEmpty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vc\Desktop\MusicBot-master\musicbot\bot.py", line 2123, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\vc\Desktop\MusicBot-master\musicbot\bot.py", line 1740, in cmd_clean
    deleted = await self.purge_from(channel, check=check, limit=search_range, before=message)
  File "C:\Users\vc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 1058, in purge_from
    yield from self.delete_messages(to_delete)
  File "C:\Users\vc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 980, in delete_messages
    yield from self.http.delete_messages(channel.id, message_ids, guild_id)
  File "C:\Users\vc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): You can only bulk delete messages that are under 14 days old.
```

**Comment by KingGold171** [comment]
File "C:\Users\vc\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): You can only bulk delete messages that are under 14 days old.

> BAD REQUEST (status code: 400): You can only bulk delete messages that are under 14 days old.

![2017-02-02_0701](https://cloud.githubusercontent.com/assets/3100621/22539983/6adb7f08-e915-11e6-831e-3d63a966f80f.png)

**Comment by Selkea** [comment]
I should have also mentioned that I am unable to clean messages that are definitely not older than 2 weeks

**Comment by Zenrac** [comment]
That's must be because you have some messages older than 2 weeks in your search_range, try to use clean with a little number such as !clean 5.

**Comment by Selkea** [comment]
I had a feeling that might be the case, and sure enough you're right. Now I'll have to look into making a function that will run periodically and perform a clean command within the range of messages received between function calls.
