### ISSUE TITLE
Bot removes songs from the auto playlist

### ISSUE THREAD

**Issue by adamja** [Just-Some-Bots/MusicBot#890]
I had a the autoplaylist.txt filled with 100 songs and came back in 12 hours and it was down to 66 in the list?

```Feb 02 11:15:44 raspberrypi python3.5[30579]: ERROR: Signature extraction failed: Traceback (most recent call last):
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
Feb 02 11:15:44 raspberrypi python3.5[30579]: video_id, player_url, s
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
Feb 02 11:15:44 raspberrypi python3.5[30579]: errnote='Download of %s failed' % player_url)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
Feb 02 11:15:44 raspberrypi python3.5[30579]: res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 424, in _download_w 
02 11:15:44 raspberrypi python3.5[30579]: ERROR: Signature extraction failed: Traceback (most recent call last):
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
Feb 02 11:15:44 raspberrypi python3.5[30579]: video_id, player_url, s
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
Feb 02 11:15:44 raspberrypi python3.5[30579]: errnote='Download of %s failed' % player_url)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
Feb 02 11:15:44 raspberrypi python3.5[30579]: res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
Feb 02 11:15:44 raspberrypi python3.5[30579]: urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
Feb 02 11:15:44 raspberrypi python3.5[30579]: return self._downloader.urlopen(url_or_request)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
Feb 02 11:15:44 raspberrypi python3.5[30579]: req = sanitized_Request(req)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 518, in sanitized_Request
Feb 02 11:15:44 raspberrypi python3.5[30579]: return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/urllib/request.py", line 268, in __init__
Feb 02 11:15:44 raspberrypi python3.5[30579]: self.full_url = url
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/urllib/request.py", line 294, in full_url
Feb 02 11:15:44 raspberrypi python3.5[30579]: self._parse()
Feb 02 11:15:44 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/urllib/request.py", line 323, in _parse
Feb 02 11:15:44 raspberrypi python3.5[30579]: raise ValueError("unknown url type: %r" % self.full_url)
Feb 02 11:15:44 raspberrypi python3.5[30579]: ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
Feb 02 11:15:44 raspberrypi python3.5[30579]: (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",))
Feb 02 11:15:44 raspberrypi python3.5[30579]: [Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=GJFmhvyf2V0
Feb 02 11:15:45 raspberrypi python3.5[30579]: ERROR: Signature extraction failed: Traceback (most recent call last):
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
Feb 02 11:15:45 raspberrypi python3.5[30579]: video_id, player_url, s
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
Feb 02 11:15:45 raspberrypi python3.5[30579]: errnote='Download of %s failed' % player_url)
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
Feb 02 11:15:45 raspberrypi python3.5[30579]: res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
Feb 02 11:15:45 raspberrypi python3.5[30579]: urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
Feb 02 11:15:45 raspberrypi python3.5[30579]: return self._downloader.urlopen(url_or_request)
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
Feb 02 11:15:45 raspberrypi python3.5[30579]: req = sanitized_Request(req)
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 518, in sanitized_Request
Feb 02 11:15:45 raspberrypi python3.5[30579]: return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/urllib/request.py", line 268, in __init__
Feb 02 11:15:45 raspberrypi python3.5[30579]: self.full_url = url
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/urllib/request.py", line 294, in full_url
Feb 02 11:15:45 raspberrypi python3.5[30579]: self._parse()
Feb 02 11:15:45 raspberrypi python3.5[30579]: File "/usr/local/lib/python3.5/urllib/request.py", line 323, in _parse
Feb 02 11:15:45 raspberrypi python3.5[30579]: raise ValueError("unknown url type: %r" % self.full_url)
Feb 02 11:15:45 raspberrypi python3.5[30579]: ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
Feb 02 11:15:45 raspberrypi python3.5[30579]: (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",))
Feb 02 11:15:45 raspberrypi python3.5[30579]: [Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=syXD19Dkhy8```

**Comment by jayktaylor** [comment]
See #873.
