### ISSUE TITLE
Can't play all of playlist

### ISSUE THREAD

**Issue by nate2014jatc** [Just-Some-Bots/MusicBot#891]
When I try to play a 99 video long playlist, MB only registers 19 songs.
I tried adding it an alternate way, and got this traceback error

> Could not extract information from https://www.youtube.com/watch?v=NVDSiwPbw1w&list=PLQvCb0odWC4zJJrKvqYoI2kTHQBwFzsl1

>ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 516, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 423, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 403, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 511, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",))

**Comment by arunesh90** [comment]
Duplicate of #873 
Check that issue for the fix.

**Comment by nate2014jatc** [comment]
@arunesh90 It's happening again, after I updated the deps

Same exact issue

**Comment by jayktaylor** [comment]
@nate2014jatc Try `sudo python3.5 -m pip install -U youtube-dl --force-reinstall`

**Comment by nate2014jatc** [comment]
That seems to have done it. 
98/99 songs queued up. 
It took 125.xx seconds, according to MB

Is that standard?
