### ISSUE TITLE
!play ... results in big errormessage

### ISSUE THREAD

**Issue by ngelus** [Just-Some-Bots/MusicBot#894]
When I try to use !play rapgod for example I just get an errormessage. Autoplaylist works perfectly. Please help!!!: ```
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 518, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/local/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/local/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",))
```

If you need more Informations on this problem please just tell me.

**Comment by ngelus** [comment]
Sorry for the bad formatting. I'm new to github.

**Comment by TomLongAshfords** [comment]
Think you just need to update your dependencies (specifically Youtube_dl). The ones which are working are probably already cached.  

Looks like it's related to [this error](https://github.com/rg3/youtube-dl/issues/11890) which has been resolved with their latest update.

**Comment by arunesh90** [comment]
Duplicate of #873 
To fix this error, update your dependencies.

**Comment by ngelus** [comment]
How do I update them on linux? Do I just type sudo apt-get upgrade?

**Comment by jayktaylor** [comment]
- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
