### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by oQuintessential** [Just-Some-Bots/MusicBot#896]
Can't startup bot, keep getting this error.

Traceback (most recent call last):
  File "C:\Users\Uhhre_000\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Uhhre_000\Desktop\New folder\New folder\vp music\MusicBot\musicbot\bot.py", line 710, in on_ready
    owner_vc = await self._auto_summon()
  File "C:\Users\Uhhre_000\Desktop\New folder\New folder\vp music\MusicBot\musicbot\bot.py", line 149, in _auto_summon
    await self.cmd_summon(owner.voice_channel, owner, None)
  File "C:\Users\Uhhre_000\Desktop\New folder\New folder\vp music\MusicBot\musicbot\bot.py", line 1325, in cmd_summon
    player = await self.get_player(author.voice_channel, create=True)
  File "C:\Users\Uhhre_000\Desktop\New folder\New folder\vp music\MusicBot\musicbot\bot.py", line 362, in get_player
    voice_client = await self.get_voice_client(channel)
  File "C:\Users\Uhhre_000\Desktop\New folder\New folder\vp music\MusicBot\musicbot\bot.py", line 237, in get_voice_client
    s_id_data = await asyncio.wait_for(s_id, timeout=10, loop=self.loop)
  File "C:\Users\Uhhre_000\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 396, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by jayktaylor** [comment]
This is caused by Discord/CloudFlare being weird. If it happens often, try using the `review` branch (`git checkout review`).
