### ISSUE TITLE
Bot cant connect

### ISSUE THREAD

**Issue by itsacorn** [Just-Some-Bots/MusicBot#898]
Hello everyone, i installed the bot, but it doesnt run correctly. It connects to my server but wont play music. I do NOT use a firewall. Here is my SSH season: 
`Last login: Sat Feb  4 02:28:13 2017 from 40.200.193.178.dynamic.wline.res.cust.swisscom.ch
root@shutteddown:~# cd MusicBot/
root@shutteddown:~/MusicBot# python3.5 run.py
Connected!  Musicbot v1.9.5_2

Bot:   277348747376066561/DJ#9849
Owner: 178409772436029440/hungrybeast#3631

Server List:
 - Iloosium

Not bound to any text channels
Not autojoining any voice channels

Options:
  Command prefix: ?
  Default volume: 15%
  Skip threshold: 4 votes or 50%
  Now Playing @mentions: Disabled
  Auto-Summon: Enabled
  Auto-Playlist: Enabled
  Auto-Pause: Enabled
  Delete Messages: Enabled
    Delete Invoking: Disabled
  Debug Mode: Disabled
  Downloaded songs will be saved

Attempting to autosummon...
Found owner in "Music", attempting to join...
Attempting connection...
Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 382, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Failed to connect, retrying (1/3)...
Attempting connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/gateway.py", line 604, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 378, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 298, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 378, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 256, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/site-packages/discord/gateway.py", line 607, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..
Failed to connect, retrying (2/3)...
Attempting connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/gateway.py", line 604, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 378, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 298, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MusicBot/musicbot/bot.py", line 256, in get_voice_client
    await asyncio.wait_for(voice_client.connect(), timeout=10, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 378, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 256, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/site-packages/discord/gateway.py", line 607, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..
Failed to connect, retrying (3/3)...
Exception in on_ready

An error has occured:

  Problem:  Cannot establish connection to              voice chat.  Something may be               blocking outgoing UDP                       connections.                      Solution: This may be an issue with a                 firewall blocking UDP.  Figure              out what is blocking UDP and                disable it.  It's most likely a             system firewall or overbearing              anti-virus firewall.            
^CTraceback (most recent call last):
  File "run.py", line 224, in <module>
    main()
  File "run.py", line 165, in main
    m.run()
  File "/root/MusicBot/musicbot/bot.py", line 551, in run
    self.loop.run_until_complete(self.start(*self.config.auth))
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 330, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 301, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1162, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.5/selectors.py", line 432, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending coro=<_run_event() running at /usr/local/lib/python3.5/site-packages/discord/client.py:280> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback(5)() at /usr/local/lib/python3.5/asyncio/tasks.py:602]>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6d088d02e8>
root@shutteddown:~/MusicBot# 
`

**Comment by itsacorn** [comment]
I forgot to say, i cancelled the bot, thats why it says pending task closed or whatever

**Comment by Chew** [comment]
the error I see is "Session is no longer valid.."

**Comment by blabel3** [comment]
I have the same issue, did you ever find a fix?

**Comment by LuBlaBo** [comment]
Have you tried to update the requirements?
# Ubuntu 14.04(.*) LTS
python3.5 -m pip install -U -r requirements.txt

**Comment by blabel3** [comment]
That fixed it! I swear I tried updating everything, but obviously not! Sorry for being dumb, and thank you so much for helping. :)

**Comment by jayktaylor** [comment]
This issue is caused by Discord's response to requests. Updating your dependencies may help.
