### ISSUE TITLE
Error when trying to request songs

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#904]
I have no clue what this means or how to fix it, im basic so..

[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 524, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'",))

**Comment by NickBonet** [comment]
Updating your dependencies should resolve the issue, there was an API update a few days ago

**Comment by brett1241** [comment]
How do I update my dependencies, I am having the same issue.

**Comment by brett1241** [comment]
Never mind I ran the bat file

**Comment by Baniita** [comment]
What do you mean updating dependencies? Us plebs have no idea what that means. Is that for Python? Or is it something else? I can't google that if I don't know what keywords to google, and just googling "dependencies update" doesn't help at all.

**Comment by imhel** [comment]
I'm getting an error using that bat file

**Comment by YoCsusu** [comment]
Same probleme with the bot all my dependance is update

**Comment by jayktaylor** [comment]
- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl --force-reinstall`.
