### ISSUE TITLE
the bot does not want to play music rasberry Pi 3 ffmpeg problem

### ISSUE THREAD

**Issue by MRJR123** [Just-Some-Bots/MusicBot#926]
so when the bot is started and done downloading this get posted in the console and i dont get why it does it. help plz

`[Download] Started: https://www.youtube.com/watch?v=BeyEGebJ1l4
[Download] Complete: https://www.youtube.com/watch?v=BeyEGebJ1l4
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/pi/MusicBot/musicbot/player.py:221> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 427, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/pi/MusicBot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable
`

**Comment by TheEssem** [comment]
Did you follow these instructions? https://github.com/Just-Some-Bots/MusicBot/wiki/Guide-for-Raspbian#1d-ffmpeg
