### ISSUE TITLE
Certain Youtube links not working 

### ISSUE THREAD

**Issue by SimplyLime** [Just-Some-Bots/MusicBot#930]
https://hastebin.com/rabodevava.sql
Didn't have this issue a while ago, any ideas?

**Comment by arunesh90** [comment]
Update your dependencies by running `python3.5 -m pip install --upgrade -r requirements.txt`

**Comment by SimplyLime** [comment]
I did this, and then did !restart. didnt work for me, still getting the error.
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    if i - prev == step:
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    }
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    if block_msg:
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    if fatal:
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    self.to_screen('%s' % (note,))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    for lang, formats in subtitles.items()]))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    """Sanitizes and normalizes path on Windows"""
  File "/usr/lib/python3.5/urllib/request.py", line 268, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 294, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))

**Comment by jayktaylor** [comment]
`!restart` may not be enough. You will likely need to hard restart your bot entirely. If it doesn't work, run `python3.5 -m pip install -U youtube-dl --force-reinstall` first, then hard restart.
