### ISSUE TITLE
I don't know..

### ISSUE THREAD

**Issue by Sxra** [Just-Some-Bots/MusicBot#932]
`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))
<class 'musicbot.exceptions.ExtractionError'>: Could not extract information from https://www.youtube.com/watch?v=trQ8iyfit5s&list=RDyH3xxpKceFY&index=3

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))
Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 357, in extract
    return self._real_extract(url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1584, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Steezy\MusicBot\musicbot\playlist.py", line 45, in add_entry
    info = await self.downloader.extract_info(self.loop, song_url, download=False)
  File "C:\Users\Steezy\MusicBot\musicbot\downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 705, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 758, in process_ie_result
    extra_info=extra_info)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 709, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 538, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Steezy\MusicBot\musicbot\bot.py", line 1931, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Steezy\MusicBot\musicbot\bot.py", line 1006, in cmd_play
    entry, position = await player.playlist.add_entry(song_url, channel=channel, author=author)
  File "C:\Users\Steezy\MusicBot\musicbot\playlist.py", line 47, in add_entry
    raise ExtractionError('Could not extract information from {}\n\n{}'.format(song_url, e))
musicbot.exceptions.ExtractionError: Could not extract information from https://www.youtube.com/watch?v=trQ8iyfit5s&list=RDyH3xxpKceFY&index=3

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Steezy\MusicBot\musicbot\bot.py", line 1953, in on_message
    also_delete=alsodelete
  File "C:\Users\Steezy\MusicBot\musicbot\bot.py", line 473, in safe_send_message
    msg = await self.send_message(dest, content, tts=tts)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 831, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Users\Steezy\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)`

Help me pls

**Comment by ghost** [comment]
https://github.com/Just-Some-Bots/MusicBot/issues/875

**Comment by jayktaylor** [comment]
duplicate #873
