### ISSUE TITLE
youtube_dl Errors 

### ISSUE THREAD

**Issue by T1MOXA** [Just-Some-Bots/MusicBot#940]
```
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 268, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 294, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))
```

Same problem on linux server and my PC :(

**Comment by TheEssem** [comment]
Try updating youtube_dl.

**Comment by T1MOXA** [comment]
Tried, not helped.

**Comment by T1MOXA** [comment]
Sorry.
Yes, the update helped. 
Before that, I did the update command incorrectly.
This is the correct command - `sudo pip install --upgrade youtube_dl`
