### ISSUE TITLE
Error when searching for songs (YouTube specifically)

### ISSUE THREAD

**Issue by Janterra** [Just-Some-Bots/MusicBot#942]
Upon running the command `python3.5 run.py` i get an error message in the terminal as follows 
`Connection established.
ERROR: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))
[Info] Removing unplayable song from autoplaylist: https://www.youtube.com/watch?v=B4fHp5Gdx-c
Done!
Starting auto-playlist`

`[Download] Started: https://www.youtube.com/watch?v=L8jL1j2am-E
ERROR: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/lib/python3.5/http/client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 1060, in https_open
    req, **kwargs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)>`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1285, in _real_extract
    video_webpage = self._download_webpage(url, video_id)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 425, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "/home/pi/MusicBot/musicbot/downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 711, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 570, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 540, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/entry.py", line 196, in _download
    await self._really_download()
  File "/home/pi/MusicBot/musicbot/entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))
Future exception was never retrieved
future: <Future finished exception=ExtractionError(DownloadError("\x1b[0;31mERROR:\x1b[0m Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))",),)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/lib/python3.5/http/client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2006, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/utils.py", line 1060, in https_open
    req, **kwargs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)>`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1285, in _real_extract
    video_webpage = self._download_webpage(url, video_id)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 425, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/entry.py", line 213, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "/home/pi/MusicBot/musicbot/downloader.py", line 82, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 711, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 570, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 540, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/entry.py", line 196, in _download
    await self._really_download()
  File "/home/pi/MusicBot/musicbot/entry.py", line 215, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: ERROR: Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))
[Download] Started: https://www.youtube.com/watch?v=L8jL1j2am-E
[Download] Complete: https://www.youtube.com/watch?v=L8jL1j2am-E
Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/pi/MusicBot/musicbot/player.py:221> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 427, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'`

`The above exception was the direct cause of the following exception:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/pi/MusicBot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable`

The bot does connect to the discord server, and functions normally until i use the !search command. when i use the !search command in discord, the following error message appears in the discord server

`[0;31mERROR:[0m unable to download video info webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))`

and this error message in the terminal

`ERROR: unable to download video info webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))
<class 'musicbot.exceptions.CommandError'>: ERROR: unable to download video info webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))`

I am running the bot a a Raspberry Pi 3b, using the latest release of Raspbian Jessie.

EDIT* Also it should be noted that during installation the "ppa" commands did not work and, as the guide said to, i continued without them.

**Comment by Chew** [comment]
Some sort of SSL error, might be with the autoplaylist, try clearing it or disabling it and see what happens. It might be because it can't make a secure connect since the entire error is scattered with SSL errors.

**Comment by Janterra** [comment]
@Chewsterchew clearing the autoplaylist.txt file worked for starting without error however, it will still throw an error whenever I search for a song as follows 

`Unable to download webpage: <urlopen error [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)> (caused by URLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:646)'),))`

I'm going to quickly set it up on a wired internet connection, and see if that does anything.

EDIT* After Connecting the pi to my modem, the error persisted.

**Comment by Chew** [comment]
Make sure you can open the page with a web browser and not through the bot

**Comment by Janterra** [comment]
Yes, I can access the webpage though a web browser. I'm staring to think it is a certificate error.

**Comment by Sorkaras** [comment]
I know this sounds like a redundant step, but you've made sure to update your deps right? I've noticed that usually when I get this error its something to do with the Youtube Depository.

**Comment by Janterra** [comment]
After checking to see if all of the deps were updated, which they were, i tried requesting a song through discord, and a new error popped up

`Task exception was never retrieved
future: <Task finished coro=<MusicPlayer._play() done, defined at /home/pi/MusicBot/musicbot/player.py:221> exception=ClientException('ffmpeg/avconv was not found in your PATH environment variable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 427, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'`

`The above exception was the direct cause of the following exception:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/pi/MusicBot/musicbot/player.py", line 256, in _play
    after=lambda: self.loop.call_soon_threadsafe(self._playback_finished)
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 430, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable`

This leads me to believe that the ffmpeg didn't get installed correctly.

I am running through and reinstalling everything from the beginning to see if this will solve my issue

**Comment by Sorkaras** [comment]
I'm not entirely certain about a PI environment, but yes that seems to be the problem. It's having issues with the PATH variable. Which could be just a reinstall, but I'd find out how to edit your variables. :)

**Comment by Janterra** [comment]
I can't believe i waitied till now to try a source other than youtube. *facepalm* 
Used a soundcloud link and it worked perfectly. apparently it is an issue with youtube-dl. I will be looking around for a solution to the issue with youtube-dl.

**Comment by Sorkaras** [comment]
The YouTube.dl seems to have a regular almost daily update, usually when I encounter an issue with just YouTube it tells me in the error log, but it could be the compression of the file to the device.

**Comment by Janterra** [comment]
I don't believe so, as i am still getting SSL errors
