### ISSUE TITLE
Only a selection of songs from !play work.

### ISSUE THREAD

**Issue by Cosmic12522** [Just-Some-Bots/MusicBot#944]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 269, in __init__
    self.full_url = url
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 295, in full_url
    self._parse()
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflg9Wu9U/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflg9Wu9U/base.js'",))
Task exception was never retrieved
future: <Task finished coro=<MusicBot.safe_send_message() done, defined at C:\Users\Aiden\Desktop\MusicBot\musicbot\bot.py:470> exception=HTTPException('BAD REQUEST (status code: 400)',)>
Traceback (most recent call last):
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Aiden\Desktop\MusicBot\musicbot\bot.py", line 473, in safe_send_message
    msg = await self.send_message(dest, content, tts=tts)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 831, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 269, in __init__
    self.full_url = url
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 295, in full_url
    self._parse()
  File "C:\Users\Aiden\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflg9Wu9U/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflg9Wu9U/base.js'",))

**Comment by jayktaylor** [comment]
Update your dependencies using the batch file, or run `pip install -U youtube-dl --force-reinstall`.
