### ISSUE TITLE
linux mint

### ISSUE THREAD

**Issue by skynyrd0110** [Just-Some-Bots/MusicBot#977]
Has anyone else tried to get the bot to run on Linux Mint?

I have been trying to get this to run on Linux Mint (MATE, version 18.1 'Serena'), which is based on Ubuntu, but I keep running into issues when trying to use pip to update Python dependencies.

After running the command
`python3 -m pip install -U -r requirements.txt`

I get back 
`Collecting discord.py[voice]~=0.12.0 (from -r requirements.txt (line 1))
  Using cached discord.py-0.12.0.zip
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.`

I've tried using `sudo` as well, but I still get the same results.

I understand that the instructions given are for Ubuntu and not for Mint, but I was just wondering if anyone might know what is causing these issues.

**Comment by jayktaylor** [comment]
`sudo apt-get install python3-setuptools` may resolve this.

**Comment by skynyrd0110** [comment]
@jaydenkieran 
That worked to resolve the initial issue, but now I am getting an error:
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bmdr34uk/PyNaCl/`

**Comment by jayktaylor** [comment]
![pynacl](https://images-ext-2.discordapp.net/eyJ1cmwiOiJodHRwOi8vaS5pbWd1ci5jb20vNWJRZVhKWC5wbmcifQ.NN_dkjOmhrtWu9ltnb2LDn2ED7k)

**Comment by skynyrd0110** [comment]
After installing python3-dev (libffi-dev was already up to date), it made some progress but threw an exception after these lines:
`Collecting pycparser (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice]~=0.12.0->-r requirements.txt (line 1))
  Using cached pycparser-2.17.tar.gz
Installing collected packages: async-timeout, multidict, aiohttp, websockets, pycparser, cffi, PyNaCl, discord.py, youtube-dl`

Here is the exception:
`Exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/user/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/user/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/user/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/user/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/user/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/user/.local/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/user/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/async_timeout'`

**Comment by jayktaylor** [comment]
Can you try running the pip install command as sudo?
