### ISSUE TITLE
!play Command Doesn't Work For Random Youtube Videos

### ISSUE THREAD

**Issue by Ethanrulesall** [Just-Some-Bots/MusicBot#997]
Here's the error it spits out in the discord chat.

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "E:\Program Files (x86)\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "E:\Program Files (x86)\Python\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "E:\Program Files (x86)\Python\lib\site-packages\youtube_dl\extractor\common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "E:\Program Files (x86)\Python\lib\site-packages\youtube_dl\extractor\common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "E:\Program Files (x86)\Python\lib\site-packages\youtube_dl\extractor\common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "E:\Program Files (x86)\Python\lib\site-packages\youtube_dl\YoutubeDL.py", line 1997, in urlopen
    req = sanitized_Request(req)
  File "E:\Program Files (x86)\Python\lib\site-packages\youtube_dl\utils.py", line 501, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "E:\Program Files (x86)\Python\lib\urllib\request.py", line 269, in __init__
    self.full_url = url
  File "E:\Program Files (x86)\Python\lib\urllib\request.py", line 295, in full_url
    self._parse()
  File "E:\Program Files (x86)\Python\lib\urllib\request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl2GjLln/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl2GjLln/base.js'",))

Any help would be appreciated.

**Comment by KingGold171** [comment]
Windows - Open update_deps.bat
Linux - In your console, run python3.5 -m pip install --upgrade -r requirements.txt
Mac - Open update_macdeps.command in Terminal
